# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orientacao', models.TextField(blank=True, help_text='Texto de orientação da Categoria da Enquete', verbose_name='Orientação da Categoria')),
                ('ordem', models.IntegerField()),
            ],
            options={'verbose_name': 'Categoria de Enquete', 'verbose_name_plural': 'Categorias de Enquete'},
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tag',
                    djtools.db.models.CharFieldPlus(
                        default='Responda à Enquete', help_text='Tag que será usada na tela inicial do questionário/enquete.', max_length=255, verbose_name='Tag'
                    ),
                ),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Término')),
                ('publicada', models.BooleanField(default=False)),
                (
                    'manter_enquete_inicio',
                    models.BooleanField(default=False, help_text='Manter enquete na tela inicial enquanto em período.', verbose_name='Manter Enquete Tela Inicial'),
                ),
                (
                    'resultado_publico',
                    models.BooleanField(
                        default=False,
                        help_text='No resultado dessa enquete irá aparecer quem respondeu (somente para Responsáveis pela Enquete).',
                        verbose_name='Resultado Público',
                    ),
                ),
                ('instrucoes', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='enquete/instrucoes/', verbose_name='Anexo')),
                ('descricao_anexo', djtools.db.models.CharFieldPlus(blank=True, default='Instruções da Enquete', max_length=255, verbose_name='Descrição do Anexo')),
                ('texto_orientacao', models.TextField(blank=True, verbose_name='Texto de Orientação')),
                ('vinculos_publico', djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='vinculos_publico', to='comum.Vinculo', verbose_name='Vínculos Público')),
                (
                    'vinculos_relacionados_enquete',
                    djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='vinculos_relacionados_enquete', to='comum.Vinculo', verbose_name='Vínculos Relacionados'),
                ),
                (
                    'vinculos_responsaveis',
                    djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='vinculos_responsaveis_enquetes', to='comum.Vinculo', verbose_name='Responsável(is)'),
                ),
            ],
            options={'verbose_name': 'Enquete', 'verbose_name_plural': 'Enquetes'},
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='enquete/opcao/imagem')),
            ],
            options={'verbose_name': 'Opções de Enquete', 'verbose_name_plural': 'Opção de Enquete', 'ordering': ('ordem',)},
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'layout',
                    djtools.db.models.CharFieldPlus(
                        choices=[('tabela', 'Tabela'), ('lista', 'Lista')],
                        default='lista',
                        help_text='Válido somente para perguntas objetivas',
                        max_length=255,
                        verbose_name='Layout das Respostas',
                    ),
                ),
                ('texto', models.TextField()),
                (
                    'numerico',
                    models.BooleanField(
                        default=False,
                        blank=True,
                        help_text='Marque este campo caso a resposta deva ser apenas numérica, em caso de pergunta subjetiva.',
                        verbose_name='Campo Numérico',
                    ),
                ),
                ('objetiva', models.BooleanField(default=True)),
                ('multipla_escolha', models.BooleanField(default=False, verbose_name='Múltipla Escolha')),
                ('ordem', models.IntegerField()),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Categoria')),
                ('enquete', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Enquete')),
            ],
            options={'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas', 'ordering': ('ordem', 'id')},
        ),
        migrations.CreateModel(
            name='PublicoCampi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo_setor',
                    djtools.db.models.CharFieldPlus(
                        choices=[('setor_suap', 'Setor SUAP'), ('setor_funcao', 'Setor da Função SIAPE'), ('setor_lotacao', 'Setor de Lotação SIAPE')],
                        default='setor_suap',
                        help_text='Este setor será levado em consideração com relação aos campi escolhidos',
                        max_length=255,
                        verbose_name='Tipo de Setor do Funcionario/Servidor',
                    ),
                ),
                ('campi', djtools.db.models.ManyToManyFieldPlus(to='rh.UnidadeOrganizacional', verbose_name='Campi')),
                ('enquete', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Enquete')),
                ('publico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Publico', verbose_name='Público')),
            ],
            options={'verbose_name': 'Público Campi', 'verbose_name_plural': 'Públicos Campi'},
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('resposta', models.TextField(help_text='Resposta')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                (
                    'opcao_ptr',
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enquete.Opcao'),
                ),
                ('pergunta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='enquete.Pergunta')),
            ],
            options={'verbose_name': 'Opções de Resposta', 'verbose_name_plural': 'Opção de Resposta', 'ordering': ('ordem',)},
            bases=('enquete.opcao',),
        ),
        migrations.AddField(
            model_name='resposta',
            name='opcao',
            field=djtools.db.models.ForeignKeyPlus(help_text='Resposta Objetiva', null=True, on_delete=django.db.models.deletion.CASCADE, to='enquete.Opcao'),
        ),
        migrations.AddField(model_name='resposta', name='pergunta', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Pergunta')),
        migrations.AddField(
            model_name='resposta',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete_resposta_uo_set', to='rh.UnidadeOrganizacional'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='vinculo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete_resposta_vinculo', to='comum.Vinculo', verbose_name='Vínculo'
            ),
        ),
        migrations.AddField(model_name='opcao', name='enquete', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Enquete')),
        migrations.AddField(model_name='categoria', name='enquete', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='enquete.Enquete')),
    ]
