# Generated by Django 2.2.7 on 2019-12-06 10:50

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('enquete', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='layout',
            field=djtools.db.models.CharFieldPlus(
                choices=[('tabela', 'Tabela'), ('lista', 'Lista'), ('galeria', 'Galeria')],
                default='lista',
                help_text='Válido somente para perguntas objetivas',
                max_length=255,
                verbose_name='Layout das Respostas',
            ),
        )
    ]
