# Generated by Django 2.2.7 on 2020-02-14 10:51

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('enquete', '0003_pergunta_obrigatoria')]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='layout',
            field=djtools.db.models.CharFieldPlus(
                blank=True,
                choices=[('tabela', 'Tabela'), ('lista', 'Lista'), ('galeria', 'Galeria')],
                default='lista',
                help_text='Válido somente para perguntas objetivas',
                max_length=255,
                verbose_name='Layout das Respostas',
            ),
        ),
        migrations.AlterField(model_name='pergunta', name='texto', field=models.TextField(verbose_name='Título da Pergunta')),
    ]
