# Generated by Django 2.2.16 on 2021-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_auto_20210219_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='data_ultima_resposta',
            field=models.DateTimeField(null=True, verbose_name='Data da última resposta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
