# Generated by Django 2.2.16 on 2021-03-09 20:04

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0006_auto_20210219_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='imagem',
            field=djtools.db.models.ImageFieldPlus(blank=True, upload_to='enquete/opcao/imagem'),
        ),
    ]
