# Generated by Django 3.2.5 on 2021-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0007_auto_20210309_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='manter_enquete_inicio',
            field=models.BooleanField(default=False, help_text='Se esta opção ficar desmarcada, quando um usuário responder a enquete, ela não vai mais aparecer na tela inicial para ele.', verbose_name='Manter Enquete na Tela Inicial'),
        ),
    ]
