# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-10 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('contracheques', '0001_initial')]

    operations = [migrations.AlterModelManagers(name='rubrica', managers=[])]
