# Generated by Django 3.2.5 on 2022-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracheques', '0002_auto_20191010_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='tipo_importacao',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Fita Espelho'), (2, 'Webservice')], default=1, null=True, verbose_name='Tipo de Importação'),
        ),
    ]
