# Generated by Django 3.2.5 on 2022-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracheques', '0003_contracheque_tipo_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
