# Generated by Django 3.2.5 on 2022-03-29 09:18

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0038_auto_20211215_1218'),
        ('contracheques', '0004_contracheque_excluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracheque',
            name='ano',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.ano', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='mes',
            field=models.SmallIntegerField(choices=[[1, 'Janeiro'], [2, 'Fevereiro'], [3, 'Março'], [4, 'Abril'], [5, 'Maio'], [6, 'Junho'], [7, 'Julho'], [8, 'Agosto'], [9, 'Setembro'], [10, 'Outubro'], [11, 'Novembro'], [12, 'Dezembro']], verbose_name='Mês'),
        ),
    ]
