# Generated by Django 3.2.5 on 2022-03-29 09:46

from django.db import migrations


def atualizado_contracheques(apps, schema_editor):
    ContraCheque = apps.get_model("contracheques", "ContraCheque")

    # atualizando contracheques com valores nulos
    ContraCheque.objects.filter(
        servidor_situacao__isnull=True,
        bruto__isnull=True,
        desconto__isnull=True,
        liquido__isnull=True,
        pensionista__isnull=True,
        servidor__excluido=True,
    ).update(excluido=True)

    # atualizando contracheques que não tem rubricas
    ContraCheque.objects.filter(contrachequerubrica__isnull=True, servidor_situacao__isnull=True).update(excluido=True)


class Migration(migrations.Migration):

    dependencies = [
        ("contracheques", "0005_auto_20220329_0918"),
    ]

    operations = [
        migrations.RunPython(atualizado_contracheques),
    ]
