# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [('financeiro', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('rh', '0001_initial'), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
                ('eh_vinculadora', models.BooleanField(default=False, verbose_name='Vinculadora?')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'permissions': (('vincular_acao', 'Pode vincular ação'), ('desvincular_acao', 'Pode desvincular ação')),
            },
        ),
        migrations.CreateModel(
            name='AcaoPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_inicial', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Inicial')),
                ('data_final', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Final')),
                ('execucao', models.SmallIntegerField(default=0, verbose_name='Execução')),
                ('cadastro_sistemico', models.BooleanField(default=False, verbose_name='Cadastrada pelo sistêmico')),
                (
                    'validacao',
                    djtools.db.models.CharFieldPlus(
                        choices=[('Deferida', 'Deferida'), ('Indeferida', 'Indeferida'), ('Em análise', 'Em análise'), ('Não analisada', 'Não analisada')],
                        default='Não analisada',
                        max_length=255,
                        verbose_name='Validação',
                    ),
                ),
            ],
            options={'verbose_name': 'Ação no Plano de Ação', 'verbose_name_plural': 'Ações no Plano de Ação'},
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('execucao', models.SmallIntegerField(default=0, verbose_name='Execução')),
                (
                    'validacao',
                    djtools.db.models.CharFieldPlus(
                        choices=[('Deferida', 'Deferida'), ('Indeferida', 'Indeferida'), ('Em análise', 'Em análise'), ('Não analisada', 'Não analisada')],
                        default='Não analisada',
                        max_length=255,
                        verbose_name='Validação',
                    ),
                ),
                (
                    'validacao_vinculadora',
                    djtools.db.models.CharFieldPlus(
                        choices=[('Deferida', 'Deferida'), ('Indeferida', 'Indeferida'), ('Em análise', 'Em análise'), ('Não analisada', 'Não analisada')],
                        default='Não analisada',
                        max_length=255,
                        verbose_name='Validação Vinculadora',
                    ),
                ),
                ('acao_pa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.AcaoPA', verbose_name='Ação')),
                (
                    'acao_pa_vinculadora',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_vinculada', to='plan_v2.AcaoPA', verbose_name='Ação Vinculadora'
                    ),
                ),
            ],
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Dimensão', 'verbose_name_plural': 'Dimensões', 'ordering': ('codigo',)},
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Eixo', 'verbose_name_plural': 'Eixos', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Denominação')),
                ('criterio_analise', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Críterio de Análise')),
                ('forma_calculo', models.TextField(verbose_name='Forma de Cálculo')),
                ('valor_fisico_inicial', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Inicial')),
                ('valor_fisico_final', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Final')),
                (
                    'metodo_incremento',
                    djtools.db.models.CharFieldPlus(
                        choices=[
                            ('Soma', 'Soma'),
                            ('Média', 'Média'),
                            ('Máximo', 'Máximo'),
                            ('Mínimo', 'Mínimo'),
                            ('Último', 'Último'),
                            ('Relação com a referência', 'Relação com a referência'),
                        ],
                        max_length=255,
                        verbose_name='Método de Incremento',
                    ),
                ),
            ],
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.CreateModel(
            name='IndicadorPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Inicial')),
                ('valor_final', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Final')),
                (
                    'tipo_composicao',
                    djtools.db.models.CharFieldPlus(choices=[('Soma', 'Soma'), ('Média', 'Média')], default='Soma', max_length=255, verbose_name='Tipo de Composição'),
                ),
                ('indicador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Indicador')),
            ],
            options={'verbose_name': 'Indicador no Plano de Ação', 'verbose_name_plural': 'Indicadores no Plano de Ação'},
        ),
        migrations.CreateModel(
            name='IndicadorPAUnidadeAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Inicial')),
                ('valor_final', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Físico Final')),
                ('indicador_pa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.IndicadorPA')),
            ],
            options={'verbose_name': 'Indicador da unidade no Plano de Ação', 'verbose_name_plural': 'Indicador da unidade no Plano de Ação'},
        ),
        migrations.CreateModel(
            name='Macroprocesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dimensao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Dimensao', verbose_name='Dimensão')),
            ],
            options={'verbose_name': 'Macroprocesso', 'verbose_name_plural': 'Macroprocessos'},
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('associado', models.BooleanField(default=False)),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('codigo_dimensao', models.IntegerField(null=True, verbose_name='Código da Dimensão')),
                ('codigo_macroprocesso', models.IntegerField(null=True, verbose_name='Código do Macroprocesso')),
                ('codigo_objetivo', models.IntegerField(null=True, verbose_name='Código do Objetivo')),
            ],
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.CreateModel(
            name='MetaPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Meta')),
            ],
            options={'verbose_name': 'Meta no Plano de Ação', 'verbose_name_plural': 'Metas no Plano de Ação'},
        ),
        migrations.CreateModel(
            name='NaturezaDespesaPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'natureza_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa', verbose_name='Natureza de Despesa'),
                ),
            ],
            options={
                'verbose_name': 'Natureza de Despesa do PDI',
                'verbose_name_plural': 'Naturezas de Despesa do PDI',
                'permissions': (
                    ('pode_ver_planoacao_naturezadespesapa', 'Pode ver natureza de despesa no plano de ação'),
                    ('pode_vincular_naturezadespesapa', 'Pode vincular natureza de despesa no plano de ação'),
                ),
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('codigo_dimensao', models.IntegerField(null=True, verbose_name='Código da Dimensão')),
                ('codigo_macroprocesso', models.IntegerField(null=True, verbose_name='Código do Macroprocesso')),
            ],
            options={
                'verbose_name': 'Objetivo Estratégico',
                'verbose_name_plural': 'Objetivos Estratégicos',
                'permissions': (
                    ('pode_ver_planoacao_objetivoestrategico', 'Pode ver objetivo estratégico no plano de ação'),
                    ('pode_importar_objetivoestrategico', 'Pode importar objetivo estratégico no plano de ação'),
                ),
            },
        ),
        migrations.CreateModel(
            name='OrigemRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_capital', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor de Capital')),
                ('valor_custeio', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor de Custeio')),
                ('visivel_campus', models.BooleanField(default=True, help_text='Indica se a origem do recurso é visualizada pelos campi.', verbose_name='Visível')),
                ('codigo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Código')),
                ('destinacao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Destinação')),
                (
                    'acao_financeira',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='origem_recurso_acaofinanceira', to='financeiro.AcaoAno', verbose_name='Ação Orçamentária'
                    ),
                ),
                ('dimensao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Dimensao', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name': 'Origem do Recurso',
                'verbose_name_plural': 'Origens dos Recursos',
                'permissions': (('pode_ver_planoacao_origemrecurso', 'Pode ver origem de recurso no plano de ação'),),
            },
        ),
        migrations.CreateModel(
            name='OrigemRecursoUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_capital', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Capital')),
                ('valor_custeio', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Custeio')),
                ('origem_recurso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.OrigemRecurso')),
            ],
            options={
                'verbose_name': 'Origem de Recurso de UA',
                'verbose_name_plural': 'Origens de Recurso de UA',
                'permissions': (('pode_detalhar_origemrecursoua', 'Pode detalhar a origem de recurso UA no plano de ação'),),
            },
        ),
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'ano_final',
                    djtools.db.models.ForeignKeyPlus(
                        help_text='Vigência final do PDI', on_delete=django.db.models.deletion.CASCADE, related_name='ano_final_pdi', to='comum.Ano', verbose_name='Ano Final'
                    ),
                ),
                (
                    'ano_inicial',
                    djtools.db.models.ForeignKeyPlus(
                        help_text='Vigência inicial do PDI', on_delete=django.db.models.deletion.CASCADE, related_name='ano_inicial_pdi', to='comum.Ano', verbose_name='Ano Inicial'
                    ),
                ),
            ],
            options={'verbose_name': 'PDI', 'verbose_name_plural': 'PDIs'},
        ),
        migrations.CreateModel(
            name='PDIAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('codigo_dimensao', models.IntegerField(null=True, verbose_name='Código da Dimensão')),
                ('codigo_macroprocesso', models.IntegerField(null=True, verbose_name='Código do Macroprocesso')),
                ('ativa_planoacao', models.BooleanField(default=True, verbose_name='Ativa para o Plano Ação Vigente')),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Acao', verbose_name='Ação')),
                ('pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='plan_v2.PDI', verbose_name='PDI')),
            ],
            options={'verbose_name': 'Ação do PDI', 'verbose_name_plural': 'Ações do PDI', 'ordering': ('codigo_dimensao', 'codigo_macroprocesso', 'codigo')},
        ),
        migrations.CreateModel(
            name='PDIMacroprocesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('codigo_dimensao', models.IntegerField(null=True, verbose_name='Código da Dimensão')),
                ('macroprocesso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Macroprocesso', verbose_name='Macroprocesso')),
                ('pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='macroprocessos', to='plan_v2.PDI', verbose_name='PDI')),
            ],
            options={'verbose_name': 'MacroProcesso do PDI', 'verbose_name_plural': 'MacroProcessos do PDI', 'ordering': ('codigo_dimensao', 'codigo')},
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geral_inicial', djtools.db.models.DateFieldPlus(verbose_name='Início da Vigência')),
                ('data_geral_final', djtools.db.models.DateFieldPlus(verbose_name='Fim da Vigência')),
                ('data_metas_inicial', djtools.db.models.DateFieldPlus(verbose_name='Início do Cadastro Sistêmico')),
                ('data_metas_final', djtools.db.models.DateFieldPlus(verbose_name='Fim do Cadastro Sistêmico')),
                ('data_acoes_inicial', djtools.db.models.DateFieldPlus(verbose_name='Início do Cadastro do Campus')),
                ('data_acoes_final', djtools.db.models.DateFieldPlus(verbose_name='Fim dp Cadastro do Campus')),
                ('data_validacao_inicial', djtools.db.models.DateFieldPlus(verbose_name='Início da Validação')),
                ('data_validacao_final', djtools.db.models.DateFieldPlus(verbose_name='Fim da Validação')),
                ('ano_base', djtools.db.models.OneToOneFieldPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano Base')),
                ('pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PDI')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ('ano_base',),
                'permissions': (('pode_detalhar_planoacao', 'Pode ver detalhe do plano de ação'), ('pode_ver_todo_planoacao', 'Pode acessar todo o plano de acao')),
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data Solicitação')),
                ('tipo', djtools.db.models.CharFieldPlus(choices=[('Ação', 'Ação')], default='Ação', max_length=255, verbose_name='Tipo')),
                ('solicitacao', models.TextField(verbose_name='Solicitação')),
                (
                    'parecer',
                    djtools.db.models.CharFieldPlus(
                        choices=[('Aceito', 'Aceito'), ('Rejeitado', 'Rejeitado'), ('Em espera', 'Em espera')], default='Em espera', max_length=255, verbose_name='Parecer'
                    ),
                ),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                (
                    'solicitante',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Solicitante',
                    ),
                ),
            ],
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.CreateModel(
            name='UnidadeAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo',
                    models.CharField(
                        choices=[('Campus', 'Campus'), ('Diretoria Sistêmica', 'Diretoria Sistêmica'), ('Pró-Reitoria', 'Pró-Reitoria')], max_length=20, verbose_name='Tipo'
                    ),
                ),
                ('pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PDI')),
                (
                    'setor_equivalente',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_setor', to='rh.Setor', verbose_name='Setor Equivalente'),
                ),
                ('setores_participantes', models.ManyToManyField(related_name='unidade_setor_participante', to='rh.Setor', verbose_name='Participantes')),
            ],
            options={'verbose_name': 'Unidade Administrativa', 'verbose_name_plural': 'Unidades Administrativas', 'ordering': ('tipo', 'setor_equivalente__nome')},
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida', 'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='unidade_administrativa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.UnidadeAdministrativa'),
        ),
        migrations.AddField(
            model_name='origemrecursoua',
            name='unidade_administrativa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.UnidadeAdministrativa'),
        ),
        migrations.AddField(
            model_name='origemrecurso', name='plano_acao', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PlanoAcao')
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='pdi_macroprocesso',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PDIMacroprocesso', verbose_name='Macroprocesso'),
        ),
        migrations.AddField(
            model_name='naturezadespesapa',
            name='plano_acao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PlanoAcao', verbose_name='Plano de Ação'),
        ),
        migrations.AddField(model_name='metapa', name='plano_acao', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PlanoAcao')),
        migrations.AddField(
            model_name='meta',
            name='objetivo_estrategico',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.ObjetivoEstrategico', verbose_name='Objetivo Estratégico'),
        ),
        migrations.AddField(
            model_name='meta',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_setor', to='rh.Setor', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='indicadorpaunidadeadministrativa',
            name='unidade_administrativa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.UnidadeAdministrativa'),
        ),
        migrations.AddField(model_name='indicadorpa', name='meta_pa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.MetaPA')),
        migrations.AddField(model_name='indicador', name='meta', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Meta')),
        migrations.AddField(model_name='dimensao', name='eixo', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Eixo')),
        migrations.AddField(
            model_name='dimensao',
            name='setor_sistemico',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Setor sistêmico responsável pela dimensão', on_delete=django.db.models.deletion.CASCADE, related_name='dimensao_setor', to='rh.Setor'
            ),
        ),
        migrations.AddField(
            model_name='atividade',
            name='natureza_despesa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_v2.NaturezaDespesaPA', verbose_name='Natureza de Despesa'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='origem_recurso',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_v2.OrigemRecurso', verbose_name='Origem de Recurso'),
        ),
        migrations.AddField(
            model_name='acaopa', name='acao', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.PDIAcao', verbose_name='Ação')
        ),
        migrations.AddField(
            model_name='acaopa', name='meta_pa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.MetaPA', verbose_name='Meta')
        ),
        migrations.AddField(
            model_name='acaopa',
            name='setores_responsaveis',
            field=models.ManyToManyField(related_name='acao_setores_responsaveis', to='rh.Setor', verbose_name='Setores Responsáveis'),
        ),
        migrations.AddField(
            model_name='acaopa',
            name='unidade_administrativa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.UnidadeAdministrativa', verbose_name='Unidade Administrativa'),
        ),
        migrations.AddField(
            model_name='acao', name='macroprocesso', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_v2.Macroprocesso')
        ),
        migrations.AlterUniqueTogether(name='unidadeadministrativa', unique_together=set([('pdi', 'setor_equivalente')])),
        migrations.AlterUniqueTogether(name='planoacao', unique_together=set([('pdi', 'ano_base')])),
        migrations.AlterUniqueTogether(name='pdimacroprocesso', unique_together=set([('pdi', 'macroprocesso')])),
        migrations.AlterUniqueTogether(name='pdiacao', unique_together=set([('pdi', 'acao')])),
        migrations.AlterUniqueTogether(name='pdi', unique_together=set([('ano_inicial', 'ano_final')])),
        migrations.AlterUniqueTogether(name='origemrecursoua', unique_together=set([('origem_recurso', 'unidade_administrativa')])),
        migrations.AlterUniqueTogether(name='objetivoestrategico', unique_together=set([('pdi_macroprocesso', 'descricao')])),
        migrations.AlterUniqueTogether(name='metapa', unique_together=set([('plano_acao', 'meta')])),
        migrations.AlterUniqueTogether(name='indicadorpaunidadeadministrativa', unique_together=set([('indicador_pa', 'unidade_administrativa')])),
        migrations.AlterUniqueTogether(name='indicadorpa', unique_together=set([('indicador', 'meta_pa')])),
        migrations.AlterUniqueTogether(name='acaopa', unique_together=set([('meta_pa', 'unidade_administrativa', 'acao')])),
    ]
