# Generated by Django 2.2.10 on 2020-02-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('centralservicos', '0001_initial')]

    operations = [migrations.AlterModelOptions(name='chamadoanexo', options={'ordering': ['anexado_em'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'})]
