# Generated by Django 2.2.10 on 2020-04-09 19:01

import django.core.validators
from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('centralservicos', '0002_auto_20200217_1332')]

    operations = [
        migrations.AlterField(
            model_name='baseconhecimentoanexo',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(
                upload_to='upload/baseconhecimento/anexos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'docx', 'doc', 'pdf', 'jpg', 'jpeg', 'png', 'zip', 'txt'])],
            ),
        )
    ]
