# Generated by Django 2.2.16 on 2021-05-26 14:20

from django.conf import settings
from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('centralservicos', '0003_auto_20200409_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconhecimento',
            name='grupos_atendimento',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, help_text='Não selecione nenhuma opção para exibir esta base de conhecimento em todos os grupos de atendimento.', to='centralservicos.GrupoAtendimento', verbose_name='Restringir aos Grupos de Atendimento'),
        ),
        migrations.AlterField(
            model_name='baseconhecimento',
            name='servicos',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, help_text='Não selecione nenhuma opção para exibir esta base de conhecimento em todos os serviços.', related_name='base_conhecimento_servicos_set', to='centralservicos.Servico', verbose_name='Restringir aos Serviços'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='outros_interessados',
            field=djtools.db.models.ManyToManyFieldPlus(help_text='Vincule neste chamado outros usuários que desejem acompanhar alterações e comentários deste chamado.', related_name='outros_interessados_set', to=settings.AUTH_USER_MODEL, verbose_name='Outros Interessados'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='bases_conhecimento',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, help_text='Sugestão de bases de conhecimento para este chamado', related_name='comunicacao_basesconhecimento_set', to='centralservicos.BaseConhecimento', verbose_name='Bases de Conhecimento'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='usuarios_citados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='usuarios_citados_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Citados'),
        ),
        migrations.AlterField(
            model_name='grupoatendimento',
            name='atendentes',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='atendentes_set', to=settings.AUTH_USER_MODEL, verbose_name='Atendentes Vinculados ao Grupo'),
        ),
        migrations.AlterField(
            model_name='grupoatendimento',
            name='responsaveis',
            field=djtools.db.models.ManyToManyFieldPlus(help_text='O responsável pelo grupo de atendimento deve ser um dos atendentes.', related_name='responsaveis_set', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='grupointeressado',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='grupointeressados_set', to=settings.AUTH_USER_MODEL, verbose_name='Interessados'),
        ),
        migrations.AlterField(
            model_name='gruposervico',
            name='categorias',
            field=djtools.db.models.ManyToManyFieldPlus(to='centralservicos.CategoriaServico'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='bases_conhecimento',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='basesconhecimento_set', to='centralservicos.BaseConhecimento', verbose_name='Bases de Conhecimento utilizadas'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='grupos',
            field=djtools.db.models.ManyToManyFieldPlus(to='centralservicos.GrupoAtendimento', verbose_name='Grupo de Atendimento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='centros_atendimento',
            field=djtools.db.models.ManyToManyFieldPlus(help_text='Informe pelo menos um centro de atendimento responsável pelo atendimento do chamado.', related_name='servicos_centros_atendimento_set', to='centralservicos.CentroAtendimento', verbose_name='Centros de Atendimento'),
        ),
    ]
