# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralservicos', '0004_auto_20210526_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconhecimento',
            name='necessita_correcao',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, help_text='Marque esta opção caso esta base de conhecimento necessite de alguma correção.', null=True, verbose_name='Necessita correção?'),
        ),
        migrations.AlterField(
            model_name='baseconhecimento',
            name='supervisao_pendente',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, help_text='Marque esta opção caso esta base de conhecimento necessite de aprovação por algum supervisor.', null=True, verbose_name='Supervisão pendente?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='autorizado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorizado?'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='fechado_automaticamente',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fechado Automaticamente?'),
        ),
    ]
