# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('financeiro', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
            ],
            options={'verbose_name': 'Crédito Orçamentário', 'verbose_name_plural': 'Créditos Orçamentários'},
        ),
        migrations.CreateModel(
            name='EstruturaProgramaticaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True)),
                ('ano_base', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano Base')),
                (
                    'programa_trabalho',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalho', verbose_name='Programa de Trabalho'),
                ),
            ],
            options={'verbose_name': 'Estrutura Programática Financeira', 'verbose_name_plural': 'Estruturas Programáticas Financeira'},
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida', 'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='estruturaprogramaticafinanceira',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='credito', name='epf', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='orcamento.EstruturaProgramaticaFinanceira')
        ),
        migrations.AddField(
            model_name='credito', name='fonte_recurso', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso')
        ),
        migrations.AddField(
            model_name='credito', name='natureza_despesa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa')
        ),
        migrations.AlterUniqueTogether(name='estruturaprogramaticafinanceira', unique_together=set([('ano_base', 'programa_trabalho')])),
        migrations.AlterUniqueTogether(name='credito', unique_together=set([('epf', 'natureza_despesa', 'fonte_recurso')])),
    ]
