# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='ComissaoPDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('central', 'Central'), ('tematica', 'Temática'), ('local', 'Local')], max_length=10, verbose_name='Tipo de Comissão')),
            ],
            options={'verbose_name': 'Comissão do PDI', 'verbose_name_plural': 'Comissões do PDI', 'ordering': ['tipo', 'nome']},
        ),
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('periodo_inicial', models.DateField(verbose_name='Data Inicial do PDI')),
                ('periodo_final', models.DateField(verbose_name='Data Final do PDI')),
                ('periodo_sugestao_inicial', models.DateField(verbose_name='Data Inicial de Contribuições')),
                ('periodo_sugestao_final', models.DateField(verbose_name='Data Final de Contribuições')),
                ('periodo_sugestao_melhoria_inicial', models.DateField(default='2014-05-09', verbose_name='Data Inicial de Proposta de Melhoria')),
                ('periodo_sugestao_melhoria_final', models.DateField(default='2014-05-09', verbose_name='Data Final de Proposta de Melhoria')),
                ('data_final_local', models.DateField(verbose_name='Data Final da Comissão Local')),
                ('data_final_tematica', models.DateField(verbose_name='Data Final da Comissão Temática')),
                ('qtd_caracteres_contribuicao', models.IntegerField(verbose_name='Quantidade de Caracteres para Contribuição da Comunidade')),
                ('qtd_caracteres_comissao_local', models.IntegerField(verbose_name='Quantidade de Caracteres para Redação Local')),
            ],
            options={'verbose_name': 'PDI', 'verbose_name_plural': 'PDIs'},
        ),
        migrations.CreateModel(
            name='SecaoPDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.PDI', verbose_name='PDI')),
            ],
            options={'verbose_name': 'Eixos do PDI', 'verbose_name_plural': 'Eixos do PDI', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='SecaoPDICampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Redação Proposta')),
                ('anexo', models.FileField(blank=True, max_length=255, upload_to='pdi/anexos/')),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
                ('secao_pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.SecaoPDI', verbose_name='Seção do PDI')),
            ],
            options={'verbose_name': 'Produção das Comissões Locais', 'verbose_name_plural': 'Produções das Comissões Locais'},
        ),
        migrations.CreateModel(
            name='SecaoPDIInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, max_length=255, upload_to='pdi/anexos/')),
                ('secao_pdi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdi.SecaoPDI', verbose_name='Seção do PDI')),
            ],
            options={'verbose_name': 'Produção das Comissões Temáticas', 'verbose_name_plural': 'Produções das Comissões Temáticas'},
        ),
        migrations.CreateModel(
            name='SugestaoComunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Contribuição')),
                ('analisada', models.BooleanField(default=False)),
                (
                    'anonima',
                    models.BooleanField(
                        default=False,
                        help_text='Como anônimo, o seu nome não será exibido na lista de Contribuições da Comunidade e não permitirá edição.',
                        verbose_name='Publicar anonimamente?',
                    ),
                ),
                (
                    'cadastrada_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
                ('secao_pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.SecaoPDI', verbose_name='Eixo do PDI')),
            ],
            options={'verbose_name': 'Contribuição da Comunidade', 'verbose_name_plural': 'Contribuições da Comunidade'},
        ),
        migrations.CreateModel(
            name='SugestaoComunidadeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concorda', models.NullBooleanField()),
                (
                    'cadastrada_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('sugestao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.SugestaoComunidade', verbose_name='Contribuição da Comunidade')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='SugestaoConsolidacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Contribuição')),
                ('analisada', models.BooleanField(default=False)),
                (
                    'anonima',
                    models.BooleanField(
                        default=False,
                        help_text='Como anônimo, o seu nome não será exibido na lista de Contribuições da Comunidade e não permitirá edição.',
                        verbose_name='Publicar anonimamente?',
                    ),
                ),
                (
                    'cadastrada_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
                ('secao_pdi', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.SecaoPDI', verbose_name='Eixo do PDI')),
            ],
            options={'verbose_name': 'Contribuição da Comunidade para a Consolidação', 'verbose_name_plural': 'Contribuições da Comunidade para a Consolidação'},
        ),
        migrations.CreateModel(
            name='SugestaoConsolidacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concorda', models.NullBooleanField()),
                (
                    'cadastrada_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sugestao',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='pdi.SugestaoConsolidacao', verbose_name='Contribuição da Comunidade Consolidação'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='comissaopdi', name='pdi', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pdi.PDI', verbose_name='PDI')
        ),
        migrations.AddField(model_name='comissaopdi', name='secoes', field=models.ManyToManyField(to='pdi.SecaoPDI', verbose_name='Seção do PDI')),
        migrations.AddField(model_name='comissaopdi', name='vinculos_avaliadores', field=models.ManyToManyField(to='comum.Vinculo')),
        migrations.AlterUniqueTogether(name='secaopdicampus', unique_together=set([('secao_pdi', 'campus')])),
    ]
