# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secaopdicampus',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, upload_to='pdi/anexos/'),
        ),
        migrations.AlterField(
            model_name='secaopdiinstitucional',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, upload_to='pdi/anexos/'),
        ),
    ]
