# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0002_auto_20210301_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestaocomunidadeusuario',
            name='concorda',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sugestaoconsolidacaousuario',
            name='concorda',
            field=models.BooleanField(null=True),
        ),
    ]
