version: '3.9'
services:

  opensearch-node1:
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - opensearch-net
    image: opensearchproject/opensearch:1.3.2
    ports:
      - ${SEARCH_HTTP_PORT:-9200}:${SEARCH_HTTP_PORT:-9200}
      - ${SEARCH_REPL_PORT:-9600}:${SEARCH_REPL_PORT:-9600}
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - network.host=0.0.0.0
      - ELASTIC_USER=admin
      - ELASTIC_PASSWORD=admin
    volumes:
      - .././volumes/opensearch_node1_data:/usr/share/opensearch/data

  opensearch-dashboards:
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - opensearch-net
    image: opensearchproject/opensearch-dashboards:1.3.2
    ports:
      - ${DASHBOARD_PORT:-5601}:${DASHBOARD_PORT:-5601}
    environment:
      OPENSEARCH_HOSTS: '["https://node1:${SEARCH_HTTP_PORT:-9200}"]'

networks:
  opensearch-net:
    driver: bridge
    #bridge, host, and none

volumes:
    postgres: