# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:57


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_periodo1', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Início do Período 1')),
                ('data_fim_periodo1', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Fim do Período 1')),
                ('data_inicio_periodo2', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Início do Período 2')),
                ('data_fim_periodo2', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Fim do Período 2')),
                ('data_inicio_periodo3', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Início do Período 3')),
                ('data_fim_periodo3', djtools.db.models.DateFieldPlus(blank=True, db_index=True, null=True, verbose_name='Data de Fim do Período 3')),
                ('quitacao', models.PositiveIntegerField(null=True)),
                ('criado_em', djtools.db.models.DateTimeFieldPlus(null=True)),
                ('observacao_criacao', models.TextField(blank=True, verbose_name='Observação')),
                ('validado_em', djtools.db.models.DateTimeFieldPlus(null=True)),
                ('observacao_validacao', models.TextField(blank=True, verbose_name='Observação Chefia')),
                ('cadastrado_em', djtools.db.models.DateTimeFieldPlus(null=True)),
                (
                    'gratificacao_natalina',
                    models.PositiveIntegerField(
                        choices=[[0, 'Sem Adiantamento'], [1, 'Período 1'], [2, 'Período 2'], [3, 'Período 3']], default=0, verbose_name='Gratificação Natalina'
                    ),
                ),
                (
                    'setenta_porcento',
                    models.PositiveIntegerField(
                        choices=[
                            [0, 'Sem Adiantamento'],
                            [1, 'Período 1'],
                            [2, 'Período 2'],
                            [3, 'Período 3'],
                            [4, 'Períodos 1 e 2'],
                            [5, 'Períodos 1 e 3'],
                            [6, 'Períodos 2 e 3'],
                            [7, 'Períodos 1, 2 e 3'],
                        ],
                        default=0,
                        help_text='Adiantamento de 70% do salário, proporcional à parcela de férias (desconto integral após 02 meses do recebimento): Caso deseje esta opção, fazer a solicitação no campo acima, especificando em qual ou quais parcelas deseja o adiantamento.',
                        verbose_name='Setenta Porcento',
                    ),
                ),
                ('validado', models.PositiveIntegerField(choices=[[0, 'Pendente'], [1, 'Validado'], [2, 'Invalidado']], default=0, verbose_name='Validado')),
                ('cadastrado', models.BooleanField(default=False)),
                ('atualiza_pelo_extrator', models.BooleanField(default=True, verbose_name='Atualiza pelo Extrator?')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano')),
                (
                    'criado_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to=settings.AUTH_USER_MODEL
                    ),
                ),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
                (
                    'validado_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validado_por', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'ordering': ('servidor__nome', '-ano'),
                'permissions': (
                    ('pode_ver_listagem_ferias', 'Pode ver a listagem de férias'),
                    ('pode_validar_ferias', 'Pode validar férias'),
                    ('pode_ver_calendario_ferias_setor', 'Pode ver calendário de férias'),
                    ('pode_gerar_arquivo_batch_ferias', 'Pode gerar arquivo batch de férias'),
                ),
            },
        ),
        migrations.CreateModel(
            name='InterrupcaoFerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interrupcao_periodo', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Interrupção do Período')),
                ('data_inicio_continuacao_periodo', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Início da Continuação')),
                ('data_fim_continuacao_periodo', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Fim da Continuação')),
                ('ferias', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ferias.Ferias')),
            ],
            options={'verbose_name': 'Interrução de Férias', 'verbose_name_plural': 'Interrupções de Férias', 'ordering': ('ferias', 'data_interrupcao_periodo')},
        ),
        migrations.CreateModel(
            name='PeriodoCadastroFerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo_lancamento',
                    models.PositiveIntegerField(choices=[[0, '--Selecione--'], [1, 'Técnico Administrativo'], [2, 'Docente']], null=True, verbose_name='Tipo de Lançamento'),
                ),
                ('data_inicio_periodo_cadastro', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Inicial')),
                ('data_fim_periodo_cadastro', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Final')),
                ('data_inicio_periodo1_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Início Período 1 de Férias Docentes')),
                ('data_fim_periodo1_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Fim Período 1 de Férias Docentes')),
                ('data_inicio_periodo2_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Início Período 2 de Férias Docentes')),
                ('data_fim_periodo2_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Fim Período 2 de Férias Docentes')),
                ('data_inicio_periodo3_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Início Período 3 de Férias Docentes')),
                ('data_fim_periodo3_ferias_docente', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Fim Período 3 de Férias Docentes')),
                ('ano_referencia', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano de Referência')),
                ('uo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='UO')),
            ],
            options={'verbose_name': 'Período de Lançamento de Férias', 'verbose_name_plural': 'Períodos de Lançamento de Férias', 'ordering': ('ano_referencia',)},
        ),
        migrations.AlterUniqueTogether(name='periodocadastroferias', unique_together=set([('ano_referencia', 'uo', 'tipo_lancamento')])),
        migrations.AlterUniqueTogether(name='interrupcaoferias', unique_together=set([('ferias', 'data_interrupcao_periodo')])),
        migrations.AlterUniqueTogether(name='ferias', unique_together=set([('servidor', 'ano')])),
    ]
