# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:57


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [('edu', '0002_auto_20190814_1454'), ('comum', '0002_auto_20190814_1443'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('situacao', models.IntegerField(blank=True, choices=[[1, 'Em acompanhamento'], [2, 'Finalizado'], [3, 'Prioriário']], null=True, verbose_name='Situação')),
                ('aluno', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
                (
                    'usuario',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
            options={'verbose_name': 'Acompanhamento', 'verbose_name_plural': 'Acompanhamento', 'ordering': ('-data',)},
        ),
        migrations.CreateModel(
            name='AcompanhamentoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Acompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='AcompanhamentoEncaminhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('acompanhamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Acompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inclusao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de envio')),
                ('data_inicio_atividade', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Início')),
                ('data_fim_atividade', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Fim')),
                (
                    'visibilidade',
                    models.BooleanField(
                        default=False, help_text='Marque essa opção para tornar visível esta atividade para os membros ETEP de outros campus', verbose_name='Visibilidade'
                    ),
                ),
            ],
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividade'},
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Tipo')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Acompanhamento', 'verbose_name_plural': 'Tipos de Acompanhamentos', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', djtools.db.models.FileFieldPlus(help_text='Anexe um arquivo referente documento da atividade', upload_to='etep/documento/', verbose_name='Anexo')),
                ('atividade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Atividade')),
            ],
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documento'},
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Tipo')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Encaminhamento', 'verbose_name_plural': 'Tipo de Encaminhamentos', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativado', models.BooleanField(default=True)),
                ('acompanhamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Acompanhamento')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo')),
            ],
            options={'verbose_name': 'Interessado', 'verbose_name_plural': 'Interessados'},
        ),
        migrations.CreateModel(
            name='RegistroAcompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('situacao', models.IntegerField(blank=True, choices=[[1, 'Em acompanhamento'], [2, 'Finalizado'], [3, 'Prioriário']], null=True, verbose_name='Situação')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                (
                    'anexo',
                    djtools.db.models.FileFieldPlus(
                        blank=True, help_text='Anexe um arquivo referente ao acompanhamento do aluno', null=True, upload_to='etep/acompanhamento/', verbose_name='Anexo'
                    ),
                ),
                ('acompanhamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Acompanhamento')),
                (
                    'usuario',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
            options={'abstract': False},
            managers=[('locals', django.db.models.manager.Manager())],
        ),
        migrations.CreateModel(
            name='RegistroAcompanhamentoInteressado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Solicitação de Ciência')),
                ('data_ciencia', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Ciência')),
                ('interessado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Interessado')),
                ('registro_acompanhamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.RegistroAcompanhamento')),
                (
                    'usuario',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInteressado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('adicionado', models.BooleanField(default=True)),
                ('interessado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Interessado')),
                (
                    'usuario',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='SolicitacaoAcompanhamento',
            fields=[
                (
                    'solicitacaousuario_ptr',
                    models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edu.SolicitacaoUsuario'
                    ),
                ),
                ('acompanhamento', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='etep.Acompanhamento')),
                ('aluno', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
            ],
            options={'verbose_name': 'Solicitação de Acompanhamento', 'verbose_name_plural': 'Solicitações de Acompanhamento', 'ordering': ('data_solicitacao',)},
            bases=('edu.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoAcompanhamentoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Categoria')),
                ('solicitacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.SolicitacaoAcompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Tipo')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Atividade', 'verbose_name_plural': 'Tipos de Atividade', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Tipo')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento', 'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.TipoDocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.TipoAtividade', verbose_name='Tipo de Atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='usuario',
            field=djtools.db.models.CurrentUserField(
                blank=True,
                default=djtools.middleware.threadlocals.get_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Autor',
            ),
        ),
        migrations.AddField(
            model_name='acompanhamentoencaminhamento',
            name='encaminhamento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Encaminhamento', verbose_name='Encaminhamento'),
        ),
        migrations.AddField(
            model_name='acompanhamentoencaminhamento',
            name='usuario',
            field=djtools.db.models.CurrentUserField(
                blank=True,
                default=djtools.middleware.threadlocals.get_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário',
            ),
        ),
        migrations.AddField(
            model_name='acompanhamentocategoria',
            name='categoria',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='etep.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterUniqueTogether(name='solicitacaoacompanhamentocategoria', unique_together=set([('solicitacao', 'categoria')])),
        migrations.AlterUniqueTogether(name='registroacompanhamentointeressado', unique_together=set([('registro_acompanhamento', 'interessado')])),
        migrations.AlterUniqueTogether(name='interessado', unique_together=set([('acompanhamento', 'vinculo')])),
        migrations.AlterUniqueTogether(name='acompanhamentoencaminhamento', unique_together=set([('acompanhamento', 'encaminhamento')])),
        migrations.AlterUniqueTogether(name='acompanhamentocategoria', unique_together=set([('acompanhamento', 'categoria')])),
    ]
