# Generated by Django 2.2.10 on 2020-03-06 09:32

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('eventos', '0004_auto_20200217_1455')]

    operations = [
        migrations.AlterField(
            model_name='tipoparticipante',
            name='tipo_participacao',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='tipos_participante', to='eventos.TipoParticipacao', verbose_name='Tipo de Participação'
            ),
        )
    ]
