# Generated by Django 2.2.9 on 2020-07-09 11:31

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200402_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='carga_horaria',
            field=models.CharField(blank=True, help_text='Carga-Horária de participação no evento. Se não for preenchida, a carga-horária do evento será utilizada.', max_length=25, null=True, verbose_name='Carga Horária'),
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_eventos', verbose_name='Imagem')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('evento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Foto de Evento',
                'verbose_name_plural': 'Fotos de Evento',
            },
        ),
        migrations.CreateModel(
            name='AnexoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', djtools.db.models.FileFieldPlus(upload_to='anexos_eventos', verbose_name='Arquivo')),
                ('descricao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('evento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Anexo de Evento',
                'verbose_name_plural': 'Anexos de Evento',
            },
        ),
    ]
