# Generated by Django 2.2.10 on 2020-07-10 09:48

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200430_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio_inscricoes',
            field=djtools.db.models.TimeFieldPlus(blank=True, null=True, verbose_name='Hora de Início das Inscrições'),
        ),
    ]
