# Generated by Django 2.2.16 on 2021-01-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200710_0948'),
        ('eventos', '0007_auto_20200709_1131'),
    ]

    operations = [
    ]
