# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_evento_registrar_presenca_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoparticipacao',
            name='modelo_certificado_padrao',
            field=djtools.db.models.FileFieldPlus(blank=True, help_text='O arquivo de modelo deve ser uma arquivo .docx contendo as marcações #EVENTO#, #PERIODOREALIZACAO#, #ATIVIDADES#, #NOMEDOPARTICIPANTE#, #TIPODOPARTICIPANTE#, #CPF#, #CAMPUS#, #CIDADE#, #UF#, #DATA#, #CODIGOVERIFICADOR#.', null=True, upload_to='eventos/modelo_certificado/', verbose_name='Modelo de Certificado Padrão'),
        ),
        migrations.AlterField(
            model_name='tipoparticipante',
            name='modelo_certificado',
            field=djtools.db.models.FileFieldPlus(blank=True, help_text='O arquivo de modelo deve ser uma arquivo .docx contendo as marcações #EVENTO#, #PARTICIPANTE#, #CPF#, #CAMPUS#, #CIDADE#, #UF#, #DATA#, #CODIGOVERIFICADOR#. Não preencher caso deseje utilizar o modelo padrão.', null=True, upload_to='eventos/modelo_certificado/', verbose_name='Modelo de Certificado'),
        ),
    ]
