# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20210309_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='deferido',
            field=models.BooleanField(null=True, verbose_name='Deferido?'),
        ),
    ]
