# Generated by Django 3.1 on 2021-07-22 15:45

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_evento_deferido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividade',
            },
        ),
        migrations.CreateModel(
            name='AtividadeEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ch', models.IntegerField(verbose_name='Carga-Horária')),
                ('evento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('tipo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoatividade', verbose_name='Tipo de Atividade')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='atividades',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='participantes', to='eventos.AtividadeEvento', verbose_name='Atividades'),
        ),
    ]
