# Generated by Django 3.1 on 2021-08-17 09:41
import json
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


def migrate(apps, editor):
    Evento = apps.get_model('eventos.Evento')
    lista = []
    for e in Evento.objects.all():
        lista.append((e.pk, e.tipo.values_list('id', flat=True).first()))
    with open('/tmp/eventos.json', 'w') as f:
        f.write(json.dumps(lista))


def unmigrate(apps, editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_evento_deferido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Espacialidade',
                'verbose_name_plural': 'Espacialidades',
            },
        ),
        migrations.AlterField(
            model_name='evento',
            name='classificacao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.classificacaoevento', verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ManyToManyField(to='eventos.TipoEvento', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='SubtipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
                ('tipo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Subtipo de Eventos',
                'verbose_name_plural': 'Subtipos de Eventos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='espacialidade',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.espacialidade', verbose_name='Espacialidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='subtipo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.subtipoevento', verbose_name='Subtipo'),
        ),
        migrations.RunPython(migrate, unmigrate)
    ]
