# Generated by Django 3.1 on 2021-08-23 06:08

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_auto_20210722_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeevento',
            name='limite_inscricoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Limite de Inscrições'),
        ),
        migrations.AddField(
            model_name='atividadeevento',
            name='modelo_certificado',
            field=djtools.db.models.FileFieldPlus(blank=True, help_text='O arquivo de modelo deve ser uma arquivo .docx contendo as marcações #EVENTO#, #PARTICIPANTE#, #CPF#, #CAMPUS#, #CIDADE#, #UF#, #DATA#, #CODIGOVERIFICADOR#, #TIPOATIVIDADE#, #ATIVIDADE#, #CHATIVIDADE#. Não preencher caso deseje utilizar o modelo padrão.', null=True, upload_to='eventos/modelo_certificado_atividade/', verbose_name='Modelo de Certificado'),
        ),
    ]
