# Generated by Django 3.1 on 2021-08-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20210817_1232'),
        ('eventos', '0015_auto_20210823_0608'),
    ]

    operations = [
    ]
