# Generated by Django 3.1 on 2021-09-10 12:21

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20210910_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='telefone',
            field=djtools.db.models.BrTelefoneField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
    ]
