# Generated by Django 3.2.5 on 2021-09-14 06:46

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_participante_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeevento',
            name='data',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='atividadeevento',
            name='hora',
            field=djtools.db.models.TimeFieldPlus(blank=True, null=True, verbose_name='Hora'),
        ),
    ]
