# Generated by Django 3.2.5 on 2021-10-04 11:21

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_auto_20211001_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=djtools.db.models.BrTelefoneField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
