# Generated by Django 3.2.5 on 2021-12-23 14:52

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_atividadeevento_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=djtools.db.models.FileFieldPlus(max_length=255, upload_to='eventos/banner', verbose_name='Imagem'),
        ),
    ]
