# Generated by Django 3.2.5 on 2022-03-03 10:28

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_auto_20211223_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeevento',
            name='descricao',
            field=djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título'),
        ),
    ]
