# Generated by Django 3.2.5 on 2022-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_alter_atividadeevento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparticipacao',
            name='ch_organizacao',
            field=models.BooleanField(default=False, help_text='Adicional de 20% da carga horária total do evento', verbose_name='Carga Horária de Organização'),
        ),
    ]
