# Generated by Django 3.2.5 on 2022-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_auto_20220311_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horaria',
            new_name='carga_horaria_str',
        ),
        migrations.AddField(
            model_name='evento',
            name='carga_horaria',
            field=models.IntegerField(null=True, verbose_name='Carga-Horária em segundos'),
        ),
    ]
