# Generated by Django 3.2.5 on 2022-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_auto_20220325_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo?'),
        ),
    ]
