# Generated by Django 3.2.5 on 2022-07-27 10:45

from django.db import migrations
from tqdm import tqdm


def migra_pessoa(apps, schema_editor):
    Convenio = apps.get_model('convenios', 'Convenio')
    ProfissionalLiberal = apps.get_model('convenios', 'ProfissionalLiberal')
    Vinculo = apps.get_model('comum', 'Vinculo')

    for convenio in tqdm(Convenio.objects.filter(conveniadas__isnull=False)):
        for conveniada in convenio.conveniadas.all():
            convenio.vinculos_conveniadas.add(Vinculo.objects.get(pessoa=conveniada))
    for profissional in tqdm(ProfissionalLiberal.objects.all()):
        profissional.vinculo_pessoa = Vinculo.objects.get(pessoa=profissional.pessoa)
        profissional.save()


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_auto_20220727_1045'),
    ]

    operations = [
        migrations.RunPython(migra_pessoa),
    ]
