# Generated by Django 3.2.5 on 2022-07-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_auto_20220727_1045'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='conveniadas',
        ),
        migrations.RemoveField(
            model_name='profissionalliberal',
            name='pessoa',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
