# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


import arquivo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('contenttypes', '0002_remove_content_type_name')]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
                ('identificado_em', models.DateTimeField(null=True)),
                ('validado_em', models.DateTimeField(null=True)),
                ('justificativa_rejeicao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Justificativa Rejeição Imagem')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome do Arquivo')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(choices=[[0, 'Pendente'], [1, 'Identificado'], [2, 'Validado'], [3, 'Imagem Rejeitada']], default=0, verbose_name='Status')),
                ('file', models.ImageField(upload_to=arquivo.models.file_upload_to)),
                ('content_type', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                (
                    'identificado_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_identificado_por', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'permissions': (
                    ('pode_fazer_upload_arquivo', 'Pode realizar o upload de arquivos'),
                    ('pode_validar_arquivo', 'Pode atestar a validade do arquivo'),
                    ('pode_identificar_arquivo', 'Pode identificar do arquivo'),
                ),
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
                ('funcao', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquivo.Funcao', verbose_name='Função')),
                (
                    'superior',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquivo.Processo', verbose_name='Processo Superior'),
                ),
            ],
            options={'verbose_name': 'Processo/Rotina Rh para o Servidor', 'verbose_name_plural': 'Processos/Rotinas Rh para o Servidor'},
        ),
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Arquivo', 'verbose_name_plural': 'Tipos de Arquivo', 'ordering': ('descricao',)},
        ),
        migrations.AddField(model_name='processo', name='tipos_arquivos', field=djtools.db.models.ManyToManyFieldPlus(to='arquivo.TipoArquivo', verbose_name='Tipos Arquivos')),
    ]
