# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('protocolo', '0001_initial'), ('arquivo', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='processo_protocolo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Processo'),
        ),
        migrations.AddField(
            model_name='arquivo', name='tipo_arquivo', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='arquivo.TipoArquivo')
        ),
        migrations.AddField(
            model_name='arquivo',
            name='upload_por',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_upload_por', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='validado_por',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_validado_por', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
