# Generated by Django 2.2.16 on 2021-03-09 20:04

import arquivo.models
from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0002_auto_20190814_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='file',
            field=djtools.db.models.ImageFieldPlus(upload_to=arquivo.models.file_upload_to),
        ),
    ]
