# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 12:17


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dispositivo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome do Dispositivo')),
                (
                    'endereco_mac_dispositivo',
                    djtools.db.models.CharFieldPlus(
                        help_text='O Endereço MAC deve ser informado no formato "0010FA6E384A".', max_length=12, verbose_name='Endereço MAC do Dispositivo'
                    ),
                ),
                ('data_hora_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data e Hora da Solicitação')),
                ('data_validade_autorizacao', djtools.db.models.DateFieldPlus(verbose_name='Data de Validade da Autorização')),
                ('expirada', models.BooleanField(default=False, verbose_name='Expirada')),
                ('excluida', models.BooleanField(default=False, verbose_name='Cancelada')),
                (
                    'localizacao_dispositivo',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Sala', verbose_name='Localização do Dispositivo'
                    ),
                ),
                ('vinculo_solicitante', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Solicitante')),
            ],
            options={'verbose_name': 'Autorização de Dispositivo IoT', 'verbose_name_plural': 'Autorizações de Dispositivo IoT'},
        ),
        migrations.CreateModel(
            name='TokenWifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateFieldPlus(verbose_name='Data da Solicitação')),
                ('validade', models.IntegerField(verbose_name='Validade em Dias')),
                ('identificacao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Identificação')),
                ('chave', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Valor')),
                (
                    'cadastrado_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tokenwifiresponsavel_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Cadastrado Por',
                    ),
                ),
                (
                    'usuario_solicitante',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
                ),
            ],
            options={'verbose_name': 'Token Wifi', 'verbose_name_plural': 'Tokens Wifi'},
        ),
    ]
