# Generated by Django 3.2.5 on 2022-03-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacaodispositivo',
            options={'permissions': (('pode_escolher_prazo_extendido_iot', 'Pode escolher prazo extendido e quantidade dispositivos ilimitado'), ('eh_administrador_iot', 'É administrador dos dispositivos IOT')), 'verbose_name': 'Autorização de Dispositivo IoT', 'verbose_name_plural': 'Autorizações de Dispositivo IoT'},
        ),
    ]
