# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='AvaliacaoComponenteCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Carga-horária total da disciplina')),
                ('sequencia_didatica', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Sequência Didática ')),
                ('ementa_programa', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Ementa e Programa')),
                ('regime_misto', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Regime Misto')),
                ('justificativa', models.TextField(null=True, verbose_name='Resposta')),
                ('aprovada', models.NullBooleanField(verbose_name='Validada')),
            ],
            options={'verbose_name': 'Avaliação de Componente', 'verbose_name_plural': 'Avaliações de Componente', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='GrupoPergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Grupo de Pergunta', 'verbose_name_plural': 'Grupo de Pergunta', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='OpcaoRespostaPergunta',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('valor', djtools.db.models.CharFieldPlus(max_length=255))],
            options={'verbose_name': 'Opção de Resposta para uma Pergunta', 'verbose_name_plural': 'Opções de Resposta para uma Pergunta', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Enunciado')),
                ('tipo_resposta', models.IntegerField(choices=[(1, 'SIM/NÃO'), (2, 'ESCALA PADRÃO'), (3, 'SUBJETIVA'), (4, 'OBJETIVA')], verbose_name='Tipo de Resposta')),
                ('multipla_escolha', models.BooleanField(default=False, verbose_name='Múltipla Escolha?')),
                ('obrigatoria', models.BooleanField(default=False, verbose_name='Obrigatória?')),
            ],
            options={'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('data_termino', djtools.db.models.DateFieldPlus(verbose_name='Data de Término')),
                ('avaliacao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Avaliacao', verbose_name='Avaliação')),
            ],
            options={'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Respondente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Questionário Finalizado')),
                ('questionario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Questionario', verbose_name='Questionário')),
            ],
            options={'verbose_name': 'Respondente', 'verbose_name_plural': 'Respondentes', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(null=True, verbose_name='Resposta')),
                ('aprovada', models.NullBooleanField(verbose_name='Validada')),
                ('pergunta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Pergunta', verbose_name='Questionário')),
                ('respondente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Respondente', verbose_name='Respondente')),
            ],
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('forma_identificacao', models.TextField(null=True, verbose_name='Forma de Identificação')),
            ],
            options={'verbose_name': 'Segmento Respondente', 'verbose_name_plural': 'Segmentos Respondentes', 'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='respondente',
            name='segmento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='setor',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='vinculo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo'),
        ),
    ]
