# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('edu', '0001_initial'), ('avaliacao_cursos', '0001_initial')]

    operations = [
        migrations.AddField(model_name='questionario', name='modalidades', field=models.ManyToManyField(to='edu.Modalidade', verbose_name='Modalidades')),
        migrations.AddField(model_name='questionario', name='segmentos', field=models.ManyToManyField(to='avaliacao_cursos.Segmento', verbose_name='Segmentos')),
        migrations.AddField(
            model_name='pergunta',
            name='grupo_pergunta',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.GrupoPergunta', verbose_name='Grupo de Pergunta'),
        ),
        migrations.AddField(
            model_name='opcaorespostapergunta',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Pergunta', verbose_name='Pergunta'),
        ),
        migrations.AddField(
            model_name='grupopergunta',
            name='questionario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Questionario', verbose_name='Questionário'),
        ),
        migrations.AddField(
            model_name='avaliacaocomponentecurricular',
            name='componente_curricular',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.ComponenteCurricular', verbose_name='Componente Curricular'),
        ),
        migrations.AddField(
            model_name='avaliacaocomponentecurricular',
            name='respondente',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.Respondente', verbose_name='Respondente'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ano',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='ano_avaliacao_set', to='comum.Ano', verbose_name='Ano'),
        ),
    ]
