# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_cursos', '0002_auto_20190814_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocomponentecurricular',
            name='aprovada',
            field=models.BooleanField(null=True, verbose_name='Validada'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='aprovada',
            field=models.BooleanField(null=True, verbose_name='Validada'),
        ),
    ]
