# Generated by Django 3.2.5 on 2022-07-18 09:53

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0093_auto_20220709_1909'),
        ('avaliacao_cursos', '0003_auto_20210719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='matrizes',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='edu.Matriz', verbose_name='Matrizes'),
        ),
    ]
