# Generated by Django 3.2.5 on 2022-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_cursos', '0004_questionario_matrizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupopergunta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.IntegerField(choices=[(1, 'SIM/NÃO'), (2, 'ESCALA PADRÃO'), (6, 'ESCALA DE SUFICIÊNCIA'), (7, 'ESCALA DE SATISFAÇÃO'), (5, 'ESCALA DE QUALIDADE'), (8, 'ESCALA DE CONCORDÂNCIA'), (3, 'SUBJETIVA'), (4, 'OBJETIVA')], verbose_name='Tipo de Resposta'),
        ),
    ]
