# Generated by Django 3.2.5 on 2022-07-25 17:08

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0099_aula_outros_professor_diario'),
        ('avaliacao_cursos', '0006_auto_20220720_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaAvaliacaoComponenteCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.IntegerField(choices=[[1, 'CH'], [3, 'Sequência Didática'], [3, 'Ementa']], verbose_name='Campo')),
                ('justificativa', models.TextField(null=True, verbose_name='Resposta')),
                ('componente_curricular', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.componentecurricular', verbose_name='Componente Curricular')),
                ('respondente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_cursos.respondente', verbose_name='Respondente')),
            ],
            options={
                'verbose_name': 'Justificativa de Avaliação de Componente',
                'verbose_name_plural': 'Justificativas de Avaliação de Componente',
                'ordering': ('id',),
            },
        ),
    ]
