# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 16:07
from __future__ import unicode_literals

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('projetos', '0001_initial')]

    operations = [migrations.AddField(model_name='visitatecnica', name='cnpj', field=djtools.db.models.BrCnpjField(blank=True, max_length=18, null=True, verbose_name='CNPJ'))]
