# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('projetos', '0002_visitatecnica_cnpj')]

    operations = [
        migrations.AddField(
            model_name='projeto', name='possui_acoes_empreendedorismo', field=models.NullBooleanField(verbose_name='O Projeto Contempla Ações de Empreendedorismo?')
        )
    ]
