# Generated by Django 2.2.7 on 2019-12-13 10:03

from django.db import migrations
from django.core.management import call_command


def atualizar_vinculo_projeto_anexo(apps, schema):
    call_command('atualizar_vinculo_projetoanexo')


class Migration(migrations.Migration):

    dependencies = [('projetos', '0004_auto_20191101_1400')]

    operations = [migrations.RunPython(atualizar_vinculo_projeto_anexo)]
