# Generated by Django 2.2.7 on 2020-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('projetos', '0005_auto_20191213_1003')]

    operations = [
        migrations.AlterModelOptions(
            name='participacao', options={'verbose_name': 'Participação em Projeto de Extensão', 'verbose_name_plural': 'Participações em Projetos de Extensão'}
        ),
        migrations.AddField(
            model_name='participacao',
            name='ch_extensao',
            field=models.IntegerField(
                blank=True, help_text='Carga horária total destinada a atividade curricular de extensão', null=True, verbose_name='Carga Horária de Extensão'
            ),
        ),
    ]
