# Generated by Django 2.2.16 on 2021-03-09 20:04

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20210301_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoprojeto',
            name='imagem',
            field=djtools.db.models.ImageFieldPlus(upload_to='upload/projetos/fotos/'),
        ),
    ]
