# Generated by Django 2.2.16 on 2021-04-22 16:24

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0018_auto_20210401_1853'),
        ('projetos', '0008_auto_20210309_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFrequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=2000, verbose_name='Descrição')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária')),
                ('cadastrada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrado em')),
                ('atendida', models.NullBooleanField(verbose_name='Atendida')),
                ('validada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                ('cadastrada_por', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_cadastro_registrofrequencia', to='comum.Vinculo', verbose_name='Cadastrado por')),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
                ('validada_por', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_avaliacao_registrofrequencia', to='comum.Vinculo', verbose_name='Avaliada por')),
            ],
            options={
                'verbose_name': 'Registro de Frequência/Atividade do Projeto',
                'verbose_name_plural': 'Registros de Frequência/Atividade do Projeto',
            },
        ),
    ]
