# Generated by Django 2.2.16 on 2021-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_registrofrequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalanexo',
            name='tipo_membro',
            field=models.CharField(choices=[('1', 'Docente'), ('5', 'Técnico Administrativo'), ('2', 'Aluno'), ('3', 'Coordenador Docente'), ('4', 'Coordenador Técnico Administrativo'), ('6', 'Colaborador Voluntário'), ('7', 'Coordenador(a) Professor(a) Visitante'), ('8', 'Professor(a) Visitante')], max_length=1, verbose_name='Tipo de Membro'),
        ),
    ]
