# Generated by Django 3.2.5 on 2021-12-21 14:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_merge_20211028_1549'),
        ('projetos', '0012_auto_20210719_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacao',
            options={'ordering': ['-responsavel', 'id'], 'verbose_name': 'Participação em Projeto de Extensão', 'verbose_name_plural': 'Participações em Projetos de Extensão'},
        ),
        migrations.AddField(
            model_name='edital',
            name='exige_anuencia',
            field=djtools.db.models.CharFieldPlus(choices=[('Não', 'Não'), ('Apenas de coordenadores TAES', 'Apenas de coordenadores TAES'), ('De todos os Coordenadores', 'De todos os Coordenadores'), ('De todos os TAES', 'De todos os TAES'), ('De todos os servidores', 'De todos os servidores')], default='Não', help_text='Ao exigir para coordenadores, apenas os projetos com registro da anuência da chefia poderão avançar para a fase de pré-seleção. Já os membros da equipe só poderão ser vinculados às atividades e imprimir certificados após o registro da anuência.', max_length=30, verbose_name='Exigir Anuência da Chefia'),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_aluno',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do aluno participante do projeto.', null=True, verbose_name='Termo de Compromisso do Aluno'),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_colaborador_voluntario',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do colaborador voluntário participante do projeto.', null=True, verbose_name='Termo de Compromisso do Colaborador Voluntário'),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_coordenador',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do coordenador do projeto.', null=True, verbose_name='Termo de Compromisso do Coordenador'),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_servidor',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do servidor participante do projeto.', null=True, verbose_name='Termo de Compromisso do Servidor'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='anuencia',
            field=models.BooleanField(null=True, verbose_name='Chefia de Acordo'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='anuencia_registrada_em',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Anuência Registrada em'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='responsavel_anuencia',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_projeto_responsavel_anuencia', to='rh.servidor', verbose_name='Responsável pela Anuência'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='termo_aceito_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='anuencia',
            field=models.BooleanField(null=True, verbose_name='Chefia de Acordo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='anuencia_registrada_em',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Anuência Registrada em'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel_anuencia',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_responsavel_anuencia', to='rh.servidor', verbose_name='Responsável pela Anuência'),
        ),
    ]
