# Generated by Django 3.2.5 on 2022-01-26 16:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_auto_20211221_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorvoluntario',
            options={'ordering': ['nome'], 'verbose_name': 'Colaborador Externo', 'verbose_name_plural': 'Colaboradores Externos'},
        ),
        migrations.AlterField(
            model_name='edital',
            name='permite_colaborador_voluntario',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso seja permitida a inclusão de colaborador externo nas equipes dos projetos', verbose_name='Permite Colaborador Externo'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='permite_colaborador_voluntario_artes',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso seja permitida a inclusão de colaborador externo vinculado ao núcleo de arte nas equipes dos projetos', verbose_name='Permite Voluntário Vinculado ao Núcleo de Arte'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='termo_compromisso_colaborador_voluntario',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do colaborador externo participante do projeto.', null=True, verbose_name='Termo de Compromisso do Colaborador Externo'),
        ),
        migrations.AlterField(
            model_name='editalanexo',
            name='tipo_membro',
            field=models.CharField(choices=[('1', 'Docente'), ('5', 'Técnico Administrativo'), ('2', 'Aluno'), ('3', 'Coordenador Docente'), ('4', 'Coordenador Técnico Administrativo'), ('6', 'Colaborador Externo'), ('7', 'Coordenador(a) Professor(a) Visitante'), ('8', 'Professor(a) Visitante')], max_length=1, verbose_name='Tipo de Membro'),
        ),
        migrations.AlterField(
            model_name='historicoequipe',
            name='tipo_de_evento',
            field=models.PositiveIntegerField(blank=True, choices=[(11, 'Saiu da coordenação do projeto'), (12, 'Tornou-se coordenador do projeto'), (1, 'Assumiu a coordenação do projeto'), (2, 'Aluno inserido'), (3, 'Servidor inserido'), (13, 'Colaborador Externo inserido'), (4, 'Participante ativado'), (5, 'Participante inativado'), (6, 'Participante excluído'), (7, 'Bolsa concedida durante a distribuição de bolsas'), (8, 'Bolsas não concedida durante a distribuição de bolsas'), (9, 'Aluno alterado'), (10, 'Servidor alterado'), (14, 'Colaborador Externo alterado')]),
        ),
    ]
