# Generated by Django 3.2.5 on 2022-02-08 12:53

from django.db import migrations, models
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_auto_20220126_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='possui_cooperacao_internacional',
            field=models.BooleanField(default=False, verbose_name='Possui acordo de cooperação internacional vigente'),
        ),
        migrations.AlterField(
            model_name='colaboradorvoluntario',
            name='documentacao',
            field=djtools.db.models.PrivateFileField(blank=True, null=True, storage=djtools.storages.get_private_storage(), upload_to='projetos/colaborador_voluntario', verbose_name='Documentação'),
        ),
    ]
