# Generated by Django 3.2.5 on 2022-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_auto_20220208_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoequipe',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
