# Generated by Django 3.2.5 on 2022-06-07 14:39

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_setor_equivalencia_codigo'),
        ('projetos', '0017_edital_colaborador_externo_bolsista'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='instituicao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='numero_agencia',
            field=models.CharField(help_text='Ex: 3293-X', max_length=50, null=True, verbose_name='Número da Agência'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='numero_conta',
            field=models.CharField(help_text='Ex: 23384-6', max_length=50, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='operacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='tipo_conta',
            field=models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança')], max_length=50, null=True, verbose_name='Tipo da Conta'),
        ),
    ]
