# Generated by Django 3.2.5 on 2022-06-21 11:22

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_setor_equivalencia_codigo'),
        ('projetos', '0019_edital_sistemico_pode_submeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='avaliadorexterno',
            name='pessoa_fisica',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_avaliador_externo', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='avaliadorindicado',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='historicoalteracaoperiodoprojeto',
            name='registrado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_registradopor_historicodata', to='rh.pessoafisica'),
        ),
    ]
