# Generated by Django 3.2.5 on 2022-06-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_auto_20220621_1122'),
    ]
    state_operations = [
        migrations.RemoveField(
            model_name='areatematica',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='avaliacaoaluno',
            name='avaliado_por',
        ),
        migrations.RemoveField(
            model_name='avaliadorexterno',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='avaliadorindicado',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='comissaoedital',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='historicoalteracaoperiodoprojeto',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='itemavaliacao',
            name='responsavel_alteracao',
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='autor_avaliacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='autor_pre_avaliacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='projetoanexo',
            name='membro_equipe',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetoanexo',
            options={'ordering': ['vinculo_membro_equipe__pessoa__nome']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )

    ]
