# Generated by Django 3.2.5 on 2022-06-29 10:56

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0042_alter_solicitacaoreservasala_status'),
        ('projetos', '0021_auto_20220621_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='autorizado',
            field=models.BooleanField(default=True, null=True, verbose_name='Edital autorizado'),
        ),
        migrations.AddField(
            model_name='edital',
            name='autorizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Autorizado em'),
        ),
        migrations.AddField(
            model_name='edital',
            name='autorizado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_edital_autorizado_por', to='comum.vinculo', verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='edital',
            name='cadastrado_em',
            field=djtools.db.models.DateTimeFieldPlus(auto_now_add=True, null=True, verbose_name='Cadastrado em'),
        ),
        migrations.AddField(
            model_name='edital',
            name='cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_edital_cadastrado_por', to='comum.vinculo', verbose_name='Cadastrado por'),
        ),
    ]
