# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_fabric', models.PositiveSmallIntegerField(blank=True, verbose_name='Ano de Fabricação')),
                ('placa_codigo_atual', models.CharField(max_length=9, unique=True, verbose_name='Placa')),
                ('placa_codigo_anterior', models.CharField(max_length=9, null=True)),
                ('lotacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('odometro', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidade_tanque', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacidade_gnv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chassi', models.CharField(max_length=17, null=True, unique=True)),
                ('renavam', models.CharField(max_length=11, null=True, unique=True)),
                ('potencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cilindrada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                (
                    'rendimento_estimado',
                    djtools.db.models.DecimalFieldPlus(
                        decimal_places=2,
                        default=Decimal('0.0'),
                        help_text='Estimativa de quantos quilômetros o veículo percorre com um litro de combustível',
                        max_digits=12,
                        verbose_name='Rendimento Estimado',
                    ),
                ),
            ],
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos', 'ordering': ['modelo', 'placa_codigo_atual']},
        ),
        migrations.CreateModel(
            name='VeiculoCombustivel',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20, unique=True))],
            options={'verbose_name': 'Combustível do Veículo', 'verbose_name_plural': 'Combustíveis de Veículos', 'ordering': ['-nome']},
        ),
        migrations.CreateModel(
            name='VeiculoCor',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20, unique=True))],
            options={'verbose_name': 'Cor do Veículo', 'verbose_name_plural': 'Cores de Veículos', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='VeiculoEspecie',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('descricao', models.CharField(max_length=20, unique=True))],
            options={'verbose_name': 'Espécie de Veículo', 'verbose_name_plural': 'Espécies de Veículos', 'ordering': ['descricao']},
        ),
        migrations.CreateModel(
            name='VeiculoMarca',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20, unique=True))],
            options={'verbose_name': 'Marca de Veículo', 'verbose_name_plural': 'Marcas de Veículos', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='VeiculoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('marca', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoMarca')),
            ],
            options={'verbose_name': 'Modelo de Veículo', 'verbose_name_plural': 'Modelos de Veículos', 'ordering': ['marca', 'nome']},
        ),
        migrations.CreateModel(
            name='VeiculoTipo',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('descricao', models.CharField(max_length=20, unique=True))],
            options={'verbose_name': 'Tipo de Veículo', 'verbose_name_plural': 'Tipos de Veículos', 'ordering': ['descricao']},
        ),
        migrations.CreateModel(
            name='VeiculoTipoEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoEspecie')),
                ('tipo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoTipo')),
            ],
            options={'verbose_name': 'Tipo e Espécie do Veículo', 'verbose_name_plural': 'Tipos e Espécies dos Veículos', 'ordering': ['tipo']},
        ),
        migrations.AddField(
            model_name='veiculotipo', name='especie', field=models.ManyToManyField(through='estacionamento.VeiculoTipoEspecie', to='estacionamento.VeiculoEspecie')
        ),
        migrations.AddField(
            model_name='veiculomodelo',
            name='tipo_especie',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoTipoEspecie', verbose_name='Tipo e Espécie'),
        ),
        migrations.AddField(model_name='veiculo', name='combustiveis', field=models.ManyToManyField(to='estacionamento.VeiculoCombustivel')),
        migrations.AddField(model_name='veiculo', name='condutores', field=models.ManyToManyField(to='rh.PessoaFisica')),
        migrations.AddField(model_name='veiculo', name='cor', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoCor')),
        migrations.AddField(
            model_name='veiculo', name='modelo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.VeiculoModelo')
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa_municipio_anterior',
            field=djtools.db.models.ForeignKeyPlus(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Municipio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa_municipio_atual',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='veiculo_placa_municipio_anterior_set',
                to='comum.Municipio',
                verbose_name='Localização',
            ),
        ),
        migrations.AddField(model_name='veiculo', name='vinculos_condutores', field=models.ManyToManyField(to='comum.Vinculo')),
        migrations.AlterUniqueTogether(name='veiculomodelo', unique_together=set([('nome', 'marca')])),
    ]
