# Generated by Django 3.2.5 on 2022-05-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='condutores',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
