# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('financeiro', '0001_initial'), ('rh', '0001_initial'), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('detalhamento', models.TextField()),
                ('quantidade', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('execucao', models.SmallIntegerField(default=0, verbose_name='Execução')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                (
                    'status',
                    models.CharField(
                        default='Não Avaliada',
                        max_length=30,
                        verbose_name=[['Deferida', 'Deferida'], ['Indeferida', 'Indeferida'], ['Não Avaliada', 'Não Avaliada'], ['Parcialmente Deferida', 'Parcialmente Deferida']],
                    ),
                ),
            ],
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações', 'ordering': ['codigo', 'titulo']},
        ),
        migrations.CreateModel(
            name='AcaoExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('texto', models.TextField()),
                ('percentual', models.SmallIntegerField(verbose_name='Execução')),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Acao')),
            ],
            options={'verbose_name': 'Acompanhamento da Ação', 'verbose_name_plural': 'Acompanhamentos da Ação', 'ordering': ['-data']},
        ),
        migrations.CreateModel(
            name='AcaoExtraTeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('detalhamento', models.TextField()),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_previsto', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Previsto')),
            ],
            options={'verbose_name': 'Ação Extra Teto', 'verbose_name_plural': 'Ações Extra Teto', 'ordering': ['titulo']},
        ),
        migrations.CreateModel(
            name='AcaoProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('data_inicial', models.DateField(null=True)),
                ('data_final', models.DateField(null=True)),
                ('acao_orcamento', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Acao')),
                ('fonte_financiamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso')),
            ],
            options={'verbose_name': 'Ação Proposta', 'verbose_name_plural': 'Ações Propostas', 'ordering': ['codigo', 'titulo']},
        ),
        migrations.CreateModel(
            name='AcaoValidacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                (
                    'status',
                    models.CharField(
                        max_length=30,
                        verbose_name=[['Deferida', 'Deferida'], ['Indeferida', 'Indeferida'], ['Não Avaliada', 'Não Avaliada'], ['Parcialmente Deferida', 'Parcialmente Deferida']],
                    ),
                ),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Acao')),
            ],
            options={'verbose_name': 'Comentário da Ação', 'verbose_name_plural': 'Comentários da Ação', 'ordering': ['acao', 'status'], 'get_latest_by': 'data'},
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unitario', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Unitário')),
                ('execucao', models.SmallIntegerField(default=0, verbose_name='Execução')),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Acao', verbose_name='Ação')),
            ],
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades', 'ordering': ['acao', 'descricao']},
        ),
        migrations.CreateModel(
            name='AtividadeExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('texto', models.TextField()),
                ('percentual', models.SmallIntegerField(verbose_name='Execução')),
                ('atividade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Atividade')),
            ],
            options={'verbose_name': 'Acompanhamento da Atividade', 'verbose_name_plural': 'Acompanhamentos da Atividade', 'ordering': ['-data']},
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geral_inicial', models.DateField()),
                ('data_geral_final', models.DateField()),
                ('data_metas_inicial', models.DateField()),
                ('data_metas_final', models.DateField()),
                ('data_acoes_inicial', models.DateField()),
                ('data_acoes_final', models.DateField()),
                ('data_validacao_inicial', models.DateField()),
                ('data_validacao_final', models.DateField()),
                ('data_planilhas_inicial', models.DateField()),
                ('data_planilhas_final', models.DateField()),
                ('ano_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano Base')),
            ],
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações', 'ordering': ['ano_base']},
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, unique=True, verbose_name='Descrição')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('setor_sistemico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor')),
            ],
            options={'verbose_name': 'Dimensão', 'verbose_name_plural': 'Dimensões', 'ordering': ['codigo', 'descricao']},
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('justificativa', models.TextField()),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas', 'ordering': ['objetivo_estrategico__codigo', 'codigo', 'titulo']},
        ),
        migrations.CreateModel(
            name='MetaUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('valor_total', djtools.db.models.DecimalFieldPlus(decimal_places=2, default=Decimal('0.0'), max_digits=12, verbose_name='Valor Total')),
                ('meta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Meta')),
            ],
            options={'verbose_name': 'Unidade Administrativa da Meta', 'verbose_name_plural': 'Unidades Administrativas das Metas', 'ordering': ['meta', 'unidade']},
        ),
        migrations.CreateModel(
            name='MetaUnidadeAcaoProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('valor_unitario', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário')),
                ('acao_proposta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.AcaoProposta', verbose_name='Ação Proposta')),
                ('meta_unidade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.MetaUnidade', verbose_name='Unid. Administrativa')),
            ],
            options={
                'verbose_name': 'Unid. Administrativa da Ação Proposta',
                'verbose_name_plural': 'Unids. Administrativas das Ações Propostas',
                'ordering': ['meta_unidade', 'acao_proposta'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'naturezadespesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa', verbose_name='Natureza de Despesa'),
                ),
            ],
            options={'verbose_name': 'Natureza de Despesa', 'verbose_name_plural': 'Naturezas de despesas', 'ordering': ['naturezadespesa']},
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_projeto_institucional', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Macro Projeto Institucional')),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Cadastro')),
                ('descricao', models.TextField(verbose_name='Objetivo Estratégico')),
                ('codigo', models.IntegerField(null=True, verbose_name='Código')),
                ('configuracao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Configuracao', verbose_name='Ano Base')),
                ('dimensao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Dimensao', verbose_name='Dimensão')),
            ],
            options={'verbose_name': 'Macro Projeto Institucional', 'verbose_name_plural': 'Macro Projeto Institucional', 'ordering': ['dimensao', 'codigo', 'descricao']},
        ),
        migrations.CreateModel(
            name='OrigemRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('valor_disponivel', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Disponível')),
                ('valor_capital', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor de Capital')),
                ('valor_custeio', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor de Custeio')),
                ('visivel_campus', models.BooleanField(default=False, help_text='Indica se a origem do recurso é visualizada pelos campi.', verbose_name='Visível')),
                ('funcionamento_campus', models.BooleanField(default=False, verbose_name='Destinado ao funcionamento do Campus')),
                ('acao_ano', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.AcaoAno', verbose_name='Ação')),
                ('configuracao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Configuracao', verbose_name='Ano base')),
                ('dimensao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.Dimensao', verbose_name='Dimensão')),
            ],
            options={'verbose_name': 'Origem do Recurso', 'verbose_name_plural': 'Origens dos Recursos', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='OrigemRecursoUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_capital', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Capital')),
                ('valor_custeio', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Custeio')),
                (
                    'origem_recurso',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.OrigemRecurso', verbose_name='Origem de Recurso'),
                ),
            ],
            options={'verbose_name': 'Origem de Recurso de UA', 'verbose_name_plural': 'Origens de Recurso de UA'},
        ),
        migrations.CreateModel(
            name='UnidadeAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_simec', models.CharField(blank=True, max_length=6, verbose_name='Código SIMEC')),
                ('codigo_simec_digito', models.CharField(blank=True, max_length=1, verbose_name='Dígito')),
                ('tipo', models.CharField(choices=[['Campus', 'Campus'], ['Diretoria Sistêmica', 'Diretoria Sistêmica'], ['Pró-Reitoria', 'Pró-Reitoria']], max_length=20)),
                ('orcamento', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Orçamento Próprio')),
                ('configuracao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Configuracao', verbose_name='Ano base')),
                ('setor_equivalente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor Equivalente')),
            ],
            options={'verbose_name': 'Unidade Administrativa', 'verbose_name_plural': 'Unidades Administrativas', 'ordering': ['setor_equivalente__nome']},
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida', 'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='origemrecursoua',
            name='unidade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeAdministrativa', verbose_name='Unidade Administrativa'),
        ),
        migrations.AddField(
            model_name='metaunidade',
            name='unidade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeAdministrativa', verbose_name='Unidade Administrativa'),
        ),
        migrations.AddField(
            model_name='meta',
            name='objetivo_estrategico',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.ObjetivoEstrategico', verbose_name='Objetivo Estratégico'),
        ),
        migrations.AddField(
            model_name='meta',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='elemento_despesa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.NaturezaDespesa', verbose_name='Elemento de Despesa'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_recurso',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.OrigemRecurso', verbose_name='Origem de Recurso'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(model_name='acaoproposta', name='meta', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.Meta')),
        migrations.AddField(
            model_name='acaoproposta',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='acaoextrateto',
            name='unidade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeAdministrativa', verbose_name='Unidade Administrativa'),
        ),
        migrations.AddField(
            model_name='acaoextrateto',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='acao',
            name='acao_indutora',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.MetaUnidadeAcaoProposta'),
        ),
        migrations.AddField(
            model_name='acao', name='acao_orcamento', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Acao')
        ),
        migrations.AddField(
            model_name='acao', name='fonte_financiamento', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso')
        ),
        migrations.AddField(
            model_name='acao',
            name='meta_unidade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='planejamento.MetaUnidade', verbose_name='Meta'),
        ),
        migrations.AddField(
            model_name='acao',
            name='setor_responsavel',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor Responsável'),
        ),
        migrations.AddField(
            model_name='acao',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_acao_unidademedida', to='planejamento.UnidadeMedida'
            ),
        ),
        migrations.AlterUniqueTogether(name='origemrecursoua', unique_together=set([('origem_recurso', 'unidade')])),
        migrations.AlterUniqueTogether(name='origemrecurso', unique_together=set([('nome', 'dimensao', 'configuracao')])),
        migrations.AlterUniqueTogether(name='objetivoestrategico', unique_together=set([('configuracao', 'descricao', 'dimensao')])),
        migrations.AlterUniqueTogether(name='metaunidadeacaoproposta', unique_together=set([('meta_unidade', 'acao_proposta')])),
        migrations.AlterUniqueTogether(name='metaunidade', unique_together=set([('meta', 'unidade')])),
        migrations.AlterUniqueTogether(name='meta', unique_together=set([('objetivo_estrategico', 'titulo')])),
        migrations.AlterUniqueTogether(name='atividade', unique_together=set([('acao', 'descricao', 'elemento_despesa')])),
        migrations.AlterUniqueTogether(name='acaoproposta', unique_together=set([('meta', 'titulo')])),
        migrations.AlterUniqueTogether(name='acao', unique_together=set([('meta_unidade', 'titulo')])),
    ]
