# -*- coding: utf-8 -*-

from django.urls import path

from planejamento import views

urlpatterns = [
    # cadastros
    path('origemrecurso/', views.origemrecurso_anobase_atual),
    path('origemrecurso/<int:id>/', views.origemrecurso),
    path('unidadeadministrativa/', views.unidadeadministrativa_anobase_atual),
    path('origemrecursoua/', views.origemrecursoua_anobase_atual),
    path('objetivoestrategico/', views.objetivoestrategico_anobase_atual),
    path('objetivoestrategico/<int:id>/', views.objetivoestrategico),
    path('meta/', views.meta_anobase_atual),
    path('meta/<int:id>/', views.meta),
    path('meta/<int:id>/remover/', views.meta_remover),
    path('metaunidade/', views.metaunidade_anobase_atual),
    path('metaunidade/<int:id>/', views.metaunidade),
    path('metaunidade/<int:id>/remover/', views.metaunidade_remover),
    path('acaoproposta/', views.acaoproposta_anobase_atual),
    path('acaoproposta/<int:id>/', views.acaoproposta),
    path('acaoproposta/<int:id>/remover/', views.acaoproposta_remover),
    path('metaunidadeacaoproposta/<int:id>/remover/', views.metaunidadeacaoproposta_remover),
    path('acao/', views.acao_anobase_atual),
    path('acao/<int:id>/', views.acao),
    path('acao/<int:id>/remover/', views.acao_remover),
    path('acao_busca/', views.acao_busca),
    path('atividade/<int:id>/', views.atividade),
    path('atividade/<int:id>/remover/', views.atividade_remover),
    path('renumerar_acoes/', views.renumerar_acoes),
    path('renumeracao_acoes_validar_periodo/', views.renumeracao_acoes_validar_periodo),
    # (r'^objetivoestrategico/<int:id>/metas/', views.objetivoestrategico_metas),
    # (r'^objetivoestrategico/<int:id_objetivo_estrategico>/meta/<int:id_meta>/remover/', views.meta_remover),
    # (r'^objetivoestrategico/<int:id_objetivo_estrategico>/meta/<int:id_meta>/', views.meta),
    # (r'^meta/<int:id>/metaunidades/', views.meta_metaunidades),
    # (r'^meta/<int:id_meta>/metaunidade/<int:id_meta_unidade>/remover/', views.metaunidade_remover),
    # (r'^meta/<int:id_meta>/metaunidade/<int:id_meta_unidade>/', views.metaunidade),
    # (r'^meta/<int:id_meta>/acoespropostas/', views.meta_acoespropostas),
    # (r'^meta/<int:id_meta>/acaoproposta/<int:id_acao_proposta>/remover/', views.acaoproposta_remover),
    # (r'^meta/<int:id_meta>/acaoproposta/<int:id_acao_proposta>/', views.acaoproposta),
    # (r'^metaunidade/', views.metaunidade_anobase_atual),
    # (r'^metaunidade/<int:id_meta_unidade>/acoespropostas/<int:id_meta_unidade_acao_proposta>/', views.metaunidade_acoespropostas),
    # (r'^metaunidade/<int:id>/acoes/', views.metaunidade_acoes),
    # (r'^metaunidade/<int:id_meta_unidade>/acao/<int:id_acao>/remover/', views.acao_remover),
    # (r'^metaunidade/<int:id_meta_unidade>/acao/<int:id_acao>/', views.acao),
    # (r'^acaoproposta/', views.acaoproposta_anobase_atual),
    # (r'^acaoproposta/<int:id>/unidades/', 'acaoproposta_metaunidades),
    # (r'^acaoproposta/<int:id_acao_proposta>/unidade/<int:id_meta_unidade_acao_proposta>/remover/', views.metaunidadeacaoproposta_remover),
    # (r'^acaoproposta/<int:id_acao_proposta>/unidade/<int:id_meta_unidade_acao_proposta>/', views.metaunidadeacaoproposta),
    # acoes
    # (r'^acao/', views.acao_anobase_atual),
    # (r'^acao/<int:id>/', views.acao_view),
    # (r'^acao/<int:id>/atividades/', 'acao_atividades),
    # (r'^acao/<int:id_acao>/atividade/<int:id_atividade>/remover/', views.atividade_remover),
    # (r'^acao/<int:id_acao>/atividade/<int:id_atividade>/', views.atividade),
    # (r'^acaovalidacao/<int:id>/', views.acaovalidacao_view),
    # (r'^acao_busca/', views.acao_busca),
    # atividades
    # (r'^atividade/<int:id>/', views.atividade_view),
    # acaoextrateto
    path('acaoextrateto/', views.acaoextrateto_anobase_atual),
    # campus
    path('resumocampus/', views.resumo_campus),
    # execucao
    path('acompanhamento/sistemico/', views.acompanhamento_sistemico),
    path('acompanhamento/execucao/', views.acompanhamento_execucao),
    path('acompanhamento/objetivoestrategico/<int:id_obj_estrategico>/', views.acompanhamento_objetivoestrategico),
    path('acompanhamento/metaunidade/<int:id_metaunidade>/', views.acompanhamento_metaunidade),
    path('acompanhamento/acao/<int:id_acao>/', views.acompanhamento_acao),
    path('acompanhamento/acao/<int:id_acao>/detalhar/', views.acompanhamento_acao_detalhar),
    path('acompanhamento/atividade/<int:id_atividade>/', views.acompanhamento_atividade),
    path('acompanhamento/atividade/<int:id_atividade>/detalhar/', views.acompanhamento_atividade_detalhar),
    path('acompanhamento/acaoatividades/<int:id_acao>/', views.acompanhamento_acao_atividades),
    # relatorios
    path('relatorio/geral/', views.relatorio_geral),
    path('relatorio/geralacaoorcamento/', views.relatorio_geral_acao_orcamento),
    path('relatorio/resumo/executivo/', views.resumo_executivo),
    path('relatorio/detalhamento/', views.detalhamento),
    path('relatorio/planoacao/', views.planoacao),
    path('relatorio/acoes/', views.relatorio_acoes),
    path('relatorio/acoes/origemrecurso/<int:id_origem_recurso>/dimensao/<int:id_dimensao>/unidadeadministrativa/<int:id_unidade_administrativa>/',
         views.relatorio_acoes_recurso_dimensao_unidade,
         ),
    path('relatorio/acoes/origemrecurso/<int:id_origem_recurso>/dimensao/unidadeadministrativa/acao/<int:id_acao>/', views.relatorio_acoes_recurso_dimensao_unidade_acao),
    path('relatorio/naturezadespesa/', views.relatorio_natureza_despesa),
    path('relatorio/acoes/dimensao/', views.relatorio_acoes_dimensao),
    path('relatorio/metas/', views.relatorio_metas),
    path('relatorio/despesas/orcamento/detalhamento/', views.detalhamento_despesas_orcamento),
    path('relatorio/despesas/orcamento/comparativo/', views.comparativo_despesas_orcamento),
    path('relatorio/despesas/acoes/naturezadespesa/', views.relatorio_despesas_acoes_elementos_despesa),
    path('relatorio/despesas/recurso/', views.despesas_recurso),
    path('relatorio/despesas/recurso/unidadeadministrativa/', views.despesas_recurso_unidadeadministrativa),
    path('relatorio/despesas/recurso/dimensao/', views.despesas_recurso_dimensao),
    path('relatorio/despesa/detalhamento/gastos/', views.relatorio_detalhamento_gastos),
    path('relatorio/acao/orcamento/', views.relatorio_acoes_orcamento),
    path('relatorio/acao/orcamento/total/<int:id_fonte>/<str:id_acao>/', views.relatorio_acoes_orcamento_total),
    path('relatorio/acao/orcamento/campus/<int:id_fonte>/<str:id_acao>/<int:id_campus>/', views.relatorio_acoes_orcamento_campus),
    path('relatorio/origemrecursoua/<int:id_unidade>/', views.relatorio_tabela_origem_recurso),
    path('relatorio/origemrecurso/', views.relatorio_origem_recurso),
    # validacoes
    path('campi/validar/', views.campi_validar),
    path('unidadeadministrativa/<int:id_campus>/metaunidade/validar/', views.metas_unidade_validar),
    path('metaunidade/<int:id_meta_unidade>/validar/', views.acoes_validar),
    path('acoes/validacao/', views.acoes_validacao),
    path('acao/<int:id_meta_unidade>/validar/<str:id_acao>/', views.validacao_confirmar),
    path('acao/comentario/<str:id_acao>/', views.comentario_detalhar),
    # novas validacoes
    path('acao/validar/', views.metaunidade_validacao),
    #    path('acao/validar/<int:id_meta_unidade>/', views.metaunidade_validacao_acoes),
    path('relatorio/avaliar/acoes/', views.relatorio_avaliar_acoes),
]
