# Generated by Django 2.2.7 on 2020-01-31 13:25

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('tesouro_gerencial', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Conta Contábil', 'verbose_name_plural': 'Conta Contábeis'},
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='favorecido_ug',
            field=djtools.db.models.ForeignKeyPlus(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='nc_gerencial_favorecido_ug',
                to='tesouro_gerencial.UnidadeGestora',
                verbose_name='UG Favorecida',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notacredito', name='numero', field=models.CharField(default=None, max_length=23, unique=True, verbose_name='Número'), preserve_default=False
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='unidade_orcamentaria',
            field=djtools.db.models.ForeignKeyPlus(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='unidade_orcamentaria_ci',
                to='tesouro_gerencial.ClassificacaoInstitucional',
                verbose_name='Unidade Orçamentaria',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notacreditoitem',
            name='nota_credito',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tesouro_gerencial.NotaCredito'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='conta_contabil',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesouro_gerencial.ContaContabil', verbose_name='Conta Contábil'),
        ),
    ]
