# Generated by Django 2.2.10 on 2020-03-26 14:03

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('tesouro_gerencial', '0003_auto_20200227_0936')]

    operations = [
        migrations.AlterField(model_name='rap', name='numero', field=djtools.db.models.CharFieldPlus(max_length=23, verbose_name='Número')),
        migrations.AlterUniqueTogether(name='rap', unique_together={('numero', 'ano')}),
    ]
