# Generated by Django 2.2.16 on 2021-03-15 11:20

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_gerencial', '0004_auto_20200326_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoempenho',
            options={'ordering': ['numero'], 'verbose_name': 'Documento de Empenho', 'verbose_name_plural': 'Documentos de Empenho'},
        ),
        migrations.AddField(
            model_name='notacreditoitem',
            name='grupo_despesa_original',
            field=djtools.db.models.CharFieldPlus(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacreditoitem',
            name='naturesa_despesa_original',
            field=djtools.db.models.CharFieldPlus(default='', max_length=6),
            preserve_default=False,
        ),
    ]
