# Generated by Django 2.2.16 on 2021-05-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_gerencial', '0005_auto_20210503_1259'),
        ('tesouro_gerencial', '0005_auto_20210315_1120'),
    ]

    operations = [
    ]
