# Generated by Django 3.2.5 on 2021-10-29 11:56

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_gerencial', '0007_auto_20211022_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempenho',
            name='grupo_despesa_original',
            field=djtools.db.models.CharFieldPlus(max_length=2),
        ),
        migrations.AlterField(
            model_name='documentoliquidacao',
            name='grupo_despesa_original',
            field=djtools.db.models.CharFieldPlus(max_length=2),
        ),
        migrations.AlterField(
            model_name='documentopagamento',
            name='grupo_despesa_original',
            field=djtools.db.models.CharFieldPlus(max_length=2),
        ),
    ]
