# Generated by Django 3.2.5 on 2022-02-25 08:31

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouro_gerencial', '0008_auto_20211029_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoEmpenhoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('aplicar_calculo', models.BooleanField(default=False, verbose_name='Aplicar a regra sobre o cálculo das variáveis financeiras')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Empenho Específico',
                'verbose_name_plural': 'Tipos de Documentos de Empenho Específicos',
            },
        ),
        migrations.AlterField(
            model_name='documentoempenhoespecifico',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='tesouro_gerencial.tipodocumentoempenhoespecifico'),
        ),
    ]
