# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:13


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='QuestionarioAcumuloCargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('publico', models.IntegerField(choices=[[0, 'Geral'], [1, 'Técnicos'], [2, 'Docentes']], verbose_name='Público')),
                ('ano', models.IntegerField()),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('campus', djtools.db.models.ManyToManyFieldPlus(blank=True, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
            ],
            options={'verbose_name': 'Questionário de Acúmulo de Cargos', 'verbose_name_plural': 'Questionários de Acúmulo de Cargos'},
        ),
        migrations.CreateModel(
            name='TermoAcumuloCargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'nao_possui_outro_vinculo',
                    models.BooleanField(
                        default=False,
                        verbose_name='Não possuo qualquer outro vínculo ativo com a administração pública direta ou indireta nas esferas federal, estadual, distrital ou municipal, nem percebo proventos de aposentadoria, reforma ou pensão de nenhum órgão ou entidade da administração pública.',
                    ),
                ),
                (
                    'tem_outro_cargo_acumulavel',
                    models.BooleanField(
                        default=False,
                        verbose_name='Ocupo cargo público acumulável com compatibilidade de horários com o vínculo assumido com o IFRN, conforme disposto no Anexo I.',
                    ),
                ),
                (
                    'tem_aposentadoria',
                    models.BooleanField(default=False, verbose_name='Percebo proventos de aposentadoria devidamente acumuláveis com o cargo assumido no IFRN, conforme Anexo II.'),
                ),
                ('tem_pensao', models.BooleanField(default=False, verbose_name='Sou beneficiário de pensão, conforme informações prestadas em Anexo III.')),
                (
                    'tem_atuacao_gerencial',
                    models.BooleanField(default=False, verbose_name='Tenho atuação gerencial em atividade mercantil, conforme informações prestadas em Anexo IV.'),
                ),
                (
                    'exerco_atividade_remunerada_privada',
                    models.BooleanField(default=False, verbose_name='Exerço atividade remunerada privada, conforme informações prestadas em Anexo V.'),
                ),
                ('anexo1_pergunta1', models.CharField(blank=True, max_length=255, verbose_name='Orgão de Lotação')),
                ('anexo1_pergunta2', models.CharField(blank=True, max_length=5, verbose_name='UF')),
                ('anexo1_pergunta3', models.CharField(blank=True, max_length=255, verbose_name='Cargo/Emprego/Função que ocupa')),
                ('anexo1_pergunta4', models.CharField(blank=True, max_length=255, verbose_name='Jornada de trabalho do cargo/emprego/função')),
                ('anexo1_pergunta5', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Nível de escolaridade do cargo/emprego/função')),
                ('anexo1_pergunta6', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de ingresso no orgão')),
                (
                    'anexo1_pergunta7',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Quadro ou Tabela: Permanente, Temporário, Comissionado, etc.', max_length=255, verbose_name='Situação'),
                ),
                (
                    'anexo1_pergunta8',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Vencimentos, Salários, Proventos, etc.', max_length=255, verbose_name='Da Remuneração'),
                ),
                (
                    'anexo1_pergunta9',
                    djtools.db.models.CharFieldPlus(
                        blank=True, help_text='Administração Direta, Autarquia, Empresa Pública ou Sociedade de Economia Mista', max_length=255, verbose_name='Natureza do Órgão'
                    ),
                ),
                (
                    'anexo1_pergunta10',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Ministério, Secretaria de Estado/Município', max_length=255, verbose_name='Subordinação'),
                ),
                ('anexo1_pergunta11', djtools.db.models.CharFieldPlus(blank=True, help_text='Federal, Estadual ou Municipal', max_length=255, verbose_name='Esfera do Governo')),
                (
                    'anexo1_pergunta12',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Técnica/Científica, Saúde ou Magistério', max_length=255, verbose_name='Área de atuação do cargo'),
                ),
                ('anexo2_pergunta1', models.CharField(blank=True, max_length=255, verbose_name='Cargo que deu origem à aposentadoria')),
                ('anexo2_pergunta2', models.CharField(blank=True, max_length=5, verbose_name='UF')),
                ('anexo2_pergunta3', models.CharField(blank=True, max_length=255, verbose_name='Fundamento legal da aposentadoria')),
                ('anexo2_pergunta4', models.CharField(blank=True, max_length=255, verbose_name='Ato legal da aposentadoria')),
                ('anexo2_pergunta5', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Jornada de trabalho do cargo que exerceu')),
                ('anexo2_pergunta6', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Nível de escolaridade do cargo/emprego/função')),
                ('anexo2_pergunta7', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de vigência da aposentadoria')),
                (
                    'anexo2_pergunta8',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Técnica/Científica, Saúde ou Magistério', max_length=255, verbose_name='Área de atuação do cargo'),
                ),
                (
                    'anexo2_pergunta9',
                    djtools.db.models.CharFieldPlus(
                        blank=True, help_text='Administração Direta, Autarquia, Empresa Pública ou Sociedade de Economia Mista', max_length=255, verbose_name='Natureza do Órgão'
                    ),
                ),
                (
                    'anexo2_pergunta10',
                    djtools.db.models.CharFieldPlus(blank=True, help_text='Ministério, Secretaria de Estado/Município', max_length=255, verbose_name='Subordinação'),
                ),
                ('anexo2_pergunta11', djtools.db.models.CharFieldPlus(blank=True, help_text='Federal, Estadual ou Municipal', max_length=255, verbose_name='Esfera do Governo')),
                ('anexo3_pergunta1', models.CharField(blank=True, max_length=255, verbose_name='Tipo de pensão')),
                ('anexo3_pergunta2', models.CharField(blank=True, max_length=255, verbose_name='Fundamento legal da pensão')),
                ('anexo3_pergunta3', models.CharField(blank=True, max_length=255, verbose_name='Grau de parentesco com o instituidor de pensão')),
                ('anexo3_pergunta4', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de início de concessão do benefício')),
                (
                    'anexo3_pergunta5',
                    djtools.db.models.CharFieldPlus(
                        blank=True, help_text='Certidão de casamento, nascimento, declaração de IR, etc', max_length=255, verbose_name='Dependência econômica'
                    ),
                ),
                ('anexo4_empresa_que_atua', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Empresa em que atua')),
                ('anexo4_tipo_atuacao_gerencial', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Tipo de atuação gerencial')),
                ('anexo4_tipo_sociedade_mercantil', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Tipo de sociedade mercantil')),
                ('anexo4_descricao_atividade_exercida', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Descrição da atividade comercial exercida')),
                ('anexo4_qual_participacao_societaria', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Qual a participação societária')),
                ('anexo4_data_inicio_atuacao', djtools.db.models.DateFieldPlus(blank=True, max_length=255, null=True, verbose_name='Data de início da atuação')),
                (
                    'anexo4_nao_exerco_atuacao_gerencial',
                    models.BooleanField(default=False, blank=True, verbose_name='NÃO exerço qualquer atuação gerencial em atividade mercantil'),
                ),
                ('anexo4_nao_exerco_comercio', models.BooleanField(default=False, blank=True, verbose_name='NÃO exerço comércio')),
                ('anexo5_nome_empresa_trabalha', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Nome da empresa onde trabalha/Empregador')),
                (
                    'anexo5_funcao_emprego_ocupado',
                    djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Função ou emprego ocupado(tipo de atividade desempenhada)'),
                ),
                ('anexo5_jornada_trabalho', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Jornada de trabalho semanal a que está submetido')),
                ('anexo5_nivel_escolaridade_funcao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Nível de escolaridade da função/emprego')),
                (
                    'anexo5_data_inicio_atividade',
                    djtools.db.models.DateFieldPlus(blank=True, max_length=255, null=True, verbose_name='Data de início da atividade remunerada privada'),
                ),
                ('anexo5_nao_exerco_atividade_remunerada', models.BooleanField(default=False, blank=True, verbose_name='NÃO exerço qualquer atividade remunerada privada')),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('hash', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Hash')),
                (
                    'alterado_por',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='termoacumulocargos_alterado_por',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'questionario_acumulo_cargos',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_rh3.QuestionarioAcumuloCargos', verbose_name='Questionário de Acúmulo de Cargos'),
                ),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
            ],
            options={'verbose_name': 'Termo Acumulação de Cargos', 'verbose_name_plural': 'Termos Acumulação de Cargos'},
        ),
        migrations.AlterUniqueTogether(name='termoacumulocargos', unique_together=set([('servidor', 'questionario_acumulo_cargos')])),
    ]
