# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('protocolo', '0001_initial'), ('comum', '0002_auto_20190814_1443'), ('almoxarifado', '0001_initial'), ('rh', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, help_text='Processo desta instituição relativo a esta entrada de NF', null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Processo'
            ),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_entrada',
            field=djtools.db.models.ForeignKeyPlus(
                db_column='tipoentrada_id', on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.EntradaTipo', verbose_name='Tipo de Entrada'
            ),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_material',
            field=djtools.db.models.ForeignKeyPlus(
                db_column='tipomaterial_id', on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialTipo', verbose_name='Tipo de Material'
            ),
        ),
        migrations.AddField(model_name='entrada', name='uo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
        migrations.AddField(
            model_name='entrada',
            name='vinculo_fornecedor',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='empenhoconsumo', name='empenho', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Empenho')
        ),
        migrations.AddField(
            model_name='empenhoconsumo', name='material', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialConsumo')
        ),
        migrations.AddField(
            model_name='empenho',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, help_text='Processo desta instituição relativo a este empenho', null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Processo'
            ),
        ),
        migrations.AddField(
            model_name='empenho',
            name='tipo_licitacao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, db_column='tipolicitacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.LicitacaoTipo', verbose_name='Tipo de Licitação'
            ),
        ),
        migrations.AddField(
            model_name='empenho',
            name='tipo_material',
            field=djtools.db.models.ForeignKeyPlus(
                db_column='tipomaterial', on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialTipo', verbose_name='Tipo de Material'
            ),
        ),
        migrations.AddField(
            model_name='empenho',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, help_text='Unidade Gestora Emitente', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='UG Emitente'
            ),
        ),
        migrations.AddField(
            model_name='empenho',
            name='vinculo_fornecedor',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='devolucaomaterial', name='material', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialConsumo')
        ),
        migrations.AddField(
            model_name='devolucaomaterial',
            name='requisicao_uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.RequisicaoAlmoxUO'),
        ),
        migrations.AddField(
            model_name='devolucaomaterial',
            name='requisicao_user',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.RequisicaoAlmoxUser'),
        ),
        migrations.AddField(
            model_name='devolucaomaterial', name='uo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='material',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialConsumo'),
        ),
        migrations.AddField(
            model_name='configuracaoestoque', name='uo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')
        ),
        migrations.AddField(
            model_name='categoriamaterialconsumo',
            name='plano_contas',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.PlanoContasAlmox'),
        ),
        migrations.AlterUniqueTogether(name='empenho', unique_together=set([('uo', 'numero')])),
    ]
