from django.urls import path
from contratos import views

urlpatterns = [
    path('upload_publicacao/<int:pub_id>/<int:contrato_id>/', views.upload_publicacao),
    path('upload_ocorrencia/<int:ocorrencia_id>/', views.upload_ocorrencia),
    path('upload_ocorrencia_resposta/<int:ocorrencia_id>/', views.upload_ocorrencia_resposta),
    path('upload_publicacao_aditivo/<int:pub_id>/<int:aditivo_id>/', views.upload_publicacao_aditivo),
    path('upload_aditivo/<int:aditivo_id>/', views.upload_aditivo),
    path('upload_contrato/<int:contrato_id>/', views.upload_contrato),
    path('upload_medicao/<int:medicao_id>/<int:contrato_id>/', views.upload_medicao),
    path('visualizar_arquivo/<int:arquivo_id>/', views.visualizar_arquivo),
    path('visualizar_arquivo_contrato/<int:contrato_id>/', views.visualizar_arquivo_contrato),
    path('contrato/<int:contrato_id>/', views.contrato, name='contrato'),
    path('exportar_maodeobra/<int:contrato_id>/', views.exportar_maodeobra),
    path('adicionar_maodeobra/<int:contrato_id>/', views.adicionar_maodeobra),
    path('editar_maodeobra/<int:maodeobra_id>/', views.editar_maodeobra),
    path('excluir_maodeobra/<int:maodeobra_id>/', views.excluir_maodeobra),
    path('adicionar_apostilamento/<int:contrato_id>/', views.adicionar_apostilamento),
    path('editar_apostilamento/<int:apostilamento_id>/', views.editar_apostilamento),
    path('excluir_apostilamento/<int:apostilamento_id>/', views.excluir_apostilamento),
    path('adicionar_garantia/<int:contrato_id>/', views.adicionar_garantia),
    path('editar_garantia/<int:garantia_id>/', views.editar_garantia),
    path('excluir_garantia/<int:garantia_id>/', views.excluir_garantia),
    path('adicionar_penalidade/<int:contrato_id>/', views.adicionar_penalidade),
    path('editar_penalidade/<int:penalidade_id>/', views.editar_penalidade),
    path('excluir_penalidade/<int:penalidade_id>/', views.excluir_penalidade),
    path('aditivo/<int:aditivo_id>/', views.aditivo),
    path('adicionar_aditivo/<int:contrato_id>/', views.adicionar_aditivo),
    path('excluir_aditivo/<int:aditivo_id>/', views.excluir_aditivo),
    path('adicionar_fiscal/<int:contrato_id>/', views.adicionar_fiscal),
    path('editar_fiscal/<int:fiscal_id>/', views.editar_fiscal),
    path('adicionar_fiscal_aditivo/<int:aditivo_id>/', views.adicionar_fiscal_aditivo),
    path('adicionar_publicacao/<int:contrato_id>/', views.adicionar_publicacao),
    path('editar_publicacao/<int:publicacao_id>/', views.editar_publicacao),
    path('adicionar_publicacao_aditivo/<int:aditivo_id>/', views.adicionar_publicacao_aditivo),
    path('editar_publicacao_aditivo/<int:publicacao_id>/', views.editar_publicacao_aditivo),
    path('excluir_publicacao_aditivo/<int:publicacao_id>/', views.excluir_publicacao_aditivo),
    path('adicionar_anexo/<int:contrato_id>/', views.adicionar_anexo),
    path('listar_documentos_adicionar_contrato/<int:contrato_id>/', views.listar_documentos_adicionar_contrato),
    path('adicionar_anexomaodeobra/<int:maodeobra_id>/', views.adicionar_anexomaodeobra),
    path('remover_anexomaodeobra/<int:anexomaodeobra_id>/', views.remover_anexomaodeobra),
    path('editar_anexo/<int:anexo_id>/', views.editar_anexo),
    path('adicionar_parcela/<int:contrato_id>/', views.adicionar_parcela),
    path('atualizar_parcela/<int:parcela_id>/<int:contrato_id>/', views.atualizar_parcela),
    path('definir_cronograma/<int:contrato_id>/', views.definir_cronograma),
    path('gerar_parcelas/<int:contrato_id>/', views.gerar_parcelas),
    path('configurar_medicao/<int:contrato_id>/', views.configurar_medicao),
    path('excluir_tipo_documento_contrato/<int:contrato_id>/<int:tipo_documento_contrato_id>/', views.excluir_tipo_documento_contrato),
    path('efetuar_medicao/<int:parcela_id>/<int:contrato_id>/', views.efetuar_medicao),
    path('sem_medicao/<int:parcela_id>/<int:contrato_id>/', views.sem_medicao),
    path('adicionar_ocorrencia_medicao/<int:medicao_id>/<int:contrato_id>/', views.adicionar_ocorrencia_medicao),
    path('atualizar_medicao/<int:medicao_id>/<int:contrato_id>/', views.atualizar_medicao),
    path('excluir_medicao/<int:medicao_id>/<int:contrato_id>/', views.excluir_medicao),
    path('conferencia_documentos/<int:medicao_id>/<int:contrato_id>/', views.conferencia_documentos),
    path('cancelar_contrato/<int:contrato_id>/', views.cancelar_contrato),
    path('despacho_medicao/<int:medicao_id>/<int:contrato_id>/', views.despacho_medicao),
    path('gerar_despacho_eletronico/<int:medicao_id>/<int:contrato_id>/', views.gerar_despacho_documentotexto),
    path('excluir_parcela/<int:parcela_id>/<int:contrato_id>/', views.excluir_parcela),
    path('contratos_a_serem_aditivados/', views.contratos_a_serem_aditivados),
    path('contratos_a_serem_licitados/', views.contratos_a_serem_licitados),
    path('solicitacao_fiscal/<int:contrato_id>/', views.solicitacao_fiscal),
    path('gerar_despacho_termo_aditivo/<int:termo_id>/', views.gerar_despacho_termo_aditivo),
    path('gerar_despacho_fiscal/<int:contrato_id>/', views.gerar_despacho_fiscal),
    path('solicitacao_publicacao_portaria_fiscal/<int:contrato_id>/', views.solicitacao_publicacao_portaria_fiscal),
    path('pendencias/', views.pendencias),
    path('registrar_ocorrencia/<int:contrato_id>/', views.registrar_ocorrencia),
    path('editar_ocorrencia/<int:ocorrencia_id>/', views.editar_ocorrencia),
    path('notificar_ocorrencia/<int:ocorrencia_id>/', views.notificar_ocorrencia),
    path('rol_responsabilidade_fiscais/', views.rol_responsabilidade_fiscais),
    path('situacao_contratos/', views.situacao_contratos),
    path('relatorio_pendencias/', views.relatorio_pendencias_dados),
    path('contrato_publico/<int:contrato_id>/', views.contrato_publico, name='contrato_publico'),
    path('listar_contratos/', views.listar_contratos, name='listar_contratos'),
    path('redirect_contratos/', views.redirect_contratos, name='redirect_contratos'),
    path('exportacao/', views.exportacao, name='exportacao'),
    path('vincular_documento_contrato/<int:contrato_id>/<int:documento_id>/',
         views.vincular_documento_contrato, name='vincular_documento_contrato'),
    path('adicionar_arrecadacao_receita/<int:contrato_id>/', views.adicionar_arrecadacao_receita),
    path('editar_arrecadacao/<int:arrecadacao_id>/', views.editar_arrecadacao),
    path('excluir_arrecadacao/<int:arrecadacao_id>/', views.excluir_arrecadacao),
    path('receber_definitivamente_medicao/<int:medicao_id>/', views.receber_definitivamente_medicao),
    path('relatorio_valores_executados/<int:contrato_id>/', views.relatorio_valores_executados),
    path('gerar_termo_definitivo_documentotexto/<int:medicao_id>/<int:contrato_id>/', views.gerar_termo_definitivo_documentotexto),
]
