# Generated by Django 2.2.16 on 2021-03-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0003_auto_20200406_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMaterialConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('sentenca', models.CharField(max_length=1024, verbose_name='Sentença processada')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=1024, verbose_name='Nome Original')),
                ('nome_processado', models.CharField(max_length=1024, null=True, verbose_name='Nome Processado')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siads.GrupoMaterialConsumo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.MaterialConsumo')),
            ],
        ),
    ]
