# Generated by Django 2.2.16 on 2021-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomaterialconsumo',
            name='unidade',
            field=models.CharField(default='', max_length=50),
        ),
    ]
