# Generated by Django 2.2.16 on 2021-03-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0002_grupomaterialconsumo_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupomaterialconsumo',
            options={'verbose_name': 'Grupo de Material de Consumo', 'verbose_name_plural': 'Grupos de Material de Consumo'},
        ),
    ]
