# Generated by Django 2.2.16 on 2021-03-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0003_auto_20210304_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupomaterialconsumo',
            name='nome',
            field=models.CharField(max_length=1024, verbose_name='Nome'),
        ),
    ]
