# Generated by Django 3.2.5 on 2021-08-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_auto_20210719_1644'),
        ('siads', '0005_auto_20210309_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMaterialPermanente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('sentenca', models.CharField(max_length=1024, verbose_name='Sentença processada')),
                ('unidade', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Grupo de Material Permanente',
                'verbose_name_plural': 'Grupos de Material Permanente',
            },
        ),
        migrations.CreateModel(
            name='MaterialPermanente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=1024, verbose_name='Nome Original')),
                ('nome_processado', models.CharField(max_length=1024, null=True, verbose_name='Nome Processado')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siads.grupomaterialpermanente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.inventario')),
            ],
        ),
    ]
