# Generated by Django 3.2.5 on 2021-08-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0006_grupomaterialpermanente_materialpermanente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupomaterialpermanente',
            name='unidade',
        ),
    ]
