# Generated by Django 3.2.5 on 2021-08-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0007_remove_grupomaterialpermanente_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupomaterialpermanente',
            name='nome',
            field=models.CharField(max_length=5048, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='grupomaterialpermanente',
            name='sentenca',
            field=models.CharField(max_length=5048, verbose_name='Sentença processada'),
        ),
        migrations.AlterField(
            model_name='materialpermanente',
            name='nome_original',
            field=models.CharField(max_length=5048, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='materialpermanente',
            name='nome_processado',
            field=models.CharField(max_length=5048, null=True, verbose_name='Nome Processado'),
        ),
    ]
