# Generated by Django 3.2.5 on 2021-08-24 11:32

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_auto_20210719_1644'),
        ('rh', '0023_servidorfuncaohistorico_atualiza_pelo_extrator'),
        ('siads', '0009_auto_20210809_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupomaterialpermanente',
            options={'verbose_name': 'Grupo de Entrada Permanente', 'verbose_name_plural': 'Grupos de Entradas Permanente'},
        ),
        migrations.RemoveField(
            model_name='materialpermanente',
            name='material',
        ),
        migrations.AddField(
            model_name='materialconsumo',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional'),
        ),
        migrations.AddField(
            model_name='materialpermanente',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.entradapermanente'),
        ),
        migrations.AddField(
            model_name='materialpermanente',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional'),
        ),
        migrations.AlterField(
            model_name='materialconsumo',
            name='nome_processado',
            field=models.CharField(max_length=8000, null=True, verbose_name='Nome Processado'),
        ),
    ]
