# Generated by Django 3.2.5 on 2021-09-21 17:53

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_alter_servidor_options'),
        ('siads', '0012_setorsiads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorsiads',
            name='chefe',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.servidor'),
        ),
    ]
