# Generated by Django 3.2.5 on 2021-09-28 11:34

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_auto_20210920_0912'),
        ('siads', '0014_setorsiads_exportavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorsiads',
            name='exportavel',
            field=models.BooleanField(default=True, verbose_name='Exportável'),
        ),
        migrations.CreateModel(
            name='MaterialConsumoSiads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=100, verbose_name='Código do material')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de medida')),
                ('codigo_conta', models.CharField(max_length=9, verbose_name='Código da conta contábil')),
                ('endereco', models.CharField(max_length=9, verbose_name='Endereço')),
                ('qtd_disponivel', models.CharField(max_length=10, verbose_name='Quantidade disponível')),
                ('valor_saldo', models.CharField(max_length=18, verbose_name='Valor Saldo')),
                ('estocavel', models.BooleanField(verbose_name='Estocável')),
                ('exportavel', models.BooleanField(default=True, verbose_name='Exportável')),
                ('material', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='siads.materialconsumo')),
                ('uo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional')),
            ],
            options={
                'verbose_name': 'Material de Consumo Siads',
                'verbose_name_plural': 'Materiais de Consumo Siads',
            },
        ),
    ]
