# Generated by Django 3.2.5 on 2021-10-15 17:44

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_auto_20210719_1644'),
        ('rh', '0025_auto_20210920_0912'),
        ('siads', '0015_auto_20210928_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPermanenteSiads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=100, verbose_name='Código')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao')),
                ('codigo_conta', models.CharField(max_length=9, verbose_name='Conta Contábil')),
                ('endereco', models.CharField(max_length=50, verbose_name='Localização')),
                ('uorg', models.CharField(max_length=100, verbose_name='Código da UORG')),
                ('tipo', models.CharField(default='1', max_length=1, verbose_name='Tipo')),
                ('situacao', models.CharField(default='1', max_length=1, verbose_name='Situação')),
                ('tipo_plaqueta', models.CharField(default='3', max_length=1, verbose_name='Tipo da Plaqueta')),
                ('dt_tombamento', models.CharField(max_length=8, verbose_name='Data do Tombamento')),
                ('vlr_bem', models.CharField(max_length=18, verbose_name='Valor do Bem')),
                ('forma_aquisicao', models.CharField(max_length=20, verbose_name='Forma da Aquisição')),
                ('especificacao', models.CharField(max_length=209, verbose_name='Detalhes Específicos')),
                ('dt_devolucao', models.CharField(max_length=8, verbose_name='Data de Devolução')),
                ('nr_serie', models.CharField(max_length=15, verbose_name='Nr. de Série')),
                ('patrimonio', models.CharField(max_length=10, verbose_name='Patrimônio')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca do Bem')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo do Bem')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('garantidor', models.CharField(max_length=50, verbose_name='Responsável pela Garantia')),
                ('nr_contrato', models.CharField(max_length=6, verbose_name='Número do Contrato')),
                ('inicio_garantia', models.CharField(max_length=8, verbose_name='Inicio da Garantia')),
                ('fim_garantia', models.CharField(max_length=8, verbose_name='Fim da Garantia')),
                ('cpf_responsavel', models.CharField(max_length=11, verbose_name='Responsável')),
                ('corresponsavel', models.CharField(max_length=50, verbose_name='Nome do Corresponsável')),
                ('almoxarifado', models.BooleanField(default=False, verbose_name='Está no Almoxarifado')),
                ('dt_reavaliacao', models.CharField(max_length=8, verbose_name='Data da Reavaliação')),
                ('vlr_reavaliacao', models.CharField(max_length=8, verbose_name='Valor da Reavaliação')),
                ('vida_util', models.CharField(max_length=3, verbose_name='Vida Útil em Meses')),
                ('exportavel', models.BooleanField(default=True, verbose_name='Exportável')),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.DO_NOTHING, to='patrimonio.inventario')),
                ('uo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional')),
            ],
            options={
                'verbose_name': 'Material Permanente Siads',
                'verbose_name_plural': 'Materiais Permanete Siads',
            },
        ),
    ]
