# Generated by Django 3.2.5 on 2021-10-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0016_materialpermanentesiads'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpermanente',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='materialpermanente',
            name='marca',
            field=models.CharField(blank=True, max_length=20, verbose_name='Marca do Bem'),
        ),
        migrations.AddField(
            model_name='materialpermanente',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Modelo do Bem'),
        ),
        migrations.AddField(
            model_name='materialpermanente',
            name='nr_serie',
            field=models.CharField(blank=True, max_length=15, verbose_name='Nr. de Série'),
        ),
    ]
