# Generated by Django 3.2.5 on 2021-10-21 10:20

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_auto_20210920_0912'),
        ('siads', '0018_alter_materialpermanente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setorsiads',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional'),
        ),
    ]
