# Generated by Django 3.2.5 on 2021-10-21 10:24

from django.db import migrations


def ajuste_setor_uo(apps, schema_editor):
    SetorSiads = apps.get_model('siads', 'SetorSiads')

    for setor in SetorSiads.objects.all():
        setor.uo = setor.setor_suap.uo
        setor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0019_setorsiads_uo'),
    ]

    operations = [
        migrations.RunPython(ajuste_setor_uo)
    ]
