# Generated by Django 3.2.5 on 2021-10-21 10:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_auto_20210920_0912'),
        ('siads', '0020_auto_20211021_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorsiads',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional'),
        ),
    ]
