# Generated by Django 3.2.5 on 2021-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0022_auto_20211021_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumosiads',
            name='ajustado',
            field=models.BooleanField(default=False, verbose_name='Exportável'),
        ),
        migrations.AddField(
            model_name='materialpermanentesiads',
            name='ajustado',
            field=models.BooleanField(default=False, verbose_name='Exportável'),
        ),
        migrations.AddField(
            model_name='setorsiads',
            name='ajustado',
            field=models.BooleanField(default=False, verbose_name='Exportável'),
        ),
    ]
