# Generated by Django 3.2.5 on 2022-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siads', '0025_auto_20211203_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorsiads',
            name='ajustado',
            field=models.BooleanField(default=False, verbose_name='Ajustado'),
        ),
    ]
