# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 15:45


from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0001_initial')]

    operations = [
        migrations.AddField(model_name='pessoa', name='search_fields_optimized', field=djtools.db.models.UnaccentField(db_index=True, max_length=400), preserve_default=False),
        migrations.AddField(model_name='servidor', name='data_ultima_atualizacao_webservice', field=models.DateTimeField(blank=True, null=True)),
    ]
