# Generated by Django 2.2.10 on 2020-02-17 10:06

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0005_auto_20200123_1113')]

    operations = [
        migrations.AlterModelOptions(
            name='servidorfuncaohistorico', options={'verbose_name': 'Histórico de Função do Servidor', 'verbose_name_plural': 'Histórico de Funções do Servidor'}
        ),
        migrations.AlterField(model_name='servidorfuncaohistorico', name='data_fim_funcao', field=djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Fim da Função')),
        migrations.AlterField(
            model_name='servidorfuncaohistorico', name='data_inicio_funcao', field=djtools.db.models.DateFieldPlus(db_index=True, verbose_name='Data de Início da Função')
        ),
        migrations.AlterField(
            model_name='servidorfuncaohistorico',
            name='funcao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Funcao', verbose_name='Função'),
        ),
        migrations.AlterField(model_name='servidorfuncaohistorico', name='nivel', field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Nível')),
        migrations.AlterField(
            model_name='servidorfuncaohistorico',
            name='setor_suap',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_suap', to='rh.Setor', verbose_name='Setor SUAP'),
        ),
    ]
