# Generated by Django 2.2.10 on 2020-03-03 16:39

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0006_auto_20200217_1006')]

    operations = [
        migrations.AddField(
            model_name='servidorfuncaohistorico', name='nome_amigavel', field=djtools.db.models.CharFieldPlus(default='', max_length=255, verbose_name='Nome Amigável')
        )
    ]
