# Generated by Django 2.2.10 on 2020-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('rh', '0007_servidorfuncaohistorico_nome_amigavel')]

    operations = [
        migrations.AddField(
            model_name='funcao', name='funcao_siape', field=models.BooleanField(default=True, help_text='Essa função tem origem no SIAPE?', verbose_name='Função SIAPE')
        ),
        migrations.AlterField(
            model_name='funcao',
            name='funcao_suap',
            field=models.BooleanField(default=False, help_text='Essa função pode ser gerenciada dentro do SUAP?', verbose_name='Função SUAP'),
        ),
    ]
