# Generated by Django 2.2.10 on 2020-03-06 16:56

from django.db import migrations


def popular_funcao_siape(apps, schema_editor):
    Funcao = apps.get_model('rh', 'Funcao')
    Funcao.objects.filter(funcao_suap=True).update(funcao_siape=False)


def despopular_funcao_siape(apps, schema_editor):
    Funcao = apps.get_model('rh', 'Funcao')
    Funcao.objects.filter(funcao_suap=True).update(funcao_siape=True)


class Migration(migrations.Migration):

    dependencies = [('rh', '0008_auto_20200306_1655')]

    operations = [migrations.RunPython(popular_funcao_siape, despopular_funcao_siape)]
