# Generated by Django 2.2.10 on 2020-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('rh', '0009_auto_20200306_1656')]

    operations = [
        migrations.AlterField(
            model_name='papel',
            name='tipo_papel',
            field=models.CharField(
                choices=[('cargo', 'cargo'), ('funcao', 'funcao'), ('comissaoconselho', 'comissaoconselho'), ('ocupacao', 'ocupacao'), ('discente', 'discente')],
                default='cargo',
                max_length=255,
                verbose_name='Tipo de papel',
            ),
        )
    ]
