# Generated by Django 2.2.10 on 2020-05-10 19:16

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0010_auto_20200421_1719')]

    operations = [
        migrations.CreateModel(
            name='ArquivoUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', djtools.db.models.FileFieldPlus(upload_to='private-media/rh/arquivo/', verbose_name='Arquivo')),
                ('tipo_conteudo', djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Tipo de Conteúdo')),
                ('tamanho_em_bytes', djtools.db.models.PositiveIntegerFieldPlus(verbose_name='Tamanho em bytes')),
                ('charset', djtools.db.models.CharFieldPlus(blank=True, max_length=50, null=True, verbose_name='Charset')),
                ('hash_sha512', djtools.db.models.CharFieldPlus(max_length=128, unique=True, verbose_name='Hash 512')),
                ('data_hora_primeiro_upload', djtools.db.models.DateTimeFieldPlus(verbose_name='Data e Hora do Primeiro Upload')),
                ('data_hora_criacao_registro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data e Hora da Criação do Registro')),
            ],
            options={'verbose_name': 'Arquivo Único', 'verbose_name_plural': 'Arquivos Únicos'},
        )
    ]
