# Generated by Django 2.2.10 on 2020-05-13 09:32

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0011_arquivounico')]

    operations = [
        migrations.AddField(
            model_name='arquivounico',
            name='dados_gerais_primeiro_upload',
            field=djtools.db.models.CharFieldPlus(default='(Nenhuma)', max_length=255, verbose_name='Tipo de Conteúdo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivounico',
            name='nome_original_primeiro_upload',
            field=djtools.db.models.CharFieldPlus(default='(Nenhum)', max_length=100, verbose_name='Tipo de Conteúdo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivounico', name='conteudo', field=djtools.db.models.FileFieldPlus(upload_to='private-media/rh/arquivo_unico/', verbose_name='Arquivo')
        ),
    ]
