# Generated by Django 2.2.10 on 2020-05-14 17:10

from django.db import migrations
import djtools.db.models
import hashlib


def hash_sha512_link_id_set_default(apps, schema_editor):
    ArquivoUnico = apps.get_model('rh', 'ArquivoUnico')
    for arquivo_unico in ArquivoUnico.objects.all():
        hash_sha512_link_id_str = '[{}],[{}]'.format(arquivo_unico.data_hora_criacao_registro.strftime('%d%m%Y__%H:%M:%S.%f'), arquivo_unico.hash_sha512)
        hash_sha512_link_id_bytes = (hash_sha512_link_id_str).encode('utf-8')
        arquivo_unico.hash_sha512_link_id = hashlib.sha512(hash_sha512_link_id_bytes).hexdigest()
        arquivo_unico.save()


def hash_sha512_link_id_reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('rh', '0012_auto_20200513_0932')]

    operations = [
        migrations.RemoveField(model_name='arquivounico', name='dados_gerais_primeiro_upload'),
        migrations.AddField(
            model_name='arquivounico', name='hash_sha512_link_id', field=djtools.db.models.CharFieldPlus(null=True, max_length=128, verbose_name='Hash 512 Link Id')
        ),
        migrations.RunPython(hash_sha512_link_id_set_default, hash_sha512_link_id_reverse_func),
        migrations.AlterField(
            model_name='arquivounico', name='hash_sha512_link_id', field=djtools.db.models.CharFieldPlus(max_length=128, unique=True, verbose_name='Hash 512 Link Id')
        ),
        migrations.AlterField(
            model_name='arquivounico', name='data_hora_criacao_registro', field=djtools.db.models.DateTimeFieldPlus(verbose_name='Data e Hora da Criação do Registro')
        ),
        migrations.AlterField(
            model_name='arquivounico', name='nome_original_primeiro_upload', field=djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Nome Original do Primeiro Upload')
        ),
    ]
