# Generated by Django 2.2.10 on 2020-05-16 02:27

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0013_auto_20200514_1710')]

    operations = [migrations.AlterField(model_name='arquivounico', name='tipo_conteudo', field=djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Tipo de Conteúdo'))]
