# Generated by Django 2.2.16 on 2021-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_auto_20210126_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeorganizacional',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número'),
        ),
    ]
