# Generated by Django 2.2.16 on 2021-05-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_servidorreativacaotemporaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afastamentosiape',
            options={'verbose_name': 'Afastamentos SIAPE', 'verbose_name_plural': 'Afastamentos SIAPE'},
        ),
    ]
