# Generated by Django 2.2.16 on 2021-06-22 10:06

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_auto_20210519_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='passaporte',
            field=djtools.db.models.CharFieldPlus(blank=True, default='', max_length=50, verbose_name='Nº do Passaporte'),
        ),
    ]
