# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_pessoafisica_passaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='eh_docente',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='eh_tecnico_administrativo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='funcao_opcao',
            field=models.BooleanField(null=True),
        ),
    ]
