# Generated by Django 3.2.5 on 2021-08-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_servidorfuncaohistorico_atualiza_pelo_extrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'permissions': (('pode_ver_relatorios_rh', 'Pode ver relatórios do RH'), ('chefe', 'Chefe'), ('gabinete', 'Gabinete'), ('auditor', 'Auditor'), ('eh_servidor', 'Servidor'), ('eh_rh_sistemico', 'RH Sistêmico'), ('eh_rh_campus', 'RH Campus'), ('cadastrador_rsc_simec', 'Cadastrador RSC/SIMEC'), ('pode_ver_cpf_servidor', 'Pode ver CPF'), ('pode_ver_dados_pessoais_servidor', 'Pode ver dados pessoais de servidores'), ('pode_ver_telefones_pessoais_servidor', 'Pode ver telefones pessoais de servidores'), ('pode_ver_endereco_servidor', 'Pode visualizar endereço de servidores'), ('pode_ver_dados_bancarios_servidor', 'Pode visualizar dados bancários de servidores'), ('pode_ver_dados_professor_servidor', 'Pode visualizar dados de professor de servidores'), ('pode_ver_ferias_servidor', 'Pode visualizar Férias dos servidores'), ('pode_ver_ocorrencias_afastamentos_servidor', 'Pode visualizar Ocorrências e Afastamentos dos Servidores'), ('pode_ver_historico_setores_servidor', 'Pode visualizar historico de setor dos Servidores'), ('pode_ver_historico_funcional_servidor', 'Pode visualizar historico funcional dos Servidores'), ('pode_ver_historico_funcao_servidor', 'Pode visualizar historico de funções dos Servidores'), ('pode_ver_arquivos_servidor', 'Pode visualizar arquivos dos Servidores'), ('pode_ver_contracheques_servidor', 'Pode visualizar contracheques dos Servidores'), ('pode_ver_viagens_servidor', 'Pode visualizar viagens dos Servidores'), ('pode_editar_cargo_emprego_externo', 'Pode editar cargo emprego de servidor fora do PCCTAE'), ('pode_ver_identificacao_unica_siape', 'Pode visualizar Identificação Única SIAPE'), ('pode_importar_servidor_ws', 'Pode importar servidor via Webservice'), ('pode_gerenciar_extracao_scdp', 'Pode gerenciar extração SCDP'), ('pode_gerenciar_extracao_siape', 'Pode gerenciar extração SIAPE')), 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
    ]
