# Generated by Django 3.1 on 2021-08-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_unidadeorganizacional_numero'),
        ('rh', '0023_servidorfuncaohistorico_atualiza_pelo_extrator'),
    ]

    operations = [
    ]
