# Generated by Django 3.2.5 on 2021-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_alter_servidor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='afastamentosiape',
            name='suspende_estagio_probatorio',
            field=models.BooleanField(blank=True, default=False, verbose_name='Suspende estágio probatório'),
        ),
        migrations.AlterField(
            model_name='afastamentosiape',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='afastamentosiape',
            name='interrompe_pagamento',
            field=models.BooleanField(blank=True, default=False, verbose_name='Interrompe pagamento'),
        ),
        migrations.AlterField(
            model_name='afastamentosiape',
            name='interrompe_tempo_servico',
            field=models.BooleanField(blank=True, default=False, verbose_name='Interrompe tempo de serviço'),
        ),
        migrations.AlterField(
            model_name='afastamentosiape',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Faltas'), (2, 'Atrasos'), (3, 'Licença Incentivada'), (4, 'Outros')], verbose_name='Tipos de Afastamentos'),
        ),
    ]
