# Generated by Django 3.2.5 on 2021-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_merge_20210811_1545'),
        ('rh', '0025_auto_20210920_0912'),
    ]

    operations = [
    ]
