# Generated by Django 3.2.5 on 2021-10-19 11:07

from django.db import migrations
from tqdm import tqdm


def atualizar_busca_pessoa_juridica(apps, schema_editor):
    PessoaJuridica = apps.get_model('rh', 'PessoaJuridica')

    for pessoa_juridica in tqdm(PessoaJuridica.objects.all()):
        pessoa_juridica.search_fields_optimized = '{}{}{}'.format(pessoa_juridica.nome or '', pessoa_juridica.cnpj or '', pessoa_juridica.matricula or '')
        pessoa_juridica.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_auto_20210920_0912'),
    ]

    operations = [
        migrations.RunPython(atualizar_busca_pessoa_juridica),
    ]
