# Generated by Django 3.2.5 on 2021-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_auto_20211019_1107'),
        ('rh', '0026_merge_20211007_1358'),
    ]

    operations = [
    ]
