# Generated by Django 3.2.5 on 2022-01-10 11:49

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_auto_20211019_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='data_criacao',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
