# Generated by Django 3.2.5 on 2022-01-19 15:10

from django.db import migrations
import djtools.db.models
import djtools.unaccent_field


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_merge_20211028_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaexterna',
            name='nome',
            field=djtools.db.models.UnaccentField(db_index=True, max_length=200),
        ),
    ]
