# Generated by Django 3.2.5 on 2022-01-10 12:02

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_setor_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='horario_funcionamento',
            field=djtools.db.models.TimeFieldPlus(blank=True, null=True, verbose_name='Horário de Funcionamento'),
        ),
    ]
