# Generated by Django 3.2.5 on 2022-01-20 17:58

from django.db import migrations
import djtools.unaccent_field


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_auto_20220119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_usual',
            field=djtools.unaccent_field.UnaccentField(blank=True, help_text='O nome apresentado no crachá ou razão social', max_length=30, verbose_name='Nome Usual'),
        ),
        migrations.AlterField(
            model_name='pessoaexterna',
            name='nome_usual',
            field=djtools.unaccent_field.UnaccentField(blank=True, help_text='O nome apresentado no crachá ou razão social', max_length=30, verbose_name='Nome Usual'),
        ),
    ]
