# Generated by Django 3.2.5 on 2022-01-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_auto_20220110_1218'),
        ('rh', '0029_auto_20220120_1758'),
    ]

    operations = [
    ]
