# Generated by Django 3.2.5 on 2022-03-17 14:10

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_auto_20220201_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcecaoDadoWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.CharField(blank=True, choices=[('nome', 'Nome'), ('situacao', 'Situação')], max_length=1000, verbose_name='Dados de Exceção')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Exceção Dados para Webservice',
                'verbose_name_plural': 'Exceções Dados para Webservice',
            },
        ),
    ]
