# Generated by Django 3.2.5 on 2022-03-17 15:10

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_excecaodadows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoExcecaoWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255, verbose_name='Campo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='excecaodadows',
            name='dados',
        ),
        migrations.AddField(
            model_name='excecaodadows',
            name='campos',
            field=djtools.db.models.ManyToManyFieldPlus(to='rh.CampoExcecaoWS', verbose_name='Campos'),
        ),
    ]
