# Generated by Django 3.2.5 on 2022-03-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0033_auto_20220317_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campoexcecaows',
            options={'verbose_name': 'Campo de exceção', 'verbose_name_plural': 'Campos de exceção'},
        ),
    ]
