# Generated by Django 3.2.5 on 2022-04-05 21:29

from django.db import migrations
import djtools.unaccent_field


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0035_auto_20220405_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=djtools.unaccent_field.UnaccentField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_registro',
            field=djtools.unaccent_field.UnaccentField(blank=True, max_length=200, verbose_name='Nome de Registro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_social',
            field=djtools.unaccent_field.UnaccentField(blank=True, max_length=200, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_usual',
            field=djtools.unaccent_field.UnaccentField(blank=True, help_text='O nome apresentado no crachá ou razão social', max_length=30, verbose_name='Nome Usual'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='search_fields_optimized',
            field=djtools.unaccent_field.UnaccentField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pessoaexterna',
            name='nome',
            field=djtools.unaccent_field.UnaccentField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaexterna',
            name='nome_registro',
            field=djtools.unaccent_field.UnaccentField(blank=True, max_length=200, verbose_name='Nome de Registro'),
        ),
        migrations.AlterField(
            model_name='pessoaexterna',
            name='nome_social',
            field=djtools.unaccent_field.UnaccentField(blank=True, max_length=200, verbose_name='Nome Social'),
        ),
    ]
