# Generated by Django 3.2.5 on 2022-06-10 07:52

import re
from django.db import migrations
from tqdm import tqdm


def atualizar_busca_pessoa_fisica(apps, schema_editor):
    PessoaFisica = apps.get_model('rh', 'PessoaFisica')
    for pessoa in tqdm(PessoaFisica.objects.all()):
        pessoa.search_fields_optimized = "{}{}{}{}".format(pessoa.nome or "", pessoa.cpf or "", pessoa.username or "", re.sub(r'\D', '', str(pessoa.cpf)) or "")
        pessoa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_setor_equivalencia_codigo'),
    ]

    operations = [
        migrations.RunPython(atualizar_busca_pessoa_fisica),
    ]
