# Generated by Django 3.2.5 on 2022-07-22 14:29

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_auto_20220610_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAlteracaoFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', djtools.db.models.FileFieldPlus(upload_to='fotos', verbose_name='Foto')),
                ('descricao', models.TextField(blank=True, help_text='Se necessário, descreva o motivo da alteração da foto.', null=True, verbose_name='Descrição')),
                ('situacao', djtools.db.models.IntegerFieldPlus(choices=[[1, 'Aguardando validação'], [2, 'Validada'], [3, 'Rejeitada']], default=1, verbose_name='Situação')),
                ('data_interacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Interação')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('responsavel_interacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_interacao', to='rh.servidor', verbose_name='Responsável pela Interação')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.servidor', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Foto',
                'verbose_name_plural': 'Solicitações de Alteração de Foto',
            },
        ),
    ]
