# Generated by Django 3.2.5 on 2022-07-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0039_alter_papel_tipo_papel'),
        ('rh', '0039_solicitacaoalteracaofoto'),
    ]

    operations = [
    ]
