# Generated by Django 3.2.5 on 2022-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0040_merge_20220722_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'Empregado Fesf', 'verbose_name_plural': 'Empregados Fesf'},
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='eh_residente',
            field=models.BooleanField(default=False),
        ),
    ]
