# Generated by Django 3.2.5 on 2022-09-27 18:07
# Generated by Django 3.2.5 on 2022-09-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0040_merge_20220722_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'Empregado Fesf', 'verbose_name_plural': 'Empregados Fesf'},
        ),
    ]
