# Generated by Django 3.2.5 on 2022-09-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0041_alter_servidor_options'),
        ('rh', '0041_auto_20220928_1126'),
    ]

    operations = [
    ]
