# Generated by Django 3.2.5 on 2022-11-17 20:41

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('rh', '0044_pessoafisica_eh_trabalhadoreducando'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancariosPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BANCO DO BRASIL', '001 - Banco do Brasil'), ('CAIXA ECONÔMICA', '104 - Caixa Econômica'), ('BRADESCO', '237 - Bradesco'), ('ITAU', '341- Itaú'), ('SANTANDER', '033 - Santander'), ('BANCO DO NORDESTE', '004 - Banco do Nordeste')], max_length=50, null=True, verbose_name='Banco')),
                ('numero_agencia', models.CharField(help_text='Ex: 3293-X', max_length=50, null=True, verbose_name='Número da Agência')),
                ('tipo_conta', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança')], max_length=50, null=True, verbose_name='Tipo da Conta')),
                ('numero_conta', models.CharField(help_text='Ex: 23384-6', max_length=50, null=True, verbose_name='Número da Conta')),
                ('operacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operação')),
                ('prioritario_servico_social', models.BooleanField(default=False, verbose_name='Prioritário para Serviço Social')),
                ('atualizado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em')),
                ('atualizado_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosbancariospessoafisica_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por')),
                ('instituicao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.banco', verbose_name='Banco')),
                ('pessoa_fisica', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='dadosbancariospessoafisica_set', to='rh.pessoafisica')),
            ],
            options={
                'verbose_name': 'Dados Bancários',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
    ]
