# Generated by Django 3.2.5 on 2022-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0045_dadosbancariospf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosbancariospf',
            options={'permissions': (('change_dados_bancarios', 'Pode alterar dados bancários'),), 'verbose_name': 'Dados Bancários', 'verbose_name_plural': 'Dados Bancários'},
        ),
        migrations.AlterField(
            model_name='dadosbancariospf',
            name='banco',
            field=models.CharField(choices=[['BANCO DO BRASIL', '001 - Banco do Brasil'], ['CAIXA ECONÔMICA', '104 - Caixa Econômica'], ['BRADESCO', '237 - Bradesco'], ['ITAU', '341 - Itaú'], ['SANTANDER', '033 - Santander'], ['BANCO DO NORDESTE', '004 - Banco do Nordeste'], ['INTER', '077 - INTER'], ['NUBANK', '260 - NUBANK'], ['HSBC', '399 - HSBC'], ['NEXT ', '237 - NEXT'], ['PAGSEGURO', '290 - Pagseguro Internet S.A'], ['PICPAY', '380 - Banco PicPay Serviços S/A'], ['VOTORANTIM', '655 - Banco Votorantim'], ['C6', '336 - Banco C6'], ['MERCADO PAGO', '323 - MERCADO PAGO'], ['NEON', '735 - NEON']], max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='dadosbancariospf',
            name='tipo_conta',
            field=models.CharField(choices=[['Conta Corrente', 'Conta Corrente'], ['Conta Poupança', 'Conta Poupança']], max_length=50, null=True, verbose_name='Tipo da Conta'),
        ),
    ]
