# Generated by Django 3.2.5 on 2023-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0047_auto_20230324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancariospf',
            name='tipo_conta',
            field=models.CharField(choices=[['Conta Corrente', 'Conta Corrente'], ['Conta Poupança', 'Conta Poupança'], ['Conta Salário', 'Conta Salário']], max_length=50, null=True, verbose_name='Tipo da Conta'),
        ),
    ]
