# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '__first__'),
        ('comum', '0002_auto_20190814_1443'),
        ('rh', '0001_initial'),
        ('ae', '0001_initial'),
        ('edu', '0001_initial'),
        ('ponto', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaorefeicaoaluno', name='aluno', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')
        ),
        migrations.AddField(
            model_name='solicitacaorefeicaoaluno',
            name='avaliador',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='solicitacaorefeicaoaluno',
            name='avaliador_vinculo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='solicitacaorefeicaoaluno', name='programa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Programa')
        ),
        migrations.AddField(
            model_name='respostaparticipacao',
            name='participacao',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='resposta_participacao', to='ae.Participacao', verbose_name='Participação'
            ),
        ),
        migrations.AddField(
            model_name='respostaparticipacao',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='resposta_pergunta_participacao', to='ae.PerguntaParticipacao', verbose_name='Pergunta'
            ),
        ),
        migrations.AddField(
            model_name='respostaparticipacao',
            name='resposta',
            field=djtools.db.models.ForeignKeyPlus(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resposta_escolhida_participacao',
                to='ae.OpcaoRespostaPerguntaParticipacao',
                verbose_name='Resposta',
            ),
        ),
        migrations.AddField(
            model_name='respostainscricaoprograma',
            name='inscricao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_inscricao', to='ae.Inscricao', verbose_name='Inscrição'),
        ),
        migrations.AddField(
            model_name='respostainscricaoprograma',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='resposta_pergunta_inscricao', to='ae.PerguntaInscricaoPrograma', verbose_name='Pergunta'
            ),
        ),
        migrations.AddField(
            model_name='respostainscricaoprograma',
            name='resposta',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_escolhida', to='ae.OpcaoRespostaInscricaoPrograma', verbose_name='Resposta'
            ),
        ),
        migrations.AddField(
            model_name='relatoriografico',
            name='relatorio',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='graficos', to='ae.RelatorioGestao'),
        ),
        migrations.AddField(
            model_name='relatoriogestaosaude', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestaoresumo', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestaoprogramas', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestaobolsas', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestaoauxilios', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestaoatendimentos', name='relatorio', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.RelatorioGestao')
        ),
        migrations.AddField(
            model_name='relatoriogestao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(model_name='programa', name='demandas', field=models.ManyToManyField(to='ae.DemandaAluno', verbose_name='Atendimentos Incluídos')),
        migrations.AddField(
            model_name='programa',
            name='instituicao',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='programas_sediados', to='rh.UnidadeOrganizacional', verbose_name='Campus'
            ),
        ),
        migrations.AddField(model_name='programa', name='publico_alvo', field=models.ManyToManyField(to='rh.UnidadeOrganizacional', verbose_name='Público-Alvo')),
        migrations.AddField(
            model_name='programa',
            name='tipo_programa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.TipoPrograma', verbose_name='Tipo de Programa'),
        ),
        migrations.AddField(
            model_name='periodoinscricao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='periodoinscricao', name='edital', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Edital', verbose_name='Edital')
        ),
        migrations.AddField(model_name='periodoinscricao', name='programa', field=djtools.db.models.ManyToManyFieldPlus(to='ae.Programa', verbose_name='Programas Vinculados')),
        migrations.AddField(
            model_name='perguntaparticipacao',
            name='tipo_programa',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_part_tipoprograma', to='ae.TipoPrograma', verbose_name='Tipo do Programa'
            ),
        ),
        migrations.AddField(
            model_name='perguntainscricaoprograma',
            name='tipo_programa',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_tipoprograma', to='ae.TipoPrograma', verbose_name='Tipo do Programa'
            ),
        ),
        migrations.AddField(
            model_name='participacaotrabalho',
            name='bolsa_concedida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.OfertaBolsa', verbose_name='Bolsa Concedida'),
        ),
        migrations.AddField(
            model_name='participacaotrabalho',
            name='participacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='participacaopasseestudantil',
            name='participacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='participacaoidioma',
            name='idioma',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Idioma', verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='participacaoidioma',
            name='participacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='participacaoidioma',
            name='turma_selecionada',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.OfertaTurma', verbose_name='Turma Selecionada'),
        ),
        migrations.AddField(
            model_name='participacaobolsa', name='aluno', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno')
        ),
        migrations.AddField(
            model_name='participacaobolsa',
            name='aluno_participante_projeto',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Participacao', verbose_name='Aluno Participante do Projeto'
            ),
        ),
        migrations.AddField(
            model_name='participacaobolsa',
            name='categoria',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.CategoriaBolsa', verbose_name='Categoria da Bolsa'),
        ),
        migrations.AddField(
            model_name='participacaobolsa',
            name='setor',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='categoria',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.CategoriaAlimentacao', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='liberado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável pela Liberação'),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='liberado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável pela Liberação'),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='participacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='solicitacao_atendida_almoco',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participacao_alimentacao_almoco',
                to='ae.SolicitacaoAlimentacao',
                verbose_name='Solicitação Atendida de Almoço',
            ),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='solicitacao_atendida_cafe',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participacao_alimentacao_cafe',
                to='ae.SolicitacaoAlimentacao',
                verbose_name='Solicitação Atendida de Café da manhã',
            ),
        ),
        migrations.AddField(
            model_name='participacaoalimentacao',
            name='solicitacao_atendida_janta',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participacao_alimentacao_janta',
                to='ae.SolicitacaoAlimentacao',
                verbose_name='Solicitação Atendida de Jantar',
            ),
        ),
        migrations.AddField(
            model_name='participacao',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='inscricao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Inscricao', verbose_name='Inscrição'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='programa',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='opcaorespostaperguntaparticipacao',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_participacao', to='ae.PerguntaParticipacao', verbose_name='Pergunta'
            ),
        ),
        migrations.AddField(
            model_name='opcaorespostainscricaoprograma',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_inscricao', to='ae.PerguntaInscricaoPrograma', verbose_name='Pergunta'
            ),
        ),
        migrations.AddField(
            model_name='ofertavalorrefeicao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ofertavalorbolsa',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ofertaturma',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ofertaturma', name='idioma', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Idioma', verbose_name='Idioma')
        ),
        migrations.AddField(
            model_name='ofertapasse',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ofertabolsa',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ofertabolsa', name='setor', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor')
        ),
        migrations.AddField(
            model_name='ofertaalimentacao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_alimentacao_set', to='rh.UnidadeOrganizacional', verbose_name='Campus'
            ),
        ),
        migrations.AddField(
            model_name='integrantefamiliarcaracterizacao',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='integrantefamiliarcaracterizacao',
            name='estado_civil',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.EstadoCivil', verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='integrantefamiliarcaracterizacao',
            name='inscricao_caracterizacao',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.InscricaoCaracterizacao', verbose_name='Inscrição da Caracterização'
            ),
        ),
        migrations.AddField(
            model_name='integrantefamiliarcaracterizacao',
            name='situacao_trabalho',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.SituacaoTrabalho', verbose_name='Situação de trabalho'),
        ),
        migrations.AddField(
            model_name='inscricaocaracterizacao',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricaocaracterizacao',
            name='moradia_responsavel_financeiro',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, to='ae.TipoImovelResidencial', verbose_name='Situação de moradia do principal responsável financeiro'
            ),
        ),
        migrations.AddField(
            model_name='inscricao', name='aluno', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno')
        ),
        migrations.AddField(
            model_name='inscricao',
            name='parecer_autor',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ae_autor_parecer_inscricao', to='rh.PessoaFisica', verbose_name='Autor do Parecer'
            ),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='parecer_autor_vinculo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ae_autor_parecer_inscricao_vinculo',
                to='comum.Vinculo',
                verbose_name='Autor do Parecer',
            ),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='periodo_inscricao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.PeriodoInscricao', verbose_name='Período de Inscrição'
            ),
        ),
        migrations.AddField(
            model_name='inscricao', name='programa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Programa', verbose_name='Programa')
        ),
        migrations.AddField(
            model_name='horariosolicitacaorefeicao',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='horariojustificativafalta',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='historicosuspensoesalimentacao',
            name='liberado_por',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável pela Liberação'),
        ),
        migrations.AddField(
            model_name='historicosuspensoesalimentacao',
            name='liberado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável pela Liberação'),
        ),
        migrations.AddField(
            model_name='historicosuspensoesalimentacao',
            name='participacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='historicorendafamiliar',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='historicofaltasalimentacao', name='aluno', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')
        ),
        migrations.AddField(
            model_name='historicofaltasalimentacao',
            name='justificada_por',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável pela Justificativa'
            ),
        ),
        migrations.AddField(
            model_name='historicofaltasalimentacao',
            name='justificada_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável pela Justificativa'
            ),
        ),
        migrations.AddField(
            model_name='historicofaltasalimentacao',
            name='participacao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Participacao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='historicofaltasalimentacao',
            name='programa',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(model_name='edital', name='tipo_programa', field=djtools.db.models.ManyToManyFieldPlus(to='ae.TipoPrograma', verbose_name='Tipos de Programa')),
        migrations.AddField(
            model_name='documentoinscricaoaluno',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='documentoinscricaoaluno',
            name='cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável pela Cadastro'),
        ),
        migrations.AddField(
            model_name='documentoinscricaoaluno',
            name='cadastrado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável pela Cadastro'),
        ),
        migrations.AddField(
            model_name='documentoinscricaoaluno',
            name='integrante_familiar',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.IntegranteFamiliarCaracterizacao', verbose_name='Integrante Familiar'
            ),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='demanda',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.DemandaAluno', verbose_name='Tipo de Atendimento'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='programa',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='responsavel_vinculo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='terminal',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto.Maquina', verbose_name='Terminal'),
        ),
        migrations.AlterUniqueTogether(name='demandaaluno', unique_together=set([('nome', 'descricao')])),
        migrations.AddField(
            model_name='datasrecessoferias',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='campus_data_recesso_ferias', to='rh.UnidadeOrganizacional'),
        ),
        migrations.AddField(
            model_name='datasliberadasfaltasalimentacao',
            name='cadastrado_por',
            field=djtools.db.models.CurrentUserField(
                blank=True,
                default=djtools.middleware.threadlocals.get_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Cadastrado Por',
            ),
        ),
        migrations.AddField(
            model_name='datasliberadasfaltasalimentacao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional'),
        ),
        migrations.AddField(
            model_name='dadosrelatoriografico',
            name='grafico',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='ae.RelatorioGrafico'),
        ),
        migrations.AddField(model_name='dadosfincanceiros', name='aluno', field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
        migrations.AddField(model_name='dadosbancarios', name='aluno', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
        migrations.AddField(
            model_name='dadosbancarios',
            name='instituicao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.Banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='caracterizacao', name='aluno', field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno')
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='beneficiario_programa_social',
            field=models.ManyToManyField(
                help_text='Informe os programas do governo federal dos quais você ou algum membro de sua família seja beneficiário.',
                to='ae.BeneficioGovernoFederal',
                verbose_name='Programas Social do Governo Federal',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='companhia_domiciliar',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Com que você mora?', on_delete=django.db.models.deletion.CASCADE, to='ae.CompanhiaDomiciliar', verbose_name='Com quem mora?'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='contribuintes_renda_familiar',
            field=models.ManyToManyField(
                help_text='Pessoas que contribuem para rendar familiar.', to='ae.ContribuinteRendaFamiliar', verbose_name='Contribuintes da Renda Familiar'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='escola_ensino_fundamental',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.TipoEscola', verbose_name='Tipo de escola que cursou o Ensino Fundamental'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='escola_ensino_medio',
            field=djtools.db.models.ForeignKeyPlus(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='escola_ensino_medio',
                to='ae.TipoEscola',
                verbose_name='Tipo de escola que cursou o Ensino Médio',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='estado_civil',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='ae.EstadoCivil', verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='frequencia_acesso_internet',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.TipoAcessoInternet', verbose_name='Frequência de Acesso à Internet'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='historico_caracterizacao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.HistoricoCaracterizacao'),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='idiomas_conhecidos',
            field=models.ManyToManyField(
                help_text='Informe os idiomas sobre os quais você tem conhecimento caso tenha marcado a opção anterior.', to='ae.Idioma', verbose_name='Idiomas'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='mae_nivel_escolaridade',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='mae', to='ae.NivelEscolaridade', verbose_name='Nível de escolaridade da mãe'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='meio_transporte_utilizado',
            field=models.ManyToManyField(help_text='Meio de transporte que você utiliza/utilizará para se deslocar.', to='ae.MeioTransporte', verbose_name='Meio de Transporte'),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='necessidade_especial',
            field=models.ManyToManyField(
                help_text='Informe as deficiências/necessidades educacionais especiais caso tenha marcado a opção anterior.',
                to='ae.NecessidadeEspecial',
                verbose_name='Especifique as deficiências/necessidades educacionais especiais',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='pai_nivel_escolaridade',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pai', to='ae.NivelEscolaridade', verbose_name='Nível de escolaridade do pai'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='raca',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Como você se considera quanto a sua questão racial?', on_delete=django.db.models.deletion.CASCADE, to='comum.Raca', verbose_name='Etnia/Raça/Cor'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='razao_ausencia_educacional',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Informe o motivo pelo qual você ficou sem estudar caso tenha marcado a opção anterior.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ae.RazaoAfastamentoEducacional',
                verbose_name='Motivo da Ausência Escolar',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='responsavel_financeir_trabalho_situacao',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Situação em que seu pai se encontra no mercado de trabalho.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responsavel_financeiro',
                to='ae.SituacaoTrabalho',
                verbose_name='Situação de Trabalho do Principal Responsável Financeiro',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='responsavel_financeiro',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Pessoa responsável pela renda familiar',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responsavel_financeiro',
                to='ae.ContribuinteRendaFamiliar',
                verbose_name='Principal responsável pela renda familiar',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='responsavel_financeiro_nivel_escolaridade',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responsavel_financeiro',
                to='ae.NivelEscolaridade',
                verbose_name='Nível de Escolaridade do Principal Responsável Financeiro',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='tipo_area_residencial',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Tipo da área residencial em que o imóvel que você reside se localiza.',
                on_delete=django.db.models.deletion.CASCADE,
                to='ae.TipoAreaResidencial',
                verbose_name='Tipo de Área Residencial',
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='tipo_imovel_residencial',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Tipo do imóvel no qual você reside.', on_delete=django.db.models.deletion.CASCADE, to='ae.TipoImovelResidencial', verbose_name='Tipo de Imóvel'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='tipo_servico_saude',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.TipoServicoSaude', verbose_name='Serviço de Saúde que você mais utiliza'
            ),
        ),
        migrations.AddField(
            model_name='caracterizacao',
            name='trabalho_situacao',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Situação em que você se encontra no mercado de trabalho.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ae.SituacaoTrabalho',
                verbose_name='Situação de Trabalho',
            ),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='cadastrado_por',
            field=djtools.db.models.CurrentUserField(
                blank=True,
                default=djtools.middleware.threadlocals.get_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Cadastrado Por',
            ),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='cancelada_por',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividade_diversa_cancelada_por', to='rh.PessoaFisica', verbose_name='Cancelada Por'
            ),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='cancelada_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividade_diversa_cancelada_por_vinculo', to='comum.Vinculo', verbose_name='Cancelada Por'
            ),
        ),
        migrations.AddField(model_name='atividadediversa', name='servidores_envolvidos', field=models.ManyToManyField(to='rh.Servidor', verbose_name='Servidores Envolvidos')),
        migrations.AddField(
            model_name='atividadediversa',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.TipoAtividadeDiversa', verbose_name='Tipo'),
        ),
        migrations.AddField(model_name='atendimentosetor', name='alunos', field=models.ManyToManyField(to='edu.Aluno', verbose_name='Alunos')),
        migrations.AddField(
            model_name='atendimentosetor',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='atendimentosetor',
            name='setor',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='atendimentosetor',
            name='tipoatendimentosetor',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.TipoAtendimentoSetor', verbose_name='Tipo de Auxílio'),
        ),
        migrations.AddField(
            model_name='agendamentorefeicao',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='agendamentorefeicao',
            name='programa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='acaoeducativa',
            name='cadastrado_por',
            field=djtools.db.models.CurrentUserField(
                blank=True,
                default=djtools.middleware.threadlocals.get_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Cadastrado Por',
            ),
        ),
        migrations.AddField(
            model_name='acaoeducativa',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='acaoeducativa',
            name='cancelada_por',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_educativa_cancelada_por', to='rh.PessoaFisica', verbose_name='Cancelada Por'
            ),
        ),
        migrations.AddField(
            model_name='acaoeducativa',
            name='cancelada_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_educativa_cancelada_por_vinculo', to='comum.Vinculo', verbose_name='Cancelada Por'
            ),
        ),
        migrations.AddField(model_name='acaoeducativa', name='servidores_envolvidos', field=models.ManyToManyField(to='rh.Servidor', verbose_name='Servidores Envolvidos')),
        migrations.AlterUniqueTogether(name='relatoriogestao', unique_together=set([('campus', 'ano', 'somente_alunos_ead', 'renda_per_capita')])),
        migrations.AddField(
            model_name='inscricaotrabalho',
            name='dados_bancarios',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.DadosBancarios', verbose_name='Dados Bancários'),
        ),
        migrations.AddField(
            model_name='inscricaotrabalho',
            name='setor_preferencia',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor de Preferência'),
        ),
        migrations.AddField(
            model_name='inscricaopasseestudantil',
            name='dados_bancarios',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.DadosBancarios', verbose_name='Dados Bancários'),
        ),
        migrations.AddField(
            model_name='inscricaoidioma',
            name='primeira_opcao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='primeira_opcao', to='ae.OfertaTurma', verbose_name='Primeira Opção'),
        ),
        migrations.AddField(
            model_name='inscricaoidioma',
            name='segunda_opcao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='segunda_opcao', to='ae.OfertaTurma', verbose_name='Segunda Opção'),
        ),
        migrations.AddField(
            model_name='inscricaoalimentacao',
            name='solicitacao_almoco',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_almoco', to='ae.SolicitacaoAlimentacao', verbose_name='Solicitação de Almoço'
            ),
        ),
        migrations.AddField(
            model_name='inscricaoalimentacao',
            name='solicitacao_cafe',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cafe', to='ae.SolicitacaoAlimentacao', verbose_name='Solicitação de Café'
            ),
        ),
        migrations.AddField(
            model_name='inscricaoalimentacao',
            name='solicitacao_janta',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_janta', to='ae.SolicitacaoAlimentacao', verbose_name='Solicitação de Jantar'
            ),
        ),
        migrations.AlterUniqueTogether(name='horariosolicitacaorefeicao', unique_together=set([('uo', 'tipo_refeicao')])),
        migrations.AlterUniqueTogether(name='horariojustificativafalta', unique_together=set([('uo', 'tipo_refeicao')])),
        migrations.AlterUniqueTogether(name='demandaalunoatendida', unique_together=set([('aluno', 'demanda', 'data')])),
        migrations.AlterUniqueTogether(name='datasrecessoferias', unique_together=set([('data', 'campus')])),
        migrations.AlterUniqueTogether(name='datasliberadasfaltasalimentacao', unique_together=set([('data', 'campus')])),
    ]
