# Generated by Django 1.11.23 on 2019-09-20 13:39


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [('edu', '0003_aluno_candidato_vaga'), ('rh', '0002_auto_20190902_1545'), ('comum', '0002_auto_20190814_1443'), ('ae', '0002_auto_20190814_1454')]

    operations = [
        migrations.CreateModel(
            name='AuxilioEventual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True, verbose_name='Atendimento')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('valor', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Registro')),
                (
                    'arquivo',
                    djtools.db.models.PrivateFileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=djtools.storages.get_private_storage(),
                        upload_to='ae/auxilios_eventuais/comprovantes',
                        verbose_name='Arquivo',
                    ),
                ),
                ('aluno', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno')),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
                (
                    'responsavel',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável'),
                ),
            ],
            options={'verbose_name': 'Auxílio Eventual', 'verbose_name_plural': 'Auxílios Eventuais'},
        ),
        migrations.CreateModel(
            name='SolicitacaoAuxilioAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('motivo_solicitacao', djtools.db.models.CharFieldPlus(max_length=5000, verbose_name='Motivo da Solicitação')),
                ('deferida', models.NullBooleanField(verbose_name='Deferida')),
                ('data_avaliacao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Avaliação')),
                ('parecer_avaliacao', djtools.db.models.CharFieldPlus(max_length=5000, null=True, verbose_name='Parecer da Avaliação')),
                (
                    'comprovante',
                    djtools.db.models.PrivateFileField(
                        max_length=500,
                        null=True,
                        storage=djtools.storages.get_private_storage(),
                        upload_to='ae/solicitacoes_auxilios/comprovantes',
                        verbose_name='Comprovantes',
                    ),
                ),
                ('aluno', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
                (
                    'avaliador_vinculo',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Avaliador'),
                ),
            ],
            options={'verbose_name': 'Solicitação de Auxílios Eventuais', 'verbose_name_plural': 'Solicitações de Auxílios Eventuais'},
        ),
        migrations.CreateModel(
            name='TipoAuxilioEventual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('exige_comprovante', models.BooleanField(default=False, verbose_name='Exige Documento de Comprovação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Tipo de Auxílio Eventual', 'verbose_name_plural': 'Tipos de Auxílios Eventuais', 'ordering': ('nome',)},
        ),
        migrations.AlterUniqueTogether(name='tipoauxilioeventual', unique_together={('nome', 'descricao')}),
        migrations.AddField(
            model_name='solicitacaoauxilioaluno',
            name='tipo_auxilio',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.TipoAuxilioEventual', verbose_name='Tipo do Auxílio'),
        ),
        migrations.AddField(
            model_name='auxilioeventual',
            name='tipo_auxilio',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ae.TipoAuxilioEventual', verbose_name='Tipo do Auxílio'),
        ),
        migrations.AlterUniqueTogether(name='auxilioeventual', unique_together={('aluno', 'tipo_auxilio', 'data')}),
    ]
