# Generated by Django 2.2.10 on 2020-04-02 12:06

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('ae', '0003_auto_20190920_1339')]

    operations = [
        migrations.AddField(model_name='caracterizacao', name='data_cadastro', field=models.DateTimeField(null=True, verbose_name='Data de Cadastro')),
        migrations.AddField(model_name='caracterizacao', name='data_ultima_atualizacao', field=models.DateTimeField(null=True, verbose_name='Data da Última Atualização')),
        migrations.AddField(
            model_name='historicocaracterizacao',
            name='caracterizacao_relacionada',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ae.Caracterizacao', verbose_name='Caracterização'),
        ),
        migrations.AddField(model_name='historicocaracterizacao', name='data_cadastro', field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data de Cadastro')),
    ]
