# Generated by Django 2.2.10 on 2020-04-02 17:48

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0008_auto_20200205_1500'), ('ae', '0004_auto_20200402_1206')]

    operations = [
        migrations.AddField(
            model_name='historicocaracterizacao',
            name='cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Cadastrado Por'),
        )
    ]
