# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0006_auto_20200402_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacao',
            name='ficou_tempo_sem_estudar',
            field=models.BooleanField(blank=True, help_text='Marque caso tenha permanecido algum tempo sem estudar.', null=True, verbose_name='Ausência Escolar'),
        ),
        migrations.AlterField(
            model_name='caracterizacao',
            name='possui_conhecimento_idiomas',
            field=models.BooleanField(blank=True, help_text='Marque caso possua conhecimento em outros idiomas.', null=True, verbose_name='Conhecimento em Idiomas'),
        ),
        migrations.AlterField(
            model_name='caracterizacao',
            name='possui_conhecimento_informatica',
            field=models.BooleanField(blank=True, help_text='Marque caso possua conhecimento em informática.', null=True, verbose_name='Conhecimento em Informática'),
        ),
        migrations.AlterField(
            model_name='solicitacaoauxilioaluno',
            name='deferida',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deferida'),
        ),
        migrations.AlterField(
            model_name='solicitacaorefeicaoaluno',
            name='deferida',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deferida'),
        ),
    ]
