# Generated by Django 3.2.5 on 2021-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0007_auto_20210719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoinscricao',
            name='apenas_participantes',
            field=models.BooleanField(default=False, verbose_name='Apenas participantes dos programas podem se inscrever'),
        ),
    ]
