# Generated by Django 3.2.5 on 2021-11-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0009_auto_20211105_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentosetor',
            options={'permissions': (('pode_visualizar_auxilios', 'Pode ver Relatórios de Auxílios'), ('pode_visualizar_auxilios_campus', 'Pode ver Relatórios de Auxílios do próprio campus')), 'verbose_name': 'Auxílio', 'verbose_name_plural': 'Auxílios'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ('tipo_programa__titulo', 'instituicao'), 'permissions': (('pode_abrir_inscricao_todos', 'Pode abrir Período de Inscrição para qualquer campus'), ('pode_abrir_inscricao_do_campus', 'Pode abrir Período de Inscrição para próprio campus'), ('pode_detalhar_programa_todos', 'Pode ver detalhamento de todos os Programas'), ('pode_detalhar_programa_do_campus', 'Pode ver detalhamento de Programas do próprio campus'), ('pode_ver_menu_agendamentos', 'Pode ver Agendamentos'), ('pode_ver_periodo_inscricao', 'Pode ver Período de Inscrição'), ('pode_ver_lista_dos_alunos', 'Pode ver Relatório de Lista dos Alunos'), ('pode_ver_lista_dos_alunos_campus', 'Pode ver Relatório de Lista dos Alunos do próprio campus'), ('pode_ver_relatorio_semanal', 'Pode ver Relatório Semanal de Alimentação'), ('pode_ver_relatorios_todos', 'Pode ver Relatórios de Programas de todos os campi'), ('pode_ver_relatorios_campus', 'Pode ver Relatórios de Programas do próprio campus'), ('pode_ver_relatorios_controle_refeicoes', 'Pode ver Relatórios de Controle de Refeições'), ('pode_ver_listas_todos', 'Pode ver listas de todos os campi'), ('pode_ver_listas_campus', 'Pode ver listas do próprio campus')), 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
    ]
