# Generated by Django 3.2.5 on 2021-12-07 12:16

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0032_alter_ocupacaoprestador_empresa'),
        ('ae', '0010_auto_20211105_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoeducativa',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='acaoeducativa',
            name='atualizado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_educativa_atualizado_por_vinculo', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='agendamentorefeicao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='agendamentorefeicao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentorefeicao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='atendimentosetor',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='atendimentosetor',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentosetor_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='atividadediversa',
            name='atualizado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividadediversa_atualizado_por_vinculo', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='auxilioeventual',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosbancarios_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='datasliberadasfaltasalimentacao',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='datasliberadasfaltasalimentacao',
            name='atualizado_por_vinculo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasliberadas_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='datasrecessoferias',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='datasrecessoferias',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recessoferias_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='demandaaluno',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='demandaaluno',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandaaluno_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='horariojustificativafalta',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='horariojustificativafalta',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horariojustificativafalta_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='horariosolicitacaorefeicao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='horariosolicitacaorefeicao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horariosolicitacaorefeicao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='entrega_doc_atualizada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Situação da Documentação Atualizada em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='entrega_doc_atualizada_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_documentacao_atualizado_por', to='comum.vinculo', verbose_name='Situação da Documentação Atualizada Por'),
        ),
        migrations.AddField(
            model_name='ofertaalimentacao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertaalimentacao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertaalimentacao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='ofertabolsa',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertabolsa',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertabolsa_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='ofertapasse',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertapasse',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertapasse_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='ofertaturma',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertaturma',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertaturma_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='ofertavalorbolsa',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertavalorbolsa',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertavalorbolsa_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='ofertavalorrefeicao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='ofertavalorrefeicao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertavalorrefeicao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='atualizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='finalizado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Finalizado em'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='finalizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacao_finalizado_por', to='comum.vinculo', verbose_name='Finalizado Por'),
        ),
    ]
