# Generated by Django 3.2.5 on 2022-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0011_auto_20211207_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandaaluno',
            name='eh_kit_alimentacao',
            field=models.BooleanField(default=False, verbose_name='É kit de alimentos'),
        ),
        migrations.AlterField(
            model_name='demandaaluno',
            name='custeio',
            field=models.CharField(blank=True, choices=[('Institucional', 'Institucional'), ('Parcerias', 'Parcerias'), ('Sem custeio', 'Sem custeio'), ('Institucional + FNDE', 'Institucional + FNDE'), ('FNDE', 'FNDE')], max_length=50, null=True, verbose_name='Custeio'),
        ),
    ]
