# Generated by Django 3.2.5 on 2022-06-02 11:11

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ae', '0013_auto_20220526_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandaalunoatendida',
            name='cadastrado_por',
            field=djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
    ]
