# Generated by Django 3.2.5 on 2022-07-13 09:06

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_auto_20220610_0752'),
        ('ae', '0014_demandaalunoatendida_cadastrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinscricaoaluno',
            name='cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Responsável pela Cadastro'),
        ),
        migrations.AlterField(
            model_name='historicosuspensoesalimentacao',
            name='liberado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Responsável pela Liberação'),
        ),
    ]
