# Generated by Django 3.2.5 on 2022-07-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0015_auto_20220713_0906'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='acaoeducativa',
            name='cancelada_por',
        ),
        migrations.RemoveField(
            model_name='atividadediversa',
            name='cancelada_por',
        ),
        migrations.RemoveField(
            model_name='demandaalunoatendida',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='documentoinscricaoaluno',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='historicofaltasalimentacao',
            name='justificada_por',
        ),
        migrations.RemoveField(
            model_name='historicosuspensoesalimentacao',
            name='liberado_por',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='parecer_autor',
        ),
        migrations.RemoveField(
            model_name='participacaoalimentacao',
            name='liberado_por',
        ),
        migrations.RemoveField(
            model_name='solicitacaorefeicaoaluno',
            name='avaliador',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
