# Generated by Django 3.2.5 on 2022-02-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import djtools.db.models
import djtools.middleware.threadlocals
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0070_auto_20220204_0920'),
        ('comum', '0038_auto_20211215_1218'),
        ('rh', '0029_auto_20220120_1758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuacamoleConnectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Laboratório', max_length=90, verbose_name='Nome')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('connection_group_name', models.CharField(help_text='<Sigla-Campus>-<LABxx>_GUACAMOLE_XXX', max_length=128, unique=True, verbose_name='Grupo de conexão')),
                ('connection_group_id', models.IntegerField(null=True, verbose_name='Identificador')),
                ('max_connections', models.IntegerField(default=10, verbose_name='Número máximo de Conexões')),
                ('max_connections_per_user', models.IntegerField(default=1, verbose_name='Número de conexões por usuário')),
                ('enable_session_affinity', models.BooleanField(default=True, verbose_name='Afinidade de sessão')),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Laboratório Físico',
                'verbose_name_plural': 'Laboratórios Físicos',
                'unique_together': {('name', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='GuacamoleServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('uri', models.CharField(help_text='Ex.: "banos.ifrn.local:8800".', max_length=255, verbose_name='URI')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('priority', models.IntegerField(default=1000, verbose_name='Prioridade')),
                ('active', models.BooleanField(default=True, verbose_name='Serviço ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Servidor Guacamole',
                'verbose_name_plural': 'Configurações dos Servidores Guacamole',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoLabFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('hora_inicio', djtools.db.models.TimeFieldPlus(verbose_name='Hora de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Data de Fim')),
                ('hora_fim', djtools.db.models.TimeFieldPlus(verbose_name='Hora de Fim')),
                ('recorrencia_segunda', models.BooleanField(default=False, verbose_name='Segunda')),
                ('recorrencia_terca', models.BooleanField(default=False, verbose_name='Terça')),
                ('recorrencia_quarta', models.BooleanField(default=False, verbose_name='Quarta')),
                ('recorrencia_quinta', models.BooleanField(default=False, verbose_name='Quinta')),
                ('recorrencia_sexta', models.BooleanField(default=False, verbose_name='Sexta')),
                ('recorrencia_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('recorrencia_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Aguardando análise'), (3, 'Indeferida'), (2, 'Deferida'), (4, 'Cancelada'), (5, 'Finalizado')], default=1, protected=True, verbose_name='Situação')),
                ('data_avaliacao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Avaliação')),
                ('observacao_avaliador', models.TextField(blank=True, verbose_name='Observação')),
                ('justificativa_cancelamento', models.TextField(blank=True, verbose_name='Justificativa do Cancelamento')),
                ('data_cancelamento', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Avaliação')),
                ('avaliador', djtools.db.models.CurrentUserField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labfisico_solicitacaolabfisico_avaliado_por', to=settings.AUTH_USER_MODEL)),
                ('cancelada_por', djtools.db.models.CurrentUserField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diario', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.diario', verbose_name='Diário')),
                ('laboratorio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='labfisico.guacamoleconnectiongroup', verbose_name='Laboratório Físico')),
                ('membros', djtools.db.models.ManyToManyFieldPlus(related_name='labfisico_solicitacaolabfisico_membros', to='comum.Vinculo', verbose_name='Membros')),
                ('solicitante', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labfisico_solicitacaolabfisico_solicitado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Agendamento',
                'verbose_name_plural': 'Solicitações de Agendamento',
                'permissions': (('pode_avaliar_solicitacao_labfisico', 'Pode avaliar solicitação reserva de Laboratório Físico'),),
            },
        ),
        migrations.CreateModel(
            name='AgendamentoLabFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Ativo'), (0, 'Inativo'), (2, 'Finalizado')], default=0, protected=True, verbose_name='Status')),
                ('data_hora_inicio', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data/Hora inicial')),
                ('data_hora_fim', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data/Hora final')),
                ('justificativa_cancelamento', models.TextField(blank=True, verbose_name='Justificativa do Cancelamento')),
                ('data_cancelamento', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Cancelamento')),
                ('cancelada_por', djtools.db.models.CurrentUserField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labfisico.guacamoleconnectiongroup')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labfisico.solicitacaolabfisico')),
            ],
            options={
                'verbose_name': 'Agendamento de Laboratório Físico',
                'verbose_name_plural': 'Agendamentos de Laboratórios Físicos',
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=128, verbose_name='Nome')),
                ('connection_id', models.IntegerField(null=True, verbose_name='Identificador')),
                ('protocol', models.CharField(default='rdp', max_length=32, verbose_name='Protocolo')),
                ('hostname', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('max_connections', models.IntegerField(default=1)),
                ('max_connections_per_user', models.IntegerField(default=1)),
                ('server_layout', models.CharField(default='pt-br-qwerty', max_length=50, verbose_name='The server-side keyboard layout.')),
                ('connection_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labfisico.guacamoleconnectiongroup', verbose_name='Laboratório Virtual')),
            ],
            options={
                'verbose_name': 'Cliente Guacamole',
                'verbose_name_plural': 'Clientes Guacamole',
                'unique_together': {('connection_name', 'connection_group')},
            },
        ),
    ]
