# Generated by Django 3.2.5 on 2022-02-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='connection_group_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Grupo de Conexão'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='enable_session_affinity',
            field=models.BooleanField(default=True, verbose_name='Afinidade de Sessão'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='max_connections',
            field=models.IntegerField(default=10, verbose_name='Número Máximo de Conexões'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='max_connections_per_user',
            field=models.IntegerField(default=1, verbose_name='Número de Conexões por Usuário'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='name',
            field=models.CharField(help_text='O nome final será: Sigla-Campus>-<LABxx>_GUACAMOLE_XXX', max_length=90, verbose_name='Nome'),
        ),
    ]
