# Generated by Django 3.2.5 on 2022-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0003_alter_guacamoleconnection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='guacamoleconnection',
            name='display_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display Height'),
        ),
        migrations.AddField(
            model_name='guacamoleconnection',
            name='display_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display Width'),
        ),
    ]
