# Generated by Django 3.2.5 on 2022-03-11 13:35

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0004_auto_20220222_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guacamoleconnectiongroup',
            options={'verbose_name': 'Laboratório Remoto', 'verbose_name_plural': 'Laboratórios Remotos'},
        ),
        migrations.AddField(
            model_name='guacamoleconnection',
            name='attrs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guacamoleconnection',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guacamoleconnection',
            name='connection_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labfisico.guacamoleconnectiongroup', verbose_name='Laboratório Remoto'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnection',
            name='connection_id',
            field=djtools.db.models.IntegerFieldPlus(null=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnection',
            name='connection_name',
            field=djtools.db.models.CharFieldPlus(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnection',
            name='protocol',
            field=djtools.db.models.CharFieldPlus(default='rdp', max_length=32, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='connection_group_id',
            field=djtools.db.models.IntegerFieldPlus(null=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='connection_group_name',
            field=djtools.db.models.CharFieldPlus(max_length=128, unique=True, verbose_name='Grupo de Conexão'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='description',
            field=djtools.db.models.CharFieldPlus(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='max_connections',
            field=djtools.db.models.IntegerFieldPlus(default=10, verbose_name='Número Máximo de Conexões'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='max_connections_per_user',
            field=djtools.db.models.IntegerFieldPlus(default=1, verbose_name='Número de Conexões por Usuário'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='name',
            field=djtools.db.models.CharFieldPlus(help_text='O nome final será: Sigla-Campus>-<LABxx>_GUACAMOLE_XXX', max_length=90, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='guacamoleserver',
            name='name',
            field=djtools.db.models.CharFieldPlus(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='guacamoleserver',
            name='password',
            field=djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='guacamoleserver',
            name='priority',
            field=djtools.db.models.IntegerFieldPlus(default=1000, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='guacamoleserver',
            name='uri',
            field=djtools.db.models.CharFieldPlus(help_text='Ex.: "banos.ifrn.local:8800".', max_length=255, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='guacamoleserver',
            name='username',
            field=djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Username'),
        ),
    ]
