# Generated by Django 3.2.5 on 2022-03-11 10:40

from django.db import migrations
from labfisico.guacamole.templates import RDP_CONNECTION_PARAMETERS, RDP_CONNECTION_ATTRS


def load_parameters(connection):
    payload = dict(RDP_CONNECTION_PARAMETERS)
    payload['hostname'] = connection.hostname
    payload['domain'] = connection.domain
    payload['username'] = connection.username
    payload['password'] = connection.password
    payload['server-layout'] = connection.server_layout
    payload['height'] = connection.display_height
    payload['width'] = connection.display_width
    connection.parameters = payload


def load_attrs(connection):
    payload = dict(RDP_CONNECTION_ATTRS)
    payload["max-connections"] = connection.max_connections
    payload["max-connections-per-user"] = connection.max_connections_per_user
    connection.attrs = payload


def transfer_to_json(apps, schema_editor):
    db = schema_editor.connection.alias
    GuacamoleConnection = apps.get_model('labfisico', 'GuacamoleConnection')
    for connection in GuacamoleConnection.objects.using(db).all():
        load_parameters(connection)
        load_attrs(connection)
        connection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0005_auto_20220311_1335'),
    ]

    operations = [
        migrations.RunPython(transfer_to_json),
    ]
