# Generated by Django 3.2.5 on 2022-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0006_auto_20220311_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guacamoleconnection',
            unique_together={('connection_name', 'connection_group')},
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='display_height',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='display_width',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='max_connections',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='max_connections_per_user',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='password',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='server_layout',
        ),
        migrations.RemoveField(
            model_name='guacamoleconnection',
            name='username',
        ),
    ]
