# Generated by Django 3.2.5 on 2022-03-11 19:45

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0007_auto_20220311_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='guacamoleconnectiongroup',
            name='ldap_group_name',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=128, null=True, verbose_name='Grupo do LDAP'),
        ),
        migrations.AlterField(
            model_name='guacamoleconnectiongroup',
            name='name',
            field=djtools.db.models.CharFieldPlus(help_text='O nome final será: Sigla-Campus>_<LABxx>_GUACAMOLE_XXX', max_length=90, verbose_name='Nome'),
        ),
    ]
