# Generated by Django 3.2.5 on 2022-03-11 19:48

from django.db import migrations


def load_ldap_group_names(apps, schema_editor):

    db = schema_editor.connection.alias
    GuacamoleConnectionGroup = apps.get_model('labfisico', 'GuacamoleConnectionGroup')
    for connection_group in GuacamoleConnectionGroup.objects.using(db).all():
        connection_group.ldap_group_name = connection_group.connection_group_name
        connection_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labfisico', '0008_auto_20220311_1945'),
    ]

    operations = [
        migrations.RunPython(load_ldap_group_names),
    ]
