# Generated by Django 2.2.7 on 2019-11-28 13:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('edu', '0010_auto_20191114_1458'), ('projetos', '0004_auto_20191101_1400'), ('rh', '0003_auto_20191009_1509'), ('comum', '0004_auto_20191009_1509')]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=500, verbose_name='Nome Completo / Razão Social')),
                ('identificador', djtools.db.models.CharFieldPlus(max_length=20, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefones', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Telefone(s) de Contato')),
                ('whatsapp', djtools.db.models.CharFieldPlus(blank=True, max_length=50, null=True, verbose_name='Whatsapp')),
                ('nome_comunidade', djtools.db.models.CharFieldPlus(max_length=500, verbose_name='Nome da Comunidade a ser atendida ou grupo a ser beneficiado pela demanda')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=5000, verbose_name='Descreva o problema/demanda')),
                ('qtd_prevista_beneficiados', models.IntegerField(verbose_name='Estimativa do número de beneficiários')),
                (
                    'situacao',
                    djtools.db.models.CharFieldPlus(
                        choices=[
                            ('Submetida', 'Submetida'),
                            ('Em Espera', 'Em Espera'),
                            ('Em Atendimento', 'Em Atendimento'),
                            ('Atendida', 'Atendida'),
                            ('Não Atendida', 'Não Atendida'),
                            ('Não Aceita', 'Não Aceita'),
                        ],
                        default='Submetida',
                        max_length=40,
                        verbose_name='Situação',
                    ),
                ),
                ('atribuida_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atribuída em')),
                ('observacoes', djtools.db.models.CharFieldPlus(blank=True, max_length=5000, null=True, verbose_name='Observações')),
                ('cadastrada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrada em')),
                ('avaliada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                ('data_prevista', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data Prevista de Atendimento')),
                ('qtd_beneficiados_atendidos', models.IntegerField(null=True, verbose_name='Quantidade de Beneficiários Atendidos')),
                ('descricao_atendimento', djtools.db.models.CharFieldPlus(blank=True, max_length=5000, null=True, verbose_name='Descrição sobre o Atendimento da Demanda')),
                ('concluida_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Concluída em')),
                (
                    'area_tematica',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.AreaTematica', verbose_name='Área Temática'),
                ),
                (
                    'atribuida_por',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_externas_atribuidapor', to='comum.Vinculo', verbose_name='Atribuída Por'
                    ),
                ),
                ('avaliada_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Avaliada Por')),
                (
                    'campus_atendimento',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='demandaexterna_campus_atendimento',
                        to='rh.UnidadeOrganizacional',
                        verbose_name='Campus de Atendimento',
                    ),
                ),
                (
                    'campus_indicado',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus que fica mais próximo da demanda'
                    ),
                ),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Demanda Externa',
                'verbose_name_plural': 'Demandas Externas',
                'permissions': (
                    ('pode_ver_todas_demandas_externas', 'Pode ver todas as demandas externas'),
                    ('pode_ver_demandas_externas', 'Pode ver demandas externas do campus'),
                ),
            },
        ),
        migrations.CreateModel(
            name='PublicoAlvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Descrição de Público-Alvo', 'verbose_name_plural': 'Descrições de Público-Alvo'},
        ),
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Tipo de Ação de Extensão', 'verbose_name_plural': 'Tipos de Ação de Extensão'},
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5000, verbose_name='Título')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Início do Período')),
                ('data_termino', djtools.db.models.DateFieldPlus(verbose_name='Término do Período')),
                (
                    'descricao',
                    ckeditor.fields.RichTextField(
                        blank=True, help_text='Este texto será exibido no formulário de cadastro das demandas.', max_length=5000, null=True, verbose_name='Descrição'
                    ),
                ),
                ('campi', djtools.db.models.ManyToManyFieldPlus(blank=True, to='rh.UnidadeOrganizacional')),
            ],
            options={'verbose_name': 'Período de Recebimento de Demandas', 'verbose_name_plural': 'Períodos de Recebimento de Demandas', 'ordering': ['data_inicio']},
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='demandas_externas.Demanda', verbose_name='Demanda')),
                ('participante', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Participante')),
            ],
            options={'verbose_name': 'Participante da Demanda', 'verbose_name_plural': 'Participantes da Demanda'},
        ),
        migrations.AddField(
            model_name='demanda',
            name='periodo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='demandas_externas.Periodo', verbose_name='Período de Recebimento'),
        ),
        migrations.AddField(
            model_name='demanda', name='publico_alvo', field=djtools.db.models.ManyToManyFieldPlus(to='demandas_externas.PublicoAlvo', verbose_name='Público-alvo a ser atendido')
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandaexterna_responsavel', to='comum.Vinculo', verbose_name='Responsável'
            ),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tipo_acao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas_externas.TipoAcao', verbose_name='Tipo de Ação'),
        ),
    ]
