# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 15:36
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):
    def carregar_dados(apps, schema_editor):
        call_command('loaddata', '../fixtures/dados_iniciais_modulo.json')

    dependencies = [('demandas_externas', '0001_initial')]

    operations = [migrations.RunPython(carregar_dados)]
