# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível')),
            ],
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriais'},
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Descrição')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editorial')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={'verbose_name': 'Fonte', 'verbose_name_plural': 'Fontes'},
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Palavra-Chave', 'verbose_name_plural': 'Palavras-Chave'},
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateFieldPlus()),
                ('titulo', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Título')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.CreateModel(
            name='PublicacaoDigital',
            fields=[
                (
                    'publicacao_ptr',
                    models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clipping.Publicacao'
                    ),
                ),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='upload/clipping/digital/')),
                ('texto', models.TextField()),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
            ],
            options={'verbose_name': 'Publicação Digital', 'verbose_name_plural': 'Publicações Digitais'},
            bases=('clipping.publicacao',),
        ),
        migrations.CreateModel(
            name='PublicacaoEletronica',
            fields=[
                (
                    'publicacao_ptr',
                    models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clipping.Publicacao'
                    ),
                ),
                ('programa', models.CharField(blank=True, max_length=50, verbose_name='Programa')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/clipping/eletronico/')),
                ('link', models.CharField(blank=True, max_length=150, verbose_name='Link')),
            ],
            options={'verbose_name': 'Publicação Eletrônica', 'verbose_name_plural': 'Publicações Eletrônicas'},
            bases=('clipping.publicacao',),
        ),
        migrations.CreateModel(
            name='PublicacaoImpressa',
            fields=[
                (
                    'publicacao_ptr',
                    models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clipping.Publicacao'
                    ),
                ),
                ('subtitulo', models.CharField(blank=True, max_length=50, verbose_name='Subtítulo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/clipping/impresso/')),
                ('pagina', models.CharField(max_length=255, verbose_name='Página')),
                ('colunista', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colunista')),
            ],
            options={'verbose_name': 'Publicação Impressa', 'verbose_name_plural': 'Publicações Impressas'},
            bases=('clipping.publicacao',),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='classificacao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='clipping.Classificacao', verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='editorial',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                help_text='Categoria da notícia. Ex: Política, Saúde, Educação',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='clipping.Editorial',
                verbose_name='Editorial',
            ),
        ),
        migrations.AddField(model_name='publicacao', name='palavras_chaves', field=models.ManyToManyField(to='clipping.PalavraChave', verbose_name='Palavras-Chaves')),
        migrations.AddField(model_name='publicacao', name='uos', field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
        migrations.AddField(
            model_name='publicacao',
            name='veiculo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='clipping.Veiculo', verbose_name='Veículo'),
        ),
    ]
