# Generated by Django 2.2.16 on 2021-03-01 17:46

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaoeletronica',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='upload/clipping/eletronico/'),
        ),
        migrations.AlterField(
            model_name='publicacaoimpressa',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='upload/clipping/impresso/'),
        ),
    ]
