# Generated by Django 2.2.16 on 2021-03-09 20:04

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_auto_20210301_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaodigital',
            name='imagem',
            field=djtools.db.models.ImageFieldPlus(blank=True, null=True, upload_to='upload/clipping/digital/'),
        ),
    ]
