# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdp_ifrn', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='ano_termino_acao',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em caso de já possuir uma opção em consideração, qual o término previsto da ação de desenvolvimento para essa necessidade?', null=True, verbose_name='Término da Ação'),
        ),
    ]
