# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 11:28
from __future__ import unicode_literals

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdp_ifrn', '0003_auto_20200729_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicostatusresposta',
            name='justificativa',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='historicostatusresposta',
            name='status',
            field=djtools.db.models.CharFieldPlus(default=(('pendente', 'Pendente'), ('deferida', 'Deferida pela Comissão Local do Campus/Reitoria'), ('indeferida', 'Indeferida pela Comissão Local do Campus/Reitoria'), ('aprovada', 'Aprovada pelo Dirigente Máximo do Campus/Reitoria'), ('reprovada', 'Reprovada pelo Dirigente Máximo do Campus/Reitoria'), ('homologada', 'Homologada pelo Reitor'), ('rejeitada', 'Rejeitada pelo Reitor')), max_length=10, verbose_name='Situação'),
        ),
    ]
