# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 11:11
from __future__ import unicode_literals

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdp_ifrn', '0004_auto_20200729_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdp',
            name='manual',
            field=djtools.db.models.FileFieldPlus(blank=True, help_text='Manual com instruções de preenchimento', max_length=255, null=True, upload_to='pdp_ifrn/pdp/manuais', verbose_name='Manual'),
        ),
    ]
