# Generated by Django 2.2.16 on 2021-07-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdp_ifrn', '0006_resposta_enfoque_outros'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaassociada',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AlterField(
            model_name='pdp',
            name='ano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comum.Ano', verbose_name='Ano'),
        ),
    ]
