# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 11:13
from __future__ import unicode_literals

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='tema',
            field=djtools.db.models.CharFieldPlus(
                choices=[('Padrão', 'Padrão'), ('Dunas', 'Dunas'), ('Aurora', 'Aurora'), ('Luna', 'Luna'), ('Gov.br', 'Gov.br')], max_length=255, verbose_name='Opção de Tema'
            ),
        )
    ]
