# Generated by Django 2.2.7 on 2019-11-28 11:42

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0005_auto_20191125_1036')]

    operations = [
        migrations.CreateModel(
            name='CategoriaNotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Assunto')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={'verbose_name': 'Categoria de Notificação', 'verbose_name_plural': 'Categorias de Notificações'},
        ),
        migrations.CreateModel(
            name='NotificacaoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.CategoriaNotificacao')),
            ],
            options={'verbose_name': 'Mensagem da Notificação', 'verbose_name_plural': 'Mensagens das Notificações'},
        ),
        migrations.AddField(model_name='preferencia', name='via_email', field=models.BooleanField(default=True, verbose_name='Notificação Via E-mail')),
        migrations.AddField(model_name='preferencia', name='via_suap', field=models.BooleanField(default=True, verbose_name='Notificação Via SUAP')),
        migrations.AlterField(
            model_name='preferencia',
            name='contraste',
            field=djtools.db.models.CharFieldPlus(
                choices=[('Normal', 'Normal'), ('Alto Contraste', 'Alto Contraste')], default='Normal', max_length=255, verbose_name='Opção de Contraste'
            ),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='tema',
            field=djtools.db.models.CharFieldPlus(
                choices=[('Padrão', 'Padrão'), ('Dunas', 'Dunas'), ('Aurora', 'Aurora'), ('Luna', 'Luna'), ('Gov.br', 'Gov.br')],
                default='Padrão',
                max_length=255,
                verbose_name='Opção de Tema',
            ),
        ),
        migrations.CreateModel(
            name='RegistroNotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida?')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('notificacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.NotificacaoSistema', verbose_name='Notificação')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo')),
            ],
            options={'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações', 'ordering': ('-data',)},
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_suap', models.BooleanField(default=True, verbose_name='Via SUAP')),
                ('via_email', models.BooleanField(default=True, verbose_name='Via E-mail')),
                ('data', models.DateTimeField(auto_now=True)),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.CategoriaNotificacao')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo')),
            ],
            options={'verbose_name': 'Preferência de Notificação', 'verbose_name_plural': 'Preferências de Notificações', 'ordering': ('-data',)},
        ),
    ]
