# Generated by Django 2.2.7 on 2020-02-05 15:00

from django.db import migrations
import django.db.models.deletion
import djtools.db.models
from django.db import models


class Migration(migrations.Migration):

    dependencies = [('contenttypes', '0002_remove_content_type_name'), ('comum', '0006_auto_20191128_1142')]

    operations = [
        migrations.AddField(
            model_name='registroemissaodocumento',
            name='tipo_objeto',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Referência'),
        ),
        migrations.AddField(model_name='registroemissaodocumento', name='cancelado', field=models.BooleanField(default=False, verbose_name='Cancelado')),
        migrations.AlterField(model_name='registroemissaodocumento', name='codigo_verificador', field=models.TextField(verbose_name='Código Verificador')),
        migrations.AlterField(model_name='registroemissaodocumento', name='data_emissao', field=djtools.db.models.DateFieldPlus(verbose_name='Data de Emissão')),
        migrations.AlterField(model_name='registroemissaodocumento', name='data_validade', field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Validade')),
        migrations.AlterField(model_name='registroemissaodocumento', name='documento', field=models.FileField(upload_to='documentos', verbose_name='Documento')),
        migrations.AlterField(model_name='registroemissaodocumento', name='modelo_pk', field=models.IntegerField(null=True, verbose_name='Id da Referência')),
        migrations.AlterField(model_name='registroemissaodocumento', name='tipo', field=djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Tipo de Documento')),
    ]
