# Generated by Django 2.2.16 on 2020-10-23 15:42

from django.db import migrations


def atualizar_dados(apps, schema):
    Group = apps.get_model('auth.Group')
    g_old = Group.objects.filter(name='Coordenador de Sede').first()
    g_new = Group.objects.filter(name='Coordenador da Sede').first()
    if g_old is not None:
        for user in g_old.user_set.all():
            g_new.user_set.add(user)
        g_old.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_auto_20200205_1500'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados)
    ]
