# Generated by Django 2.2.10 on 2020-07-20 21:43
import hashlib
import tqdm
from django.db import migrations


def atualizar_nome_arquivos(apps, schema_editor):
    Arquivo = apps.get_model('comum', 'arquivo')

    fd = open('deploy/arquivo_bkp', 'w')

    for arquivo in tqdm.tqdm(Arquivo.objects.all().exclude(nome__isnull=True)):
        fd.write(f'{arquivo.id};{arquivo.nome}\n')
        nome = arquivo.nome
        ext_file = nome[nome.rfind('.'):]
        nome = hashlib.md5(f'{arquivo.vinculo.id}{nome}{arquivo.data_geracao}'.encode()).hexdigest()
        nome = f'{nome}{ext_file}'
        Arquivo.objects.filter(pk=arquivo.pk).update(nome=nome)

    fd.close()


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_auto_20200205_1500'),
    ]

    operations = [
        migrations.RunPython(atualizar_nome_arquivos)
    ]
