# Generated by Django 2.2.16 on 2020-11-09 14:44

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('comum', '0009_auto_20201023_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Grupo')),
                ('group', djtools.db.models.OneToOneFieldPlus(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Detalhes do Grupo',
                'verbose_name_plural': 'Detalhes dos Grupos',
            },
        ),
    ]
