# Generated by Django 2.2.16 on 2020-12-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0010_groupdetail'),
        ('comum', '0009_auto_20200720_2143'),
    ]

    operations = [
    ]
