# Generated by Django 2.2.16 on 2021-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0015_auto_20210301_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservico',
            name='email_google_classroom',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Google Classroom'),
        ),
    ]
