# Generated by Django 2.2.16 on 2021-03-30 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0016_prestadorservico_email_google_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', djtools.db.models.FileFieldPlus(upload_to='certificados_digitais', verbose_name='Arquivo')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
                ('organizacao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Organização')),
                ('unidade', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Unidade Organizacional')),
                ('validade', djtools.db.models.DateFieldPlus(verbose_name='Validade')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('user', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitais',
            },
        ),
    ]
