# Generated by Django 2.2.16 on 2021-04-01 18:51

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0016_prestadorservico_email_google_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='search',
            field=djtools.db.models.SearchField(blank=True, default='', editable=False),
        ),
    ]
