# Generated by Django 2.2.16 on 2021-04-01 18:53
from django.db import migrations
from django.db.models import F, Value, CharField
from django.db.models.functions import Concat


def atualizar_search_field_vinculo(apps, schema):
    Vinculo = apps.get_model('comum', 'vinculo')
    for vinculo in Vinculo.objects.all().annotate(search_field=Concat(F('user__username'), Value(' '),
                                                                      F('pessoa__nome'), Value(' '),
                                                                      F('pessoa__pessoafisica__cpf'), Value(' '),
                                                                      F('pessoa__pessoajuridica__cnpj'),
                                                                      output_field=CharField())):
        vinculo.search = vinculo.search_field
        vinculo.save()


def reverter_search_field_vinculo(apps, schema):
    Vinculo = apps.get_model('comum', 'vinculo')
    Vinculo.objects.update(search='')


class Migration(migrations.Migration):
    dependencies = [
        ('comum', '0017_vinculo_search'),
    ]

    operations = [migrations.RunPython(atualizar_search_field_vinculo, reverter_search_field_vinculo)]
