# Generated by Django 2.2.16 on 2021-04-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0017_certificadodigital'),
        ('comum', '0018_auto_20210401_1853'),
    ]

    operations = [
    ]
