# Generated by Django 2.2.16 on 2021-06-03 15:29

import comum.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0018_auto_20210401_1853'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', comum.models.UserManager()),
            ],
        ),
    ]
