# Generated by Django 2.2.16 on 2021-06-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0019_merge_20210407_0935'),
        ('comum', '0019_auto_20210603_1529'),
    ]

    operations = [
    ]
