# Generated by Django 2.2.24 on 2021-07-01 14:06
from django.core.management import call_command
from django.db import migrations


def atualizar_dados(apps, schema):
    IndexLayout = apps.get_model('comum.IndexLayout')
    IndexLayout.objects.filter(quadro_nome='PDI: FAROL DE DESEMPENHO').delete()
    call_command('limpar_index_layout')


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0020_emailblocklist'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados)
    ]
