# Generated by Django 2.2.24 on 2021-07-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0021_auto_20210701_1652'),
        ('comum', '0021_auto_20210701_1406'),
    ]

    operations = [
    ]
