# Generated by Django 2.2.16 on 2021-07-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0020_merge_20210622_1017'),
        ('comum', '0022_merge_20210702_1616'),
    ]

    operations = [
    ]
