# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0022_merge_20210702_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='ocorreu',
            field=models.BooleanField(null=True, verbose_name='Atividade Ocorreu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
