# Generated by Django 3.1 on 2021-08-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0023_merge_20210711_1548'),
        ('comum', '0024_pais_codigo_educacenso'),
    ]

    operations = [
    ]
