# Generated by Django 3.2.5 on 2021-08-17 20:44

from django.db import migrations


def remover_group_detail(apps, schema_editor):
    GroupDetail = apps.get_model('comum', 'GroupDetail')
    for group_detail in GroupDetail.objects.all():
        group_detail.delete()


def nao_faca_nada(apps, schema_editor):
    print('Ok')


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0025_merge_20210809_1005'),
    ]

    operations = [
        migrations.RunPython(remover_group_detail, nao_faca_nada),
    ]
