# Generated by Django 3.2.5 on 2021-08-17 20:55

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comum', '0026_auto_20210817_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetail',
            name='app',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='group',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdetail',
            unique_together={('app', 'group')},
        ),
    ]
