# Generated by Django 3.2.5 on 2021-09-17 17:04

import tqdm
from django.db import migrations
import user_agents


def atualizar_dados(apps, schema):
    SessionInfo = apps.get_model('comum.SessionInfo')
    Device = apps.get_model('comum.Device')

    for session in tqdm.tqdm(SessionInfo.objects.all()):
        ua = user_agents.parse(session.agent)
        ua_device = str(ua)
        device, _ = Device.objects.get_or_create(user_id=session.user_id, user_agent=session.agent, ip_address=session.ip_address, friendly_name=ua_device)
        session.device = device
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0028_auto_20210917_1607'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados),
    ]
