# Generated by Django 3.2.5 on 2021-10-19 11:25

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_auto_20211019_1107'),
        ('comum', '0031_forcar_habilitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocupacaoprestador',
            name='empresa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoajuridica', verbose_name='Pessoa Jurídica'),
        ),
    ]
