# Generated by Django 3.2.5 on 2021-12-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0033_groupdetail_app_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publico',
            options={'ordering': ['nome'], 'verbose_name': 'Público', 'verbose_name_plural': 'Públicos'},
        ),
    ]
