# Generated by Django 3.2.5 on 2021-12-08 16:51
import tqdm
from django.db import migrations


def atualizar_dados(apps, schema):
    SessionInfo = apps.get_model('comum.SessionInfo')
    Device = apps.get_model('comum.Device')

    ids_excluidos = []

    for device in tqdm.tqdm(Device.objects.all().order_by('user_agent', 'user', 'nickname')):
        if device.pk not in ids_excluidos:
            another_devices = Device.objects.filter(user_agent=device.user_agent, user=device.user).exclude(pk=device.pk)
            SessionInfo.objects.filter(device=device).update(ip_address=device.ip_address)
            for another in another_devices:
                SessionInfo.objects.filter(device=another).update(ip_address=another.ip_address, device=device)
            ids_excluidos = ids_excluidos + list(another_devices.values_list('pk', flat=True))
            another_devices.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0034_sessioninfo_ip_address'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados)
    ]
