# Generated by Django 3.2.5 on 2022-04-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0038_auto_20211215_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='contraste',
        ),
    ]
