# Generated by Django 3.2.5 on 2022-05-10 14:39

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.storages.storage


class Migration(migrations.Migration):

    dependencies = [
        # ('protocolo', '0003_alter_processo_interessado_nome'),
        ('comum', '0039_remove_preferencia_contraste'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcabamentoExternoPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Acabamento Externo (Fachada)',
                'verbose_name_plural': 'Acabamentos Externos (Fachadas)',
            },
        ),
        migrations.CreateModel(
            name='AcabamentoParedeSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Acabamento da Parede',
                'verbose_name_plural': 'Acabamentos das Paredes',
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('descricao_expandida', models.TextField(verbose_name='Descrição Expandida')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.CreateModel(
            name='ClimatizacaoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Climatização',
                'verbose_name_plural': 'Climatizações',
            },
        ),
        migrations.CreateModel(
            name='CoberturaPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
            },
        ),
        migrations.CreateModel(
            name='EsquadriasSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Esquadria',
                'verbose_name_plural': 'Esquadrias',
            },
        ),
        migrations.CreateModel(
            name='EstruturaPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Estrutura',
                'verbose_name_plural': 'Estruturas',
            },
        ),
        migrations.CreateModel(
            name='ForroSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forro',
                'verbose_name_plural': 'Forros',
            },
        ),
        migrations.CreateModel(
            name='InstalacaoEletricaSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Instalação Elétrica',
                'verbose_name_plural': 'Instalações Elétricas',
            },
        ),
        migrations.CreateModel(
            name='InstalacaoGasesSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Instalação de Gases',
                'verbose_name_plural': 'Instalações de Gases',
            },
        ),
        migrations.CreateModel(
            name='InstalacaoHidraulicaSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstalacaoLogicaSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Instalação de Lógica',
                'verbose_name_plural': 'Instalações de Lógica',
            },
        ),
        migrations.CreateModel(
            name='PisoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='SistemaAbastecimentoPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sistema de Abastecimento',
                'verbose_name_plural': 'Sistemas de Abastecimentos',
            },
        ),
        migrations.CreateModel(
            name='SistemaAlimentacaoEletricaPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sistema de Alimentação Elétrica',
                'verbose_name_plural': 'Sistemas de Alimentação Elétrica',
            },
        ),
        migrations.CreateModel(
            name='SistemaProtecaoDescargaAtmosfericaPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sistema de Proteção Contra Descargas Atmosféricas',
                'verbose_name_plural': 'Sistemas de Proteção Contra Descargas Atmosféricas',
            },
        ),
        migrations.CreateModel(
            name='SistemaSanitarioPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sistema Sanitário',
                'verbose_name_plural': 'Sistemas Sanitários',
            },
        ),
        migrations.CreateModel(
            name='UsoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Uso da Sala',
                'verbose_name_plural': 'Usos da Sala',
            },
        ),
        migrations.CreateModel(
            name='VedacaoPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Vedação',
                'verbose_name_plural': 'Vedações',
            },
        ),
        migrations.AddField(
            model_name='predio',
            name='informacao_sistema_alimentacao_eletrica',
            field=models.TextField(blank=True, help_text='Informações adicionais do sistema de alimentação elétrica', null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='predio',
            name='potencia_transformador',
            field=models.PositiveIntegerField(blank=True, help_text='Informar em KVA', null=True, verbose_name='Potência do Transformador'),
        ),
        migrations.AddField(
            model_name='sala',
            name='area_parede',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Informar em m²', max_digits=12, null=True, verbose_name='Área de Parede'),
        ),
        migrations.AddField(
            model_name='sala',
            name='area_util',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Informar em m²', max_digits=12, null=True, verbose_name='Área Útil'),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[[0, 'Original'], [1, 'Ampliação'], [2, 'Reforma']], verbose_name='Tipo da Obra')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Início da Obra')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Escopo')),
                ('data_recebimento', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Recebimento Definitivo')),
                ('area_construida', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Informar em m²', max_digits=12, null=True, verbose_name='Área Construída')),
                ('predio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.predio', verbose_name='Prédio')),
                # ('processo_recebimento', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.processo', verbose_name='Processo de Recebimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombateIncendioPanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_pscip', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Protocolo PSCIP')),
                ('data_vistoria', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Vistoria Técnica')),
                ('data_validade_alvara', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Validade do Alvará')),
                ('alvara', djtools.db.models.PrivateFileField(blank=True, max_length=255, null=True, storage=djtools.storages.storage.PrivateFileSystemStorage(), upload_to='comum/predio/alvaras', verbose_name='Alvará')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('predio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.predio', verbose_name='Prédio')),
            ],
            options={
                'verbose_name': 'Combate a Incêndio e Pânico',
                'verbose_name_plural': 'Combates a Incêndio e Pânico',
                'ordering': ['predio__uo__setor__sigla', '-data_vistoria'],
            },
        ),
        migrations.AddField(
            model_name='predio',
            name='acabamento_externo',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.AcabamentoExternoPredio', verbose_name='Acabamento Externo (Fachadas)'),
        ),
        migrations.AddField(
            model_name='predio',
            name='cobertura',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.CoberturaPredio', verbose_name='Cobertura'),
        ),
        migrations.AddField(
            model_name='predio',
            name='estrutura',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.EstruturaPredio', verbose_name='Estrutura'),
        ),
        migrations.AddField(
            model_name='predio',
            name='sistema_abastecimento',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.SistemaAbastecimentoPredio', verbose_name='Sistema de Abastecimento'),
        ),
        migrations.AddField(
            model_name='predio',
            name='sistema_alimentacao_eletrica',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.SistemaAlimentacaoEletricaPredio', verbose_name='Sistema de Alimentação Elétrica'),
        ),
        migrations.AddField(
            model_name='predio',
            name='sistema_protecao_descarga_atmosferica',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.SistemaProtecaoDescargaAtmosfericaPredio', verbose_name='Sistema de Proteção Contra Descargas Atmosféricas'),
        ),
        migrations.AddField(
            model_name='predio',
            name='sistema_sanitario',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.SistemaSanitarioPredio', verbose_name='Sistema Sanitário'),
        ),
        migrations.AddField(
            model_name='predio',
            name='vedacao',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.VedacaoPredio', verbose_name='Vedação'),
        ),
        migrations.AddField(
            model_name='sala',
            name='acabamento_parede',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.AcabamentoParedeSala', verbose_name='Acabamento das Paredes'),
        ),
        migrations.AddField(
            model_name='sala',
            name='classificacao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.classificacaosala', verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='sala',
            name='climatizacao',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.ClimatizacaoSala', verbose_name='Climatização'),
        ),
        migrations.AddField(
            model_name='sala',
            name='esquadrias',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.EsquadriasSala', verbose_name='Esquadrias'),
        ),
        migrations.AddField(
            model_name='sala',
            name='forro',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.ForroSala', verbose_name='Forro'),
        ),
        migrations.AddField(
            model_name='sala',
            name='instalacao_eletrica',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.InstalacaoEletricaSala', verbose_name='Instalação Elétrica'),
        ),
        migrations.AddField(
            model_name='sala',
            name='instalacao_gases',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.InstalacaoGasesSala', verbose_name='Instalação de Gases'),
        ),
        migrations.AddField(
            model_name='sala',
            name='instalacao_hidraulica',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.InstalacaoHidraulicaSala', verbose_name='Instalação Hidráulica'),
        ),
        migrations.AddField(
            model_name='sala',
            name='instalacao_logica',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.InstalacaoLogicaSala', verbose_name='Instalação de Lógica'),
        ),
        migrations.AddField(
            model_name='sala',
            name='piso',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='comum.PisoSala', verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='sala',
            name='uso',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.usosala', verbose_name='Uso da sala'),
        ),
    ]
