# Generated by Django 3.2.5 on 2022-05-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0040_auto_20220510_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacaohidraulicasala',
            options={'verbose_name': 'Instalação Hidráulica', 'verbose_name_plural': 'Instalações Hidráulicas'},
        ),
    ]
