# Generated by Django 3.2.5 on 2022-06-20 10:42

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0041_alter_instalacaohidraulicasala_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoreservasala',
            name='status',
            field=djtools.db.models.CharFieldPlus(choices=[('deferida', 'Deferida'), ('indeferida', 'Indeferida'), ('parcialmente_deferida', 'Parcialmente Deferida'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('excluida', 'Excluída')], default='aguardando_avaliacao', max_length=255, verbose_name='Situação'),
        ),
    ]
