# Generated by Django 3.2.4 on 2022-06-21 17:42

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0042_alter_solicitacaoreservasala_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaosistema',
            name='objeto_relacionado',
            field=djtools.db.models.CharFieldPlus(db_index=True, max_length=255, null=True, verbose_name='Objeto Relacionado'),
        ),
    ]
