# Generated by Django 3.2.5 on 2022-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0044_contatoemergencia'),
        ('comum', '0044_merge_20220705_1111'),
    ]

    operations = [
    ]
