# Generated by Django 3.2.5 on 2022-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0045_merge_0044_contatoemergencia_0044_merge_20220705_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservico',
            name='chefia_imediata',
            field=models.BooleanField(default=False, help_text='Indica se o prestador é uma Chefia imediata', verbose_name='Chefia imediata'),
        ),
    ]
