# Generated by Django 3.2.5 on 2022-09-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0046_nivelensino_orgaoemissorrg'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='uf_code',
            field=models.CharField(blank=True, help_text='Código IBGE UF', max_length=10, null=True, verbose_name='Código IBGE UF'),
        ),
    ]
