# Generated by Django 3.2.5 on 2022-09-28 13:38

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0048_alter_vinculo_tipo_relacionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Nome do Conselho')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=10, verbose_name='Sigla do Conselho')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Conselho Profissional',
                'verbose_name_plural': 'Conselhos Profissionais',
            },
        ),
    ]
