# Generated by Django 3.2.5 on 2022-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0049_conselhoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eh_residente',
            field=models.BooleanField(default=False),
        ),
    ]
