# Generated by Django 3.2.5 on 2022-09-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0046_prestadorservico_chefia_imediata'),
        ('comum', '0050_user_eh_residente'),
    ]

    operations = [
    ]
