# Generated by Django 3.2.5 on 2022-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0051_merge_20220929_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eh_trabalhadoreducando',
            field=models.BooleanField(default=False),
        ),
    ]
