# Generated by Django 3.2.5 on 2022-09-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0052_auto_20220929_2124'),
        ('comum', '0052_user_eh_trabalhadoreducando'),
    ]

    operations = [
    ]
