# Generated by Django 3.2.5 on 2023-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0056_alter_vinculo_tipo_relacionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorioIdentidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('lista_cidades', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Território de identidade',
                'verbose_name_plural': 'Territórios de identidade',
            },
        ),
    ]
