# Generated by Django 3.2.5 on 2023-04-27 16:02

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0058_municipio_territorio_identidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservico',
            name='data_admissao',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='data_demissao',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
    ]
