# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='UUID')),
                ('type', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Tipo')),
                ('message', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Mensagem')),
                ('file', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Arquivo')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('partial', models.IntegerField(default=0, verbose_name='Parcial')),
                ('error', models.TextField(null=True, verbose_name='Erro')),
                ('start', djtools.db.models.DateTimeFieldPlus(auto_now=True, verbose_name='Início')),
                ('end', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Fim')),
                ('url', djtools.db.models.CharFieldPlus(default='', max_length=524, verbose_name='URL de Redirecionamento')),
                (
                    'user',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        )
    ]
