# Generated by Django 2.2.16 on 2021-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
