# Generated by Django 2.2.16 on 2021-07-09 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djtools', '0002_task_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthenticationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='E-mail')),
                ('expires', djtools.db.models.DateTimeFieldPlus()),
                ('code', djtools.db.models.CharFieldPlus(max_length=6, verbose_name='Código')),
                ('user', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código de Autenticação',
                'verbose_name_plural': 'Códigos de Autenticação',
            },
        ),
    ]
