# Generated by Django 3.2.5 on 2022-07-14 11:08

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('djtools', '0005_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCidadaoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_api', models.JSONField(verbose_name='Filtros de API')),
                ('resultado', models.JSONField()),
                ('data_expiracao', djtools.db.models.DateTimeFieldPlus()),
                ('cpf_operador', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Cpf do Operador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
