# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import oauth2_provider.generators
import oauth2_provider.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='AplicacaoOAuth2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                (
                    'authorization_grant_type',
                    models.CharField(
                        choices=[
                            ('authorization-code', 'Authorization code'),
                            ('implicit', 'Implicit'),
                            ('password', 'Resource owner password-based'),
                            ('client-credentials', 'Client credentials'),
                        ],
                        max_length=32,
                    ),
                ),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logotipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'Aplicação (OAuth2)', 'verbose_name_plural': 'Aplicações (OAuth2)', 'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.CreateModel(
            name='SolicitacaoAplicacaoOAuth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aplicacao', djtools.db.models.CharFieldPlus(max_length=120, verbose_name='Nome da Aplicação')),
                ('descricao', models.TextField(verbose_name='Breve Descrição da Aplicação')),
                ('url_repositorio', models.URLField(verbose_name='URL do Repositório')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logotipo')),
                (
                    'forma_autenticacao',
                    models.CharField(
                        choices=[('authorization-code', 'Authorization Code'), ('client-credentials', 'Client Credentials')],
                        default='client-credentials',
                        help_text='\n            <strong>Authorization Code</strong>: Essa forma de autenticação deve ser utilizada por aplicações que \n            queiram acessar as informações privadas das contas de usuários do SUAP.\n            <br/>\n            <strong>Client Credentials</strong>: Essa forma de autenticação deve ser usada por aplicações que queiram \n            acessar os dados públicos do SUAP.\n        ',
                        max_length=32,
                        verbose_name='Forma de Autenticação',
                    ),
                ),
                (
                    'redirect_uris',
                    models.TextField(
                        blank=True,
                        help_text='\n            É para onde o cliente será enviado depois que a autorização da conta for bem-sucedida. \n            Informe uma ou mais URIs separadas por espaço.\n        ',
                        verbose_name='Redirect URIs',
                    ),
                ),
                ('deferida', models.BooleanField(default=False)),
                (
                    'vinculo_responsavel',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo do Responsável pela Aplicação'),
                ),
            ],
            options={'verbose_name': 'Solicitação de Aplicação (OAuth2)', 'verbose_name_plural': 'Solicitações de Aplicação (OAuth2)'},
        ),
        migrations.AddField(
            model_name='aplicacaooauth2',
            name='solicitacao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SolicitacaoAplicacaoOAuth2', verbose_name='Solicitação de Criação de Aplicação'
            ),
        ),
        migrations.AddField(
            model_name='aplicacaooauth2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_aplicacaooauth2', to=settings.AUTH_USER_MODEL),
        ),
    ]
