# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('api', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='solicitacaoaplicacaooauth2', name='vinculo_responsavel'),
        migrations.AlterModelOptions(name='aplicacaooauth2', options={'ordering': ['id']}),
        migrations.RemoveField(model_name='aplicacaooauth2', name='ativa'),
        migrations.RemoveField(model_name='aplicacaooauth2', name='descricao'),
        migrations.RemoveField(model_name='aplicacaooauth2', name='logotipo'),
        migrations.RemoveField(model_name='aplicacaooauth2', name='solicitacao'),
        migrations.AlterField(
            model_name='aplicacaooauth2',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('client-credentials', 'Client credentials')], max_length=32),
        ),
        migrations.DeleteModel(name='SolicitacaoAplicacaoOAuth2'),
    ]
