# Generated by Django 2.2.9 on 2020-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('api', '0002_auto_20191108_1116')]

    operations = [migrations.AddField(model_name='aplicacaooauth2', name='granted_scopes', field=models.TextField(blank=True))]
