# Generated by Django 2.2.24 on 2021-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aplicacaooauth2_granted_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaooauth2',
            name='algorithm',
            field=models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5),
        ),
    ]
