# Generated by Django 3.2.5 on 2022-02-04 09:36

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_aplicacaooauth2_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaooauth2',
            name='user',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_aplicacaooauth2', to=settings.AUTH_USER_MODEL),
        ),
    ]
