# Generated by Django 2.2.9 on 2020-02-11 20:37

import boletim_servico.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('documento_eletronico', '0003_auto_20191230_1458'), ('rh', '0005_auto_20200123_1113')]

    operations = [
        migrations.CreateModel(
            name='BoletimProgramado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512, verbose_name='Título')),
                (
                    'nivel_acesso',
                    boletim_servico.models.ChoiceArrayField(
                        base_field=models.PositiveSmallIntegerField(choices=[(1, 'Sigiloso'), (2, 'Restrito'), (3, 'Público')]),
                        size=None,
                        verbose_name='Nível de Acesso de Documentos',
                    ),
                ),
                ('programado', models.BooleanField(default=False, verbose_name='Gerar boletim diário?')),
                ('programado_semanal', models.BooleanField(default=False, verbose_name='Gerar boletim semanal?')),
                ('programado_mensal', models.BooleanField(default=False, verbose_name='Gerar boletim mensal?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tipo_documento', models.ManyToManyField(to='documento_eletronico.TipoDocumento', verbose_name='Tipos de Documentos')),
            ],
            options={'verbose_name': 'Boletim de Serviço Programado', 'verbose_name_plural': 'Boletins de Serviço Programados'},
        ),
        migrations.CreateModel(
            name='ConfiguracaoSetorBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=512, verbose_name='Nome do Setor no Boletim')),
                ('ordenacao', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem do Setor no Boletim')),
                ('material_anexo', models.FileField(blank=True, null=True, upload_to='boletim_servico/anexos/', verbose_name='Material a anexar no final da seção do setor')),
                ('boletim_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim_servico.BoletimProgramado', verbose_name='Boletim Programado')),
                (
                    'setor_documento',
                    models.ForeignKey(limit_choices_to={'codigo': None}, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor', verbose_name='Setor do Documento'),
                ),
            ],
            options={'verbose_name': 'Configuração de Setor no Boletim', 'verbose_name_plural': 'Configurações de Setor no Boletim'},
        ),
        migrations.CreateModel(
            name='BoletimPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo do boletim')),
                (
                    'situacao',
                    models.PositiveSmallIntegerField(choices=[(1, '--'), (2, 'Solicitado'), (3, 'Gerando'), (4, 'Finalizado'), (6, 'Erro')], default=1, verbose_name='Situação'),
                ),
                ('data_inicio', models.DateField(verbose_name='Data Inicial do boletim')),
                ('data_fim', models.DateField(verbose_name='Data Final do boletim')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do boletim')),
                ('edicao_extra', models.PositiveSmallIntegerField(default=0, verbose_name='Número da edição extra')),
                ('boletim_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim_servico.BoletimProgramado', verbose_name='Boletim programado')),
                ('documentos', models.ManyToManyField(to='documento_eletronico.DocumentoTexto', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'Boletim de Serviço do Período',
                'verbose_name_plural': 'Boletins de Serviço do Período',
                'unique_together': {('boletim_programado', 'data_inicio', 'data_fim', 'edicao_extra')},
            },
        ),
        migrations.CreateModel(
            name='BoletimDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo do boletim')),
                (
                    'situacao',
                    models.PositiveSmallIntegerField(choices=[(1, '--'), (2, 'Solicitado'), (3, 'Gerando'), (4, 'Finalizado'), (6, 'Erro')], default=1, verbose_name='Situação'),
                ),
                ('data', models.DateField(verbose_name='Data do boletim')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do boletim')),
                ('edicao_extra', models.PositiveSmallIntegerField(default=0, verbose_name='Número da edição extra')),
                ('boletim_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim_servico.BoletimProgramado', verbose_name='Boletim programado')),
                ('documentos', models.ManyToManyField(to='documento_eletronico.DocumentoTexto', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'Boletim de Serviço Diário',
                'verbose_name_plural': 'Boletins de Serviços Diários',
                'unique_together': {('boletim_programado', 'data', 'edicao_extra')},
            },
        ),
    ]
