# Generated by Django 2.2.10 on 2020-03-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('boletim_servico', '0001_initial')]

    operations = [
        migrations.AlterField(model_name='boletimperiodo', name='arquivo', field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo do Boletim')),
        migrations.AlterField(
            model_name='boletimperiodo',
            name='boletim_programado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim_servico.BoletimProgramado', verbose_name='Boletim Programado'),
        ),
        migrations.AlterField(model_name='boletimperiodo', name='data_criacao', field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Boletim')),
    ]
