# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('boletim_servico', '0002_auto_20200305_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimdiario',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Arquivo do boletim'),
        ),
        migrations.AlterField(
            model_name='boletimperiodo',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Arquivo do Boletim'),
        ),
        migrations.AlterField(
            model_name='configuracaosetorboletim',
            name='material_anexo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='boletim_servico/anexos/', verbose_name='Material a anexar no final da seção do setor'),
        ),
    ]
