# Generated by Django 3.2.5 on 2021-12-23 11:54

import os
import shutil
import tqdm
from django.db import migrations
from django.conf import settings


def atualizar(qs, field_str, path):
    marcar_para_deletar = []
    folder = os.path.join(settings.MEDIA_ROOT, path)
    os.makedirs(folder, exist_ok=True)
    for obj in tqdm.tqdm(qs):
        field = getattr(obj, field_str)
        file_name = field.name
        file_name = file_name and file_name.startswith('./') and file_name[2:] or file_name
        if file_name:
            original = os.path.join(settings.MEDIA_ROOT, file_name)
            marcar_para_deletar.append(original)
            target = os.path.join(folder, file_name)
            setattr(obj, field_str, os.path.join(path, file_name))
            obj.save()
            if not settings.DEBUG:
                shutil.copyfile(original, target)
    if not settings.DEBUG:
        for arquivo in marcar_para_deletar:
            os.remove(arquivo)
    with open(os.path.join(settings.MEDIA_ROOT, 'arquivos_excluidos.txt'), 'a') as f:
        for arquivo in marcar_para_deletar:
            f.write(arquivo + '\n')
    return marcar_para_deletar


def atualizar_dados(apps, schema):
    print('\natualizando boletimperiodo\n')
    BoletimPeriodo = apps.get_model('boletim_servico.BoletimPeriodo')
    atualizar(BoletimPeriodo.objects.exclude(arquivo__startswith='boletim_servico'), 'arquivo', 'boletim_servico/boletim_periodo')

    print('\natualizando boletimdiario\n')
    BoletimDiario = apps.get_model('boletim_servico.BoletimDiario')
    atualizar(BoletimDiario.objects.exclude(arquivo__startswith='boletim_servico'), 'arquivo', 'boletim_servico/boletim_diario')


class Migration(migrations.Migration):

    dependencies = [
        ('boletim_servico', '0004_auto_20211223_1154'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados),
    ]
