# Generated by Django 3.2.5 on 2022-09-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0046_prestadorservico_chefia_imediata'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ChefiaImediata',
        #     fields=[
        #     ],
        #     options={
        #         'verbose_name': 'Chefia imediata',
        #         'verbose_name_plural': 'Chefias imediatas',
        #         'proxy': True,
        #         'indexes': [],
        #         'constraints': [],
        #     },
        #     bases=('comum.prestadorservico',),
        # ),
    ]
