# Generated by Django 3.2.5 on 2022-10-21 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppe', '0003_observacao_sequencialmatriculatrabalhadoreducando_trabalhadoreducando'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativa')),
                ('criterio_avaliacao', models.PositiveIntegerField(choices=[[1, 'Nota'], [2, 'Frequência']], verbose_name='Critério de Avaliação')),
                ('media_aprovacao_sem_prova_final', djtools.db.models.NotaField(blank=True, null=True, verbose_name='Média para passar sem prova final')),
                ('media_aprovacao_avaliacao_final', djtools.db.models.NotaField(blank=True, null=True, verbose_name='Média para aprovação após avaliação final')),
                ('percentual_frequencia', models.PositiveIntegerField(default=90, help_text='Percentual (%) mínimo de frequência para que os alunos não reprovem no período ou na disciplina.', verbose_name='Percentual Mínimo de Frequência')),
            ],
            options={
                'verbose_name': 'Estrutura de Curso',
                'verbose_name_plural': 'Estruturas de Curso',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', djtools.db.models.DateTimeFieldPlus(auto_now=True)),
                ('tipo', models.IntegerField(choices=[[1, 'Cadastro'], [2, 'Edição'], [3, 'Exclusão'], [4, 'Visualização']])),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255)),
                ('app', djtools.db.models.CharFieldPlus(max_length=255)),
                ('modelo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('nome_modelo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('ref', models.IntegerField(db_index=True)),
                ('ref_aluno', models.IntegerField(db_index=True, null=True)),
                ('ref_diario', models.IntegerField(db_index=True, null=True)),
                ('trabalhador_educando', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppe.trabalhadoreducando')),
                ('user', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_user_ppe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiferenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.TextField()),
                ('valor_atual', models.TextField()),
                ('campo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('log', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.log')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
