# Generated by Django 3.2.5 on 2022-10-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0004_estruturacurso_log_registrodiferenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ref_aluno',
            new_name='ref_trabalhador_educando',
        ),
        migrations.RemoveField(
            model_name='log',
            name='ref_diario',
        ),
    ]
