# Generated by Django 3.2.5 on 2022-10-21 08:48

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0005_auto_20221021_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo_academico', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('descricao_historico', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição no Diploma e Histórico')),
                ('data_inicio', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', djtools.db.models.CharFieldPlus(help_text='Código para composição de turmas e matrículas', max_length=255, unique=True, verbose_name='Código')),
                ('ch_total', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Carga Horária Total h/r')),
                ('ch_aula', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Carga Horária Total h/a')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('-ativo',),
            },
        ),
    ]
