# Generated by Django 3.2.5 on 2022-10-21 09:21

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0006_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoFormacaoPPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'Regular']])),
                ('optativo', models.BooleanField(default=False)),
                ('qtd_avaliacoes', models.PositiveIntegerField(choices=[[0, 'Zero'], [1, 'Uma'], [2, 'Duas'], [4, 'Quatro']], verbose_name='Qtd. Avaliações')),
                ('ch_presencial', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Teórica')),
                ('ch_pratica', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Prática')),
                ('ementa', models.TextField(blank=True, default='', null=True, verbose_name='Ementa')),
                ('co_requisitos', djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='corequisitos_ppe_set', to='ppe.CursoFormacaoPPE')),
                ('curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.curso')),
            ],
            options={
                'verbose_name': 'Curso PPE',
                'verbose_name_plural': 'Cursos PPE',
            },
        ),
        migrations.CreateModel(
            name='FormacaoPPE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de fim')),
                ('ppp', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='ppe/ppp/', verbose_name='PPP')),
                ('ch_componentes_obrigatorios', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Componentes obrigatórios')),
                ('inconsistente', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cursos', models.ManyToManyField(through='ppe.CursoFormacaoPPE', to='ppe.Curso')),
                ('estrutura', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.estruturacurso')),
            ],
            options={
                'verbose_name': 'Formação PPE',
                'verbose_name_plural': 'Formações PPE',
                'ordering': ('descricao',),
            },
        ),
        migrations.AddField(
            model_name='cursoformacaoppe',
            name='formacao_ppe',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.formacaoppe'),
        ),
        migrations.AddField(
            model_name='cursoformacaoppe',
            name='pre_requisitos',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='prerequisitos_ppe_set', to='ppe.CursoFormacaoPPE'),
        ),
    ]
