# Generated by Django 3.2.5 on 2022-11-15 16:47

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0009_auto_20221104_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacaoppe',
            name='estrutura',
        ),
        migrations.AddField(
            model_name='cursoformacaoppe',
            name='estrutura',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.estruturacurso'),
        ),
    ]
