# Generated by Django 3.2.5 on 2022-11-22 16:50

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0010_auto_20221115_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Grupo')),
                ('codigo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Código')),
                ('sequencial', models.PositiveIntegerField(default=1)),
                ('formacao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.formacaoppe')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('codigo',),
                'permissions': (('gerar_turmas', 'Gerar Turmas'),),
            },
        ),
    ]
