# Generated by Django 3.2.5 on 2022-11-30 08:48

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('ppe', '0011_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('turma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.turma', verbose_name='Turma')),
                ('tutor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.bolsista', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Vínculo de Tutor em uma Turma',
                'verbose_name_plural': 'Vínculos de Tutor em uma Turma',
            },
        ),
    ]
