# Generated by Django 3.2.5 on 2022-11-30 11:14

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('ppe', '0013_rename_tutortruma_tutorturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoiadorTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('apoiador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.bolsista', verbose_name='Apoiador(a) Pedagógico')),
                ('turma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Vínculo de Apoiador Pedagógico em uma Turma',
                'verbose_name_plural': 'Vínculos de Apoiadores Pedagógico em uma Turma',
            },
        ),
    ]
