# Generated by Django 3.2.5 on 2022-11-30 14:07

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0014_apoiadorturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('quantidade_vagas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Vagas')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'Aberto'], [2, 'Fechado']], default=1, verbose_name='Situação')),
                ('descricao_dinamica', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição Dinâmica')),
                ('posse_etapa_1', models.PositiveIntegerField(choices=[[1, 'Tutor'], [0, 'Coordenador']], default=1)),
                ('curso_formacao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.cursoformacaoppe', verbose_name='Curso')),
                ('estrutura_curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.estruturacurso', verbose_name='Estrutura de Curso')),
                ('turma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Diário de Curso',
                'verbose_name_plural': 'Diários de Cursos',
                'permissions': (('lancar_nota_curso_turma', 'Pode lançar nota em Cursos'),),
            },
        ),
    ]
