# Generated by Django 3.2.5 on 2022-12-01 09:39

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0015_cursoturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoturma',
            name='data_fim_etapa_1',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da primeira etapa', null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='data_fim_prova_final',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Encerramento da Prova Final'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='data_inicio_etapa_1',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da primeira etapa', null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='data_inicio_prova_final',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início da Prova Final'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='posse_fim_prova_final',
            field=models.PositiveIntegerField(choices=[[1, 'Tutor'], [0, 'Coordenador']], default=1),
        ),
    ]
