# Generated by Django 3.2.5 on 2022-12-01 16:33

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0016_auto_20221201_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhadoreducando',
            name='formacao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.formacaoppe'),
        ),
    ]
