# Generated by Django 3.2.5 on 2022-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0019_matriculacursotruma'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ref_curso_turma',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
