# Generated by Django 3.2.5 on 2022-12-09 09:23

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0021_anamnese'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosTrabalhadorEducando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Curso que o trabalhador educando participa')),
            ],
            options={
                'verbose_name': 'Curso que o trabalhador educando participa',
                'verbose_name_plural': 'Cursos que o trabalhador educando participa',
            },
        ),
        migrations.CreateModel(
            name='ItensResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Item da Residência do Trabalhador Educando')),
            ],
            options={
                'verbose_name': 'Item da Residência do Trabalhador Educando',
                'verbose_name_plural': 'Itens da Residência do Trabalhador Educando',
            },
        ),
        migrations.CreateModel(
            name='MeioTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Meio de Transporte para deslocamento para o trabalho')),
            ],
            options={
                'verbose_name': 'Meio de Transporte para deslocamento para o trabalho',
                'verbose_name_plural': 'Meios de Transporte para deslocamento para o trabalho',
            },
        ),
        migrations.CreateModel(
            name='MembrosCarteiraAssinada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Pessoa da família do Trabalhador Educando que tem carteira assinada')),
            ],
            options={
                'verbose_name': 'Pessoa da família do Trabalhador Educando que tem carteira assinada',
                'verbose_name_plural': 'Pessoas da família do Trabalhador Educando que tem carteira assinada',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoGruposSociais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Grupo Social que o Trabalhador Educando participa')),
            ],
            options={
                'verbose_name': 'Grupo Social que o trabalhador educando participa',
                'verbose_name_plural': 'Grupos Sociais que o trabalhador educando participa',
            },
        ),
        migrations.CreateModel(
            name='ResideCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Pessoa com a qual o Trabalhador Educando reside')),
            ],
            options={
                'verbose_name': 'Pessoa com a qual o Trabalhador Educando reside',
                'verbose_name_plural': 'Pessoas com as quais o Trabalhador Educando reside',
            },
        ),
        migrations.CreateModel(
            name='ResidenciaSaneamentoBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Tipo de Saneamento básico')),
            ],
            options={
                'verbose_name': 'Saneamento básico',
                'verbose_name_plural': 'Saneamentos básicos',
            },
        ),
        migrations.CreateModel(
            name='TrabalhoAnteriorAoPPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Trabalho Antes de Ingressar ao ppe')),
            ],
            options={
                'verbose_name': 'Trabalho Antes de Ingressar ao ppe',
                'verbose_name_plural': 'Trabalhos Antes de Ingressar ao ppe',
            },
        ),
    ]
