# Generated by Django 3.2.5 on 2022-12-09 09:57

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0022_cursostrabalhadoreducando_itensresidencia_meiotransporte_membroscarteiraassinada_participacaogruposs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Rede social que trabalhador educando participa')),
            ],
            options={
                'verbose_name': 'Rede social que trabalhador educando participa',
                'verbose_name_plural': '(Anamnese) Redes sociais que trabalhador educando participa',
            },
        ),
        migrations.AlterModelOptions(
            name='cursostrabalhadoreducando',
            options={'verbose_name': 'Curso que o trabalhador educando realiza/realizou', 'verbose_name_plural': '(Anamnese) Cursos que o trabalhador educando realiza/realizou'},
        ),
        migrations.AlterModelOptions(
            name='itensresidencia',
            options={'verbose_name': 'Item da Residência do Trabalhador Educando', 'verbose_name_plural': '(Anamnese) Itens da Residência do Trabalhador Educando'},
        ),
        migrations.AlterModelOptions(
            name='meiotransporte',
            options={'verbose_name': 'Meio de Transporte para deslocamento para o trabalho', 'verbose_name_plural': '(Anamnese) Meios de Transporte para deslocamento para o trabalho'},
        ),
        migrations.AlterModelOptions(
            name='membroscarteiraassinada',
            options={'verbose_name': 'Pessoa da família do Trabalhador Educando que tem carteira assinada', 'verbose_name_plural': '(Anamnese) Pessoas da família do Trabalhador Educando que tem carteira assinada'},
        ),
        migrations.AlterModelOptions(
            name='participacaogrupossociais',
            options={'verbose_name': 'Grupo Social que o trabalhador educando participa', 'verbose_name_plural': '(Anamnese) Grupos Sociais que o trabalhador educando participa'},
        ),
        migrations.AlterModelOptions(
            name='residecom',
            options={'verbose_name': 'Pessoa com a qual o Trabalhador Educando reside', 'verbose_name_plural': '(Anamnese) Pessoas com as quais o Trabalhador Educando reside'},
        ),
        migrations.AlterModelOptions(
            name='residenciasaneamentobasico',
            options={'verbose_name': 'Saneamento básico', 'verbose_name_plural': '(Anamnese) Saneamentos básicos'},
        ),
        migrations.AlterModelOptions(
            name='trabalhoanterioraoppe',
            options={'verbose_name': 'Trabalho Antes de Ingressar ao ppe', 'verbose_name_plural': '(Anamnese) Trabalhos Antes de Ingressar ao ppe'},
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='identidade_genero',
            field=djtools.db.models.CharFieldPlus(choices=[['Masculino', 'Masculino'], ['Feminino', 'Feminino'], ['Pessoa transsexual', 'Pessoa transsexual'], ['Outro', 'Outro']], max_length=255, verbose_name='Sexo / identidade de gênero'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='participa_rede_social',
            field=djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Participa de alguma rede social?'),
        ),
        migrations.AlterField(
            model_name='cursostrabalhadoreducando',
            name='descricao',
            field=djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Curso que o trabalhador educando realiza/realizou'),
        ),
    ]
