# Generated by Django 3.2.5 on 2022-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0024_auto_20221209_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='onde_trabalhou_anteriormente',
            field=models.ManyToManyField(blank=True, to='ppe.TrabalhoAnteriorAoPPE', verbose_name='Caso você tenha trabalhado antes de ingressar no PPE, onde foi?'),
        ),
    ]
