# Generated by Django 3.2.5 on 2022-12-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0025_alter_anamnese_onde_trabalhou_anteriormente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='dominacao_evangelica',
            new_name='denominacao_evangelica',
        ),
    ]
