# Generated by Django 3.2.5 on 2022-12-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0026_rename_dominacao_evangelica_anamnese_denominacao_evangelica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='estado',
        ),
    ]
