# Generated by Django 3.2.5 on 2022-12-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0030_auto_20221219_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatriculaCursoTruma',
            new_name='MatriculaCursoTurma',
        ),
    ]
