# Generated by Django 3.2.5 on 2022-12-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0031_rename_matriculacursotruma_matriculacursoturma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoturma',
            old_name='posse_fim_prova_final',
            new_name='posse_etapa_5',
        ),
    ]
