# Generated by Django 3.2.5 on 2022-12-27 10:48

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0033_auto_20221227_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.PositiveIntegerField(choices=[[1, 'Primeira'], [5, 'Final']], default=1, verbose_name='Etapa')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade de aulas ministradas')),
                ('url', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='URL da Aula')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tipo', djtools.db.models.PositiveIntegerFieldPlus(choices=[[1, 'Teórica'], [2, 'Prática']], default=1, null=True, verbose_name='Tipo')),
                ('curso_turma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.cursoturma', verbose_name='Curso Turma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ('etapa', 'data'),
            },
        ),
    ]
