# Generated by Django 3.2.5 on 2022-12-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0034_aula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoturma',
            options={'permissions': (('lancar_nota_curso_turma', 'Pode lançar nota em Cursos'), ('reabrir_cursoturma', 'Pode reabri Cursos'), ('emitir_boletins', 'Pode emitir boletins dos Cursos')), 'verbose_name': 'Diário de Curso', 'verbose_name_plural': 'Diários de Cursos'},
        ),
    ]
