# Generated by Django 3.2.5 on 2022-12-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0037_configuracaoavaliacao_itemconfiguracaoavaliacao_notaavaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaoavaliacao',
            old_name='diario',
            new_name='curso_turma',
        ),
    ]
