# Generated by Django 3.2.5 on 2023-02-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppe', '0038_rename_diario_configuracaoavaliacao_curso_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, null=True, verbose_name='Data da Solicitação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_avaliacao', djtools.db.models.DateTimeFieldPlus(null=True)),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('razao_indeferimento', models.TextField(null=True, verbose_name='Razão do Indeferimento')),
                ('avaliador', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_avaliador_ppe_set', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('solicitante', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_solicitante_ppe_set', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Usuário',
                'verbose_name_plural': 'Solicitações de Usuários',
                'ordering': ('data_solicitacao',),
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAmpliacaoPrazoCurso',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='E-mail para contato')),
            ],
            options={
                'verbose_name': 'Solicitação de ampliação de prazo para execução de curso',
                'verbose_name_plural': 'Solicitações de ampliação de prazo para execução de curso',
            },
            bases=('ppe.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoAtendimentoPsicossocial',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('motivo', models.TextField(null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Solicitação de Atendimento pelo Núcleo de Atenção Psicossocial',
                'verbose_name_plural': 'Solicitações de Atendimento pelo Núcleo de Atenção Psicossocial',
            },
            bases=('ppe.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoContinuidadeAperfeicoamentoProfissional',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('observacao', models.TextField(null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Solicitação de continuidade no Aperfeiçoamento Profissional',
                'verbose_name_plural': 'Solicitações de continuidade no Aperfeiçoamento Profissional',
            },
            bases=('ppe.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoRealocacao',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('unidade_lotacao', models.CharField(max_length=80, verbose_name='Unidade de lotação')),
                ('novo_setor_trabalho', models.CharField(max_length=80, verbose_name='Novo setor de trabalho')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('nome_nova_chefia', models.CharField(max_length=100, verbose_name='Nome da nova chefia')),
                ('cargo_nova_chefia', models.CharField(max_length=100, verbose_name='Cargo da nova chefia')),
            ],
            options={
                'verbose_name': 'Solicitação de realocação',
                'verbose_name_plural': 'Solicitações de realocação',
            },
            bases=('ppe.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoVisitaTecnicaUnidade',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('hora_inicio', djtools.db.models.TimeFieldPlus(blank=True, help_text='Utilize o formato hh:mm:ss', null=True, verbose_name='Horário Início')),
                ('hora_fim', djtools.db.models.TimeFieldPlus(blank=True, help_text='Utilize o formato hh:mm:ss', null=True, verbose_name='Horário Fim')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Solicitação de visita técnica na unidade',
                'verbose_name_plural': 'Solicitações de visita técnica na unidade',
            },
            bases=('ppe.solicitacaousuario',),
        ),
    ]
