# Generated by Django 3.2.5 on 2023-03-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0039_solicitacaoampliacaoprazocurso_solicitacaoatendimentopsicossocial_solicitacaocontinuidadeaperfeicoam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDesligamentos',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppe.solicitacaousuario')),
                ('motivo', models.TextField(null=True, verbose_name='Motivo')),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Desligamentos',
                'verbose_name_plural': 'Solicitações de Desligamentos',
            },
            bases=('ppe.solicitacaousuario',),
        ),
    ]
