# Generated by Django 3.2.5 on 2023-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0040_auto_20230302_1421'),
        ('ppe', '0040_falta'),
    ]

    operations = [
    ]
