# Generated by Django 3.2.5 on 2023-03-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppe', '0042_merge_20230303_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaovisitatecnicaunidade',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacaovisitatecnicaunidade',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='solicitacaorealocacao',
            name='a_partir_quando',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='A partir de quando?'),
        ),
        migrations.AddField(
            model_name='solicitacaorealocacao',
            name='indicacao_nova_unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Indicação Nova Unidade'),
        ),
        migrations.AddField(
            model_name='solicitacaovisitatecnicaunidade',
            name='opcoes',
            field=djtools.db.models.CharFieldPlus(choices=[['Tipo1', 'Tipo1'], ['Tipo2', 'Tipo2'], ['Tipo3', 'Tipo3']], max_length=255, null=True, verbose_name='Tipo de Opções'),
        ),
        migrations.AddField(
            model_name='solicitacaovisitatecnicaunidade',
            name='visitante',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='solicitacaocontinuidadeaperfeicoamentoprofissional',
            name='anexo_termo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=250, null=True, upload_to='ppe/anexo_termo/'),
        ),
        migrations.AlterField(
            model_name='solicitacaorealocacao',
            name='cargo_nova_chefia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo da nova chefia'),
        ),
        migrations.AlterField(
            model_name='solicitacaovisitatecnicaunidade',
            name='data',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='HistoricoRelatorioPpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255)),
                ('query_string', models.TextField()),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'Trabalhador Educando']])),
                ('user', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Relatório',
                'verbose_name_plural': 'Histórico de Relatórios',
            },
        ),
    ]
