# Generated by Django 3.2.5 on 2023-03-23 15:50

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0043_auto_20230309_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='OpcaoRespostaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.CharFieldPlus(max_length=200, verbose_name='Opção de Resposta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Opção de Resposta da Avaliação',
                'verbose_name_plural': 'Opções de Respostas das Avaliações',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', djtools.db.models.CharFieldPlus(max_length=2000, verbose_name='Pergunta')),
                ('tipo_resposta', djtools.db.models.CharFieldPlus(choices=[('Texto', 'Texto'), ('Parágrafo', 'Parágrafo'), ('Número', 'Número'), ('Sim/Não', 'Sim/Não'), ('Única Escolha', 'Única Escolha'), ('Múltipla Escolha', 'Múltipla Escolha')], max_length=100, verbose_name='Tipo de Resposta')),
                ('obrigatoria', models.BooleanField(default=True, verbose_name='Resposta Obrigatória')),
                ('ordem', models.IntegerField(null=True, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pergunta da Avaliação',
                'verbose_name_plural': 'Perguntas da Avaliação',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=2000, verbose_name='Descrição')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=10, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_informado', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_avaliacao', to='ppe.avaliacao', verbose_name='Avaliação')),
                ('pergunta', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_pergunta_inscricao', to='ppe.perguntaavaliacao', verbose_name='Pergunta')),
                ('resposta', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_escolhida', to='ppe.opcaorespostaavaliacao', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta da Avaliacão',
                'verbose_name_plural': 'Respostas da Avaliacão',
            },
        ),
        migrations.AddField(
            model_name='perguntaavaliacao',
            name='tipo_avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_tipoavaliacao', to='ppe.tipoavaliacao', verbose_name='Tipo de avaliação'),
        ),
        migrations.AddField(
            model_name='opcaorespostaavaliacao',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_avaliacao', to='ppe.perguntaavaliacao', verbose_name='Pergunta'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.tipoavaliacao', verbose_name='avaliacao_tipoavalaicao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='trabalhador_educando',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.trabalhadoreducando', verbose_name='Trabalhador Educando'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('tipo_avaliacao', 'trabalhador_educando')},
        ),
    ]
