# Generated by Django 3.2.5 on 2023-03-23 16:11

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0044_auto_20230323_1550'),
    ]

    operations = [
    ]
