# Generated by Django 3.2.5 on 2023-03-24 09:22

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0045_auto_20230323_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='papel_avalidor',
            field=djtools.db.models.IntegerFieldPlus(blank=True, choices=[(1, 'AUTOAVALIAÇÃO'), (2, 'AVALIAÇÃO DA CHEFIA')], default=0, null=True, verbose_name='Tipo de Avaliação'),
        ),
        migrations.AlterField(
            model_name='perguntaavaliacao',
            name='tipo_resposta',
            field=djtools.db.models.CharFieldPlus(choices=[('Texto', 'Texto'), ('Parágrafo', 'Parágrafo'), ('Número', 'Número'), ('Sim/Não', 'Sim/Não'), ('Sim/Não/NA', 'Sim/Não/NA'), ('Escala 0 a 5', 'Escala 0 a 5'), ('Única Escolha', 'Única Escolha'), ('Múltipla Escolha', 'Múltipla Escolha')], max_length=100, verbose_name='Tipo de Resposta'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('tipo_avaliacao', 'trabalhador_educando', 'papel_avalidor')},
        ),
    ]
