# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('ppe', '0048_auto_20230324_1220'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ChefiaImediata',
        # ),
        # migrations.CreateModel(
        #     name='ChefiaImediata',
        #     fields=[
        #         ('prestadorservico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.prestadorservico')),
        #         ('funcao', models.CharField(max_length=60, verbose_name='Função')),
        #         ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
        #     ],
        #     options={
        #         'verbose_name': 'Chefia imediata',
        #         'verbose_name_plural': 'Chefias imediatas',
        #     },
        #     bases=('comum.prestadorservico',),
        # ),
        migrations.AlterField(
            model_name='TrabalhadorEducando',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhadoreducando_set', to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='TutorTurma',
            name='tutor',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.bolsista', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='ApoiadorTurma',
            name='apoiador',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.bolsista', verbose_name='Apoiador(a) Pedagógico'),
        ),
        # migrations.AlterField(
        #     model_name='SolicitacaoRealocacao',
        #     name='nome_nova_chefia',
        #     field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.ChefiaImediata', verbose_name='Nome da Nova Chefia'),
        # ),
    ]
