# Generated by Django 3.2.5 on 2023-03-24 13:21

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_atualizacao',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Atualziação'),
        ),
    ]
