# Generated by Django 3.2.5 on 2023-03-25 09:15

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0054_auto_20230324_1239'),
        ('ppe', '0051_alter_avaliacao_data_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMonitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.ano', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Configuração Monitoramento',
                'verbose_name_plural': 'Configurações Monitoramento',
            },
        ),
        migrations.AlterField(
            model_name='respostaavaliacao',
            name='pergunta',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_pergunta_avaliacao', to='ppe.perguntaavaliacao', verbose_name='Pergunta'),
        ),
        migrations.CreateModel(
            name='EtapaMonitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidade', djtools.db.models.CharFieldPlus(choices=[('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL')], default='TRIMESTRAL', max_length=255, verbose_name='Periodicidade')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('configuracao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.configuracaomonitoramento', verbose_name='etata_configuracao')),
                ('tipo_avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.tipoavaliacao', verbose_name='Instrumento  de monitoramento')),
            ],
            options={
                'verbose_name': 'Etapa Monitoramento',
                'verbose_name_plural': 'Etapas Monitoramento',
            },
        ),
    ]
