# Generated by Django 3.2.5 on 2023-03-25 09:36

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0053_tipoavaliacao_pre_requsito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='pre_requsito',
        ),
        migrations.AddField(
            model_name='tipoavaliacao',
            name='pre_requisito',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.tipoavaliacao', verbose_name='Pré-requisito'),
        ),
    ]
