# Generated by Django 3.2.5 on 2023-03-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0054_auto_20230325_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapamonitoramento',
            name='periodicidade',
        ),
    ]
