# Generated by Django 3.2.5 on 2023-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0055_remove_etapamonitoramento_periodicidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Formação técnica',
                'verbose_name_plural': 'Formações técnicas',
            },
        ),
        migrations.AddField(
            model_name='trabalhadoreducando',
            name='formacao_tecnica',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.formacaotecnica', verbose_name='Formação técnica '),
        ),
    ]
