# Generated by Django 3.2.5 on 2023-03-25 10:29

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0056_auto_20230325_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaavaliacao',
            name='formacao_tecnica',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_formacaotecnica', to='ppe.formacaotecnica', verbose_name='Formação técnica'),
        ),
    ]
