# Generated by Django 3.2.5 on 2023-03-25 13:28

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0054_auto_20230324_1239'),
        ('ppe', '0057_auto_20230325_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('excluido', models.BooleanField(default=False, help_text='Setores excluídos não farão parte das buscas e não devem possuir servidores', verbose_name='Excluído')),
                ('superior', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.setor', verbose_name='Setor Superior')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=25, verbose_name='Sigla')),
                ('cnpj', djtools.db.models.BrCnpjField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('zona_rual', models.BooleanField(default=False, verbose_name='Zona Rural?')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax')),
                ('municipio', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.municipio', verbose_name='Município')),
                ('setor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_setor', to='ppe.setor')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'ordering': ['setor__sigla'],
            },
        ),
        migrations.AddField(
            model_name='setor',
            name='unidade',
            field=djtools.db.models.ForeignKeyPlus(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_unidade_set', to='ppe.unidade', verbose_name='Unidade'),
        ),
    ]
