# Generated by Django 3.2.5 on 2023-03-25 15:29

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0058_auto_20230325_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['setor__sigla'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
