# Generated by Django 3.2.5 on 2023-03-25 15:47

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0059_auto_20230325_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhadorSetorHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', djtools.db.models.DateFieldPlus(db_index=True, verbose_name='Data de Início')),
                ('data_fim_chefia', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Fim')),
                ('setor', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_trabalhador', to='ppe.setor', verbose_name='Setor Lotação Trabalhador')),
                ('trabalhador_educando', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.trabalhadoreducando')),
            ],
            options={
                'verbose_name': 'Histórico de Setor do Trabalhador Educando',
                'verbose_name_plural': 'Históricos de Setores do Trabalhador Educando',
            },
        ),
    ]
