# Generated by Django 3.2.5 on 2023-03-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0060_auto_20230325_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalhadorsetorhistorico',
            old_name='data_fim_chefia',
            new_name='data_fim',
        ),
    ]
