# Generated by Django 3.2.5 on 2023-03-25 15:57

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0061_auto_20230325_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhadorsetorhistorico',
            name='data_fim',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Fim'),
        ),
    ]
