# Generated by Django 3.2.5 on 2023-03-30 15:12

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0064_auto_20230325_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhadoreducando',
            name='data_admissao',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
    ]
