# Generated by Django 3.2.5 on 2023-03-30 16:24

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.unaccent_field


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0002_alter_inscricaofiscal_pessoa_fisica'),
        ('comum', '0056_alter_vinculo_tipo_relacionamento'),
        ('processo_eletronico', '0002_auto_20230324_1239'),
        ('rh', '0047_auto_20230324_1239'),
        ('edu', '0004_auto_20230324_1239'),
        ('residencia', '0046_auto_20230324_1239'),
        ('documento_eletronico', '0002_auto_20230324_1239'),
        ('estagios', '0002_auto_20230324_1239'),
        ('ppe', '0065_trabalhadoreducando_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefiaPPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.unaccent_field.UnaccentField(max_length=200)),
                ('cpf', models.CharField(db_index=True, max_length=20, null=True, verbose_name='CPF')),
                ('funcao', models.CharField(max_length=60, verbose_name='Função')),
                ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Principal')),
                ('excluido', models.BooleanField(default=False, help_text='Indica se a última ocorrência é de exclusão', verbose_name='Excluído')),
                ('pessoa_fisica', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica')),
            ],
            options={
                'verbose_name': 'Chefia imediata',
                'verbose_name_plural': 'Chefias imediatas',
            },
        ),
        migrations.AddField(
            model_name='chefiasetorhistorico',
            name='chefe_imediato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.chefiappe'),
        ),
        migrations.AlterField(
            model_name='solicitacaorealocacao',
            name='nome_nova_chefia',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='ppe.chefiappe', verbose_name='Nome da Nova Chefia'),
        ),

    ]
