# Generated by Django 3.2.5 on 2023-03-31 11:04

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0066_auto_20230330_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaorespostaavaliacao',
            name='valor',
            field=djtools.db.models.CharFieldPlus(max_length=400, verbose_name='Opção de Resposta'),
        ),
    ]
