# Generated by Django 3.2.5 on 2023-03-31 11:46

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0067_alter_opcaorespostaavaliacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaorespostaavaliacao',
            name='pontuacao',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=200, null=True, verbose_name='Pontuação'),
        ),
    ]
