# Generated by Django 3.2.5 on 2023-04-02 09:05

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0058_municipio_territorio_identidade'),
        ('ppe', '0068_opcaorespostaavaliacao_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atualizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_atualizado_por', to='comum.vinculo', verbose_name='Atualizado Por'),
        ),
    ]
