# Generated by Django 3.2.5 on 2023-04-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0069_avaliacao_atualizado_por'),
    ]


    operations = [
        migrations.AlterUniqueTogether(
            name='chefiasetorhistorico',
            unique_together=set(),
        ),


    ]
