# Generated by Django 3.2.5 on 2023-04-26 12:23

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0070_alter_chefiasetorhistorico_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhadoreducando',
            name='estado_civil_mae',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Solteiro', 'Solteiro'], ['Casado', 'Casado'], ['União Estável', 'União Estável'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo']], max_length=255, null=True, verbose_name='Estado Civil da Mãe'),
        ),
        migrations.AlterField(
            model_name='trabalhadoreducando',
            name='estado_civil_pai',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Solteiro', 'Solteiro'], ['Casado', 'Casado'], ['União Estável', 'União Estável'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo']], max_length=255, null=True, verbose_name='Estado Civil do Pai'),
        ),
        migrations.AlterField(
            model_name='trabalhadoreducando',
            name='logradouro',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Logradouro (Avenida, Rua, etc)'),
        ),
        migrations.AlterField(
            model_name='trabalhadoreducando',
            name='telefone_principal',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='trabalhadoreducando',
            name='tipo_zona_residencial',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['1', 'Urbana'], ['2', 'Rural']], max_length=255, null=True, verbose_name='Zona Residencial'),
        ),
    ]
