# Generated by Django 3.2.5 on 2023-04-27 16:02

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0071_auto_20230426_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhadoreducando',
            name='data_demissao',
            field=djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
    ]
