# Generated by Django 3.2.5 on 2023-05-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0071_auto_20230422_1016'),
        ('ppe', '0072_trabalhadoreducando_data_demissao'),
    ]

    operations = [
    ]
