# Generated by Django 3.2.5 on 2023-07-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0073_merge_20230503_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabalhadoreducando',
            options={'ordering': ('pessoa_fisica__nome',), 'permissions': (('efetuarmatriculatrabalhadoreducando', 'Pode efetuar o cadastro de Trabalhador Educando'), ('emitir_diploma', 'Pode emitir diploma de Trabalhador Educando'), ('emitir_boletim', 'Pode emitir boletim de Trabalhador Educando'), ('emitir_historico', 'Pode emitir histórico de Trabalhador Educando'), ('efetuar_matricula', 'Pode efetuar matricula de Trabalhador Educando'), ('pode_sincronizar_dados', 'Pode sincronizar dados de Trabalhador Educando'), ('gerar_relatorio', 'Pode gerar relatórios de Trabalhador Educando'), ('pode_ver_chave_acesso_pais', 'Pode ver chave de acesso dos pais'), ('change_foto', 'Pode editar foto de Trabalhador Educando'), ('view_dados_academicos', 'Pode visualizar dados acadêmicos de Trabalhador Educando'), ('view_dados_pessoais', 'Pode visualizar dados pessoais de Trabalhador Educando')), 'verbose_name': 'Trabalhador Educando', 'verbose_name_plural': 'Trabalhadores Educandos'},
        ),
    ]
