# Generated by Django 3.2.5 on 2023-07-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0074_alter_trabalhadoreducando_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhadoreducando',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='trabalhadoreducando',
            name='email_responsavel',
        ),
        migrations.RemoveField(
            model_name='trabalhadoreducando',
            name='mae_falecida',
        ),
        migrations.RemoveField(
            model_name='trabalhadoreducando',
            name='pai_falecido',
        ),
    ]
