# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0002_auto_20190902_1545'), ('plan_estrategico', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='TotalizadorIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('total_indicadores', models.PositiveIntegerField(null=True, verbose_name='Total Campus')),
                (
                    'status',
                    djtools.db.models.CharFieldPlus(
                        choices=[
                            ('Indicador Alcançado', 'Indicador Alcançado'),
                            ('Indicador Parcialmente Alcançado', 'Indicador Parcialmente Alcançado'),
                            ('Indicador Não Alcançado', 'Indicador Não Alcançado'),
                        ],
                        max_length=255,
                        verbose_name='Status',
                    ),
                ),
                (
                    'uo',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Unidade Administrativa'),
                ),
            ],
            options={'abstract': False},
        )
    ]
