# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0002_totalizadorindicador')]

    operations = [
        migrations.AddField(
            model_name='pdi',
            name='mapa_estrategico',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='plan_estrategico/anexos/', verbose_name='Mapa Estratégico'),
        ),
        migrations.AddField(model_name='perspectiva', name='descricao', field=models.TextField(blank=True, verbose_name='Descrição')),
        migrations.AlterField(model_name='perspectiva', name='nome', field=djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
    ]
