# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0004_auto_20191105_0814')]

    operations = [
        migrations.AddField(
            model_name='pdi', name='manual', field=models.FileField(blank=True, max_length=255, null=True, upload_to='plan_estrategico/anexos/', verbose_name='Manual do PDI')
        )
    ]
