# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0005_pdi_manual')]

    operations = [
        migrations.AddField(model_name='projetoestrategico', name='codigo', field=models.CharField(max_length=2, null=True, verbose_name='Código')),
        migrations.AddField(
            model_name='projetoestrategico',
            name='tipo',
            field=djtools.db.models.CharFieldPlus(choices=[('Rotineiro', 'Rotineiro'), ('Estratégico', 'Estratégico')], default='Estratégico', max_length=255, verbose_name='Tipo'),
        ),
    ]
