# Generated by Django 2.2.7 on 2019-12-03 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0004_auto_20191127_1640'),
        ('financeiro', '0001_initial'),
        ('plan_estrategico', '0006_auto_20191008_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProjetoPlanoAtividade',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'))],
            options={'verbose_name': 'Etapa do projeto', 'verbose_name_plural': 'Etapas do projeto'},
        ),
        migrations.CreateModel(
            name='OrigemRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinacao', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Destinação')),
                (
                    'acao_financeira',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='origemrecurso_acaofinanceira', to='financeiro.AcaoAno', verbose_name='Ação Orçamentária'
                    ),
                ),
                (
                    'gnd',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.GrupoNaturezaDespesa', verbose_name='Grupo Elemento de Despesa'),
                ),
                ('plano_atividade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.PlanoAtividade')),
            ],
            options={'verbose_name': 'Origem do Recurso', 'verbose_name_plural': 'Origens dos Recursos'},
        ),
        migrations.CreateModel(
            name='OrigemRecursoProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Projeto')),
                (
                    'origem_recurso',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.OrigemRecurso', verbose_name='Origem de recurso do projeto do plano de atividade'
                    ),
                ),
            ],
            options={'verbose_name': 'Origem de recurso do projeto', 'verbose_name_plural': 'Origens de recursos do projeto'},
        ),
        migrations.AddField(model_name='etapaprojeto', name='codigo', field=models.IntegerField(null=True, verbose_name='Código da Etapa')),
        migrations.AddField(
            model_name='unidadegestora', name='codigo_projeto', field=djtools.db.models.CharFieldPlus(blank=True, max_length=1, null=True, verbose_name='Código para Projeto')
        ),
        migrations.AlterField(model_name='etapaprojeto', name='descricao', field=models.CharField(max_length=100, verbose_name='Descrição')),
        migrations.AlterField(model_name='etapaprojeto', name='responsaveis_etapa', field=models.CharField(max_length=100, null=True, verbose_name='Setores Responsáveis')),
        migrations.AlterField(
            model_name='etapaprojeto', name='valor_etapa', field=djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Etapa')
        ),
        migrations.AlterField(
            model_name='pdi',
            name='manual',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='plan_estrategico/anexos/', verbose_name='Manual de Indicadores'),
        ),
        migrations.AlterField(
            model_name='projetoestrategico',
            name='meta_projeto',
            field=djtools.db.models.DecimalFieldPlus(decimal_places=2, help_text='Resultado esperado do projeto', max_digits=12, verbose_name='Meta do Projeto'),
        ),
        migrations.AlterField(
            model_name='projetoestrategico', name='recurso_total', field=djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Recurso Total')
        ),
        migrations.AlterField(
            model_name='projetoestrategico', name='unidade_medida', field=models.CharField(help_text='Unidade de medida da meta', max_length=50, verbose_name='Unidade de Medida')
        ),
        migrations.AlterField(
            model_name='unidadegestora',
            name='tipo',
            field=models.CharField(
                choices=[('Diretoria Sistêmica', 'Diretoria Sistêmica'), ('Pró-Reitoria', 'Pró-Reitoria'), ('Campus', 'Campus')], max_length=20, verbose_name='Tipo'
            ),
        ),
        migrations.CreateModel(
            name='ProjetoPlanoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrigensRecurso', models.ManyToManyField(through='plan_estrategico.OrigemRecursoProjeto', to='plan_estrategico.OrigemRecurso')),
                ('etapas_projeto_plano_atividade', models.ManyToManyField(through='plan_estrategico.EtapaProjetoPlanoAtividade', to='plan_estrategico.EtapaProjeto')),
                ('plano_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.PlanoAtividade', verbose_name='Plano de Atividade')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.ProjetoEstrategico', verbose_name='Projeto Estratégico')),
            ],
            options={
                'verbose_name': 'Projetos do plano de Atividade',
                'verbose_name_plural': 'Projetos do Plano de Atividade',
                'unique_together': {('projeto', 'plano_atividade')},
            },
        ),
        migrations.CreateModel(
            name='OrigemRecursoProjetoEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'etapa_projeto_plano_atividade',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.EtapaProjetoPlanoAtividade', verbose_name='Etapa do projeto do plano de atividade'
                    ),
                ),
                (
                    'origem_recurso_projeto',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.OrigemRecursoProjeto', verbose_name='Origem de recurso do projeto do plano de atividade'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Origem de recurso da etapa do projeto',
                'verbose_name_plural': 'Origens de recurso da etapa do projeto',
                'unique_together': {('etapa_projeto_plano_atividade', 'origem_recurso_projeto')},
            },
        ),
        migrations.AddField(
            model_name='origemrecursoprojeto',
            name='projeto_plano_atividade',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.ProjetoPlanoAtividade', verbose_name='Projeto do plano de atividade'
            ),
        ),
        migrations.CreateModel(
            name='NaturezaDespesaPlanoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'natureza_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa', verbose_name='Natureza de Despesa'),
                ),
                (
                    'plano_atividade',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.PlanoAtividade', verbose_name='Plano de Atividade'),
                ),
            ],
            options={'verbose_name': 'Natureza de Despesa do Plano de Atividade', 'verbose_name_plural': 'Naturezas de Despesa do Plano de Atividade'},
        ),
        migrations.AddField(
            model_name='etapaprojetoplanoatividade',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.EtapaProjeto', verbose_name='Etapa do projeto do plano de atividade'),
        ),
        migrations.AddField(
            model_name='etapaprojetoplanoatividade',
            name='origens_recurso_projeto_etapa',
            field=models.ManyToManyField(through='plan_estrategico.OrigemRecursoProjetoEtapa', to='plan_estrategico.OrigemRecursoProjeto'),
        ),
        migrations.AddField(
            model_name='etapaprojetoplanoatividade',
            name='projeto_plano_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.ProjetoPlanoAtividade', verbose_name='Projeto Estratégico'),
        ),
        migrations.CreateModel(
            name='CompartilhamentoPoderdeGestorUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(blank=True, editable=False, null=True, verbose_name='Data de Criação')),
                (
                    'pessoa_permitida',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Pessoa', verbose_name='Pessoa com Poder de Gestor de UA'),
                ),
                ('setor_dono', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor')),
                (
                    'usuario_criacao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Configuração de Compartilhamento de Poder de Gestor de Unid. Administrativa',
                'verbose_name_plural': 'Configurações de Compartilhamento Poder de Gestor de Unid. Administrativa',
                'permissions': (('pode_gerenciar_permissoes_da_ua', 'Pode gerenciar permissoes da Unidade'),),
            },
        ),
        migrations.CreateModel(
            name='AtividadeEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Solicitado')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Atividade')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                (
                    'etapa_projeto_plano_atividade',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.EtapaProjetoPlanoAtividade', verbose_name='Etapa do projeto do plano de atividade'
                    ),
                ),
                (
                    'naturezadespesa',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.NaturezaDespesaPlanoAtividade', verbose_name='Natureza de Despesa'
                    ),
                ),
                (
                    'origem_recurso_etapa',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='plan_estrategico.OrigemRecursoProjetoEtapa',
                        verbose_name='Origem de Recurso da Etapa',
                    ),
                ),
                (
                    'unidade_gestora',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.UnidadeGestora', verbose_name='Unidade gestora da atividade'
                    ),
                ),
            ],
            options={'verbose_name': 'Atividade da Etapa', 'verbose_name_plural': 'Atividades da Etapa'},
        ),
        migrations.AddField(
            model_name='planoatividade', name='projetos', field=models.ManyToManyField(through='plan_estrategico.ProjetoPlanoAtividade', to='plan_estrategico.ProjetoEstrategico')
        ),
        migrations.CreateModel(
            name='UnidadeGestoraEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'etapa_projeto_plano_atividade',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unidades_gestoras',
                        to='plan_estrategico.EtapaProjetoPlanoAtividade',
                        verbose_name='Etapa do projeto do plano de atividade',
                    ),
                ),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.UnidadeGestora', verbose_name='Unidade gestora da etapa')),
            ],
            options={
                'verbose_name': 'Unidade gestora da etapa',
                'verbose_name_plural': 'Unidades gestoras da etapa',
                'unique_together': {('etapa_projeto_plano_atividade', 'unidade_gestora')},
            },
        ),
        migrations.AlterUniqueTogether(name='origemrecursoprojeto', unique_together={('projeto_plano_atividade', 'origem_recurso')}),
        migrations.AlterUniqueTogether(name='etapaprojetoplanoatividade', unique_together={('projeto_plano_atividade', 'etapa')}),
    ]
