# Generated by Django 2.2.7 on 2019-12-06 13:01

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0007_auto_20191203_1042')]

    operations = [
        migrations.AddField(
            model_name='origemrecursoprojetoetapa',
            name='valor',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Solicitado'),
        )
    ]
