# Generated by Django 2.2.7 on 2019-12-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0009_auto_20191209_1505')]

    operations = [
        migrations.RemoveField(model_name='unidadegestoraetapa', name='valor'),
        migrations.CreateModel(
            name='UnidadeOrigemEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                (
                    'origem_recurso_etapa',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.OrigemRecursoProjetoEtapa', verbose_name='Origem Recurso da Etapa'
                    ),
                ),
                (
                    'unidade_gestora',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.UnidadeGestoraEtapa', verbose_name='Unidade gestora da etapa'),
                ),
            ],
            options={
                'verbose_name': 'Unidade gestora da etapa',
                'verbose_name_plural': 'Unidades gestoras da etapa',
                'unique_together': {('origem_recurso_etapa', 'unidade_gestora')},
            },
        ),
    ]
