# Generated by Django 2.2.7 on 2020-01-09 14:35

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0006_auto_20191128_1142'), ('plan_estrategico', '0012_remove_origemrecurso_destinacao')]

    operations = [
        migrations.AddField(
            model_name='variavelcampus', name='valor_trimestral', field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Valor Trimestral')
        ),
        migrations.CreateModel(
            name='PeriodoPreenchimentoVariavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre'), (4, '4º Trimestre')], verbose_name='Trimestre')),
                ('data_inicio', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Início do Preenchimento')),
                ('data_termino', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Término do Preenchimento')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano do Período')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.PDI', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'Período de preenchimento da variável',
                'verbose_name_plural': 'Período de preenchimento das variáveis',
                'unique_together': {('pdi', 'ano', 'trimestre')},
            },
        ),
    ]
