# Generated by Django 2.2.7 on 2020-01-09 15:59

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0013_auto_20200109_1435')]

    operations = [
        migrations.AlterModelOptions(
            name='periodopreenchimentovariavel', options={'verbose_name': 'Período de preenchimento da variável', 'verbose_name_plural': 'Períodos de preenchimento das variáveis'}
        ),
        migrations.AlterField(model_name='periodopreenchimentovariavel', name='data_inicio', field=djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Início')),
        migrations.AlterField(model_name='periodopreenchimentovariavel', name='data_termino', field=djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Término')),
    ]
