# Generated by Django 2.2.7 on 2020-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0015_indicadortrimestralcampus')]

    operations = [migrations.AlterField(model_name='atividadeetapa', name='descricao', field=models.TextField(max_length=1500, verbose_name='Descrição'))]
