# Generated by Django 2.2.10 on 2020-03-05 09:16

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0017_atividadeetapa_valor_rateio')]

    operations = [
        migrations.AddField(model_name='indicador', name='calcular_media', field=models.BooleanField(default=False, verbose_name='Calcular Média')),
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=djtools.db.models.CharFieldPlus(
                choices=[('Percentual', 'Percentual'), ('Absoluto', 'Absoluto')], default='Absoluto', max_length=255, verbose_name='Tipo de Exibição'
            ),
        ),
    ]
