# Generated by Django 2.2.10 on 2020-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0018_etapaprojetoplanoatividade_tipo_especial')]

    operations = [migrations.AddField(model_name='origemrecursoprojetoetapa', name='tipo_especial', field=models.BooleanField(default=False))]
