# Generated by Django 2.2.10 on 2020-03-10 13:26

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0021_atividadeetapa_valor_reserva_tecnica')]

    operations = [
        migrations.AddField(
            model_name='atividadeetapa',
            name='origem_recurso_reserva_tecnica',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='origem_especial',
                to='plan_estrategico.OrigemRecursoProjetoEtapa',
                verbose_name='Origem Reserva Técnica',
            ),
        )
    ]
