# Generated by Django 2.2.10 on 2020-03-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('plan_estrategico', '0022_atividadeetapa_origem_recurso_reserva_tecnica'), ('plan_estrategico', '0018_auto_20200305_0916')]

    operations = []
