# Generated by Django 2.2.10 on 2020-07-06 14:33

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0024_unidadegestora_recurso_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeetapa',
            name='valor',
            field=djtools.db.models.DecimalFieldPlus(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Proposto'),
        ),
    ]
