# Generated by Django 2.2.10 on 2020-08-25 13:48

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0025_auto_20200706_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='TematicaVariavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Nome da Temática')),
            ],
            options={
                'verbose_name': 'Temática da variável',
                'verbose_name_plural': 'Temáticas das variáveis',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterField(
            model_name='variavelcampus',
            name='valor_trimestral',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Valor Acumulado'),
        ),
        migrations.AddField(
            model_name='variavel',
            name='tematica',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.TematicaVariavel', verbose_name='Temática'),
        ),
    ]
