# Generated by Django 2.2.16 on 2020-10-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20191130_1519'),
        ('plan_estrategico', '0027_pdi_qtd_anos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='origemrecurso',
            unique_together={('acao_financeira', 'gnd')},
        ),
    ]
