# Generated by Django 2.2.16 on 2020-11-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0028_auto_20201015_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadegestoraetapa',
            options={'ordering': ['unidade_gestora__setor_equivalente'], 'verbose_name': 'Unidade gestora da etapa', 'verbose_name_plural': 'Unidades gestoras da etapa'},
        ),
        migrations.AlterModelOptions(
            name='unidadeorigemetapa',
            options={'ordering': ['unidade_gestora__setor_equivalente'], 'verbose_name': 'Unidade gestora da etapa', 'verbose_name_plural': 'Unidades gestoras da etapa'},
        ),
    ]
