# Generated by Django 2.2.16 on 2021-01-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0029_auto_20201126_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelTrimestralCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Valor Real')),
                ('trimestre', models.PositiveIntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre'), (4, '4º Trimestre')], verbose_name='Trimestre')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_estrategico.VariavelCampus', verbose_name='Variavel Campus')),
            ],
            options={
                'verbose_name': 'Valor Trimestral da Variável Campus',
                'verbose_name_plural': 'Valores Trimestrais das Variáveis Campus',
            },
        ),
    ]
