# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0031_indicador_indicador_acompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='documento',
            field=djtools.db.models.FileFieldPlus(max_length=255, upload_to='plan_estrategico/anexos/', verbose_name='Documento PDI'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='manual',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='plan_estrategico/anexos/', verbose_name='Manual de Indicadores'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='mapa_estrategico',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='plan_estrategico/anexos/', verbose_name='Mapa Estratégico'),
        ),
        migrations.AlterField(
            model_name='projetoestrategico',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(max_length=255, upload_to='plan_estrategico/anexos/', verbose_name='Projeto Estratégico'),
        ),
    ]
