# Generated by Django 2.2.16 on 2021-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0032_auto_20210301_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='variavelcampus',
            name='situacao',
            field=models.PositiveIntegerField(choices=[(1, 'Ativa'), (2, 'Não se aplica')], default=1, verbose_name='Situação'),
        ),
    ]
