# Generated by Django 2.2.16 on 2021-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0033_variavelcampus_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='sem_escalonamento_trimestral',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, a meta trimestral fica igual à meta anual.', verbose_name='Sem Escalonamento Trimestral'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='calcular_media',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o valor Hoje exibido para o valor da instituição será consolidado pela média dos resultados das unidades, excluindo-se zeros.', verbose_name='Calcular Média'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='indicador_acompanhamento',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, não haverá comparação Hoje X Meta, nem cor no farol.', verbose_name='Indicador de acompanhamento'),
        ),
    ]
