# Generated by Django 2.2.24 on 2021-07-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0034_auto_20210622_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadeorigemetapa',
            options={'ordering': ['unidade_gestora__unidade_gestora__setor_equivalente'], 'verbose_name': 'Unidade gestora da etapa', 'verbose_name_plural': 'Unidades gestoras da etapa'},
        ),
    ]
