# Generated by Django 3.2.5 on 2021-08-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0035_auto_20210715_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodopreenchimentovariavel',
            options={'verbose_name': 'Período de preenchimento de variável', 'verbose_name_plural': 'Períodos de preenchimento de variáveis'},
        ),
    ]
