# Generated by Django 3.2.5 on 2021-12-23 15:17

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_estrategico', '0036_alter_periodopreenchimentovariavel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivometa',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(max_length=255, upload_to='plan_estrategico/arquivometa', verbose_name='Arquivo'),
        ),
    ]
