# Generated by Django 3.2.5 on 2022-09-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'ordering': ('pessoa_fisica__nome',), 'permissions': (('emitir_diploma', 'Pode emitir diploma de Residente'), ('emitir_boletim', 'Pode emitir boletim de Residente'), ('emitir_historico', 'Pode emitir histórico de Residente'), ('efetuar_matricula', 'Pode efetuar matricula de Residente'), ('pode_sincronizar_dados', 'Pode sincronizar dados de Residente'), ('gerar_relatorio', 'Pode gerar relatórios de Residente'), ('pode_ver_chave_acesso_pais', 'Pode ver chave de acesso dos pais'), ('change_foto', 'Pode editar foto de Residente'), ('view_dados_academicos', 'Pode visualizar dados acadêmicos de Residente'), ('view_dados_pessoais', 'Pode visualizar dados pessoais de Residente')), 'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
    ]
