# Generated by Django 3.2.5 on 2022-09-28 14:46

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0049_conselhoprofissional'),
        ('residencia', '0002_alter_residente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='conselho',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.conselhoprofissional', verbose_name='Conselho de Fiscalização Profissional'),
        ),
        migrations.AddField(
            model_name='residente',
            name='numero_registro',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Número de Registro no Conselho de Fiscalização Profissional'),
        ),
    ]
