# Generated by Django 3.2.5 on 2022-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0003_auto_20220928_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='email_academico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Acadêmico'),
        ),
        migrations.AddField(
            model_name='residente',
            name='email_google_classroom',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Google Classroom'),
        ),
        migrations.AddField(
            model_name='residente',
            name='email_qacademico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Q-Acadêmico'),
        ),
    ]
