# Generated by Django 3.2.5 on 2022-09-28 16:55

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0004_auto_20220928_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[('Biomedicina', 'Biomedicina'), ('Enfermagem', 'Enfermagem'), ('Farmácia', 'Farmácia'), ('Fisioterapia', 'Fisioterapia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Medicina', 'Medicina'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Nutrição', 'Nutrição'), ('Odontologia', 'Odontologia'), ('Psicologia', 'Psicologia'), ('Terapia Ocupacional', 'Terapia Ocupacional')], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
