# Generated by Django 3.2.5 on 2022-10-22 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0044_pessoafisica_eh_trabalhadoreducando'),
        ('residencia', '0006_alter_residente_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('descricao_historico', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição no Diploma e Histórico')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('ch_hora_relogio', models.PositiveIntegerField(verbose_name='Hora/relógio')),
                ('ch_hora_aula', models.PositiveIntegerField(verbose_name='Hora/aula')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('abreviatura', djtools.db.models.CharFieldPlus(max_length=10, null=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período')),
                ('ch_presencial', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Teórica')),
                ('ch_pratica', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Prática')),
                ('avaliacao_por_conceito', models.BooleanField(default=False, help_text='Marque essa opção caso a representação conceitual da nota deve ser apresentada ao invés do valor numérico.', verbose_name='Avaliação por Conceito')),
                ('ementa', models.TextField(blank=True, default='', null=True, verbose_name='Ementa')),
                ('co_requisitos', djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='corequisitosresidencia_set', to='residencia.ComponenteCurricular')),
                ('componente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.componente')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
                'ordering': ('matriz', 'periodo_letivo', 'componente__descricao'),
            },
        ),
        migrations.CreateModel(
            name='CursoResidencia',
            fields=[
                ('codigo_academico', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('descricao_historico', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição no Diploma e Histórico')),
                ('data_inicio', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', djtools.db.models.CharFieldPlus(help_text='Código para composição de turmas e matrículas', max_length=255, unique=True, verbose_name='Código')),
                ('periodicidade', models.PositiveIntegerField(choices=[[1, 'Anual']], null=True, verbose_name='Periodicidade')),
                ('ppc', djtools.db.models.FileFieldPlus(blank=True, default=None, null=True, upload_to='residencia/ppc/', verbose_name='PPC')),
                ('coordenador', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Residênca',
                'verbose_name_plural': 'Residêncas',
                'ordering': ('-ativo',),
            },
        ),
        migrations.CreateModel(
            name='EstruturaCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativa')),
                ('criterio_avaliacao', models.PositiveIntegerField(choices=[[1, 'Nota'], [2, 'Frequência']], verbose_name='Critério de Avaliação')),
                ('media_aprovacao_sem_prova_final', djtools.db.models.NotaField(blank=True, null=True, verbose_name='Média para passar sem prova final')),
            ],
            options={
                'verbose_name': 'Estrutura da Residência',
                'verbose_name_plural': 'Estruturas da Residência',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', djtools.db.models.DateTimeFieldPlus(auto_now=True)),
                ('tipo', models.IntegerField(choices=[[1, 'Cadastro'], [2, 'Edição'], [3, 'Exclusão'], [4, 'Visualização']])),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255)),
                ('app', djtools.db.models.CharFieldPlus(max_length=255)),
                ('modelo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('nome_modelo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('ref', models.IntegerField(db_index=True)),
                ('ref_residente', models.IntegerField(db_index=True, null=True)),
                ('residente', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residencia.residente')),
                ('user', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_user_residente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de fim')),
                ('ppp', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='residencia/ppp/', verbose_name='PPP')),
                ('qtd_periodos_letivos', models.PositiveIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10], [11, 11], [12, 12]], verbose_name='Quantidade de Períodos Letivos')),
                ('ch_pratica_teorico_pratica', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Carga Horária Prática e Teórico Prática')),
                ('ch_teorica', models.PositiveIntegerField(help_text='Hora-Relógio', verbose_name='Carga Horária Teórica')),
                ('inconsistente', models.BooleanField(default=False)),
                ('exige_tcr', models.BooleanField(default=False, help_text='Marque essa opção caso a apresentação de um Trabalho de Conclusão de Residência seja um pré-requisito para a finalização do curso', verbose_name='Exige TCR')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('componentes', models.ManyToManyField(through='residencia.ComponenteCurricular', to='residencia.Componente')),
                ('estrutura', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.estruturacurso')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='RepresentacaoConceitual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('valor_minimo', djtools.db.models.NotaField(verbose_name='Valor Mínimo')),
                ('valor_maximo', djtools.db.models.NotaField(verbose_name='Valor Máximo')),
                ('estrutura_curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.estruturacurso')),
            ],
            options={
                'verbose_name': 'Representação Conceitual',
                'verbose_name_plural': 'Representações Conceituais',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiferenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.TextField()),
                ('valor_atual', models.TextField()),
                ('campo', djtools.db.models.CharFieldPlus(max_length=255)),
                ('log', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.log')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrizCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', djtools.db.models.SearchField(blank=True, default='', editable=False)),
                ('curso_campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.cursoresidencia', verbose_name='Curso')),
                ('matriz', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.matriz', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Vínculo de Matriz em Curso',
                'verbose_name_plural': 'Vínculos de Matriz em Curso',
                'unique_together': {('matriz', 'curso_campus')},
            },
        ),
        migrations.AddField(
            model_name='cursoresidencia',
            name='matrizes',
            field=djtools.db.models.ManyToManyFieldPlus(through='residencia.MatrizCurso', to='residencia.Matriz'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='matriz',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.matriz'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='pre_requisitos',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='prerequisitosresidencia_set', to='residencia.ComponenteCurricular'),
        ),
        migrations.AlterUniqueTogether(
            name='componentecurricular',
            unique_together={('matriz', 'componente')},
        ),
    ]
