# Generated by Django 3.2.5 on 2022-10-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0007_auto_20221022_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='porcetagem_cumprimento_ch_teorica',
            field=models.PositiveIntegerField(default=100, help_text='0-100%', verbose_name='Porcetagem de cumprimento mínimo da carga horária teórica'),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='qtd_periodos_letivos',
            field=models.PositiveIntegerField(choices=[[1, 1], [2, 2]], verbose_name='Quantidade de Anos Letivos'),
        ),
    ]
