# Generated by Django 3.2.5 on 2022-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0008_auto_20221026_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[1, 'Prática e Teórico Prática'], [2, 'Teórica']], default=1),
        ),
    ]
