# Generated by Django 3.2.5 on 2022-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0009_componentecurricular_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='ch_hora_aula',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hora/aula'),
        ),
    ]
