# Generated by Django 3.2.5 on 2022-11-16 20:02

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0011_alter_cursoresidencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='contato_emergencia',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Em caso de emergência para quem ligar e em qual número?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='em_tratamento_medico',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Está em tratamento médico?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='em_tratamento_medico_qual',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Está em tratamento médico?', informe qual e para que doença:"),
        ),
        migrations.AddField(
            model_name='residente',
            name='outra_info_saude',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Existe alguma outra informação a respeito da sua saúde que queira fazer constar?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS / PASEP'),
        ),
        migrations.AddField(
            model_name='residente',
            name='possui_alergia',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Alguma alergia?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='possui_alergia_qual',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Alguma alergia?', informe qual(is):"),
        ),
        migrations.AddField(
            model_name='residente',
            name='possui_problema_saude',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Tem algum problema de Saúde?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='usa_medicacao',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Está em uso de alguma medicação?'),
        ),
        migrations.AddField(
            model_name='residente',
            name='usa_medicacao_qual',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Está em uso de alguma medicação?', informe qual e quando encerrará o uso:"),
        ),
        migrations.AlterField(
            model_name='residente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Biomedicina', 'Biomedicina'], ['Enfermagem', 'Enfermagem'], ['Farmácia', 'Farmácia'], ['Fisioterapia', 'Fisioterapia'], ['Fonoaudiologia', 'Fonoaudiologia'], ['Medicina', 'Medicina'], ['Medicina Veterinária', 'Medicina Veterinária'], ['Nutrição', 'Nutrição'], ['Odontologia', 'Odontologia'], ['Psicologia', 'Psicologia'], ['Terapia Ocupacional', 'Terapia Ocupacional'], ['Saúde Ocupacional', 'Saúde Ocupacional']], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
