# Generated by Django 3.2.5 on 2022-12-09 11:53

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0015_solicitacaoresidente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='naturalidade',
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='nomecidade',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='nomenaturalidade',
            field=djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Naturalidade'),
        ),
    ]
