# Generated by Django 3.2.5 on 2022-12-10 20:11

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('residencia', '0016_auto_20221209_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='autorizacao_carteira_estudantil',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='bairro_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='cartao_sus',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='cep_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='cidade_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='codigo_educacenso',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='complemento_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='contato_emergencia',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='csf',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='em_tratamento_medico',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='em_tratamento_medico_qual',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='email_academico',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='email_google_classroom',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='email_qacademico',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='habilitacao_pedagogica',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='logradouro_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='nis',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='numero_dependentes',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='numero_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='outra_info_saude',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='pis_pasep',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='possui_alergia',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='possui_alergia_qual',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='possui_problema_saude',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='renda_per_capita',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='telefone_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='tipo_zona_residencial_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='usa_medicacao',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='usa_medicacao_qual',
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='nascimento_data',
            field=djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='parecer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Parecer da Solicitação'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='parecer_autor_vinculo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_autor_parecer_vinculo', to='comum.vinculo', verbose_name='Autor do Parecer'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='parecer_data',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data do Parecer'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='sexo',
            field=models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1, null=True),
        ),
    ]
