# Generated by Django 3.2.5 on 2022-12-11 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residencia', '0017_auto_20221210_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'Anual'], [2, 'Semestral'], [3, 'Livre']], verbose_name='Tipo')),
                ('periodo_letivo', models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período letivo')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Início das Aulas')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Término das Aulas')),
                ('data_fechamento_periodo', djtools.db.models.DateFieldPlus(help_text='Data limite para lançamento de notas/faltas pelos professores', verbose_name='Data de Fechamento do Período')),
                ('eh_calendario_referencia', models.BooleanField(default=False, verbose_name='Calendário de Referência?')),
                ('qtd_etapas', models.PositiveIntegerField(choices=[[1, 'Etapa Única'], [2, 'Duas Etapas'], [4, 'Quatro Etapas']], verbose_name='Quantidade de Etapas')),
                ('data_inicio_etapa_1', djtools.db.models.DateFieldPlus(help_text='Data de início da primeira etapa', verbose_name='Início')),
                ('data_fim_etapa_1', djtools.db.models.DateFieldPlus(help_text='Data de encerramento da primeira etapa', verbose_name='Fim')),
                ('data_inicio_etapa_2', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da segunda etapa', null=True, verbose_name='Início')),
                ('data_fim_etapa_2', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da segunda etapa', null=True, verbose_name='Fim')),
                ('data_inicio_etapa_3', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da terceira etapa', null=True, verbose_name='Início')),
                ('data_fim_etapa_3', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da terceira etapa', null=True, verbose_name='Fim')),
                ('data_inicio_etapa_4', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da quarta etapa', null=True, verbose_name='Início')),
                ('data_fim_etapa_4', djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da quarta etapa', null=True, verbose_name='Fim')),
                ('data_inicio_trancamento', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do Trancamento')),
                ('data_fim_trancamento', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Encerramento do Trancamento')),
                ('data_inicio_certificacao', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início da Cert. e Aproveitamento')),
                ('data_fim_certificacao', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Encerramento da Cert. e Aproveitamento')),
                ('data_inicio_prova_final', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início da Prova Final')),
                ('data_fim_prova_final', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Encerramento da Prova Final')),
                ('data_inicio_espaco_pedagogico', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início')),
                ('data_fim_espaco_pedagogico', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Fim')),
                ('ano_letivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_residencia_por_ano_letivo_set', to='comum.ano', verbose_name='Ano letivo')),
            ],
            options={
                'verbose_name': 'Calendário Acadêmico',
                'verbose_name_plural': 'Calendários Acadêmicos',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('percentual_minimo_ch', models.PositiveIntegerField(verbose_name='Percentual Mínimo (Carga Horária)')),
                ('periodo_letivo', models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período Letivo')),
                ('quantidade_vagas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Vagas')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'Aberto'], [2, 'Fechado']], default=1, verbose_name='Situação')),
                ('descricao_dinamica', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Descrição Dinâmica')),
                ('segundo_ano', models.BooleanField(default=False, verbose_name='Segundo Semestre')),
                ('posse_etapa_1', models.PositiveIntegerField(choices=[[1, 'Professor'], [0, 'Registro Escolar']], default=1)),
                ('posse_etapa_2', models.PositiveIntegerField(choices=[[1, 'Professor'], [0, 'Registro Escolar']], default=1)),
                ('posse_etapa_3', models.PositiveIntegerField(choices=[[1, 'Professor'], [0, 'Registro Escolar']], default=1)),
                ('posse_etapa_4', models.PositiveIntegerField(choices=[[1, 'Professor'], [0, 'Registro Escolar']], default=1)),
                ('posse_etapa_5', models.PositiveIntegerField(choices=[[1, 'Professor'], [0, 'Registro Escolar']], default=1)),
                ('entregue_fisicamente', models.BooleanField(null=True, verbose_name='Entregue Fisicamente')),
                ('ano_letivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_residencia_por_ano_letivo_set', to='comum.ano', verbose_name='Ano Letivo')),
                ('calendario_academico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_residencia_calendario_academico_set', to='residencia.calendarioacademico', verbose_name='Calendário Acadêmico')),
                ('componente_curricular', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diarios_componente_curriculares_residencia_set', to='residencia.componentecurricular', verbose_name='Componente')),
                ('estrutura_curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_residencia_estrutura_curso_set', to='residencia.estruturacurso', verbose_name='Estrutura de Curso')),
                ('locais_aula_secundarios', djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='diarios_residencia_ocais_aula_secundarios_set', to='comum.Sala', verbose_name='Locais de Aula Secundários')),
                ('local_aula', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diarios_residencia_local_aula_set', to='comum.sala', verbose_name='Local de Aula')),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
                'permissions': (('reabrir_diario', 'Pode reabrir Diário'), ('lancar_nota_diario', 'Pode lançar nota em Diário'), ('mudar_posse_diario', 'Pode mudar posse de Diário'), ('emitir_boletins', 'Pode emitir boletins de Diário')),
            },
        ),
        migrations.CreateModel(
            name='SituacaoMatriculaPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_academico', models.IntegerField(null=True)),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação de Matrícula no Período',
                'verbose_name_plural': 'Situações de Matrículas no Período',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('periodo_letivo', models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período Letivo')),
                ('periodo_matriz', models.PositiveIntegerField(verbose_name='Período Turma')),
                ('sequencial', models.PositiveIntegerField(default=1)),
                ('quantidade_vagas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Vagas')),
                ('sigla', djtools.db.models.CharFieldPlus(blank=True, default='', max_length=255, null=True)),
                ('ano_letivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='turma_residencia_por_ano_letivo_set', to='comum.ano', verbose_name='Ano Letivo')),
                ('calendario_academico', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_residencia_calendario_academico_set', to='residencia.calendarioacademico')),
                ('curso_campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.cursoresidencia', verbose_name='Curso')),
                ('matriz', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_residencia_matriz_set', to='residencia.matriz')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('descricao',),
                'permissions': (('gerar_turmas', 'Gerar Turmas'),),
            },
        ),
        migrations.CreateModel(
            name='ObservacaoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observação do Diário')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('diario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='observacao_diarios_residencia_set', to='residencia.diario', verbose_name='Diário')),
                ('usuario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='observacao_diarios_usuario_residencia_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'permissions': (('adm_delete_observacaodiario', 'Pode deletar observações de outros usuários'),),
            },
        ),
        migrations.CreateModel(
            name='MatriculaPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.PositiveIntegerField(db_index=True, verbose_name='Período Letivo')),
                ('periodo_matriz', models.PositiveIntegerField(null=True, verbose_name='Período Matriz')),
                ('gerada_suap', models.BooleanField(default=False, verbose_name='Matrícula-Período Gerada pelo SUAP')),
                ('percentual_ch_cumprida', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='C.H. Cumprida (%)')),
                ('ano_letivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_periodos_ano_letivo_residencia_set', to='comum.ano', verbose_name='Ano Letivo')),
                ('residente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_periodos_residente_residencia_set', to='residencia.residente')),
                ('situacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_periodos_situacao_residencia_set', to='residencia.situacaomatriculaperiodo', verbose_name='Situação')),
                ('turma', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_periodos_turma_residencia_set', to='residencia.turma')),
            ],
            options={
                'verbose_name': 'Matrícula em Período',
                'verbose_name_plural': 'Matrículas em Período',
                'ordering': ('ano_letivo__ano', 'periodo_letivo'),
                'unique_together': {('ano_letivo', 'periodo_letivo', 'residente')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', djtools.db.models.NotaField(null=True, verbose_name='N1')),
                ('nota_2', djtools.db.models.NotaField(null=True, verbose_name='N2')),
                ('nota_3', djtools.db.models.NotaField(null=True, verbose_name='N3')),
                ('nota_4', djtools.db.models.NotaField(null=True, verbose_name='N4')),
                ('nota_final', djtools.db.models.NotaField(null=True, verbose_name='NAF')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'Cursando'], [2, 'Aprovado'], [3, 'Reprovado'], [4, 'Prova Final'], [5, 'Reprovado por falta'], [6, 'Trancado'], [7, 'Cancelado'], [8, 'Dispensado'], [9, 'Pendente'], [10, 'Aprovado/Reprovado no Módulo'], [13, 'Transferido']], default=1, verbose_name='Situação')),
                ('diario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_diarios_diario_residencia_set', to='residencia.diario')),
                ('matricula_periodo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_diarios_matricula_periodo_residencia_set', to='residencia.matriculaperiodo')),
            ],
            options={
                'verbose_name': 'Matrícula em Diário',
                'verbose_name_plural': 'Matrículas em Diário',
                'ordering': ('matricula_periodo__residente__pessoa_fisica__nome',),
                'permissions': (('delete_matriculadiario_cancelada_trancada', 'Pode excluir do diário residente com matrícula período cancelada ou trancada'),),
            },
        ),
        migrations.AddField(
            model_name='diario',
            name='turma',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_turma_residencia_set', to='residencia.turma', verbose_name='Turma'),
        ),
        migrations.AddIndex(
            model_name='matriculadiario',
            index=models.Index(fields=['matricula_periodo'], name='residencia__matricu_95bdea_idx'),
        ),
    ]
