# Generated by Django 3.2.5 on 2022-12-11 17:03

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0018_auto_20221211_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_academico', models.IntegerField(null=True)),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Situação de Matrícula',
                'verbose_name_plural': 'Situações de Matrículas',
                'ordering': ('descricao',),
            },
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_fim',
            field=djtools.db.models.DateFieldPlus(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_inicio',
            field=djtools.db.models.DateFieldPlus(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1']], verbose_name='Período letivo'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='qtd_etapas',
            field=models.PositiveIntegerField(choices=[[1, 'Etapa Única']], verbose_name='Quantidade de Etapas'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[1, 'Anual']], verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1']], verbose_name='Período Letivo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1']], verbose_name='Período Letivo'),
        ),
    ]
