# Generated by Django 3.2.5 on 2022-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0019_auto_20221211_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='periodo_atual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Período Atual'),
        ),
    ]
