# Generated by Django 3.2.5 on 2022-12-11 18:19

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('residencia', '0020_residente_periodo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='ano_letivo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.ano', verbose_name='Ano de Ingresso'),
        ),
        migrations.AddField(
            model_name='residente',
            name='periodo_letivo',
            field=models.PositiveIntegerField(blank=True, choices=[[1, '1']], null=True, verbose_name='Período de Ingresso'),
        ),
    ]
