# Generated by Django 3.2.5 on 2022-12-26 15:02

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0046_auto_20221120_1533'),
        ('residencia', '0023_residente_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPreceptorDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Preceptor em Diário',
                'verbose_name_plural': 'Tipos de Preceptor em Diário',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='PreceptorDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_etapa_1', djtools.db.models.DateFieldPlus(blank=True, help_text='Início da posse do diário para a 1ª etapa', null=True, verbose_name='Data de Início')),
                ('data_fim_etapa_1', djtools.db.models.DateFieldPlus(blank=True, help_text='Encerramento da posse incluindo 5 dias de tolerância', null=True, verbose_name='Data de Encerramento')),
                ('data_inicio_etapa_2', djtools.db.models.DateFieldPlus(blank=True, help_text='Início da posse do diário para a 2ª etapa', null=True, verbose_name='Data de Início')),
                ('data_fim_etapa_2', djtools.db.models.DateFieldPlus(blank=True, help_text='Encerramento da posse incluindo 5 dias de tolerância', null=True, verbose_name='Data de Encerramento')),
                ('data_inicio_etapa_3', djtools.db.models.DateFieldPlus(blank=True, help_text='Início da posse do diário para a 3ª etapa', null=True, verbose_name='Data de Início')),
                ('data_fim_etapa_3', djtools.db.models.DateFieldPlus(blank=True, help_text='Encerramento da posse incluindo 5 dias de tolerância', null=True, verbose_name='Data de Encerramento')),
                ('data_inicio_etapa_4', djtools.db.models.DateFieldPlus(blank=True, help_text='Início da posse do diário para a 4ª etapa', null=True, verbose_name='Data de Início')),
                ('data_fim_etapa_4', djtools.db.models.DateFieldPlus(blank=True, help_text='Encerramento da posse incluindo 5 dias de tolerância', null=True, verbose_name='Data de Encerramento')),
                ('data_inicio_etapa_final', djtools.db.models.DateFieldPlus(blank=True, help_text='Início da posse do diário para a etapa final', null=True, verbose_name='Data de Início')),
                ('data_fim_etapa_final', djtools.db.models.DateFieldPlus(blank=True, help_text='Encerramento da posse incluindo 5 dias de tolerância', null=True, verbose_name='Data de Encerramento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('financiamento_externo', models.BooleanField(default=False, help_text='Vínculo com financiamento extraorçamentário (Bolsa, PRONATEC, Mulheres Mil, ETEC, UAB, etc.)', verbose_name='Financiamento Externo')),
                ('percentual_ch', models.PositiveSmallIntegerField(help_text='Valor entre 0 e 100 correspondente ao percentual da carga horária ministrada pelo preceptor.', null=True, verbose_name='Percentual da Carga Horária')),
                ('periodo_letivo_ch', models.IntegerField(blank=True, choices=[[1, '1']], help_text='Informar caso o percentual da carga horária ministrada se refira a apenas um período letivo.', null=True, verbose_name='Período Letivo da Carga-Horária')),
                ('diario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.diario', verbose_name='Diário')),
                ('preceptor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.servidor', verbose_name='Preceptor')),
                ('tipo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.tipopreceptordiario', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Vínculo de Preceptor em Diário',
                'verbose_name_plural': 'Vínculos de Preceptor em Diário',
            },
        ),
    ]
