# Generated by Django 3.2.5 on 2023-01-02 12:55

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('edu', '0003_auto_20221211_1703'),
        ('rh', '0046_auto_20221120_1533'),
        ('residencia', '0023_residente_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoFinalResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título do Trabalho')),
                ('resumo', models.TextField(verbose_name='Resumo do Trabalho')),
                ('tipo', djtools.db.models.CharFieldPlus(choices=[['Monografia', 'Monografia'], ['Dissertação', 'Dissertação'], ['Tese', 'Tese'], ['Artigo Científico', 'Artigo Científico'], ['Capítulo de Livro', 'Capítulo de Livro'], ['Portfólio', 'Portfólio'], ['Trabalho de Conclusão de Curso', 'Trabalho de Conclusão de Curso'], ['Relatório de Projeto', 'Relatório de Projeto']], max_length=255, verbose_name='Tipo de Trabalho')),
                ('informacao_complementar', models.TextField(blank=True, null=True, verbose_name='Informações Complementares')),
                ('documento', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='residencia/projeto_final/', verbose_name='Arquivo Digitalizado do Projeto')),
                ('documento_final', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='residencia/projeto_final/', verbose_name='Arquivo Final Digitalizado do Projeto')),
                ('data_defesa', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Apresentação')),
                ('data_deposito', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Depósito ')),
                ('defesa_online', models.BooleanField(blank=True, default=False, help_text='Marque essa opção caso os membros da banca tenham acompanhado ou acompanharão a defesa virtualmente.', verbose_name='Defesa Online')),
                ('is_examinador_externo', models.BooleanField(default=True, help_text='Marque essa opção caso o segundo examinador seja externo.', verbose_name='Externo')),
                ('is_terceiro_examinador_externo', models.BooleanField(default=True, help_text='Marque essa opção caso o terceiro examinador seja externo.', verbose_name='Externo')),
                ('is_suplente_externo', models.BooleanField(default=True, help_text='Marque essa opção caso o segundo suplente seja externo.', verbose_name='Externo')),
                ('is_terceiro_suplente_externo', models.BooleanField(default=True, help_text='Marque essa opção caso o terceiro suplente seja externo.', verbose_name='Externo')),
                ('resultado_data', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Defesa')),
                ('nota', djtools.db.models.NotaField(blank=True, null=True)),
                ('situacao', models.PositiveIntegerField(blank=True, choices=[[1, 'Aprovado'], [2, 'Reprovado']], null=True, verbose_name='Situação')),
                ('ata', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='residencia/projeto_final_ata/', verbose_name='Ata da Defesa')),
                ('documento_url', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Link para Arquivo Digitalizado do Projeto')),
                ('documento_final_url', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Link Final para Arquivo Digitalizado do Projeto')),
                ('coorientadores', djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='coorientadores_residencia_set', to='rh.PessoaFisica', verbose_name='Coorientadores Residencia')),
                ('examinador_externo', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_externo_residencia_set', to='rh.pessoafisica', verbose_name='Segundo Examinador')),
                ('examinador_interno', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_interno_residencia_set', to='rh.pessoafisica', verbose_name='Examinador Interno')),
                ('local_defesa', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.sala', verbose_name='Local')),
                ('matricula_periodo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.matriculaperiodo')),
                ('orientador', djtools.db.models.ForeignKeyPlus(blank=True, limit_choices_to={'groups__name': 'Preceptor(a)'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_set', to='rh.servidor', verbose_name='Orientador')),
                ('presidente', djtools.db.models.ForeignKeyPlus(blank=True, limit_choices_to={'groups__name': 'Preceptor(a)'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente_set', to='rh.servidor', verbose_name='Presidente')),
                ('suplente_externo', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_externo_residencia_set', to='rh.pessoafisica', verbose_name='Segundo Suplente')),
                ('suplente_interno', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_interno_residencia_set', to='rh.pessoafisica', verbose_name='Suplente Interno')),
                ('terceiro_examinador', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_examinador_residencia_set', to='rh.pessoafisica', verbose_name='Terceiro Examinador')),
                ('terceiro_suplente', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_suplente_residencia_set', to='rh.pessoafisica', verbose_name='Terceiro Suplente')),
            ],
            options={
                'verbose_name': 'Trabalho de Conclusão de Curso',
                'verbose_name_plural': 'Trabalhos de Conclusão de Curso',
            },
        ),
        migrations.CreateModel(
            name='MembroBancaResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sexo', models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1, null=True)),
                ('instituicao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Instituição')),
                ('formacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.modalidade', verbose_name='Formação')),
            ],
            options={
                'verbose_name': 'Membro da Banca',
                'verbose_name_plural': 'Membros da Banca',
            },
        ),
        migrations.CreateModel(
            name='AtaEletronicaResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consideracoes', models.TextField(verbose_name='Considerações')),
                ('projeto_final', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.projetofinalresidencia', verbose_name='Projeto Final')),
            ],
            options={
                'verbose_name': 'Ata Eletrônica',
                'verbose_name_plural': 'Atas Eletrônicas',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaAtaEletronicaResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Assinatura')),
                ('chave', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Chave')),
                ('ata', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.ataeletronicaresidencia', verbose_name='Ata Eletrônica')),
                ('pessoa_fisica', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Assinatura de Ata Eletrônica',
                'verbose_name_plural': 'Assinaturas de Atas Eletrônicas',
            },
        ),
    ]
