# Generated by Django 3.2.5 on 2023-01-13 12:58

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0046_auto_20221120_1533'),
        ('residencia', '0024_preceptordiario_tipopreceptordiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Biomedicina', 'Biomedicina'], ['Enfermagem', 'Enfermagem'], ['Farmácia', 'Farmácia'], ['Fisioterapia', 'Fisioterapia'], ['Fonoaudiologia', 'Fonoaudiologia'], ['Medicina', 'Medicina'], ['Medicina Veterinária', 'Medicina Veterinária'], ['Nutrição', 'Nutrição'], ['Odontologia', 'Odontologia'], ['Psicologia', 'Psicologia'], ['Terapia Ocupacional', 'Terapia Ocupacional'], ['Saúde Ocupacional', 'Saúde Ocupacional'], ['Sanitarista / saúde coletiva', 'Sanitarista / saúde coletiva']], max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='solicitacaoresidente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Biomedicina', 'Biomedicina'], ['Enfermagem', 'Enfermagem'], ['Farmácia', 'Farmácia'], ['Fisioterapia', 'Fisioterapia'], ['Fonoaudiologia', 'Fonoaudiologia'], ['Medicina', 'Medicina'], ['Medicina Veterinária', 'Medicina Veterinária'], ['Nutrição', 'Nutrição'], ['Odontologia', 'Odontologia'], ['Psicologia', 'Psicologia'], ['Terapia Ocupacional', 'Terapia Ocupacional'], ['Saúde Ocupacional', 'Saúde Ocupacional'], ['Sanitarista / saúde coletiva', 'Sanitarista / saúde coletiva']], max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='FrequenciaResidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmacao', models.BooleanField(blank=True, null=True, verbose_name='Confirmado?')),
                ('diario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='diario_frequencia_residente_set', to='residencia.diario', verbose_name='Diário')),
                ('preceptor_confirmador', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.servidor', verbose_name='Preceptor')),
                ('residente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_residente_set', to='residencia.residente')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
    ]
