# Generated by Django 3.2.5 on 2023-01-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0024_assinaturaataeletronicaresidencia_ataeletronicaresidencia_membrobancaresidencia_projetofinalresidenc'),
        ('residencia', '0024_preceptordiario_tipopreceptordiario'),
    ]

    operations = [
    ]
