# Generated by Django 3.2.5 on 2023-01-13 18:00

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0026_alter_frequenciaresidente_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaresidente',
            name='diario',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculadiario_frequencia_residente_set', to='residencia.matriculadiario', verbose_name='Matricula Diario'),
        ),
    ]
