# Generated by Django 3.2.5 on 2023-01-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0025_merge_20230118_0821'),
        ('residencia', '0027_alter_frequenciaresidente_diario'),
    ]

    operations = [
    ]
