# Generated by Django 3.2.5 on 2023-01-30 13:47

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0029_auto_20230130_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciaresidente',
            name='documento_fisico',
        ),
        migrations.CreateModel(
            name='DocumentoFrequenciaMensalResidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_fisico', djtools.db.models.FileFieldPlus(blank=True, max_length=250, null=True, upload_to='residencia/frequencias_fisicas/')),
                ('mes_referencia', djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=1, null=True, verbose_name='Mês de Referência')),
                ('ano_referencia', djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], db_index=True, default=2023, null=True, verbose_name='Ano de Referência')),
                ('data_hora_upload', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('residente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documento_frequencia_residente_set', to='residencia.residente')),
            ],
            options={
                'verbose_name': 'Documento de Frequencia Mensal',
                'verbose_name_plural': 'Documentos de Frequencia Mensal',
            },
        ),
    ]
