# Generated by Django 3.2.5 on 2023-01-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0029_auto_20230127_0903'),
        ('residencia', '0030_auto_20230130_1347'),
    ]

    operations = [
    ]
