# Generated by Django 3.2.5 on 2023-02-01 15:36

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('residencia', '0031_merge_0029_auto_20230127_0903_0030_auto_20230130_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstagioEletivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Seguro Saúde (caso seja uma exigência do serviço)')),
                ('nome_servico', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome do Serviço de interesse para o estágio')),
                ('cidade_servico', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Cidade/Estado/País')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Data de Término')),
                ('local_estagio', models.TextField(blank=True, verbose_name='Caracterização do local do estágio')),
                ('justificativa_estagio', models.TextField(blank=True, verbose_name='Justificativa para o estágio')),
                ('situacao', models.PositiveIntegerField(choices=[(1, 'Em Andamento'), (2, 'Concluído'), (3, 'Não Concluído')], default=1, verbose_name='Situação')),
                ('alterado_em', djtools.db.models.DateTimeFieldPlus(auto_now=True, null=True, verbose_name='Data de Alteração')),
                ('residente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.residente')),
            ],
            options={
                'verbose_name': 'Estágio Eletivo',
                'verbose_name_plural': 'Estágios Eletivos',
            },
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='documento_fisico',
            field=djtools.db.models.FileFieldPlus(max_length=250, upload_to='residencia/frequencias_fisicas/'),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=2, null=True, verbose_name='Mês de Referência'),
        ),
        migrations.CreateModel(
            name='SolicitacaoEletivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Seguro Saúde (caso seja uma exigência do serviço)')),
                ('nome_servico', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome do Serviço de interesse para o estágio')),
                ('cidade_servico', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Cidade/Estado/País')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Data de Término')),
                ('local_estagio', models.TextField(blank=True, verbose_name='Caracterização do local do estágio')),
                ('justificativa_estagio', models.TextField(blank=True, verbose_name='Justificativa para o estágio')),
                ('situacao', models.PositiveIntegerField(choices=[(1, 'Em Análise'), (2, 'Atendido'), (3, 'Não Atendido'), (4, 'Cancelado')], default=1, verbose_name='Situação')),
                ('alterado_em', djtools.db.models.DateTimeFieldPlus(auto_now=True, null=True, verbose_name='Data de Alteração')),
                ('parecer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Parecer da Solicitação')),
                ('parecer_data', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data do Parecer')),
                ('estagio', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.estagioeletivo', verbose_name='Estágio Eletivo')),
                ('parecer_autor_vinculo', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_solic_eletivo_autor_parecer_vinculo', to='comum.vinculo', verbose_name='Autor do Parecer')),
                ('residente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.residente')),
            ],
            options={
                'verbose_name': 'Solicitação de Estágio Eletivo',
                'verbose_name_plural': 'Solicitações de Estágio Eletivo',
            },
        ),
    ]
