# Generated by Django 3.2.5 on 2023-01-31 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residencia', '0031_merge_0029_auto_20230127_0903_0030_auto_20230130_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, null=True, verbose_name='Data da Solicitação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_avaliacao', djtools.db.models.DateTimeFieldPlus(null=True)),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('razao_indeferimento', models.TextField(null=True, verbose_name='Razão do Indeferimento')),
                ('avaliador', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_avaliador_residencia_set', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('solicitante', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_solicitante_residencia_set', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Usuário',
                'verbose_name_plural': 'Solicitações de Usuários',
                'ordering': ('data_solicitacao',),
            },
        ),
    ]
