# Generated by Django 3.2.5 on 2023-01-31 13:43

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0031_merge_0029_auto_20230127_0903_0030_auto_20230130_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='documento_fisico',
            field=djtools.db.models.FileFieldPlus(default='', max_length=250, upload_to='residencia/frequencias_fisicas/'),
        ),
    ]
