# Generated by Django 3.2.5 on 2023-01-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0033_solicitacaodesligamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDiplomas',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residencia.solicitacaousuario')),
                ('observacao', models.TextField(null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Solicitação de Diplomas',
                'verbose_name_plural': 'Solicitações de Diplomas',
            },
            bases=('residencia.solicitacaousuario',),
        ),
    ]
