# Generated by Django 3.2.5 on 2023-02-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0032_auto_20230201_1536'),
        ('residencia', '0033_alter_documentofrequenciamensalresidente_documento_fisico'),
    ]

    operations = [
    ]
