# Generated by Django 3.2.5 on 2023-02-01 17:20

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0034_merge_20230201_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoeletivo',
            name='solicitado_em',
            field=djtools.db.models.DateTimeFieldPlus(auto_now=True, null=True, verbose_name='Data de Solicitação'),
        ),
    ]
