# Generated by Django 3.2.5 on 2023-02-01 20:24

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0034_solicitacaodiplomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoFerias',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residencia.solicitacaousuario')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Fim')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='E-mail para contato')),
            ],
            options={
                'verbose_name': 'Solicitação de Férias',
                'verbose_name_plural': 'Solicitações de Férias',
            },
            bases=('residencia.solicitacaousuario',),
        ),
        migrations.CreateModel(
            name='SolicitacaoLicencas',
            fields=[
                ('solicitacaousuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residencia.solicitacaousuario')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Fim')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='E-mail para contato')),
            ],
            options={
                'verbose_name': 'Solicitação de Licenças',
                'verbose_name_plural': 'Solicitações de Licenças',
            },
            bases=('residencia.solicitacaousuario',),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=2, null=True, verbose_name='Mês de Referência'),
        ),
    ]
