# Generated by Django 3.2.5 on 2023-02-01 20:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residencia', '0035_solicitacaoeletivo_solicitado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstagioEletivoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.PositiveIntegerField(choices=[(1, 'Relatório'), (2, 'Avaliação'), (3, 'Frequência')], default=1, verbose_name='Tipo do Arquivo')),
                ('descricao', djtools.db.models.CharFieldPlus(help_text='Informe uma descrição resumida sobre o arquivo anexado', max_length=80, verbose_name='Descrição')),
                ('anexo', djtools.db.models.FileFieldPlus(max_length=255, upload_to='upload/estagioeletivo/anexos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'docx', 'doc', 'pdf'])])),
                ('anexado_em', models.DateTimeField(auto_now_add=True, verbose_name='Anexado Em')),
                ('anexado_por', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Anexado Por')),
                ('estagio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.estagioeletivo', verbose_name='Estágio Eletivo')),
            ],
            options={
                'verbose_name': 'Anexo de Estágio Eletivo',
                'verbose_name_plural': 'Anexos de Estágio Eletivo',
                'ordering': ['anexado_em'],
            },
        ),
    ]
