# Generated by Django 3.2.5 on 2023-02-02 00:34

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0053_merge_20220929_2218'),
        ('residencia', '0036_estagioeletivoanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagioeletivo',
            name='alterado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_estagio_eletivo_alterado_por_vinculo', to='comum.vinculo', verbose_name='Alterado por'),
        ),
    ]
