# Generated by Django 3.2.5 on 2023-02-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0034_merge_20230201_1546'),
        ('residencia', '0037_solicitacaocongressos_turma'),
    ]

    operations = [
    ]
