# Generated by Django 3.2.5 on 2023-02-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0037_estagioeletivo_alterado_por'),
        ('residencia', '0038_merge_20230201_2226'),
    ]

    operations = [
    ]
