# Generated by Django 3.2.5 on 2023-02-10 12:31

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0040_alter_documentofrequenciamensalresidente_documento_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicencas',
            name='tipo_solicitacao',
            field=djtools.db.models.CharFieldPlus(choices=[['Tipo1', 'Tipo1'], ['Tipo2', 'Tipo2'], ['Tipo3', 'Tipo3']], max_length=255, null=True, verbose_name='Tipo de Licença'),
        ),
    ]
