# Generated by Django 3.2.5 on 2023-03-03 00:40

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0041_auto_20230213_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(null=True, verbose_name='Etapa')),
                ('forma_calculo', models.IntegerField(choices=[[4, 'Maior Nota'], [2, 'Média Aritmética'], [3, 'Média Ponderada'], [5, 'Soma com Divisor Informado'], [1, 'Soma Simples'], [6, 'Média Atitudinal']], default=2, verbose_name='Forma de Cálculo')),
                ('divisor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Divisor')),
                ('maior_nota', models.BooleanField(default=False, verbose_name='Ignorar Maior Nota')),
                ('menor_nota', models.BooleanField(default=False, verbose_name='Ignorar Menor Nota')),
                ('autopublicar', models.BooleanField(default=True, help_text='As notas das avaliacões serão exibidas aos residentes a medida que forem lançadas.', verbose_name='Autopublicar Notas')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('diario', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.diario', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Configuração de Avaliação',
                'verbose_name_plural': 'Configurações de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='ItemConfiguracaoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[[4, 'Prova'], [2, 'Seminário'], [1, 'Trabalho'], [3, 'Teste'], [5, 'Atividade'], [6, 'Exercício'], [7, 'Atitudinal']], default=4, verbose_name='Tipo da Avaliação')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Sigla')),
                ('descricao', djtools.db.models.CharFieldPlus(default='', max_length=255, verbose_name='Descrição')),
                ('data', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('nota_maxima', models.PositiveIntegerField(default=100, verbose_name='Nota Máxima')),
                ('peso', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('configuracao_avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.configuracaoavaliacao', verbose_name='Configuração da Avaliação')),
            ],
            options={
                'verbose_name': 'Item de Configuração de Avaliação',
                'verbose_name_plural': 'Itens de Configuração de Avaliação',
            },
        ),
        migrations.RemoveField(
            model_name='componentecurricular',
            name='ch_pratica',
        ),
        migrations.RemoveField(
            model_name='componentecurricular',
            name='ch_presencial',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='nota3',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='nota4',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='ch_pratica_teorico_pratica',
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_cumprimento',
            field=models.PositiveIntegerField(choices=[[1, '8 horas mensais'], [2, '4 horas mensais'], [3, '2 horas semanais']], default=1, verbose_name='Cumprimento da Carga Horária'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Toral'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='registro_freq',
            field=models.PositiveIntegerField(choices=[[1, 'Registro realizado pelo Residente - Atividades Práticas'], [2, 'Registro realizado pelo Preceptor/Apoiador'], [3, 'Registro realizado pelo Residente - Atividades Extras']], default=1, verbose_name='Tipo de Registro de Frequência'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='ch_pratica',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Prática'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='ch_teorico_pratica',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Teórico Prática'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='tipo',
            field=models.PositiveIntegerField(choices=[[1, 'Prática'], [2, 'Teórica'], [3, 'Teórico Prática']], default=1),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=3, null=True, verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='ch_teorica',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Teórica'),
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', djtools.db.models.NotaField(null=True, verbose_name='Nota')),
                ('item_configuracao_avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.itemconfiguracaoavaliacao', verbose_name='Item de Configuração de Avaliação')),
                ('matricula_diario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.matriculadiario', verbose_name='Matrícula Diário')),
            ],
            options={
                'verbose_name': 'Nota de Avaliação',
                'verbose_name_plural': 'Notas de Avaliações',
                'ordering': ('-id',),
            },
        ),
    ]
