# Generated by Django 3.2.5 on 2023-03-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0042_auto_20230303_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicencas',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Licença Maternidade'), (2, 'Licença Médica'), (10, 'Outras')], null=True, verbose_name='Tipo de licença'),
        ),
    ]
