# Generated by Django 3.2.5 on 2023-03-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0042_auto_20230302_1034'),
        ('residencia', '0043_solicitacaolicencas_tipo'),
    ]

    operations = [
    ]
