# Generated by Django 3.2.5 on 2023-03-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0044_merge_20230303_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ('descricao',), 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.RemoveField(
            model_name='solicitacaolicencas',
            name='tipo_solicitacao',
        ),
    ]
