# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('residencia', '0045_auto_20230309_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Residente',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='residente_set', to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='examinador_interno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_interno_residencia_set', to='rh.pessoafisica', verbose_name='Examinador Interno'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='examinador_externo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_externo_residencia_set', to='rh.pessoafisica', verbose_name='Segundo Examinador'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='terceiro_examinador',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_examinador_residencia_set', to='rh.pessoafisica', verbose_name='Terceiro Examinador'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='suplente_interno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_interno_residencia_set', to='rh.pessoafisica', verbose_name='Suplente Interno'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='suplente_externo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_externo_residencia_set', to='rh.pessoafisica', verbose_name='Segundo Suplente'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='terceiro_suplente',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_suplente_residencia_set', to='rh.pessoafisica', verbose_name='Terceiro Suplente'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinalResidencia',
            name='coorientadores',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='coorientadores_residencia_set', to='rh.PessoaFisica', verbose_name='Coorientadores Residencia'),
        ),
        migrations.AlterField(
            model_name='AssinaturaAtaEletronicaResidencia',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='CursoResidencia',
            name='coordenador',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario'),
        ),
    ]
