# Generated by Django 3.2.5 on 2023-04-18 08:02

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0047_alter_documentofrequenciamensalresidente_mes_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeAprendizagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Unidade de Aprendizagem',
                'verbose_name_plural': 'Unidades de Aprendizagem',
            },
        ),
        migrations.AddField(
            model_name='matriz',
            name='unidade_arendizagem',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.unidadeaprendizagem'),
        ),
    ]
