# Generated by Django 3.2.5 on 2023-04-18 08:36

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0048_auto_20230418_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriz',
            name='unidade_arendizagem',
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='unidade_arendizagem',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.unidadeaprendizagem'),
        ),
    ]
