# Generated by Django 3.2.5 on 2023-04-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0049_auto_20230418_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentecurricular',
            old_name='unidade_arendizagem',
            new_name='unidade_aprendizagem',
        ),
    ]
