# Generated by Django 3.2.5 on 2023-05-03 16:14

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0050_rename_unidade_arendizagem_componentecurricular_unidade_aprendizagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=5, null=True, verbose_name='Mês de Referência'),
        ),
    ]
