# Generated by Django 3.2.5 on 2023-05-01 09:19

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0050_rename_unidade_arendizagem_componentecurricular_unidade_aprendizagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeaprendizagem',
            name='qtd_avaliacoes',
            field=models.PositiveIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], default=1, verbose_name='Quantidade de Avaliações'),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=5, null=True, verbose_name='Mês de Referência'),
        ),
    ]
