# Generated by Django 3.2.5 on 2023-04-25 10:49

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0051_auto_20230425_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='outras_necessidades',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Outras necessidades especiais'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='outras_necessidades',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Outras necessidades'),
        ),
    ]
