# Generated by Django 3.2.5 on 2023-04-26 12:23

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0058_municipio_territorio_identidade'),
        ('residencia', '0052_auto_20230425_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='email_responsavel',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='parentesco_responsavel',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='email_responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacaoresidente',
            name='responsavel',
        ),
        migrations.AlterField(
            model_name='residente',
            name='cidade_profissional',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residente_cidade_profissional_set', to='comum.municipio', verbose_name='Cidade Profissional'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='contato_emergencia',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Em caso de emergência para quem ligar e em qual número?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='csf',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ciência sem Fronteiras'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='em_tratamento_medico',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, null=True, verbose_name='Está em tratamento médico?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='em_tratamento_medico_qual',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Está em tratamento médico?', informe qual e para que doença:"),
        ),
        migrations.AlterField(
            model_name='residente',
            name='email_academico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Acadêmico'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='email_google_classroom',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Google Classroom'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='email_qacademico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Q-Acadêmico'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='estado_civil_mae',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Solteiro', 'Solteiro'], ['Casado', 'Casado'], ['União Estável', 'União Estável'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo']], max_length=255, null=True, verbose_name='Estado Civil da Mãe'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='nacionalidade',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Brasileira', 'Brasileira'], ['Brasileira - Nascido no exterior ou naturalizado', 'Brasileira - Nascido no exterior ou naturalizado'], ['Estrangeira', 'Estrangeira']], max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='numero_dependentes',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, null=True, verbose_name='Número de Dependentes'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='outra_info_saude',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Existe alguma outra informação a respeito da sua saúde que queira fazer constar?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='passaporte',
            field=djtools.db.models.CharFieldPlus(blank=True, default='', max_length=50, null=True, verbose_name='Nº do Passaporte'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='possui_alergia',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, null=True, verbose_name='Alguma alergia?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='possui_alergia_qual',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Alguma alergia?', informe qual(is):"),
        ),
        migrations.AlterField(
            model_name='residente',
            name='possui_problema_saude',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, null=True, verbose_name='Tem algum problema de Saúde?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='renda_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Número de salários mínimos ganhos pelos integrantes da família dividido pelo número de integrantes', max_digits=15, null=True, verbose_name='Renda Per Capita'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefone_secundario',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='usa_medicacao',
            field=models.BooleanField(blank=True, choices=[(False, 'Não'), (True, 'Sim')], default=False, null=True, verbose_name='Está em uso de alguma medicação?'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='usa_medicacao_qual',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name="Se marcou 'Sim' para 'Está em uso de alguma medicação?', informe qual e quando encerrará o uso:"),
        ),
        migrations.AlterField(
            model_name='solicitacaoresidente',
            name='estado_civil_mae',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Solteiro', 'Solteiro'], ['Casado', 'Casado'], ['União Estável', 'União Estável'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo']], max_length=255, null=True, verbose_name='Estado Civil da Mãe'),
        ),
        migrations.AlterField(
            model_name='solicitacaoresidente',
            name='telefone_secundario',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
    ]
