# Generated by Django 3.2.5 on 2023-04-26 12:26

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0053_auto_20230426_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='email_responsavel',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Email do Responsável'),
        ),
        migrations.AddField(
            model_name='residente',
            name='parentesco_responsavel',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Pai/Mãe', 'Pai/Mãe'], ['Avô/Avó', 'Avô/Avó'], ['Tio/Tia', 'Tio/Tia'], ['Sobrinho/Sobrinha', 'Sobrinho/Sobrinha'], ['Outro', 'Outro']], max_length=255, null=True, verbose_name='Parentesco do Responsável'),
        ),
        migrations.AddField(
            model_name='residente',
            name='responsavel',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='email_responsavel',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Email do Responsável'),
        ),
        migrations.AddField(
            model_name='solicitacaoresidente',
            name='responsavel',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
    ]
