# Generated by Django 3.2.5 on 2023-05-02 16:12

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0053_auto_20230502_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeaprendizagem',
            name='ordem',
            field=models.PositiveIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9]], default=1, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_fim_etapa_1',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da primeiro ciclo', null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_fim_etapa_2',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da segundo ciclo', null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_fim_etapa_3',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da terceiro ciclo', null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_fim_etapa_4',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de encerramento da quarto ciclo', null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_inicio_etapa_1',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da primeiro ciclo', null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_inicio_etapa_2',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da segundo ciclo', null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_inicio_etapa_3',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da terceiro ciclo', null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='data_inicio_etapa_4',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Data de início da quarto ciclo', null=True, verbose_name='Início'),
        ),
    ]
