# Generated by Django 3.2.5 on 2023-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0054_auto_20230502_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadeaprendizagem',
            name='ordem',
        ),
        migrations.AddField(
            model_name='unidadeaprendizagem',
            name='ciclo',
            field=models.PositiveIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4]], default=1, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='unidadeaprendizagem',
            name='qtd_avaliacoes',
            field=models.PositiveIntegerField(choices=[[1, 1], [2, 2]], default=1, verbose_name='Quantidade de Avaliações'),
        ),
    ]
