# Generated by Django 3.2.5 on 2023-05-03 09:35

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0056_auto_20230502_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConfiguracaoAvaliacaoUnidadeAprendizagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[[4, 'Prova'], [2, 'Seminário'], [1, 'Trabalho'], [3, 'Teste'], [5, 'Atividade'], [6, 'Exercício'], [7, 'Atitudinal']], default=4, verbose_name='Tipo da Avaliação')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Sigla')),
                ('descricao', djtools.db.models.CharFieldPlus(default='', max_length=255, verbose_name='Descrição')),
                ('data', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('nota_maxima', models.PositiveIntegerField(default=100, verbose_name='Nota Máxima')),
                ('peso', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('configuracao_avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.configuracaoavaliacao', verbose_name='Configuração da Avaliação')),
            ],
            options={
                'verbose_name': 'Item de Configuração de Avaliação',
                'verbose_name_plural': 'Itens de Configuração de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='MatriculaUnidadeAprendizagemTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', djtools.db.models.NotaField(null=True, verbose_name='N1')),
                ('nota_2', djtools.db.models.NotaField(null=True, verbose_name='N2')),
                ('nota_final', djtools.db.models.NotaField(null=True, verbose_name='NAF')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'Cursando'], [2, 'Aprovado'], [3, 'Reprovado'], [4, 'Prova Final'], [5, 'Reprovado por falta'], [6, 'Trancado'], [7, 'Cancelado'], [8, 'Dispensado'], [9, 'Pendente'], [10, 'Aprovado/Reprovado no Módulo'], [13, 'Transferido']], default=1, verbose_name='Situação')),
                ('matricula_periodo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_unidadeaprendizagemturma_matricula_periodo_set', to='residencia.matriculaperiodo')),
                ('unidade_aprendizagem_turma', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_unidadeaprendizagemturma_unidade_aprendizagem_turma_set', to='residencia.unidadeaprendizagemturma')),
            ],
            options={
                'verbose_name': 'Matrícula em Unidade Aprendizagem',
                'verbose_name_plural': 'Matrículas em Unidade Aprendizagem',
                'ordering': ('matricula_periodo__residente__pessoa_fisica__nome',),
            },
        ),
        migrations.CreateModel(
            name='NotaAvaliacaoUnidadeAprendizagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', djtools.db.models.NotaField(null=True, verbose_name='Nota')),
                ('item_configuracao_avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.itemconfiguracaoavaliacaounidadeaprendizagem', verbose_name='Item de Configuração de Avaliação')),
                ('matricula_unidade_aprendizagem_turma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.matriculaunidadeaprendizagemturma', verbose_name='Matrícula Unidade Aprendizagem Turma')),
            ],
            options={
                'verbose_name': 'Nota de Avaliação',
                'verbose_name_plural': 'Notas de Avaliações',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAvaliacaoUnidadeAprendizagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(null=True, verbose_name='Etapa')),
                ('forma_calculo', models.IntegerField(choices=[[4, 'Maior Nota'], [2, 'Média Aritmética'], [3, 'Média Ponderada'], [5, 'Soma com Divisor Informado'], [1, 'Soma Simples'], [6, 'Média Atitudinal']], default=2, verbose_name='Forma de Cálculo')),
                ('divisor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Divisor')),
                ('maior_nota', models.BooleanField(default=False, verbose_name='Ignorar Maior Nota')),
                ('menor_nota', models.BooleanField(default=False, verbose_name='Ignorar Menor Nota')),
                ('autopublicar', models.BooleanField(default=True, help_text='As notas das avaliacões serão exibidas aos residentes a medida que forem lançadas.', verbose_name='Autopublicar Notas')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('unidadeaprendizagemturma', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.unidadeaprendizagemturma', verbose_name='Unidade Aprendizagem Turma')),
            ],
            options={
                'verbose_name': 'Configuração de Avaliação Unidade Aprendizagem',
                'verbose_name_plural': 'Configurações de Avaliação Unidade Aprendizagem',
            },
        ),
        migrations.AddIndex(
            model_name='matriculaunidadeaprendizagemturma',
            index=models.Index(fields=['matricula_periodo'], name='residencia__matricu_0b01d8_idx'),
        ),
    ]
