# Generated by Django 3.2.5 on 2023-05-03 10:40

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0058_municipio_territorio_identidade'),
        ('residencia', '0057_auto_20230503_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeaprendizagemturma',
            name='ano_letivo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidadesapredizagens_residencia_por_ano_letivo_set', to='comum.ano', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='unidadeaprendizagemturma',
            name='periodo_letivo',
            field=models.PositiveIntegerField(blank=True, choices=[[1, '1']], null=True, verbose_name='Período Letivo'),
        ),
    ]
