# Generated by Django 3.2.5 on 2023-05-03 11:13

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0058_auto_20230503_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconfiguracaoavaliacaounidadeaprendizagem',
            name='configuracao_avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.configuracaoavaliacaounidadeaprendizagem', verbose_name='Configuração da Avaliação da Unidade'),
        ),
    ]
