# Generated by Django 3.2.5 on 2023-05-03 12:03

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0059_alter_itemconfiguracaoavaliacaounidadeaprendizagem_configuracao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeaprendizagemturma',
            name='posse_etapa_2',
            field=models.PositiveIntegerField(choices=[[1, 'Preceptor'], [0, 'Registro']], default=1),
        ),
        migrations.AlterField(
            model_name='itemconfiguracaoavaliacaounidadeaprendizagem',
            name='configuracao_avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.configuracaoavaliacaounidadeaprendizagem', verbose_name='Configuração da Avaliação da Uminidade'),
        ),
    ]
