# Generated by Django 3.2.5 on 2023-05-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0051_alter_documentofrequenciamensalresidente_mes_referencia'),
        ('residencia', '0054_auto_20230426_1226'),
        ('residencia', '0060_auto_20230503_1203'),
    ]

    operations = [
    ]
