# Generated by Django 3.2.5 on 2024-03-04 21:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0063_alter_documentofrequenciamensalresidente_mes_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetofinalresidencia',
            options={'verbose_name': 'Trabalho de Conclusão de Residência', 'verbose_name_plural': 'Trabalhos de Conclusão de Residência'},
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='ano_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], db_index=True, default=2024, null=True, verbose_name='Ano de Referência'),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=3, null=True, verbose_name='Mês de Referência'),
        ),
    ]
