# Generated by Django 3.2.5 on 2024-09-03 11:39

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0064_auto_20240304_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='lotacao',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Nome da Lotação'),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período letivo'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período Letivo'),
        ),
        migrations.AlterField(
            model_name='documentofrequenciamensalresidente',
            name='mes_referencia',
            field=djtools.db.models.PositiveIntegerFieldPlus(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_index=True, default=9, null=True, verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='preceptordiario',
            name='periodo_letivo_ch',
            field=models.IntegerField(blank=True, choices=[[1, '1'], [2, '2']], help_text='Informar caso o percentual da carga horária ministrada se refira a apenas um período letivo.', null=True, verbose_name='Período Letivo da Carga-Horária'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='periodo_letivo',
            field=models.PositiveIntegerField(blank=True, choices=[[1, '1'], [2, '2']], null=True, verbose_name='Período de Ingresso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo_letivo',
            field=models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período Letivo'),
        ),
        migrations.AlterField(
            model_name='unidadeaprendizagemturma',
            name='periodo_letivo',
            field=models.PositiveIntegerField(blank=True, choices=[[1, '1'], [2, '2']], null=True, verbose_name='Período Letivo'),
        ),
    ]
