# Generated by Django 3.2.5 on 2024-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0065_auto_20240903_1110'),
        ('residencia', '0065_auto_20240903_1139'),
        ('residencia', '0065_auto_20240903_1422'),
    ]

    operations = [
    ]
