# Generated by Django 3.2.5 on 2024-09-19 16:19

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0066_merge_20240905_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentecurricular',
            options={'ordering': ('nome_do_componente', 'matriz', 'periodo_letivo', 'componente__descricao'), 'verbose_name': 'Componente Curricular', 'verbose_name_plural': 'Componentes Curriculares'},
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='nome_do_componente',
            field=djtools.db.models.CharFieldPlus(default='', max_length=255, null=True, verbose_name='Nome do Componente'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='componente',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.componente', verbose_name='Atividades'),
        ),
    ]
