# Generated by Django 3.2.5 on 2024-09-06 15:58

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0066_merge_20240905_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='is_dinamico',
            field=models.BooleanField(default=False, help_text='Marque essa opção caso deseje que a descrição do componente possa ser complementada no diário.', verbose_name='Descrição Dinâmica'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='componente',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.componente', verbose_name='Atividades'),
        ),
    ]
