# Generated by Django 3.2.5 on 2024-09-17 15:13

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0066_merge_20240905_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, help_text='Hora-Relógio', null=True, verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='componente',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='residencia.componente', verbose_name='Atividades'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Biomedicina', 'Biomedicina'], ['Educação Física', 'Educação Física'], ['Enfermagem', 'Enfermagem'], ['Farmácia', 'Farmácia'], ['Fisioterapia', 'Fisioterapia'], ['Fonoaudiologia', 'Fonoaudiologia'], ['Medicina', 'Medicina'], ['Medicina Veterinária', 'Medicina Veterinária'], ['Nutrição', 'Nutrição'], ['Odontologia', 'Odontologia'], ['Psicologia', 'Psicologia'], ['Terapia Ocupacional', 'Terapia Ocupacional'], ['Saúde Ocupacional', 'Saúde Ocupacional'], ['Sanitarista / saúde coletiva', 'Sanitarista / saúde coletiva']], max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='solicitacaoresidente',
            name='categoria',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[['Biomedicina', 'Biomedicina'], ['Educação Física', 'Educação Física'], ['Enfermagem', 'Enfermagem'], ['Farmácia', 'Farmácia'], ['Fisioterapia', 'Fisioterapia'], ['Fonoaudiologia', 'Fonoaudiologia'], ['Medicina', 'Medicina'], ['Medicina Veterinária', 'Medicina Veterinária'], ['Nutrição', 'Nutrição'], ['Odontologia', 'Odontologia'], ['Psicologia', 'Psicologia'], ['Terapia Ocupacional', 'Terapia Ocupacional'], ['Saúde Ocupacional', 'Saúde Ocupacional'], ['Sanitarista / saúde coletiva', 'Sanitarista / saúde coletiva']], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
