# Generated by Django 3.2.5 on 2024-09-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0067_auto_20240906_1558'),
        ('residencia', '0067_auto_20240917_1513'),
    ]

    operations = [
    ]
