# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LdapConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucao', models.CharField(choices=[('active_directory', 'Active Directory'), ('open_ldap', 'OpenLDAP')], max_length=20, verbose_name='Solução de autenticação')),
                ('uri', djtools.db.models.CharFieldPlus(help_text='Ex.: "ldap://ldap.ifrn.local:389".', max_length=255, verbose_name='URI')),
                ('who', djtools.db.models.CharFieldPlus(help_text='Ex.: "cn=admin,dc=ifrn,dc=edu,dc=br".', max_length=255, verbose_name='Usuário (DN)')),
                ('cred', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Senha')),
                ('base', djtools.db.models.CharFieldPlus(help_text='Ex.: "OU=IFRN,DC=ifrn,DC=local".', max_length=255, verbose_name='Base DN')),
                (
                    'filterstr_prefix',
                    djtools.db.models.CharFieldPlus(default='sAMAccountName=', help_text='Ex.: "sAMAccountName=", "uid=".', max_length=255, verbose_name='Filtro de autenticação'),
                ),
                ('domain', djtools.db.models.CharFieldPlus(help_text='Ex.: "ifrn.local".', max_length=255, verbose_name='Domínio')),
                ('email_admin', models.EmailField(default='digti@ifrn.edu.br', help_text='Email da coordenação de TI', max_length=254)),
                ('active', models.BooleanField(default=True, verbose_name='Serviço ativo')),
                ('resolve_referral', models.BooleanField(default=True, verbose_name='LDAP should resolve referrals')),
            ],
            options={
                'verbose_name': 'Configuração do Serviço de Diretório',
                'verbose_name_plural': 'Configurações dos Serviços de Diretório',
                'permissions': (
                    ('change_ldap_user_password_subtree', 'Pode modificar a senha de usuários da sub-árvore'),
                    ('change_ldap_user_password_all', 'Pode modificar a senha de todos os usuários'),
                    ('change_ldap_user_password_aluno', 'Pode modificar a senha de alunos'),
                    ('sync_ldap_user', 'Pode sincronizar usuários'),
                    ('view_ldap_user', 'Pode ver usuários'),
                    ('pode_acessar_google_classroom', 'Pode acessar o Google Classrooom'),
                ),
            },
        )
    ]
