# Generated by Django 3.2.5 on 2021-12-30 14:18

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_backend', '0002_ldapconf_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200, unique=True, verbose_name='Common Name')),
                ('name', ldapdb.models.fields.CharField(blank=True, db_column='name', help_text='Name', max_length=200, null=True, verbose_name='Name')),
                ('sAMAccountName', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200, unique=True, verbose_name='Account Name')),
                ('member', ldapdb.models.fields.ListField(db_column='member', default=[], null=True, verbose_name='Group Members')),
            ],
            options={
                'verbose_name': 'LDAP Grupo',
                'verbose_name_plural': 'LDAP Grupos',
            },
        ),
        migrations.CreateModel(
            name='LdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('uid', ldapdb.models.fields.CharField(db_column='uSNCreated', help_text='uid', max_length=200, verbose_name='User ID')),
                ('sAMAccountName', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200, unique=True, verbose_name='Account Name')),
                ('givenName', ldapdb.models.fields.CharField(blank=True, db_column='givenName', max_length=200, null=True, verbose_name='First Name')),
                ('sn', ldapdb.models.fields.CharField(db_column='sn', help_text='Surname', max_length=200, verbose_name='Surname')),
                ('mail', ldapdb.models.fields.CharField(blank=True, db_column='mail', help_text='E-mail', max_length=200, null=True, verbose_name='E-mail')),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', help_text='Common Name', max_length=200, verbose_name='Common Name')),
                ('name', ldapdb.models.fields.CharField(blank=True, db_column='displayName', help_text='Display Name', max_length=200, null=True, verbose_name='Display Name')),
                ('distinguishedName', ldapdb.models.fields.CharField(db_column='distinguishedName', max_length=200, unique=True, verbose_name='Distinguished Name')),
                ('member_of', ldapdb.models.fields.ListField(db_column='memberOf', editable=False, null=True)),
            ],
            options={
                'verbose_name': 'LDAP User',
                'verbose_name_plural': 'LDAP Users',
            },
        ),
    ]
