# Generated by Django 2.2.10 on 2020-04-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servico_portal_govbr', models.PositiveIntegerField(unique=True, verbose_name='Id Gov Br')),
                ('icone', models.CharField(max_length=50, verbose_name='Ícone')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços', 'ordering': ['id_servico_portal_govbr']},
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('numero_total_etapas', models.PositiveSmallIntegerField(verbose_name='Nº Total de Etapas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização')),
                (
                    'status',
                    models.CharField(
                        choices=[('INCOMPLETO', 'Incompleto'), ('EM_ANALISE', 'Em Análise'), ('ATENDIDO', 'Atendido'), ('NAO_ATENDIDO', 'Não Atendido')],
                        default='EM_ANALISE',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('status_detalhamento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Detalhamento do Status')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Servico')),
            ],
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações', 'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='SolicitacaoEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização')),
                ('numero_etapa', models.PositiveSmallIntegerField(verbose_name='Número da Etapa')),
                ('dados', models.TextField(verbose_name='Dados')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao')),
            ],
            options={'verbose_name': 'Solicitação Etapa', 'verbose_name_plural': 'Solicitações Etapas', 'ordering': ['solicitacao', 'id']},
        ),
    ]
