# Generated by Django 2.2.10 on 2020-04-23 19:22


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='RegistroAcompanhamentoGovBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                (
                    'tipo',
                    models.CharField(
                        choices=[('ACOMPANHAMENTO', 'Acompanhamento'), ('CONCLUSAO', 'Conclusão'), ('REABERTURA', 'Reabertura')],
                        default='ACOMPANHAMENTO',
                        max_length=50,
                        verbose_name='Tipo de Registro',
                    ),
                ),
                (
                    'status',
                    models.CharField(choices=[('ENVIADO', 'Enviado'), ('PENDENTE', 'Pendente'), ('ERRO', 'Erro')], default='PENDENTE', max_length=50, verbose_name='Status'),
                ),
            ],
            options={'verbose_name': 'Registro de Acompanhamento de Serviço', 'verbose_name_plural': 'Registros de Acompanhamentos de Serviços'},
        )
    ]
