# Generated by Django 2.2.10 on 2020-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0002_registroacompanhamentogovbr')]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(
                choices=[
                    ('INCOMPLETO', 'Incompleto'),
                    ('EM_ANALISE', 'Em Análise'),
                    ('AGUARDANDO_CORRECAO_DE_DADOS', 'Aguardando Correção de Dados'),
                    ('ATENDIDO', 'Atendido'),
                    ('NAO_ATENDIDO', 'Não Atendido'),
                ],
                default='EM_ANALISE',
                max_length=50,
                verbose_name='Status',
            ),
        )
    ]
