# Generated by Django 2.2.10 on 2020-04-25 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0003_auto_20200424_1349')]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentogovbr',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        )
    ]
