# Generated by Django 2.2.10 on 2020-04-27 08:01

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0004_registroacompanhamentogovbr_data_criacao')]

    operations = [
        migrations.AlterField(
            model_name='registroacompanhamentogovbr', name='data_criacao', field=djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')
        ),
        migrations.AlterField(
            model_name='registroacompanhamentogovbr',
            name='status',
            field=djtools.db.models.CharFieldPlus(
                choices=[('ENVIADO', 'Enviado'), ('PENDENTE', 'Pendente'), ('ERRO', 'Erro')], default='PENDENTE', max_length=50, verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentogovbr',
            name='tipo',
            field=djtools.db.models.CharFieldPlus(
                choices=[('ACOMPANHAMENTO', 'Acompanhamento'), ('CONCLUSAO', 'Conclusão'), ('REABERTURA', 'Reabertura')],
                default='ACOMPANHAMENTO',
                max_length=50,
                verbose_name='Tipo de Registro',
            ),
        ),
        migrations.AlterField(model_name='servico', name='descricao', field=djtools.db.models.CharFieldPlus(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
        migrations.AlterField(model_name='servico', name='icone', field=djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Ícone')),
        migrations.AlterField(model_name='servico', name='titulo', field=djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Título')),
        migrations.AlterField(model_name='solicitacao', name='cpf', field=djtools.db.models.CharFieldPlus(max_length=14, verbose_name='CPF')),
        migrations.AlterField(model_name='solicitacao', name='data_criacao', field=djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
        migrations.AlterField(
            model_name='solicitacao', name='data_ultima_atualizacao', field=djtools.db.models.DateTimeFieldPlus(auto_now=True, verbose_name='Data da Última Atualização')
        ),
        migrations.AlterField(
            model_name='solicitacao', name='servico', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Servico')
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=djtools.db.models.CharFieldPlus(
                choices=[
                    ('INCOMPLETO', 'Incompleto'),
                    ('EM_ANALISE', 'Em Análise'),
                    ('AGUARDANDO_CORRECAO_DE_DADOS', 'Aguardando Correção de Dados'),
                    ('ATENDIDO', 'Atendido'),
                    ('NAO_ATENDIDO', 'Não Atendido'),
                ],
                default='EM_ANALISE',
                max_length=50,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status_detalhamento',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=1000, null=True, verbose_name='Detalhamento do Status'),
        ),
        migrations.AlterField(model_name='solicitacaoetapa', name='data_criacao', field=djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
        migrations.AlterField(
            model_name='solicitacaoetapa', name='data_ultima_atualizacao', field=djtools.db.models.DateTimeFieldPlus(auto_now=True, verbose_name='Data da Última Atualização')
        ),
        migrations.AlterField(
            model_name='solicitacaoetapa',
            name='solicitacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao'),
        ),
    ]
