# Generated by Django 2.2.10 on 2020-05-04 14:49

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0005_auto_20200427_0801')]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentogovbr',
            name='solicitacao',
            field=djtools.db.models.ForeignKeyPlus(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroacompanhamentogovbr', name='status_code', field=djtools.db.models.CharFieldPlus(max_length=50, null=True, verbose_name='Status Code HTTP')
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=djtools.db.models.CharFieldPlus(
                choices=[
                    ('INCOMPLETO', 'Incompleto'),
                    ('EM_ANALISE', 'Em Análise'),
                    ('AGUARDANDO_CORRECAO_DE_DADOS', 'Aguardando Correção de Dados'),
                    ('PRONTO_PARA_EXECUCAO', 'Pronto Para Execução'),
                    ('ATENDIDO', 'Atendido'),
                    ('NAO_ATENDIDO', 'Não Atendido'),
                ],
                default='EM_ANALISE',
                max_length=50,
                verbose_name='Status',
            ),
        ),
    ]
