# Generated by Django 2.2.10 on 2020-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0006_auto_20200504_1449')]

    operations = [migrations.AddField(model_name='registroacompanhamentogovbr', name='avaliado', field=models.BooleanField(default=False))]
