# Generated by Django 2.2.10 on 2020-05-10 23:34

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0011_arquivounico'), ('catalogo_provedor_servico', '0007_registroacompanhamentogovbr_avaliado')]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEtapaArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Nome Original')),
                ('nome_exibicao', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Nome para Exibição')),
                ('data_hora_upload', djtools.db.models.DateTimeFieldPlus(verbose_name='Data e Hora do Upload')),
                ('data_hora_criacao_registro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data e Hora da Criação do Registro')),
                ('hash_sha512_link_id', djtools.db.models.CharFieldPlus(max_length=128, unique=True, verbose_name='Hash 512 Link Id')),
                ('nome_atributo_json', djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Nome do Atributo no Json')),
                ('arquivo_unico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.PROTECT, to='rh.ArquivoUnico')),
                ('solicitacao_etapa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.PROTECT, to='catalogo_provedor_servico.SolicitacaoEtapa')),
            ],
            options={'verbose_name': 'Registro de Acompanhamento de Serviço', 'verbose_name_plural': 'Registros de Acompanhamentos de Serviços'},
        )
    ]
