# Generated by Django 2.2.10 on 2020-05-12 16:50

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0007_registroacompanhamentogovbr_avaliado')]

    operations = [
        migrations.CreateModel(
            name='RegistroAvaliacaoGovBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_avaliacao', models.TextField(null=True)),
                ('resposta_avaliacao', models.TextField(null=True)),
                ('data_cadastro_link_formulario', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de Cadastro do Formulaŕio')),
                ('data_cadastro_avaliacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('avaliado', models.BooleanField(default=False)),
                ('solicitacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao')),
            ],
            options={'verbose_name': 'Registro de Avaliação de Serviço', 'verbose_name_plural': 'Registros de Avaliações de Serviços'},
        )
    ]
