# Generated by Django 2.2.10 on 2020-05-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0008_solicitacaoetapaarquivo')]

    operations = [migrations.AlterUniqueTogether(name='solicitacaoetapaarquivo', unique_together={('solicitacao_etapa', 'nome_atributo_json')})]
