# Generated by Django 2.2.10 on 2020-05-12 17:41

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0008_registroavaliacaogovbr')]

    operations = [
        migrations.AlterField(
            model_name='registroavaliacaogovbr',
            name='data_cadastro_link_formulario',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data de Cadastro do Formulaŕio'),
        )
    ]
