# Generated by Django 2.2.10 on 2020-05-13 09:33

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0009_auto_20200511_1732')]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoetapa', options={'ordering': ['solicitacao', 'numero_etapa'], 'verbose_name': 'Solicitação Etapa', 'verbose_name_plural': 'Solicitações Etapas'}
        ),
        migrations.AlterField(
            model_name='solicitacaoetapaarquivo',
            name='solicitacao_etapa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.SolicitacaoEtapa'),
        ),
        migrations.AlterUniqueTogether(name='solicitacaoetapa', unique_together={('solicitacao', 'numero_etapa')}),
    ]
