# Generated by Django 2.2.10 on 2020-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0009_auto_20200512_1741')]

    operations = [migrations.AddField(model_name='registroavaliacaogovbr', name='notificado_por_email', field=models.BooleanField(default=False))]
