# Generated by Django 2.2.10 on 2020-05-13 17:01

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0010_auto_20200513_0933')]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoetapaarquivo', options={'verbose_name': 'Arquivo da Etapa da Solicitação', 'verbose_name_plural': 'Arquivos da Etapa da Solicitação'}
        ),
        migrations.AlterField(
            model_name='solicitacaoetapaarquivo', name='data_hora_criacao_registro', field=djtools.db.models.DateTimeFieldPlus(verbose_name='Data e Hora da Criação do Registro')
        ),
    ]
