# Generated by Django 2.2.10 on 2020-05-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0011_auto_20200513_1701')]

    operations = [migrations.RemoveField(model_name='solicitacaoetapaarquivo', name='hash_sha512_link_id')]
