# Generated by Django 2.2.10 on 2020-05-14 17:27

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0012_remove_solicitacaoetapaarquivo_hash_sha512_link_id')]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoetapaarquivo',
            name='data_hora_criacao_registro',
            field=djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data e Hora da Criação do Registro'),
        )
    ]
