# Generated by Django 2.2.10 on 2020-05-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0014_merge_20200514_2223')]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={
                'ordering': ['id'],
                'permissions': (('pode_avaliar_solicitacoes', 'Pode Avaliar Solicitações'),),
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        )
    ]
