# Generated by Django 2.2.10 on 2020-05-17 06:10

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0015_auto_20200515_1605')]

    operations = [
        migrations.AddField(
            model_name='solicitacaoetapaarquivo',
            name='descricao',
            field=djtools.db.models.CharFieldPlus(default='----', max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaoetapaarquivo',
            name='nome_exibicao',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=50, null=True, verbose_name='Nome para Exibição'),
        ),
    ]
