# Generated by Django 2.2.10 on 2020-05-18 15:52

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0014_auto_20200516_0227'), ('catalogo_provedor_servico', '0016_auto_20200517_0610')]

    operations = [
        migrations.CreateModel(
            name='ServicoEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_fisica', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica')),
                ('servico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Servico')),
            ],
            options={'verbose_name': 'Equipe do Serviço', 'verbose_name_plural': 'Equipe do Serviço'},
        )
    ]
