# Generated by Django 2.2.10 on 2020-05-18 16:49

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0014_auto_20200516_0227'), ('catalogo_provedor_servico', '0017_servicoequipe')]

    operations = [
        migrations.AddField(model_name='servico', name='entra_campo', field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Campo a apresentar')),
        migrations.AddField(model_name='servico', name='extra_label', field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Label da informação extra')),
        migrations.AddField(
            model_name='solicitacao', name='data_associacao_responsavel', field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data de Associação ao Responsável')
        ),
        migrations.AddField(model_name='solicitacao', name='extra_dados', field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Informação Extra')),
        migrations.AddField(
            model_name='solicitacao', name='responsavel', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica')
        ),
        migrations.CreateModel(
            name='SolicitacaoResponsavelHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_associacao_responsavel', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data de Associação ao Responsável')),
                ('responsavel', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica')),
                ('solicitacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao')),
            ],
            options={'abstract': False},
        ),
    ]
