# Generated by Django 2.2.10 on 2020-05-19 00:19

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('catalogo_provedor_servico', '0020_auto_20200518_2014')]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=djtools.db.models.CharFieldPlus(
                choices=[
                    ('INCOMPLETO', 'Incompleto'),
                    ('EM_ANALISE', 'Em Análise'),
                    ('AGUARDANDO_CORRECAO_DE_DADOS', 'Aguardando Correção de Dados'),
                    ('DADOS_CORRIGIDOS', 'Dados Corrigidos'),
                    ('PRONTO_PARA_EXECUCAO', 'Pronto Para Execução'),
                    ('ATENDIDO', 'Atendido'),
                    ('NAO_ATENDIDO', 'Não Atendido'),
                ],
                default='EM_ANALISE',
                max_length=50,
                verbose_name='Status',
            ),
        ),
    ]
