# Generated by Django 2.2.10 on 2020-05-30 11:09

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_auto_20200516_0227'),
        ('catalogo_provedor_servico', '0024_auto_20200525_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='label_btn_executar_solicitacao',
            field=djtools.db.models.CharFieldPlus(default='Executar', max_length=50, verbose_name='Label para Botão de Execução da Solicitação'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
    ]
