# Generated by Django 2.2.10 on 2020-06-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0025_auto_20200530_1109'),
        ('catalogo_provedor_servico', '0025_auto_20200526_1959'),
    ]

    operations = [
    ]
