# Generated by Django 2.2.10 on 2020-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0026_merge_20200601_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='dados_registros_execucao',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Dados dos Registros Criados Durante a Execução'),
        ),
    ]
