# Generated by Django 2.2.10 on 2020-07-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo_provedor_servico', '0027_solicitacao_dados_registros_execucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoHistoricoSituacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Status')),
                ('status_detalhamento', djtools.db.models.CharFieldPlus(blank=True, max_length=1000, null=True, verbose_name='Detalhamento do Status')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('responsavel', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Cadastro')),
                ('solicitacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='catalogo_provedor_servico.Solicitacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
