# Generated by Django 2.2.10 on 2020-07-10 14:17

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0032_historico_responsavel_solicitacao_novos_atributos_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='atribuinte',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_atribuinte', to='rh.PessoaFisica', verbose_name='Atribuinte'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_associacao_responsavel',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Associação ao Responsável'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='instrucao',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=100, null=True, verbose_name='Instrução'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável'),
        ),
    ]
