# Generated by Django 2.2.10 on 2020-07-13 02:21

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0034_solicitacao_uo_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
    ]
