# Generated by Django 2.2.10 on 2020-07-13 20:42

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0035_auto_20200713_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaohistoricosituacao',
            name='responsavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica', verbose_name='Responsável'),
        ),
    ]
