# Generated by Django 2.2.16 on 2020-09-15 14:29

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_auto_20200205_1500'),
        ('catalogo_provedor_servico', '0036_auto_20200713_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoequipe',
            name='vinculo',
            field=djtools.db.models.ForeignKeyPlus(default=1, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='vinculo_atribuinte',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_atribuinte', to='comum.Vinculo', verbose_name='Atribuinte'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='vinculo_responsavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='solicitacaohistoricosituacao',
            name='vinculo_responsavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='solicitacaoresponsavelhistorico',
            name='vinculo_atribuinte',
            field=djtools.db.models.ForeignKeyPlus(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_historico_atribuinte', to='comum.Vinculo', verbose_name='Atribuinte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaoresponsavelhistorico',
            name='vinculo_responsavel',
            field=djtools.db.models.ForeignKeyPlus(default=1, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Responsável'),
            preserve_default=False,
        ),
    ]
