# Generated by Django 2.2.16 on 2020-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0039_pessoa_unica_03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='extra_dados',
            field=models.TextField(blank=True, verbose_name='Informação Extra'),
        ),
    ]
