# Generated by Django 2.2.16 on 2020-11-30 20:03

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_auto_20200516_0227'),
        ('comum', '0010_groupdetail'),
        ('catalogo_provedor_servico', '0041_auto_20201104_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoGerenteEquipeLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE,
                                                            to='rh.UnidadeOrganizacional')),
                ('servico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE,
                                                             to='catalogo_provedor_servico.Servico')),
                ('vinculo',
                 djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo')),
            ],
            options={
                'verbose_name': 'Gerente Local do Serviço',
                'verbose_name_plural': 'Gerentes Locais dos Serviços',
            },
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={
                'ordering': ['id_servico_portal_govbr'],
                'permissions': (
                    ('eh_gerente_sistemico_catalogo', 'É Gerente sistemico do catalogo.'),
                    ('eh_gerente_local_catalogo', 'É Gerente local do catalogo.')
                ),
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços'
            },
        ),
    ]
