# Generated by Django 2.2.16 on 2021-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0044_auto_20201216_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='registronotificacaogovbr',
            name='enviada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registronotificacaogovbr',
            name='tipo',
            field=models.IntegerField(choices=[[0, 'SMS'], [1, 'Email'], [2, 'Aplicativo'], [3, 'Email Suap'], [4, 'Ligação Telefônica']], default=1),
            preserve_default=False,
        ),
    ]
