# Generated by Django 2.2.16 on 2021-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0045_auto_20210121_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentogovbr',
            name='tentativas_envio',
            field=models.IntegerField(default=0, verbose_name='Tentativas de Envio'),
        ),
    ]
