# Generated by Django 2.2.16 on 2021-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0046_registroacompanhamentogovbr_tentativas_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroavaliacaogovbr',
            name='tentativas_envio',
            field=models.IntegerField(default=0, verbose_name='Tentativas de Envio'),
        ),
    ]
