# Generated by Django 2.2.16 on 2021-04-26 17:48

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_auto_20210126_1840'),
        ('catalogo_provedor_servico', '0047_registroavaliacaogovbr_tentativas_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoequipe',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional'),
        ),
    ]
