# Generated by Django 2.2.16 on 2021-04-26 17:59

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0049_auto_20210426_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoequipe',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional'),
        ),
    ]
