# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0050_auto_20210426_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacompanhamentogovbr',
            name='payload',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='registronotificacaogovbr',
            name='response_content',
            field=models.JSONField(null=True),
        ),
    ]
