# Generated by Django 3.2.5 on 2021-11-22 17:08

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_provedor_servico', '0052_alter_solicitacao_instrucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registronotificacaogovbr',
            name='data_envio',
            field=djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AddField(
            model_name='registronotificacaogovbr',
            name='mensagem',
            field=models.TextField(null=True, verbose_name='Mensagem'),
        ),
    ]
