# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


import almoxarifado.estoque
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [('financeiro', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20)),
                ('codigo_completo', models.CharField(editable=False, max_length=20, unique=True)),
                ('validade', models.IntegerField(help_text='Em número de dias', null=True)),
                ('sub_elemento_nd', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.SubElementoNaturezaDespesa')),
            ],
            options={
                'permissions': (
                    ('add_categoriamaterialconsumo', 'Can add categoria de material de consumo'),
                    ('change_categoriamaterialconsumo', 'Can change categoria de material de consumo'),
                )
            },
            bases=(models.Model, almoxarifado.estoque.Estocavel),
        ),
        migrations.CreateModel(
            name='CategoriaDescritor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField()),
                ('obrigatorio', models.BooleanField(default=True, help_text='Indica se o descritor é obrigatório para os materiais')),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.Categoria')),
            ],
            options={'ordering': ['categoria', 'ordem']},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_catmat', models.CharField(max_length=20, verbose_name='Código CATMAT')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('especificacao', models.TextField(verbose_name='Especificação')),
                ('valor_medio', djtools.db.models.DecimalFieldPlus(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.Categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['id'],
                'permissions': (('add_materialconsumo', 'Can add de material de consumo'), ('change_materialconsumo', 'Can change de material de consumo')),
            },
            bases=(models.Model, almoxarifado.estoque.Estocavel),
        ),
        migrations.CreateModel(
            name='MaterialCotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('data', djtools.db.models.DateTimeFieldPlus(default=datetime.datetime.now)),
                ('site', models.TextField(blank=True, verbose_name='Site')),
                ('uasg', models.CharField(blank=True, max_length=200, verbose_name='UASG')),
                ('numero_pregao', models.CharField(blank=True, max_length=50, verbose_name='Nº de Pregão')),
                ('numero_item', models.CharField(blank=True, max_length=50, verbose_name='Nº do Item')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/cotacao/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_validade', djtools.db.models.DateFieldPlus(blank=True, null=True)),
                (
                    'fornecedor',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaJuridica', verbose_name='Fornecedor'),
                ),
                ('material', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.Material')),
            ],
            options={'verbose_name': 'Cotação de material', 'verbose_name_plural': 'Cotações de material', 'ordering': ['material', 'valor']},
        ),
        migrations.CreateModel(
            name='MaterialDescritor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('categoria_descritor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.CategoriaDescritor')),
                ('material', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags de materiais'},
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            [1, 'Aguardando Avaliação'],
                            [2, 'Deferido (o material foi cadastrado)'],
                            [3, 'Indeferido (o material já existe no catálogo)'],
                            [4, 'Indeferido (outros motivos)'],
                        ],
                        default=1,
                    ),
                ),
                ('cadastrada_em', models.DateTimeField(auto_now_add=True)),
                (
                    'requerimento',
                    models.TextField(
                        help_text='Informe aqui a DESCRIÇÃO e o código CATMAT.<br/>\n    De preferência, pesquisar através do\n    <a href="http://www.comprasnet.gov.br/">COMPRASNET</a>\n    uma descrição equivalente ao material sugerido, informando junto à descrição\n    o código CATMAT correspondente.\n    '
                    ),
                ),
                ('respondida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resposta', models.TextField(blank=True, help_text='Observações sobre a avaliação desta requisição')),
                (
                    'material',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, help_text='Informe aqui o material referente à resposta', null=True, on_delete=django.db.models.deletion.CASCADE, to='materiais.Material'
                    ),
                ),
                (
                    'usuario_resposta',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_requisicoesrespondidas_set', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'usuario_solicitante',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='materiais_requisicoessolicitadas_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisições'},
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(model_name='material', name='tags', field=models.ManyToManyField(to='materiais.MaterialTag')),
        migrations.AddField(
            model_name='material', name='unidade_medida', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.UnidadeMedida')
        ),
        migrations.AlterUniqueTogether(name='materialdescritor', unique_together=set([('material', 'categoria_descritor')])),
        migrations.AlterUniqueTogether(name='material', unique_together=set([('categoria', 'descricao', 'especificacao', 'unidade_medida')])),
        migrations.AlterUniqueTogether(name='categoriadescritor', unique_together=set([('categoria', 'ordem')])),
        migrations.AlterUniqueTogether(name='categoria', unique_together=set([('sub_elemento_nd', 'descricao'), ('sub_elemento_nd', 'codigo')])),
    ]
