# Generated by Django 2.2.10 on 2020-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('materiais', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={
                'permissions': (
                    ('add_categoriamaterialconsumo', 'Can add categoria de material de consumo'),
                    ('change_categoriamaterialconsumo', 'Can change categoria de material de consumo'),
                ),
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(name='materialtag', options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags de Materiais'}),
        migrations.AlterModelOptions(name='unidademedida', options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida'}),
        migrations.AlterField(model_name='categoria', name='codigo', field=models.CharField(max_length=20, verbose_name='Código')),
        migrations.AlterField(model_name='categoria', name='descricao', field=models.CharField(max_length=255, verbose_name='Descrição')),
        migrations.AlterField(
            model_name='categoria',
            name='sub_elemento_nd',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.SubElementoNaturezaDespesa', verbose_name='Subelemento'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade_medida',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='materiais.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
    ]
