# Generated by Django 2.2.10 on 2020-08-12 17:49

from django.db import migrations


def popular_servidor_remanejamento(apps, schema_editor):
    Inscricao = apps.get_model('remanejamento', 'inscricao')
    EditalRecurso = apps.get_model('remanejamento', 'editalrecurso')
    Servidor = apps.get_model('rh', 'servidor')
    for editalrecurso in EditalRecurso.objects.all():
        editalrecurso.servidor = Servidor.objects.get(pk=editalrecurso.pessoa.pk)
        editalrecurso.save()
    for inscricao in Inscricao.objects.all():
        inscricao.servidor = Servidor.objects.get(pk=inscricao.pessoa.pk)
        inscricao.save()


def despopular_servidor_remanejamento(apps, schema_editor):
    Inscricao = apps.get_model('remanejamento', 'inscricao')
    EditalRecurso = apps.get_model('remanejamento', 'editalrecurso')

    EditalRecurso.objects.all().update(servidor=None)
    Inscricao.objects.all().update(servidor=None)


class Migration(migrations.Migration):

    dependencies = [
        ('remanejamento', '0002_auto_20200812_1748'),
    ]

    operations = [
        migrations.RunPython(popular_servidor_remanejamento, despopular_servidor_remanejamento)
    ]
