# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('remanejamento', '0004_auto_20200812_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, upload_to='remanejamento/anexos/'),
        ),
    ]
