# Generated by Django 2.2.16 on 2021-04-16 12:32

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('remanejamento', '0005_auto_20210301_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalrecurso',
            name='edital',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='remanejamento.Edital', verbose_name='Edital'),
        ),
        migrations.AlterField(
            model_name='editalrecurso',
            name='recurso_respondido',
            field=models.BooleanField(default=False, verbose_name='O recurso foi respondido?'),
        ),
    ]
