# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(unique=True, verbose_name='Descrição')),
                ('valor_hora', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor da Hora')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades', 'ordering': ['descricao']},
        ),
        migrations.CreateModel(
            name='CotaAnualServidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={'verbose_name': 'Cota anual do servidor', 'verbose_name_plural': 'Cotas anuais de servidores'},
        ),
        migrations.CreateModel(
            name='CotaExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_permitida', models.FloatField(verbose_name='Horas Permitidas')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={'verbose_name': 'Cota Extra', 'verbose_name_plural': 'Cotas Extras'},
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('edital', models.FileField(blank=True, upload_to='cursos/editais', verbose_name='Edital')),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'Concurso'], [2, 'Curso'], [3, 'Atividade Externa']], verbose_name='Tipo')),
                (
                    'situacao',
                    models.PositiveIntegerField(
                        choices=[[0, 'Não iniciado'], [1, 'Iniciado'], [2, 'Finalizado'], [3, 'Aguardando cadastro em Folha'], [4, 'Cadastrado em Folha']],
                        default=0,
                        verbose_name='Situação',
                    ),
                ),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('data_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Início do Curso')),
                ('data_cadastrado_folha', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Finalização do Curso')),
                (
                    'ano_pagamento',
                    djtools.db.models.ForeignKeyPlus(
                        help_text='Ano referente ao pagamento das horas trabalhadas neste Curso/Concurso.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='comum.Ano',
                        verbose_name='Ano de Pagamento',
                    ),
                ),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Curso ou Concurso',
                'verbose_name_plural': 'Cursos ou Concursos',
                'permissions': (
                    ('pode_informar_cadastro_em_folha', 'Pode Informar Cadastro em Folha'),
                    ('pode_gerenciar_participantes', 'Pode Gerenciar Participantes'),
                    ('pode_ver_relatorio_pagamento_gecc', 'Pode Ver Relatório de Pagamento GECC'),
                    ('pode_gerenciar_curso_concurso', 'Pode Gerenciar Curso/Concurso'),
                ),
            },
        ),
        migrations.CreateModel(
            name='HorasPermitidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_horas', models.FloatField(unique=True)),
                ('default', models.BooleanField(default=False, verbose_name='Default?')),
            ],
            options={'verbose_name': 'Horas Permitidas', 'verbose_name_plural': 'Horas Permitidas'},
        ),
        migrations.CreateModel(
            name='HorasTrabalhadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'mes_pagamento',
                    models.PositiveIntegerField(
                        choices=[
                            [1, 'Janeiro'],
                            [2, 'Fevereiro'],
                            [3, 'Março'],
                            [4, 'Abril'],
                            [5, 'Maio'],
                            [6, 'Junho'],
                            [7, 'Julho'],
                            [8, 'Agosto'],
                            [9, 'Setembro'],
                            [10, 'Outubro'],
                            [11, 'Novembro'],
                            [12, 'Dezembro'],
                        ],
                        verbose_name='Mês de Pagamento',
                    ),
                ),
                (
                    'atividade_valor_hora',
                    djtools.db.models.DecimalFieldPlus(
                        decimal_places=2, editable=False, help_text='Replicado devido a possibilidade de mudança no valor da hora da atividade relacionada.', max_digits=12
                    ),
                ),
                ('qtd_horas', models.FloatField()),
                ('atividade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='cursos.Atividade')),
                ('cota_anual_servidor', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cursos.CotaAnualServidor')),
                ('curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
            options={'verbose_name': 'Horas Trabalhadas', 'verbose_name_plural': 'Horas Trabalhadas', 'ordering': ('mes_pagamento', 'cota_anual_servidor__vinculo__nome')},
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_pagamento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mês de Pagamento')),
                ('atividade_mes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mês da Atividade')),
                ('horas_prevista', models.FloatField(verbose_name='Horas Previstas de Trabalho')),
                ('horas_trabalhada', models.FloatField(blank=True, null=True, verbose_name='Horas Trabalhadas')),
                ('data_liberacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Liberação')),
                (
                    'situacao',
                    models.PositiveIntegerField(
                        choices=[[0, 'Liberado pela Chefia'], [1, 'Não Liberado pela Chefia'], [2, 'Aguardando Liberação'], [3, 'Pendente']], default=2, verbose_name='Situação'
                    ),
                ),
                ('motivo_nao_liberacao', djtools.db.models.CharFieldPlus(blank=True, max_length=500, null=True, verbose_name='Motivo do Indeferimento')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ano_desconto_carga_horaria', djtools.db.models.PositiveIntegerFieldPlus(blank=True, null=True, verbose_name='Ano de Desconto da Carga Horária')),
                ('atividade', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='cursos.Atividade', verbose_name='Atividade')),
                ('curso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso', verbose_name='Curso ou Concurso')),
                (
                    'responsavel_liberacao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responsavel_liberacao_set',
                        to='rh.Servidor',
                        verbose_name='Responsável pela Liberação',
                    ),
                ),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
            ],
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes', 'permissions': (('pode_ver_seu_relatorio', 'Pode Ver o Próprio Relatório'),)},
        ),
    ]
