# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20190814_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='edital',
            field=djtools.db.models.FileFieldPlus(blank=True, upload_to='cursos/editais', verbose_name='Edital'),
        ),
    ]
