# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egressos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='publicada',
            field=models.BooleanField(null=True, verbose_name='Publicada'),
        ),
    ]
