# Generated by Django 2.2.16 on 2021-04-16 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0017_auto_20210126_1840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comum', '0018_auto_20210401_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoAquisitivoUsofrutoServidorEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField(verbose_name='Período')),
                ('inicio_aquisitivo', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do Aquisitivo')),
                ('final_aquisitivo_teorico', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Final do Aquisitivo teórico')),
                ('qtd_dias_afast_nao_conta_como_efet_exerc', models.PositiveIntegerField(verbose_name='Qud dias de afastamento (não contabiliza efetivo exercício)')),
                ('final_aquisitivo_na_patrica', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Final do Aquisitivo na prática')),
                ('inicio_uso_fruto', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do Usufruto')),
                ('final_uso_fruto', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Final do Usufruto')),
                ('ativo_pelo_edital', models.BooleanField(default=False, verbose_name='Ativo pelo edital (Válido para este edital) ')),
                ('qtd_dias_lc_siape', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de dias cadastradas no SIAPE')),
                ('qtd_dias_lc_suap', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de dias cadastradas no SUAP')),
            ],
            options={
                'verbose_name': 'Cálculo do Período Aquisitivo e Usufruto do Servidor no Edital',
                'verbose_name_plural': 'Cálculo do Período Aquisitivo e Usufruto do Servidor no Edital',
            },
        ),
        migrations.CreateModel(
            name='EditalLicCapacitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('periodo_abrangencia_inicio', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do período de abragência do edital')),
                ('periodo_abrangencia_final', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Final do período de abragência do edital')),
                ('periodo_submissao_inscricao_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início das submissões')),
                ('periodo_submissao_inscricao_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final das submissões')),
                ('periodo_resultado_parcial_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início da publicação do resultado parcial')),
                ('periodo_resultado_parcial_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final da publicação do resultado parcial')),
                ('periodo_recurso_resultado_parcial_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início dos recursos do resultado parcial')),
                ('periodo_recurso_resultado_parcial_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final dos recursos do resultado parcial')),
                ('periodo_desistencia_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início das desistências')),
                ('periodo_desistencia_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final das desistências')),
                ('periodo_resultado_final_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início da publicação do resultado final')),
                ('periodo_resultado_final_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final da publicação do resultado final')),
                ('periodo_submissao_segunda_etapa_inicio', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Início da submissão dos dados finais')),
                ('periodo_submissao_segunda_etapa_final', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Final da submissão dos dados finais')),
                ('qtd_max_periodos_por_pedido', models.PositiveIntegerField(default=1, verbose_name='Quantidade de máxima de parcelas em um pedido')),
                ('total_taes_em_exercicio', models.PositiveIntegerField(default=0, verbose_name='Total de Taes em Exercício')),
                ('total_docentes_em_exercicio', models.PositiveIntegerField(default=0, verbose_name='Total de Docentes em Exercício')),
                ('total_geral_em_exercicio', models.PositiveIntegerField(default=0, verbose_name='Total de Geral em Exercício')),
                ('percentual_limite_servidores_em_lic_capacitacao', djtools.db.models.DecimalFieldPlus(decimal_places=2, default=5, max_digits=6, verbose_name='Percentual limite de servidores em licença capacitação')),
                ('qtd_limite_servidores_em_lic_capacitacao_por_dia', models.PositiveIntegerField(default=0, verbose_name='Quantidade limite de servidores em licença capacitação por dia')),
                ('qtd_limite_taes_em_lic_capacitacao_por_dia', models.PositiveIntegerField(default=0, verbose_name='Quantidade limite de técnicos administrativos em licença capacitação por dia')),
                ('qtd_limite_docentes_em_lic_capacitacao_por_dia', models.PositiveIntegerField(default=0, verbose_name='Quantidade limite de docentes em licença capacitação por dia')),
                ('processamento_externo', models.BooleanField(default=False, verbose_name='Este edital terá seu resultado (parcial e final) processado em estrutura externa.')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Edital de Licença para Capacitação',
                'verbose_name_plural': 'Editais de Licença para Capacitação',
            },
        ),
        migrations.CreateModel(
            name='LicCapacitacaoPorDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('dia', models.IntegerField(verbose_name='Dia')),
                ('data', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data')),
                ('qtd_docentes', models.IntegerField(default=0, verbose_name='Docente')),
                ('qtd_taes', models.IntegerField(default=0, verbose_name='Técnico-administrativo')),
                ('qtd_total', models.IntegerField(default=0, verbose_name='Total')),
                ('qtd_docentes_suap', models.IntegerField(default=0, verbose_name='Docente')),
                ('qtd_taes_suap', models.IntegerField(default=0, verbose_name='Técnico-administrativo')),
                ('qtd_total_suap', models.IntegerField(default=0, verbose_name='Total')),
                ('qtd_docentes_geral', models.IntegerField(default=0, verbose_name='Docente')),
                ('qtd_taes_geral', models.IntegerField(default=0, verbose_name='Técnico-administrativo')),
                ('qtd_total_geral', models.IntegerField(default=0, verbose_name='Total')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Licença capacitação por dia',
                'verbose_name_plural': 'Licenças capacitação por dia',
                'unique_together': {('ano', 'mes', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='MotivoLicencaCapacitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Motivo para licença capacitação',
                'verbose_name_plural': 'Motivos para licença capacitação',
            },
        ),
        migrations.CreateModel(
            name='PedidoLicCapacitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'PENDENTE DE SUBMISSÃO'], [2, 'SUBMETIDO'], [3, 'CANCELADO']], default=1, editable=False, verbose_name='Situação da Submissão')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, null=True, verbose_name='Data de cadastro')),
                ('data_ultima_submissao', djtools.db.models.DateTimeFieldPlus(blank=True, editable=False, null=True, verbose_name='Data da última Submissão')),
                ('data_ultimo_cancelamento', djtools.db.models.DateTimeFieldPlus(blank=True, editable=False, null=True, verbose_name='Data do último Cancelamento')),
                ('modalidade', models.PositiveIntegerField(choices=[[1, 'PRESENCIAL'], [2, 'A DISTÂNCIA']], verbose_name='Modalidade')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga horária total (horas)')),
                ('instituicao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Instituição/Local')),
                ('acao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Curso/Ação')),
                ('outros_detalhes', models.TextField(blank=True, null=True, verbose_name='Outros detalhes')),
                ('observacao_desistencia', models.TextField(blank=True, null=True, verbose_name='Observação da desistência')),
                ('desistencia', models.BooleanField(default=False, verbose_name='Desistência')),
                ('aprovado_resultado_parcial', models.NullBooleanField(verbose_name='Aprovado no Resultado Parcial')),
                ('justificativa_nao_aprovacao_resultado_parcial', models.TextField(blank=True, null=True, verbose_name='Justificativa de não aprovação no Resultado Parcial')),
                ('ordem_classificacao_resultado_parcial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Parcial')),
                ('ordem_classificacao_resultado_parcial_gestao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Parcial (gestão)')),
                ('aprovado_resultado_final', models.NullBooleanField(verbose_name='Aprovado no Resultado Final')),
                ('justificativa_nao_aprovacao_resultado_final', models.TextField(blank=True, null=True, verbose_name='Justificativa de não aprovação no Resultado Final')),
                ('ordem_classificacao_resultado_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Final')),
                ('ordem_classificacao_resultado_final_gestao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Final (gestão)')),
                ('cadastrado_no_siape', models.NullBooleanField(default=False, verbose_name='Sincronizado com o SIAPE')),
                ('aprovado_em_definitivo', models.BooleanField(default=False, verbose_name='Aprovado de forma definitiva')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital')),
                ('motivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.MotivoLicencaCapacitacao', verbose_name='Motivo da licença capacitação')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
                ('usuario_cadastro_desistencia', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário cadastro desistência')),
            ],
            options={
                'verbose_name': 'Submissão de Pedido de Licença para Capacitação',
                'verbose_name_plural': 'Submissões de Pedido de Licença para Capacitação',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoDataInicioExercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de cadastro da solicitação')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'DEFERIDA'], [2, 'INDEFERIDA']], null=True, verbose_name='Situação')),
                ('pode_analisar', models.BooleanField(default=False, verbose_name='Pode analisar')),
                ('justificativa', models.TextField(verbose_name='Justificativa da solicitação')),
                ('data_suap', djtools.db.models.DateFieldPlus(verbose_name='Data obtida no SUAP pelo módulo de licença capacitação')),
                ('data_solicitada', djtools.db.models.DateFieldPlus(verbose_name='Data solicitada')),
                ('parecer_gestao', models.TextField(blank=True, null=True, verbose_name='Parecer/observações da gestão')),
                ('data_hora_parecer', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data/hora do parecer')),
                ('data_informada_parecer', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de início de exercício informada pela gestão')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
                ('usuario_parecer', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do parecer')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Data de início de exercício',
                'verbose_name_plural': 'Solicitações de Alteração de Data de início de exercício',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de cadastro da solicitação')),
                ('situacao', models.PositiveIntegerField(choices=[[1, 'DEFERIDA'], [2, 'INDEFERIDA']], null=True, verbose_name='Situação')),
                ('pode_analisar', models.BooleanField(default=False, verbose_name='Pode analisar')),
                ('justificativa', models.TextField(verbose_name='Justificativa da solicitação')),
                ('parecer_gestao', models.TextField(blank=True, null=True, verbose_name='Parecer/observações da gestão')),
                ('data_hora_parecer', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data/hora do parecer')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
                ('usuario_parecer', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do parecer')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Dados',
                'verbose_name_plural': 'Solicitações de Alteração de Dados',
            },
        ),
        migrations.CreateModel(
            name='ServidorDataInicioExercicioAjustada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_ajuste', djtools.db.models.DateFieldPlus(editable=False, verbose_name='Data do ajuste')),
                ('data_inicio_exercicio', djtools.db.models.DateFieldPlus(editable=False, verbose_name='Data de início de exercício')),
                ('servidor', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
                ('usuario_ajuste', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável pelo ajuste')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Data de início de exercício',
                'verbose_name_plural': 'Solicitações de Alteração de Data de início de exercício',
            },
        ),
        migrations.CreateModel(
            name='QuadroPedidosTemporario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.PedidoLicCapacitacao', verbose_name='Pedido')),
                ('quadro', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.LicCapacitacaoPorDia', verbose_name='Quadro original')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessamentoEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Processamento finalizado')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do cancelamento')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Processamento cancelado')),
                ('definitivo', models.BooleanField(default=False, verbose_name='Definitivo?')),
                ('titulo', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('data_hora_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data/hora de cadastro')),
                ('data_hora_finalizacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data/hora de finalização')),
                ('tipo_processamento', models.PositiveIntegerField(choices=[[1, 'RESULTADO PARCIAL'], [2, 'RESULTADO FINAL']], editable=False, verbose_name='Tipo de processamento')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoPedidoLicCapacitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data início')),
                ('data_termino', djtools.db.models.DateFieldPlus(verbose_name='Data Final')),
                ('qtd_dias_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de dias desta parcela')),
                ('aquisitivo_uso_fruto', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.CalculoAquisitivoUsofrutoServidorEdital', verbose_name='Aquisitivo/Uso fruto')),
                ('pedido', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.PedidoLicCapacitacao', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Parcela do Pedido',
                'verbose_name_plural': 'Parcelas do Pedido',
            },
        ),
        migrations.CreateModel(
            name='DadosProcessamentoEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_exercicio', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do exercício')),
                ('qtd_dias_total_licenca_capacitacao_utilizada', models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias de licença capacitação já concedidas')),
                ('periodo_aquisitivo_proximo_do_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Período aquisitivo mais próximo do fim (data final)')),
                ('qtd_dias_efetivo_exercicio', models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias de efetivo exercício')),
                ('qtd_dias_afastamento_capacitacao', models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias de afastamento capacitação')),
                ('qtd_dias_afast_nao_conta_como_efet_exerc', models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias que não contabilizam como efetivo exercício')),
                ('idade_servidor_inicio_abrangencia_edital', models.PositiveIntegerField(default=0, verbose_name='Idade do servidor (no início da abrangência do edital)')),
                ('aprovado_resultado_parcial', models.NullBooleanField(verbose_name='Aprovado no Resultado Parcial')),
                ('justificativa_nao_aprovacao_resultado_parcial', models.TextField(blank=True, null=True, verbose_name='Justificativa de não aprovação no Resultado Parcial')),
                ('ordem_classificacao_resultado_parcial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Parcial')),
                ('ordem_classificacao_resultado_parcial_gestao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Parcial (gestão)')),
                ('aprovado_resultado_final', models.NullBooleanField(verbose_name='Aprovado no Resultado Final')),
                ('justificativa_nao_aprovacao_resultado_final', models.TextField(blank=True, null=True, verbose_name='Justificativa de não aprovação no Resultado Final')),
                ('ordem_classificacao_resultado_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Final')),
                ('ordem_classificacao_resultado_final_gestao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de classificação no Resultado Final (gestão)')),
                ('empatado', models.NullBooleanField(verbose_name='Empatado')),
                ('pedido', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.PedidoLicCapacitacao', verbose_name='Pedido')),
                ('processamento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.ProcessamentoEdital', verbose_name='Processamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculosGeraisServidorEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_exercicio', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Início do exercício')),
                ('qtd_dias_exercicio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd de dias de exercício')),
                ('qtd_dias_afast_nao_conta_como_efet_exerc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd de dias de afastamento (apenas que o não contabilizam como efetivo exercício)')),
                ('qtd_dias_efet_exercicio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd de dias de efetivo exercício')),
                ('qtd_dias_afast_capacitacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd de dias de afastamento capacitação')),
                ('idade_servidor_inicio_abrangencia_edital', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade do servidor no dia do início da abrangência do edital')),
                ('parametro_inicio_exercicio', models.PositiveIntegerField(choices=[[1, 'INÍCIO NO SERVIÇO PÚBLICO'], [2, 'INÍCIO DO EXERCÍCIO NA INSTITUIÇÃO'], [3, 'SOLICITADA PELO SERVIDOR'], [4, 'AJUSTADA PELA GESTÃO']], default=1, editable=False, verbose_name='Parâmetro utilizado para obter o início do exercício do servidor')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Cálculo do Exercício do Servidor no Edital',
                'verbose_name_plural': 'Cálculo do Exercício do Servidor no Edital',
            },
        ),
        migrations.AddField(
            model_name='calculoaquisitivousofrutoservidoredital',
            name='edital',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Edital'),
        ),
        migrations.AddField(
            model_name='calculoaquisitivousofrutoservidoredital',
            name='servidor',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor'),
        ),
        migrations.CreateModel(
            name='AnexosPedidoLicCapacitacaoSubmissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/lic_capacitacao/anexos/')),
                ('pedido', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.PedidoLicCapacitacao', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Anexo do Pedido',
                'verbose_name_plural': 'Anexos do Pedido',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='AnexosEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='upload/lic_capacitacao/anexos/', verbose_name='Arquivo')),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'GERAL'], [2, 'RESULTADO PARCIAL'], [3, 'RESULTADO FINAL']], default=1, verbose_name='Tipo do arquivo')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de cadastro')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.EditalLicCapacitacao', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Anexo do Edital',
                'verbose_name_plural': 'Anexos do Edital',
                'ordering': ['data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='CadastroDesistencia',
            fields=[
            ],
            options={
                'verbose_name': 'Cadastro de Desistência',
                'verbose_name_plural': 'Cadastro de Desistência',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licenca_capacitacao.pedidoliccapacitacao',),
        ),
        migrations.CreateModel(
            name='PedidoLicCapacitacaoServidor',
            fields=[
            ],
            options={
                'verbose_name': 'Submissão de Pedido de Licença para Capacitação',
                'verbose_name_plural': 'Submissões de Pedido de Licença para Capacitação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licenca_capacitacao.pedidoliccapacitacao',),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoDadosAdicionar',
            fields=[
            ],
            options={
                'verbose_name': 'Adicionar Solicitação de Alteração de Dados',
                'verbose_name_plural': 'Adicionar Solicitações de Alteração de Dados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licenca_capacitacao.solicitacaoalteracaodados',),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoDataInicioExercicioAdicionar',
            fields=[
            ],
            options={
                'verbose_name': 'Adicionar Solicitação de Alteração de Data de início de exercício',
                'verbose_name_plural': 'Adicionar Solicitações de Alteração de Data de início de exercício',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licenca_capacitacao.solicitacaoalteracaodatainicioexercicio',),
        ),
    ]
