# Generated by Django 2.2.16 on 2021-04-16 12:14

from django.db import migrations

import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosedital',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(max_length=400, upload_to='upload/lic_capacitacao/anexos/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexospedidoliccapacitacaosubmissao',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=400, null=True, upload_to='upload/lic_capacitacao/anexos/', verbose_name='Arquivo'),
        ),
    ]
