# Generated by Django 2.2.16 on 2021-04-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0003_auto_20210419_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editalliccapacitacao',
            options={'ordering': ['-id'], 'verbose_name': 'Edital de Licença para Capacitação', 'verbose_name_plural': 'Editais de Licença para Capacitação'},
        ),
    ]
