# Generated by Django 2.2.16 on 2021-05-10 14:49

from django.db import migrations


def processar_quadro(apps, schema):
    # call_command('processar_quantitativo_lic_capacitacao')
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0004_auto_20210429_1546'),
    ]

    operations = [migrations.RunPython(processar_quadro)]
