# Generated by Django 2.2.16 on 2021-05-13 16:30

from django.db import migrations

import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0007_auto_20210513_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoliccapacitacao',
            name='data_parecer_desistencia',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data do Parecer da desistência'),
        ),
    ]
