# Generated by Django 2.2.16 on 2021-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0008_pedidoliccapacitacao_data_parecer_desistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='parecer_desistencia',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer da desistência'),
        ),
    ]
