# Generated by Django 2.2.16 on 2021-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_auto_20210512_1917'),
        ('licenca_capacitacao', '0010_servidorcomplementar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoliccapacitacao',
            name='eh_docente',
            field=models.NullBooleanField(default=False, verbose_name='DOCENTE'),
        ),
        migrations.AddField(
            model_name='pedidoliccapacitacao',
            name='eh_tecnico_administrativo',
            field=models.NullBooleanField(default=False, verbose_name='TAE'),
        ),
        migrations.AlterUniqueTogether(
            name='servidorcomplementar',
            unique_together={('edital', 'servidor')},
        ),
    ]
