# Generated by Django 2.2.16 on 2021-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0012_calculosgeraisservidoredital_categoria_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='editalliccapacitacao',
            name='bloqueia_pedido_servidor_nao_apto',
            field=models.BooleanField(default=False, verbose_name='Bloquear pedido de servidor em Não Efetivo Exercício.'),
        ),
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='cadastrado_no_siape',
            field=models.BooleanField(default=False, verbose_name='Sincronizado com o SIAPE'),
        ),
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='eh_docente',
            field=models.BooleanField(default=False, verbose_name='DOCENTE'),
        ),
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='eh_tecnico_administrativo',
            field=models.BooleanField(default=False, verbose_name='TAE'),
        ),
    ]
