# Generated by Django 2.2.16 on 2021-05-28 11:40

import django.db.models.deletion
from django.db import migrations

import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_auto_20210512_1917'),
        ('licenca_capacitacao', '0014_auto_20210519_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidordatainicioexercicioajustada',
            options={'verbose_name': 'Ajuste de data de início de exercício', 'verbose_name_plural': 'Ajustes de data de início de exercício'},
        ),
        migrations.AddField(
            model_name='servidordatainicioexercicioajustada',
            name='solicitacao_alteracao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenca_capacitacao.SolicitacaoAlteracaoDataInicioExercicio', verbose_name='Solicitação de alteração'),
        ),
        migrations.AlterField(
            model_name='servidordatainicioexercicioajustada',
            name='data_inicio_exercicio',
            field=djtools.db.models.DateFieldPlus(verbose_name='Data de início de exercício ajustada'),
        ),
        migrations.AlterField(
            model_name='servidordatainicioexercicioajustada',
            name='servidor',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor'),
        ),
        migrations.AlterUniqueTogether(
            name='servidordatainicioexercicioajustada',
            unique_together={('servidor',)},
        ),
    ]
