# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca_capacitacao', '0016_auto_20210607_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosprocessamentoedital',
            name='aprovado_resultado_final',
            field=models.BooleanField(null=True, verbose_name='Aprovado no Resultado Final'),
        ),
        migrations.AlterField(
            model_name='dadosprocessamentoedital',
            name='aprovado_resultado_parcial',
            field=models.BooleanField(null=True, verbose_name='Aprovado no Resultado Parcial'),
        ),
        migrations.AlterField(
            model_name='dadosprocessamentoedital',
            name='empatado',
            field=models.BooleanField(null=True, verbose_name='Empatado'),
        ),
        migrations.AlterField(
            model_name='dadosprocessamentoedital',
            name='tem_erro_checklist',
            field=models.BooleanField(null=True, verbose_name='Erro no checklist'),
        ),
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='aprovado_resultado_final',
            field=models.BooleanField(null=True, verbose_name='Aprovado no Resultado Final'),
        ),
        migrations.AlterField(
            model_name='pedidoliccapacitacao',
            name='aprovado_resultado_parcial',
            field=models.BooleanField(null=True, verbose_name='Aprovado no Resultado Parcial'),
        ),
    ]
