# Generated by Django 3.2.5 on 2021-12-07 16:45

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_merge_20211028_1549'),
        ('licenca_capacitacao', '0017_auto_20210719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='editalliccapacitacao',
            name='codigos_afastamento',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='rh.AfastamentoSiape', verbose_name='Códigos de Afastamento Capacitação'),
        ),
    ]
