# Generated by Django 3.2.5 on 2021-12-07 19:04

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_merge_20211028_1549'),
        ('licenca_capacitacao', '0020_auto_20211207_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigolicencacapacitacao',
            old_name='codigo_licenca_capacitacao',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='editalliccapacitacao',
            name='codigos_afastamento',
        ),
        migrations.CreateModel(
            name='SituacaoContabilizaExercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.situacao', verbose_name='Situação que contabiliza como efetivo exercício')),
            ],
            options={
                'verbose_name': 'Situação que contabiliza como efetivo exercício',
                'verbose_name_plural': 'Situações que contabilizam como efetivo exercício',
            },
        ),
        migrations.CreateModel(
            name='CodigoAfastamentoNaoContabilizaExercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.afastamentosiape', verbose_name='Código de afastamentos que não contabilizam como efetivo exercício')),
            ],
            options={
                'verbose_name': 'Código de afastamentos que não contabilizam como efetivo exercício',
                'verbose_name_plural': 'Códigos de afastamentos que não contabilizam como efetivo exercício',
            },
        ),
        migrations.CreateModel(
            name='CodigoAfastamentoCapacitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.afastamentosiape', verbose_name='Código de Afastamento Capacitação')),
            ],
            options={
                'verbose_name': 'Código de Afastamento Capacitação',
                'verbose_name_plural': 'Códigos de Afastamento Capacitação',
            },
        ),
    ]
