# Generated by Django 3.2.5 on 2022-04-05 21:15

from django.db import migrations
import djtools.unaccent_field


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='interessado_nome',
            field=djtools.unaccent_field.UnaccentField(db_index=False, max_length=200, verbose_name='Nome do Interessado'),
        ),
    ]
