# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='arquivo_nf_pecas',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/notas_fiscais/'),
        ),
        migrations.AlterField(
            model_name='manutencaoviatura',
            name='arquivo_nf_servicos',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/notas_fiscais/'),
        ),
        migrations.AlterField(
            model_name='maquinaordemabastecimento',
            name='arquivo_nf',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/ordens_abastecimento/', verbose_name='Arquivo da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='motoristatemporario',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/portarias/'),
        ),
        migrations.AlterField(
            model_name='viagemagendamento',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/comprovante_agendamento/', verbose_name='Documento de Comprovação'),
        ),
        migrations.AlterField(
            model_name='viaturaordemabastecimento',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/frota/nota_fiscal/'),
        ),
    ]
