# Generated by Django 3.2.5 on 2022-05-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_auto_20210301_1709'),
    ]
    state_operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='motorista',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
