# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=255)),
                ('concurso', models.CharField(max_length=255, verbose_name='Concurso')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('turno', models.CharField(max_length=255, null=True, verbose_name='Turno')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('cpf', models.CharField(max_length=250, verbose_name='CPF do Candidato')),
                ('candidato', models.CharField(max_length=255, verbose_name='Nome do Candidato')),
                ('nivel', models.CharField(max_length=255, null=True, verbose_name='Nível')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('uo', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
            ],
            options={'verbose_name': 'Inscrições', 'verbose_name_plural': 'Inscrição'},
        ),
        migrations.CreateModel(
            name='OfertaVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=255)),
                ('concurso', models.CharField(max_length=255, verbose_name='Concurso')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('turno', models.CharField(max_length=255, null=True, verbose_name='Turno')),
                ('qtd', models.IntegerField(default=0, null=True, verbose_name='Quantidade')),
                ('ano', models.IntegerField(default=2011)),
                ('semestre', models.IntegerField()),
                ('uo', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
            ],
            options={'verbose_name': 'Oferta de Vaga', 'verbose_name_plural': 'Ofertas de Vagas'},
        ),
    ]
