# Generated by Django 3.2.5 on 2022-07-31 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processo_seletivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0040_merge_20220722_1505'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='candidato_vaga',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.candidatovaga', verbose_name='Candidato Vaga'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cartorio',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.cartorio', verbose_name='Cartório'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade_profissional',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_cidade_profissional_set', to='edu.cidade', verbose_name='Cidade Profissional'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='convenio',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.convenio', verbose_name='Convênio'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_campus',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.cursocampus', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado_emissao_carteira_reservista',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_emissor_carteira_reservista_set', to='edu.estado', verbose_name='Estado Emissor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_ingresso',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.formaingresso', verbose_name='Forma de Ingresso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='habilitacao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.habilitacao', verbose_name='Habilitação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='linha_pesquisa',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.linhapesquisa', verbose_name='Linha de Pesquisa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matriz',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.matriz', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Cidade em que o aluno nasceu. Obrigatório para brasileiros', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_naturalidade_set', to='edu.cidade', verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nivel_ensino_anterior',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.nivelensino'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='orgao_emissao_rg',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.orgaoemissorrg', verbose_name='Orgão Emissor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pais_origem',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Obrigatório para estrangeiros', null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.pais', verbose_name='País de Origem'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_edu_set', to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='polo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.polo', verbose_name='Polo EAD'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.situacaomatricula', verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turno',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.turno', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf_emissao_rg',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_emissor_rg_set', to='edu.estado', verbose_name='Estado Emissor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf_emissao_titulo_eleitor',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_emissor_titulo_eleitor_set', to='edu.estado', verbose_name='Estado Emissor'),
        ),
        migrations.AddField(
            model_name='abonofaltas',
            name='aluno',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.aluno'),
        ),
        migrations.AddField(
            model_name='abonofaltas',
            name='responsavel_abono',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Abono'),
        ),
        migrations.CreateModel(
            name='MensagemEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'Mensagem Recebida',
                'verbose_name_plural': 'Mensagens Recebidas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('edu.mensagem',),
        ),
        migrations.CreateModel(
            name='MensagemSaida',
            fields=[
            ],
            options={
                'verbose_name': 'Mensagem Enviada',
                'verbose_name_plural': 'Mensagens Enviadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('edu.mensagem',),
        ),
        migrations.CreateModel(
            name='Minicurso',
            fields=[
            ],
            options={
                'verbose_name': 'Curso FIC < 160h',
                'verbose_name_plural': 'Cursos FIC < 160h',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('edu.cursocampus',),
        ),
        migrations.AddField(
            model_name='turmaminicurso',
            name='minicurso',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.minicurso'),
        ),
        migrations.AddField(
            model_name='solicitacaorelancamentoetapa',
            name='professor_diario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.professordiario'),
        ),
        migrations.AddField(
            model_name='solicitacaoprorrogacaoetapa',
            name='professor_diario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.professordiario'),
        ),
        migrations.AddField(
            model_name='requerimentocancelamentodisciplina',
            name='matriculas_diario',
            field=models.ManyToManyField(to='edu.MatriculaDiario', verbose_name='Matrículas em Diário'),
        ),
        migrations.AddField(
            model_name='periodoletivoatualpolo',
            name='polo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.polo', verbose_name='Polo'),
        ),
        migrations.AlterUniqueTogether(
            name='matrizcurso',
            unique_together={('matriz', 'curso_campus')},
        ),
        migrations.AlterUniqueTogether(
            name='matriculaperiodo',
            unique_together={('ano_letivo', 'periodo_letivo', 'aluno')},
        ),
        migrations.AddIndex(
            model_name='matriculadiario',
            index=models.Index(fields=['matricula_periodo'], name='edu_matricu_matricu_434ca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemconfiguracaoatividadecomplementar',
            unique_together={('configuracao', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='falta',
            unique_together={('matricula_diario', 'aula')},
        ),
        migrations.AddField(
            model_name='conteudominicurso',
            name='minicurso',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.minicurso'),
        ),
        migrations.AlterUniqueTogether(
            name='componentecurricular',
            unique_together={('matriz', 'componente')},
        ),
    ]
