# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('edu', '0003_auto_20221211_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='examinador_interno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_interno_set', to='rh.pessoafisica', verbose_name='Examinador Interno'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='examinador_externo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinador_externo_set', to='rh.pessoafisica', verbose_name='Segundo Examinador'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='terceiro_examinador',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_examinador_set', to='rh.pessoafisica', verbose_name='Terceiro Examinador'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='suplente_interno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_interno_set', to='rh.pessoafisica', verbose_name='Suplente Interno'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='suplente_externo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplente_externo_set', to='rh.pessoafisica', verbose_name='Segundo Suplente'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='terceiro_suplente',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceiro_suplente_set', to='rh.pessoafisica', verbose_name='Terceiro Suplente'),
        ),
        migrations.AlterField(
            model_name='ProjetoFinal',
            name='coorientadores',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='coorientadores_set', to='rh.PessoaFisica', verbose_name='Coorientadores'),
        ),
        migrations.AlterField(
            model_name='AssinaturaAtaEletronica',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='Professor',
            name='pessoa_fisica_remover',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='RegistroEmissaoDiploma',
            name='dirigente_maximo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red1_set', to='rh.pessoafisica', verbose_name='Dirigente Máximo'),
        ),
        migrations.AlterField(
            model_name='RegistroEmissaoDiploma',
            name='responsavel_emissao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red2_set', to='rh.pessoafisica', verbose_name='Responsável pela Emissão'),
        ),
        migrations.AlterField(
            model_name='RegistroEmissaoDiploma',
            name='responsavel_registro',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red3_set', to='rh.pessoafisica', verbose_name='Responsável pelo Registro'),
        ),
        migrations.AlterField(
            model_name='Evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participantes_set', through='edu.ParticipanteEvento', to='rh.PessoaFisica'),
        ),
        migrations.AlterField(
            model_name='ParticipanteEvento',
            name='participante',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoafisica', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='Aluno',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_edu_set', to='rh.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='PlanoEnsino',
            name='coordenador_curso',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario', verbose_name='Coordenador do Curso'),
        ),
        migrations.AlterField(
            model_name='TutorPolo',
            name='funcionario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='CoordenadorPolo',
            name='funcionario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='Diretoria',
            name='diretor_geral',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretorgeral_set', to='rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='Diretoria',
            name='diretor_geral_exercicio',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretorgeralexercicio_set', to='rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='Diretoria',
            name='diretor_academico',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretoracademico_set', to='rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='Diretoria',
            name='diretor_academico_exercicio',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diretoracademicoexercicio_set', to='rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='CursoCampus',
            name='coordenador',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='CursoCampus',
            name='coordenador_2',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursocampus_vicecoordenador_set', to='rh.funcionario', verbose_name='Vice-Coordenador'),
        ),
        migrations.AlterField(
            model_name='AssinaturaEletronica',
            name='diretor_geral',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario', verbose_name='Diretor Geral'),
        ),
        migrations.AlterField(
            model_name='AssinaturaEletronica',
            name='diretor_academico',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_diretoracademico', to='rh.funcionario', verbose_name='Diretor Acadêmico'),
        ),
        migrations.AlterField(
            model_name='AssinaturaEletronica',
            name='diretor_ensino',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_diretorensino', to='rh.funcionario', verbose_name='Diretor de Ensino'),
        ),
        migrations.AlterField(
            model_name='AssinaturaDigital',
            name='diretor_geral',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario', verbose_name='Diretor Geral'),
        ),
        migrations.AlterField(
            model_name='AssinaturaDigital',
            name='diretor_academico',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais_diretoracademico', to='rh.funcionario', verbose_name='Diretor Acadêmico'),
        ),
        migrations.AlterField(
            model_name='AssinaturaDigital',
            name='diretor_ensino',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_digitais_diretorensino', to='rh.funcionario', verbose_name='Diretor de Ensino'),
        ),
        migrations.AlterField(
            model_name='ConfiguracaoCertificadoENEM',
            name='responsaveis',
            field=djtools.db.models.ManyToManyFieldPlus(to='rh.Funcionario', verbose_name='Responsáveis pela Certificação'),
        ),
    ]
