# Generated by Django 3.2.5 on 2024-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20240903_1110'),
        ('edu', '0005_auto_20240903_1139'),
        ('edu', '0005_auto_20240903_1422'),
    ]

    operations = [
    ]
