# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('encceja', '0001_initial'), ('processo_eletronico', '0001_initial'), ('rh', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_eletronico.Processo', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='area_conhecimento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='encceja.AreaConhecimento', verbose_name='Área do Conhecimento'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='encceja.Avaliacao', verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='solicitacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='encceja.Solicitacao', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='ano',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encceja_set', to='comum.Ano', verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ano',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='encceja_ano_set', to='comum.Ano', verbose_name='Ano'),
        ),
    ]
