# Generated by Django 2.2.10 on 2020-07-09 13:56

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('encceja', '0003_auto_20191209_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='avaliacao_redacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='encceja.Avaliacao', verbose_name='Avaliação da Redação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
