# Generated by Django 3.2.5 on 2021-12-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encceja', '0005_auto_20210421_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='aproveitamento_de_notas_outras_edicoes',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aproveitamento de notas de outras edições?'),
        ),
    ]
