# Generated by Django 3.2.5 on 2021-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_titular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacaocppd',
            name='avaliacao_desempenho_status',
            field=models.IntegerField(choices=[[1, 'Validado'], [2, 'Data errada'], [3, 'Documentação não autenticada'], [4, 'Documentação não condiz com o exigido']], null=True, verbose_name='Situação da Avaliações de Desempenho'),
        ),
        migrations.AddField(
            model_name='validacaocppd',
            name='graduacao_ebtt_status',
            field=models.IntegerField(choices=[[1, 'Validado'], [2, 'Data errada'], [3, 'Documentação não autenticada'], [4, 'Documentação não condiz com o exigido']], null=True, verbose_name='Situação da Graduação EBTT'),
        ),
        migrations.AddField(
            model_name='validacaocppd',
            name='progressao_status',
            field=models.IntegerField(choices=[[1, 'Validado'], [2, 'Data errada'], [3, 'Documentação não autenticada'], [4, 'Documentação não condiz com o exigido']], null=True, verbose_name='Situação da Progressão'),
        ),
        migrations.AddField(
            model_name='validacaocppd',
            name='titulacao_status',
            field=models.IntegerField(choices=[[1, 'Validado'], [2, 'Data errada'], [3, 'Documentação não autenticada'], [4, 'Documentação não condiz com o exigido']], null=True, verbose_name='Situação da Titulação'),
        ),
    ]
