# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('edu', '0002_auto_20190814_1454')]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAcessoDreamspark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Padrão', max_length=255)),
                ('tipo', models.IntegerField(choices=[[1, 'Liberação'], [2, 'Restrição']], default=1, verbose_name='Tipo')),
                ('cursos', djtools.db.models.ManyToManyFieldPlus(to='edu.CursoCampus')),
            ],
            options={'verbose_name': 'Configuração de Acesso ao Dreamspark', 'verbose_name_plural': 'Configurações de Acesso ao Dreamspark'},
        )
    ]
