version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - suap-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - suap-network
    volumes:
      - ./nginx/suapdevs.conf:/etc/nginx/conf.d/suapdevs.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - suap-network
volumes:
  postgres: {}
networks:
  suap-network: {}
