# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('processo_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Processo',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(to='rh.Pessoa'),
        ),
        migrations.AlterField(
            model_name='Processo',
            name='pessoas_acompanhando_processo',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, related_name='pessoas_acompanhando_processo', to='rh.Pessoa', verbose_name='Usuários Que Marcaram o Processo como Interesse'),
        ),
        migrations.AlterField(
            model_name='ComentarioProcesso',
            name='pessoa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='Tramite',
            name='pessoa_recebimento',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_recebidos', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='Tramite',
            name='remetente_pessoa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_remetente', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='Tramite',
            name='destinatario_pessoa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_destinatario', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoCiencia',
            name='cancelada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaociencia_cancelada_por', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoDespacho',
            name='destinatario_pessoa_tramite',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_pessoa_tramite', to='rh.pessoa', verbose_name='Pessoa de Destino de Trâmite'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoDespacho',
            name='remetente_pessoa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaodespacho_remetente_pessoa', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='DocumentoDigitalizadoRequerimento',
            name='compartilhamento_pessoa',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, to='rh.Pessoa', verbose_name='Compartilhamento com pessoas'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoJuntada',
            name='solicitado',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaojuntada_solicitado_a', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoJuntada',
            name='cancelada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaojuntada_cancelada_por', to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoProcessoEletronicoSetorPessoa',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentoprocessoeletronicosetorpessoa_pessoa_permitida_set', to='rh.pessoa', verbose_name='Pessoa Colaboradora'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoProcessoEletronicoPoderDeChefe',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentoprocessoeletronicopoderchefe_pessoa_permitida_set', to='rh.pessoa', verbose_name='Pessoa com Poder de Chefe'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoProcessoEletronicoLog',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentoprocessoeletronicolog_pessoa_permitida_set', to='rh.pessoa', verbose_name='Pessoa com Poder de Chefe'),
        ),
        migrations.AlterField(
            model_name='Tramite',
            name='atribuido_para',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramite_pe_atribuido_para', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='Tramite',
            name='atribuido_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramite_pe_atribuido_por', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoCiencia',
            name='solicitado',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaociencia_solicitado_a', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoDespacho',
            name='solicitado',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaodespacho_solicitado_a', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoJuntadaDocumento',
            name='avaliado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_eletronico_solicitacaojuntadadocumento_avaliado_por', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='TramiteDistribuicao',
            name='pessoa_para_distribuir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuir_tramite_para', to='rh.pessoafisica', verbose_name='Distribuir para'),
        ),
    ]
