# Generated by Django 1.11.23 on 2019-08-14 15:02


import comum.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0002_auto_20190814_1454'),
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolo', '0001_initial'),
        ('comum', '0002_auto_20190814_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('numero', models.CharField(max_length=25, verbose_name='Nº da Portaria')),
                ('observacao', models.CharField(max_length=250, null=True, verbose_name='Observação')),
                (
                    'processo',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, help_text='Processo desta instituição relativo a esta baixa', null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Processo'
                    ),
                ),
            ],
            options={'db_table': 'baixa'},
        ),
        migrations.CreateModel(
            name='BaixaTipo',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20, unique=True))],
            options={'db_table': 'baixatipo'},
        ),
        migrations.CreateModel(
            name='CategoriaMaterialPermanente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('percentual_residual', models.FloatField(default=0.1)),
                ('vida_util_em_anos', models.FloatField(default=10)),
                ('omitir', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Elemento de Despesa de Mat. Permanente',
                'verbose_name_plural': 'Elementos de Despesa de Mat. Permanente',
                'db_table': 'categoriamaterialpermanente',
            },
        ),
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('data_inicio', models.DateField(db_column='datainicio')),
                ('data_fim', models.DateField(db_column='datafim')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Cautela', 'verbose_name_plural': 'Cautelas', 'db_table': 'cautela'},
        ),
        migrations.CreateModel(
            name='CautelaInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cautela', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Cautela')),
            ],
            options={'db_table': 'cautelainventario'},
        ),
        migrations.CreateModel(
            name='CautelaRenovacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('data_fim', models.DateField(db_column='datafim')),
                ('cautela', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Cautela')),
            ],
            options={'db_table': 'cautelarenovacao'},
        ),
        migrations.CreateModel(
            name='ConferenciaItem',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('dh_coleta', djtools.db.models.DateTimeFieldPlus())],
            options={'verbose_name': 'Conferência de Itens', 'verbose_name_plural': 'Conferências de Itens'},
        ),
        migrations.CreateModel(
            name='ConferenciaItemErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_coleta', djtools.db.models.DateTimeFieldPlus()),
                ('inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConferenciaSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('token', models.CharField(max_length=40)),
                ('responsavel', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
                ('sala', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Sala')),
            ],
            options={'verbose_name': 'Conferência de Sala', 'verbose_name_plural': 'Conferências de Sala'},
        ),
        migrations.CreateModel(
            name='DescricaoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'descricaoinventario'},
        ),
        migrations.CreateModel(
            name='EmpenhoPermanente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('qtd_empenhada', models.IntegerField(db_column='qtdempenhada')),
                ('qtd_adquirida', models.IntegerField(db_column='qtdadquirida', default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.CategoriaMaterialPermanente')),
                ('empenho', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Empenho')),
            ],
            options={
                'verbose_name': 'Empenho Permanente',
                'verbose_name_plural': 'Empenhos Permanentes',
                'db_table': 'empenhopermanente',
                'ordering': ['empenho', 'id'],
                'permissions': (('change_empenhopermanente_movimentados', 'Pode alterar empenhopermanente mov'),),
            },
        ),
        migrations.CreateModel(
            name='EntradaPermanente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('qtd', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.CategoriaMaterialPermanente')),
                (
                    'empenho_permanente',
                    djtools.db.models.ForeignKeyPlus(
                        help_text='Vazio caso seja entrada do tipo doação.', null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.EmpenhoPermanente'
                    ),
                ),
                ('entrada', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Entrada')),
            ],
            options={'verbose_name': 'Entrada Permanente', 'verbose_name_plural': 'Entradas Permanentes', 'db_table': 'entradapermanente'},
        ),
        migrations.CreateModel(
            name='FotoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('data', djtools.db.models.DateFieldPlus()),
                ('foto', models.ImageField(upload_to='patrimonio/inventario_fotos/')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='HistoricoCatDepreciacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_bruto', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Bruto (R$)')),
                ('valor_liquido', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Líquido (R$)')),
                ('valor_depreciado', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Depreciável Mensal (R$)')),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
                ('categoria', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.CategoriaMaterialPermanente')),
            ],
            options={'verbose_name': 'Histórico de Categoria de Depreciação', 'verbose_name_plural': 'Histórico de Categoria de Depreciações'},
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número')),
                ('numero_serie', models.CharField(blank=True, db_column='numeroserie', max_length=50)),
                ('campo_busca', djtools.db.models.SearchField(blank=True, default='', editable=False)),
                (
                    'estado_conservacao',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('', 'Não aplicar'),
                            ('bom', 'Bom'),
                            ('ocioso', 'Ocioso'),
                            ('recuperavel', 'Recuperável'),
                            ('antieconomico', 'Antieconômico'),
                            ('irreversivel', 'Irreversível'),
                        ],
                        max_length=30,
                        verbose_name='Estado de conservação',
                    ),
                ),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'db_table': 'inventario',
                'ordering': ['numero'],
                'permissions': (
                    ('ver_inventarios', 'Pode buscar e visualizar inventários'),
                    ('pode_ver_propria_carga', 'Pode ver a própria carga'),
                    ('editar_do_meu_campus', 'Pode editar inventários do seu campus'),
                    ('editar_todos', 'Pode editar todos os inventários'),
                    ('pode_ver_relatorios', 'Pode ver todos os relatórios'),
                    ('pode_alterar_carga_contabil', 'Pode alterar a carga contábil'),
                    ('pode_alterar_carga_contabil_todos', 'Pode alterar a carga contábil de todos'),
                    ('pode_alterar_carga_contabil_do_campus', 'Pode alterar a carga contábil do campus'),
                ),
            },
        ),
        migrations.CreateModel(
            name='InventarioCargaContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Requisição'), (2, 'Manual')])),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_contabeis', to='patrimonio.Inventario')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='InventarioCategoria',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=100))],
            options={'verbose_name': 'Categoria de Inventário', 'verbose_name_plural': 'Categorias de Inventários'},
        ),
        migrations.CreateModel(
            name='InventarioReavaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Automático'), (2, 'Deferida'), (3, 'Reavaliação Manual')], default=1)),
                ('percentual_residual', models.FloatField()),
                ('vida_util_em_anos', models.FloatField()),
                ('data', djtools.db.models.DateFieldPlus()),
                ('valor_anterior', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')),
                (
                    'operador',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='InventarioRotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, null=True, verbose_name='Descrição')),
                (
                    'unidade_organizacional',
                    djtools.db.models.ForeignKeyPlus(
                        db_column='unidadeorganizacional_id', default=comum.utils.get_uo, editable=False, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional'
                    ),
                ),
            ],
            options={'verbose_name': 'Rótulo', 'verbose_name_plural': 'Rótulos', 'db_table': 'inventariorotulo', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='InventarioStatus',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20))],
            options={'db_table': 'inventariostatus', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='InventarioTipoUsoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, unique=True)),
                ('requisicao_periodo_inicio', models.DateTimeField(blank=True, null=True)),
                ('requisicao_periodo_fim', models.DateTimeField(blank=True, null=True)),
                ('texto_requisicao', models.TextField(blank=True, help_text='Texto a ser informado no questionário')),
                ('enviar_email_inscrito', models.NullBooleanField(default=False)),
                ('enviar_email_copia', models.TextField(blank=True, max_length=75)),
            ],
            options={'verbose_name': 'Inventário Tipo Uso Pessoal', 'verbose_name_plural': 'Inventários Tipo Uso Pessoal'},
        ),
        migrations.CreateModel(
            name='InventarioValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Depreciação')], default=1)),
                ('percentual_residual', models.FloatField()),
                ('vida_util_em_anos', models.FloatField()),
                ('data', djtools.db.models.DateFieldPlus()),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')),
                (
                    'operador',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('uo', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoPatrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('baixa', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Baixa')),
                (
                    'entrada_permanente',
                    djtools.db.models.ForeignKeyPlus(db_column='entradapermanente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.EntradaPermanente'),
                ),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')),
            ],
            options={'db_table': 'movimentopatrim', 'ordering': ['-data']},
        ),
        migrations.CreateModel(
            name='MovimentoPatrimTipo',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', models.CharField(max_length=20, unique=True))],
            options={'db_table': 'movimentopatrimtipo'},
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_desativacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Desativação')),
            ],
            options={'verbose_name': 'Plano de Contas', 'verbose_name_plural': 'Planos de Contas'},
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.PositiveIntegerField(
                        choices=[
                            (1, 'Aguardando aprovação do servidor de destino'),
                            (2, 'Deferida'),
                            (3, 'Indeferida'),
                            (4, 'Aguardando informação de PA Campus Origem'),
                            (5, 'Cancelada'),
                            (6, 'Aguardando informação de PA Campus Destino'),
                        ],
                        default=1,
                        verbose_name='Situação',
                    ),
                ),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Mesmo campus'), (2, 'Entre diferentes campi')], default=1)),
                ('observacao', models.TextField(blank=True, help_text='Observação quando a requisição foi negada', verbose_name='Observação')),
                ('numero_pa_origem', models.TextField(blank=True, verbose_name='Número da PA Campus Origem')),
                ('numero_pa_destino', models.TextField(blank=True, verbose_name='Número da PA Campus Destino')),
                ('inv_inconsistentes', models.NullBooleanField(default=False)),
                ('descricao', models.TextField(max_length=500, null=True, verbose_name='Descrição')),
                (
                    'campus_destino',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='requisicao_campusdestino',
                        to='rh.UnidadeOrganizacional',
                        verbose_name='Campus de Destino',
                    ),
                ),
                (
                    'campus_origem',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='requisicao_campusorigem',
                        to='rh.UnidadeOrganizacional',
                        verbose_name='Campus de Origem',
                    ),
                ),
                (
                    'vinculo_coordenador',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_coordenador', to='comum.Vinculo'),
                ),
                (
                    'vinculo_destino',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_vinculodestino', to='comum.Vinculo', verbose_name='Pessoa de Destino'
                    ),
                ),
                (
                    'vinculo_origem',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_vinculoorigem', to='comum.Vinculo', verbose_name='Pessoa de Origem'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Requisição de Transferência',
                'verbose_name_plural': 'Requisições de Transferência',
                'permissions': (
                    ('pode_requisitar_transferencia_do_campus', 'Pode requisitar transferência do próprio campus'),
                    ('pode_visualizar_requisicao_do_campus', 'Pode visualizar requisições do próprio campus'),
                ),
            },
        ),
        migrations.CreateModel(
            name='RequisicaoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.PositiveIntegerField(
                        choices=[
                            (1, 'Aguardando aprovação do servidor de destino'),
                            (2, 'Deferida'),
                            (3, 'Indeferida'),
                            (4, 'Aguardando informação de PA Campus Origem'),
                            (5, 'Cancelada'),
                            (6, 'Aguardando informação de PA Campus Destino'),
                        ]
                    ),
                ),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                (
                    'alterado_por',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('requisicao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Requisicao')),
            ],
            options={'verbose_name': 'Histórico de Requisição', 'verbose_name_plural': 'Históricos de Requisições'},
        ),
        migrations.CreateModel(
            name='RequisicaoInventarioUsoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('cadastrado', models.NullBooleanField(default=False)),
                ('indicado', models.NullBooleanField(default=False)),
                ('tipo_uso_pessoal', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.InventarioTipoUsoPessoal')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo')),
            ],
            options={'verbose_name': 'Requisição de Tipo Uso Pessoal', 'verbose_name_plural': 'Requisições de Tipo Uso Pessoal'},
        ),
        migrations.CreateModel(
            name='RequisicaoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True, null=True)),
                ('situacao', models.PositiveIntegerField(choices=[(1, 'Aprovado'), (2, 'Rejeitado'), (3, 'Pendente'), (4, 'Cancelado')], default=3, null=True)),
                (
                    'avaliador',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('inventario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')),
                ('requisicao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='patrimonio.Requisicao')),
            ],
            options={'verbose_name': 'Item de Requisição', 'verbose_name_plural': 'Itens de Requisição'},
        ),
        migrations.AddField(
            model_name='movimentopatrim',
            name='requisicao_item',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.RequisicaoItem'),
        ),
        migrations.AddField(
            model_name='movimentopatrim', name='tipo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.MovimentoPatrimTipo')
        ),
        migrations.AddField(
            model_name='movimentopatrim',
            name='usuario',
            field=djtools.db.models.CurrentUserField(
                blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='movimentopatrim', name='vinculo', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo')
        ),
        migrations.AddField(
            model_name='inventariocargacontabil',
            name='requisicao',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Requisicao'),
        ),
        migrations.AddField(
            model_name='inventariocargacontabil',
            name='usuario',
            field=djtools.db.models.CurrentUserField(
                blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='inventario',
            name='carga_contabil',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_atual', to='patrimonio.InventarioCargaContabil'
            ),
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.InventarioCategoria'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='entrada_permanente',
            field=djtools.db.models.ForeignKeyPlus(db_column='entradapermanente_id', on_delete=django.db.models.deletion.CASCADE, to='patrimonio.EntradaPermanente'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsavel_vinculo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo'),
        ),
        migrations.AddField(model_name='inventario', name='rotulos', field=models.ManyToManyField(blank=True, to='patrimonio.InventarioRotulo')),
        migrations.AddField(
            model_name='inventario', name='sala', field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Sala')
        ),
        migrations.AddField(
            model_name='inventario', name='status', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.InventarioStatus')
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_uso_pessoal',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.InventarioTipoUsoPessoal'),
        ),
        migrations.AddField(
            model_name='fotoinventario',
            name='inventario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='patrimonio.Inventario'),
        ),
        migrations.AddField(
            model_name='descricaoinventario',
            name='inventario',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='descricoesinventario', to='patrimonio.Inventario'),
        ),
        migrations.AddField(
            model_name='conferenciaitemerro',
            name='conferencia',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.ConferenciaSala'),
        ),
        migrations.AddField(
            model_name='conferenciaitem', name='conferencia', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.ConferenciaSala')
        ),
        migrations.AddField(
            model_name='conferenciaitem', name='inventario', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')
        ),
        migrations.AddField(
            model_name='cautelainventario', name='inventario', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.Inventario')
        ),
        migrations.AddField(
            model_name='categoriamaterialpermanente',
            name='plano_contas',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.PlanoContas'),
        ),
        migrations.AddField(
            model_name='baixa', name='tipo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.BaixaTipo', verbose_name='Tipo')
        ),
        migrations.AddField(
            model_name='baixa', name='uo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')
        ),
        migrations.AlterUniqueTogether(name='requisicaoitem', unique_together={('requisicao', 'inventario')}),
        migrations.AlterUniqueTogether(name='requisicaohistorico', unique_together={('requisicao', 'status')}),
        migrations.AlterUniqueTogether(name='inventariovalor', unique_together={('tipo', 'inventario', 'data')}),
        migrations.AlterUniqueTogether(name='conferenciaitemerro', unique_together={('conferencia', 'inventario')}),
        migrations.AlterUniqueTogether(name='conferenciaitem', unique_together={('conferencia', 'inventario')}),
    ]
