# Generated by Django 2.2.7 on 2020-02-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('patrimonio', '0001_initial')]

    operations = [migrations.AlterModelOptions(name='baixa', options={'verbose_name': 'Baixa', 'verbose_name_plural': 'Baixas'})]
