# Generated by Django 2.2.16 on 2021-03-09 20:04

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_auto_20200214_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoinventario',
            name='foto',
            field=djtools.db.models.ImageFieldPlus(upload_to='patrimonio/inventario_fotos/'),
        ),
    ]
