# Generated by Django 3.2.5 on 2022-06-08 13:57

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0041_alter_instalacaohidraulicasala_options'),
        ('patrimonio', '0004_auto_20210719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='requisitante',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo'),
        ),
    ]
