# Generated by Django 3.2.5 on 2022-07-31 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import djtools.db.models
import djtools.middleware.threadlocals
import documento_eletronico.utils
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0040_merge_20220722_1505'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='CPF')),
                ('nome_papel', djtools.db.models.CharFieldPlus(help_text='Nome do Papel da Pessoa', max_length=255, verbose_name='Nome do Papel')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('hmac', models.TextField(unique=True, verbose_name='Hash Assinado')),
                ('papel', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.papel')),
                ('pessoa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ('-data_assinatura',),
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDocumentoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.assinatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.CharFieldPlus(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('fase_corrente', models.TextField(blank=True, verbose_name='Fase Corrente')),
                ('fase_intermediaria', models.TextField(blank=True, verbose_name='Fase Intermediária')),
                ('destinacao_final', models.TextField(blank=True, verbose_name='Destinação Final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('suficiente_para_classificar_processo', models.BooleanField(default=True, verbose_name='Suficiente para classificar um processo?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('migrado', models.BooleanField(default=False, verbose_name='Migrado')),
                ('mec', models.BooleanField(default=False, verbose_name='Do MEC')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('pai', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='documento_eletronico.classificacao')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='DocumentoDigitalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', djtools.db.models.CharFieldPlus(db_index=True, max_length=255, verbose_name='Assunto')),
                ('nivel_acesso', models.PositiveIntegerField(choices=[(1, 'Sigiloso'), (2, 'Restrito'), (3, 'Público')], default=3, verbose_name='Nível de Acesso')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_modificacao', djtools.db.models.DateTimeFieldPlus(editable=False, verbose_name='Data da Última Modificação')),
                ('data_remocao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Remoção')),
                ('justificativa_remocao', models.TextField(blank=True, null=True, verbose_name='Justificativa de Remoção')),
                ('data_emissao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Emissão')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('identificador_tipo_documento_sigla', djtools.db.models.CharFieldPlus(blank=True, max_length=50, null=True, verbose_name='Sigla do Tipo de Documento')),
                ('identificador_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('identificador_ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('identificador_setor_sigla', djtools.db.models.CharFieldPlus(blank=True, max_length=100, null=True, verbose_name='Sigla do Setor')),
                ('arquivo', djtools.db.models.FileFieldPlus(max_length=400, upload_to=documento_eletronico.utils.file_upload_to, verbose_name='Arquivo')),
                ('interno', models.BooleanField(help_text='Documento produzido na instituição', null=True, verbose_name='Documento Interno')),
                ('orgao_externo', djtools.db.models.CharFieldPlus(help_text='Nome do órgão externo que produziu o documento', max_length=255, verbose_name='Órgão Externo')),
                ('anexo_simples', models.BooleanField(default=False, editable=False)),
                ('dono_documento', djtools.db.models.ForeignKeyPlus(help_text='Esse campo é obrigatório caso você esteja adicionando um documento sigiloso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donos_documento', to='rh.pessoafisica', verbose_name='Dono do Documento')),
            ],
            options={
                'verbose_name': 'Documento Digitalizado',
                'verbose_name_plural': 'Documentos Digitalizados',
                'permissions': (('pode_alterar_nivel_acesso_documento_digitalizado', 'Pode alterar nível de acesso dos documentos eletrônicos - digitalizado'), ('pode_ver_todos_log_acoes_documento_digitalizado', 'Pode acessar todos os logs de acessos - digitalizado')),
            },
        ),
        migrations.CreateModel(
            name='DocumentoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', djtools.db.models.CharFieldPlus(db_index=True, max_length=255, verbose_name='Assunto')),
                ('nivel_acesso', models.PositiveIntegerField(choices=[(1, 'Sigiloso'), (2, 'Restrito'), (3, 'Público')], default=3, verbose_name='Nível de Acesso')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_modificacao', djtools.db.models.DateTimeFieldPlus(editable=False, verbose_name='Data da Última Modificação')),
                ('data_remocao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Remoção')),
                ('justificativa_remocao', models.TextField(blank=True, null=True, verbose_name='Justificativa de Remoção')),
                ('data_emissao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de Emissão')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('identificador', djtools.db.models.CharFieldPlus(blank=True, db_index=True, max_length=100, verbose_name='Identificador do Documento')),
                ('identificador_tipo_documento_sigla', djtools.db.models.CharFieldPlus(blank=True, max_length=50, null=True, verbose_name='Sigla do Tipo de Documento')),
                ('identificador_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('identificador_ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('identificador_setor_sigla', djtools.db.models.CharFieldPlus(blank=True, max_length=100, null=True, verbose_name='Sigla do Setor')),
                ('identificador_dono_documento', djtools.db.models.CharFieldPlus(blank=True, max_length=100, null=True, verbose_name='Identificador Dono Documento')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Rascunho'), (2, 'Concluído'), (3, 'Em Revisão'), (4, 'Revisado'), (8, 'Cancelado'), (5, 'Aguardando assinatura'), (6, 'Assinado'), (7, 'Finalizado')], default=1, protected=True, verbose_name='Situação')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('cabecalho', models.TextField(verbose_name='Cabeçalho')),
                ('rodape', models.TextField(verbose_name='Rodapé')),
                ('variaveis', models.TextField(editable=False, verbose_name='Variaveis')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('justificativa_cancelamento', models.TextField(blank=True, null=True, verbose_name='Justificativa do Cancelamento')),
                ('assinatura_balizadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentotexto_assinatura_balizadora', to='documento_eletronico.assinaturadocumentotexto')),
            ],
            options={
                'verbose_name': 'Documento de Texto',
                'verbose_name_plural': 'Documentos de Texto',
                'ordering': ('-data_ultima_modificacao', 'modelo__tipo_documento_texto__nome', '-identificador_numero'),
                'permissions': (('pode_vincular_interesssados', 'Pode vincular interessados'), ('pode_alterar_nivel_acesso_documento_texto', 'Pode alterar nível de acesso dos documentos eletrônicos - texto'), ('pode_ver_todos_log_acoes_documento_texto', 'Pode acessar todos os logs de acessos - texto')),
            },
        ),
        migrations.CreateModel(
            name='HipoteseLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', djtools.db.models.CharFieldPlus(choices=[('SIGILOSO', 'Sigiloso'), ('RESTRITO', 'Restrito')], max_length=10, verbose_name='Nível de Acesso')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
                ('base_legal', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Base Legal')),
            ],
            options={
                'verbose_name': 'Hipótese Legal',
                'verbose_name_plural': 'Hipóteses Legais',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='TipoConferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Conferência',
                'verbose_name_plural': 'Tipos de Conferência',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=50, unique=True, verbose_name='Sigla')),
                ('vincular_pessoa', models.BooleanField(default=False, verbose_name='Permite vincular interessado')),
                ('ativo', models.BooleanField(default=True, help_text='Somente os registros ativos ficam disponíveis no cadastro de documentos.', verbose_name='ativo')),
                ('permite_documentos_pessoais', models.BooleanField(default=False, verbose_name='Permite criar documentos pessoais')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Externo',
                'verbose_name_plural': 'Tipos de Documentos Externos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoTextoHistoricoConteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_conteudo', models.CharField(choices=[('C', 'Cabeçalho'), ('R', 'Rodapé')], max_length=1, verbose_name='Área de Conteúdo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('hash', models.TextField(verbose_name='Hash')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Interno (Histórico Conteúdo)',
                'verbose_name_plural': 'Tipos de Documentos Internos ((Histórico Conteúdo)',
                'ordering': ('tipo_documento_texto__nome', 'data_criacao'),
            },
        ),
        migrations.CreateModel(
            name='TipoVinculoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=50, unique=True, verbose_name='Descrição')),
                ('descricao_voz_ativa', djtools.db.models.CharFieldPlus(max_length=100, unique=True, verbose_name='Descrição na Voz Ativa')),
                ('descricao_voz_passiva', djtools.db.models.CharFieldPlus(max_length=100, unique=True, verbose_name='Descrição na Voz Passiva')),
            ],
            options={
                'verbose_name': 'Tipo de Vínculo de Documento',
                'verbose_name_plural': 'Tipos de Vínculos de Documentos',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('assinatura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documento_eletronico.assinatura')),
                ('chave_publica', models.TextField(verbose_name='Public Key RSA')),
                ('numero_serie_certificado', models.CharField(blank=True, max_length=48, null=True)),
                ('certificado_criado_em', models.DateTimeField(blank=True, null=True)),
                ('certificado_expira_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'ordering': ('-data_assinatura',),
            },
            bases=('documento_eletronico.assinatura',),
        ),
        migrations.CreateModel(
            name='TipoDocumentoTexto',
            fields=[
                ('tipodocumento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documento_eletronico.tipodocumento')),
                ('cabecalho_padrao', models.TextField(blank=True, verbose_name='Cabeçalho Padrão')),
                ('cabecalho_hash', models.TextField(editable=False, verbose_name='Hash do Cabeçalho')),
                ('rodape_padrao', models.TextField(blank=True, verbose_name='Rodapé Padrão')),
                ('rodape_hash', models.TextField(editable=False, verbose_name='Hash do Rodapé')),
                ('permite_documentos_anexos', models.BooleanField(default=False, verbose_name='Permite receber documentos em anexo')),
                ('tipo_sequencia', models.CharField(choices=[('identificador_sequencial', 'Identificador Sequencial'), ('identificador_sequencial_anual', 'Identificador Sequencial Anual')], default='identificador_sequencial_anual', max_length=50, verbose_name='Tipo de numeração')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Interno',
                'verbose_name_plural': 'Tipos de Documentos Internos',
                'ordering': ('nome',),
            },
            bases=('documento_eletronico.tipodocumento',),
        ),
        migrations.CreateModel(
            name='VinculoDocumentoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('documento_texto_alvo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_documento_texto_alvo', to='documento_eletronico.documentotexto', verbose_name='Documento Alvo')),
                ('documento_texto_base', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_documento_texto_base', to='documento_eletronico.documentotexto', verbose_name='Documento Base')),
                ('tipo_vinculo_documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_documento_texto', to='documento_eletronico.tipovinculodocumento', verbose_name='Tipo de Vínculo')),
                ('usuario_criacao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Vínculo de Documento',
                'verbose_name_plural': 'Tipos de Vínculos de Documentos',
                'ordering': ('tipo_vinculo_documento',),
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoRevisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Aguardando assinatura'), (3, 'Indeferida'), (2, 'Deferida')], default=1, protected=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('notas_revisor', models.TextField(blank=True, null=True, verbose_name='Notas do Revisor')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('status_avaliacao', django_fsm.FSMIntegerField(choices=[(1, 'Aguardando avaliação'), (2, 'Deferida'), (3, 'Rejeitada')], default=1, null=True)),
                ('avaliador', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisao_avaliada_por', to='rh.pessoa', verbose_name='Avaliador')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentotexto')),
                ('revisor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Revisor')),
                ('solicitante', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisao_solicitado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_solicitacao',),
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCompartilhamentoDocumentoDigitalizadoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_solicitacao', models.TextField(verbose_name='Justificativa Solicitação de Acesso')),
                ('status_solicitacao', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Deferida'), (2, 'Indeferida')], default=0, verbose_name='Situação')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_autorizacao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Autorização')),
                ('justificativa_autorizacao', models.TextField(blank=True, default='', verbose_name='Justificativa (Des)Autorização')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_compartilhamento_pessoa_documento_digitalizado', to='documento_eletronico.documentodigitalizado')),
                ('pessoa_solicitante', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Solicitante')),
                ('usuario_autorizacao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_autorizacao_solicitacao_compartilhamento_documento_digitalizado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Autorizador')),
                ('usuario_solicitacao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Solicitação de Compartilhamento de Documento Digitalizado Sigiloso',
                'verbose_name_plural': 'Solicitações de Compartilhamento de Documentos Digitalizados Sigilosos',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Aguardando assinatura'), (3, 'Indeferida'), (2, 'Deferida')], default=1, protected=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('justificativa_rejeicao', models.TextField(blank=True, null=True, verbose_name='Justificativa da Rejeição')),
                ('condicionantes', djtools.db.models.ManyToManyFieldPlus(to='documento_eletronico.SolicitacaoAssinatura', verbose_name='Assinatura condicionada à')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentotexto')),
                ('solicitado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_solicitacaoassinatura_solicitado_a', to='rh.pessoafisica')),
                ('solicitante', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_solicitacaoassinatura_solicitado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_solicitacao',),
            },
        ),
        migrations.CreateModel(
            name='RegistroAcaoDocumentoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Criação'), (2, 'Visualização'), (3, 'Impressão'), (4, 'Edição'), (5, 'Assinatura'), (6, 'Adição em Processo'), (7, 'Remoção em Processo'), (8, 'Compartilhamento'), (9, 'Descompartilhamento'), (10, 'Solicitação de Revisão'), (11, 'Revisão'), (12, 'Solicitação de revisão revogada'), (13, 'Cancelar documento'), (14, 'Finalização'), (15, 'Edição de interessados'), (16, 'Revisão avaliada'), (17, 'Solicitação de assinatura rejeitada'), (18, 'Alteração de Nível de Acesso'), (19, 'Acesso em função do cargo')], editable=False)),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data')),
                ('ip', models.GenericIPAddressField(editable=False, verbose_name='IP')),
                ('observacao', models.TextField(editable=False)),
                ('documento', djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentotexto')),
                ('user', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAcaoDocumentoDigitalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Criação'), (2, 'Visualização'), (3, 'Impressão'), (4, 'Edição'), (5, 'Assinatura'), (6, 'Adição em Processo'), (7, 'Remoção em Processo'), (8, 'Compartilhamento'), (9, 'Descompartilhamento'), (10, 'Solicitação de Revisão'), (11, 'Revisão'), (12, 'Solicitação de revisão revogada'), (13, 'Cancelar documento'), (14, 'Finalização'), (15, 'Edição de interessados'), (16, 'Revisão avaliada'), (17, 'Solicitação de assinatura rejeitada'), (18, 'Alteração de Nível de Acesso'), (19, 'Acesso em função do cargo')], editable=False)),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data')),
                ('ip', models.GenericIPAddressField(editable=False, verbose_name='IP')),
                ('observacao', models.TextField(editable=False)),
                ('documento', djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentodigitalizado')),
                ('user', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Descrição')),
                ('corpo_padrao', models.TextField(blank=True, verbose_name='Corpo Padrão')),
                ('permite_nivel_acesso_sigiloso', models.BooleanField(default=True, verbose_name='Sigiloso?')),
                ('permite_nivel_acesso_restrito', models.BooleanField(default=True, verbose_name='Restrito?')),
                ('permite_nivel_acesso_publico', models.BooleanField(default=True, verbose_name='Público?')),
                ('nivel_acesso_padrao', models.PositiveIntegerField(choices=[(1, 'Sigiloso'), (2, 'Restrito'), (3, 'Público')], default=1, verbose_name='Nível de Acesso Padrão')),
                ('ativo', models.BooleanField(default=True, help_text='Somente os registros ativos ficam disponíveis no cadastro de documentos.', verbose_name='ativo')),
                ('classificacao', djtools.db.models.ManyToManyFieldPlus(blank=True, to='documento_eletronico.Classificacao', verbose_name='Classificação')),
                ('tipo_documento_texto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='documento_eletronico.tipodocumentotexto', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
                'ordering': ('tipo_documento_texto__nome', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='DocumentoTextoAnexoDocumentoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inclusao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_documento_texto', to='documento_eletronico.documentotexto', verbose_name='Documento')),
                ('documento_anexado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_documento_texto_anexado', to='documento_eletronico.documentotexto', verbose_name='Documento')),
                ('usuario_inclusao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_texto_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Inclusão')),
            ],
            options={
                'verbose_name': 'Documento Texto Anexado',
                'verbose_name_plural': 'Documentos Textos Anexados',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTextoAnexoDocumentoDigitalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inclusao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_documento_digitalizado', to='documento_eletronico.documentotexto', verbose_name='Documento')),
                ('documento_anexado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_documento_digitalizado_anexado', to='documento_eletronico.documentodigitalizado', verbose_name='Documento')),
                ('usuario_inclusao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados_digitalizado_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Inclusão')),
            ],
            options={
                'verbose_name': 'Documento Digitalizado Anexado',
                'verbose_name_plural': 'Documentos Digitalizados Anexados',
            },
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='cabecalho_base_original',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_usando_cabecalho', to='documento_eletronico.tipodocumentotextohistoricoconteudo'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='hipotese_legal',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.hipoteselegal', verbose_name='Hipótese Legal'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='documento_eletronico_documentotexto_interessados', to='rh.Pessoa'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='modelo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.PROTECT, to='documento_eletronico.modelodocumento', verbose_name='Modelo de Documento de Texto'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='rodape_base_original',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_usando_rodape', to='documento_eletronico.tipodocumentotextohistoricoconteudo'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='setor_dono',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.setor', verbose_name='Setor Dono'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='usuario_criacao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentotexto_usuario_criacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='usuario_remocao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentotexto_usuario_remocao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Remoção'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='usuario_ultima_modificacao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentotexto_usuario_ultima_modificacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Última Modificação'),
        ),
        migrations.AddField(
            model_name='documentotexto',
            name='usuarios_marcadores_favoritos',
            field=djtools.db.models.ManyToManyFieldPlus(blank=True, editable=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuários Que Marcaram o Documento como Favorito'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='hipotese_legal',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.hipoteselegal', verbose_name='Hipótese Legal'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='documento_eletronico_documentodigitalizado_interessados', to='rh.Pessoa'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='setor_dono',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.setor', verbose_name='Setor Dono'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.tipodocumento'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='tipo_conferencia',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.tipoconferencia', verbose_name='Tipo de Conferência'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='usuario_criacao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentodigitalizado_usuario_criacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='usuario_remocao',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentodigitalizado_usuario_remocao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Remoção'),
        ),
        migrations.AddField(
            model_name='documentodigitalizado',
            name='usuario_ultima_modificacao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_documentodigitalizado_usuario_ultima_modificacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Última Modificação'),
        ),
        migrations.CreateModel(
            name='CompartilhamentoSetorPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_permissao', models.PositiveIntegerField(choices=[(1, 'Leitura'), (2, 'Leitura e Edição')], default=1, verbose_name='Permissão de Acesso')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('pessoa_permitida', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora')),
                ('setor_dono', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.setor')),
                ('usuario_criacao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Configuração de Compartilhamento de Documentos entre Setor e Pessoas',
                'verbose_name_plural': 'Configurações de Compartilhamento de Documentos entre Setores e Pessoas',
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoDocumentoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_permissao', models.PositiveIntegerField(choices=[(1, 'Leitura'), (2, 'Leitura e Edição')], default=1, verbose_name='Permissão de Acesso')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('tipo_permissao', models.PositiveIntegerField(choices=[(1, 'Compartilhamento'), (2, 'Revisão')], default=1, verbose_name='Tipo de Permissão de Acesso')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamento_pessoa_documento', to='documento_eletronico.documentotexto')),
                ('pessoa_permitida', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora')),
                ('solicitacao_assinatura', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.solicitacaoassinatura')),
                ('usuario_criacao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Documentos com Pessoa',
                'verbose_name_plural': 'Compartilhamento de Documentos com Pessoas',
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoDocumentoDigitalizadoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamento_pessoa_documento_digitalizado', to='documento_eletronico.documentodigitalizado')),
                ('pessoa_permitida', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora')),
                ('usuario_criacao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Documentos Digitalizados com Pessoa',
                'verbose_name_plural': 'Compartilhamento de Documentos Digitalizados com Pessoas',
            },
        ),
        migrations.AddField(
            model_name='assinaturadocumentotexto',
            name='documento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentotexto'),
        ),
        migrations.CreateModel(
            name='AssinaturaDocumentoDigitalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.assinatura')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.documentodigitalizado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoDigitalizadoAnexoSimples',
            fields=[
            ],
            options={
                'verbose_name': 'Documento Digitalizado Anexo Simples',
                'verbose_name_plural': 'Documentos Digitalizados Anexos Simples',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documento_eletronico.documentodigitalizado',),
        ),
        migrations.CreateModel(
            name='DocumentoDigitalizadoPessoal',
            fields=[
            ],
            options={
                'verbose_name': 'Documento Digitalizado Pessoal',
                'verbose_name_plural': 'Documentos Digitalizados Pessoais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documento_eletronico.documentodigitalizado',),
        ),
        migrations.CreateModel(
            name='DocumentoTextoPessoal',
            fields=[
            ],
            options={
                'verbose_name': 'Documento de Texto Pessoal',
                'verbose_name_plural': 'Documentos de Texto Pessoais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documento_eletronico.documentotexto',),
        ),
        migrations.AddField(
            model_name='tipodocumentotextohistoricoconteudo',
            name='tipo_documento_texto',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_conteudo', to='documento_eletronico.tipodocumentotexto', verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='RestricaoAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_content_id', models.PositiveIntegerField(verbose_name='Papel Object')),
                ('papel_content_type', djtools.db.models.ForeignKeyPlus(limit_choices_to=models.Q(models.Q(('app_label', 'rh'), ('model', 'CargoEmprego')), models.Q(('app_label', 'rh'), ('model', 'Funcao')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Papel')),
                ('tipo_documento_texto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_assinatura', to='documento_eletronico.tipodocumentotexto', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Restrição de Assinatura',
                'verbose_name_plural': 'Restrições de Assinatura',
                'ordering': ('tipo_documento_texto__nome',),
                'unique_together': {('tipo_documento_texto', 'papel_content_type', 'papel_content_id')},
            },
        ),
    ]
