# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('documento_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='DocumentoTexto',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='documento_eletronico_documentotexto_interessados', to='rh.Pessoa'),
        ),
        migrations.AlterField(
            model_name='DocumentoDigitalizado',
            name='interessados',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='documento_eletronico_documentodigitalizado_interessados', to='rh.Pessoa'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoRevisao',
            name='revisor',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Revisor'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoRevisao',
            name='avaliador',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisao_avaliada_por', to='rh.pessoa', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='Assinatura',
            name='pessoa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoDocumentoPessoa',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoDocumentoDigitalizadoPessoa',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoCompartilhamentoDocumentoDigitalizadoPessoa',
            name='pessoa_solicitante',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Solicitante'),
        ),
        migrations.AlterField(
            model_name='CompartilhamentoSetorPessoa',
            name='pessoa_permitida',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Pessoa Colaboradora'),
        ),
        migrations.AlterField(
            model_name='DocumentoDigitalizado',
            name='dono_documento',
            field=djtools.db.models.ForeignKeyPlus(help_text='Esse campo é obrigatório caso você esteja adicionando um documento sigiloso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donos_documento', to='rh.pessoafisica', verbose_name='Dono do Documento'),
        ),
        migrations.AlterField(
            model_name='SolicitacaoAssinatura',
            name='solicitado',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documento_eletronico_solicitacaoassinatura_solicitado_a', to='rh.pessoafisica'),
        ),
    ]
