# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-16 11:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0002_auto_20190902_1545'), ('saude', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='pessoa_externa',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaExterna'),
        )
    ]
