# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-04 09:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('saude', '0006_auto_20190808_1123')]

    operations = [
        migrations.AlterField(
            model_name='bloqueioatendimentosaude',
            name='vinculo_paciente',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_paciente_bloqueio_agendamento', to='comum.Vinculo', verbose_name='Paciente'
            ),
        ),
        migrations.AlterField(
            model_name='bloqueioatendimentosaude',
            name='vinculo_profissional',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_profissional_bloqueio_agendamento', to='comum.Vinculo', verbose_name='Profissional'
            ),
        ),
    ]
