# Generated by Django 2.2.7 on 2019-12-03 09:16

from django.db import migrations
from django.core.management import call_command


def atualizar_vinculos_dos_prontuarios(apps, schema):
    call_command('atualizar_vinculos_dos_prontuarios')


class Migration(migrations.Migration):

    dependencies = [('saude', '0007_auto_20190904_0957')]

    operations = [migrations.RunPython(atualizar_vinculos_dos_prontuarios)]
