# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0008_auto_20191203_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadegrupo',
            name='anexo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/saude/atividades_grupo/', verbose_name='Anexo'),
        ),
    ]
