# Generated by Django 2.2.16 on 2021-06-29 13:08

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0020_emailblocklist'),
        ('saude', '0009_auto_20210301_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometria',
            name='periodo_sem_comida',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[('Nunca', 'Nunca'), ('Raramente', 'Raramente'), ('Muitas vezes', 'Muitas vezes'), ('Sempre', 'Sempre')], max_length=50, null=True, verbose_name='NOS ÚLTIMOS 30 DIAS, com que frequência você ficou com fome por não ter comida suficiente em sua casa?'),
        ),
        migrations.AddField(
            model_name='antropometria',
            name='sentimento_relacao_corpo',
            field=djtools.db.models.CharFieldPlus(blank=True, choices=[('Muito satisfeito(a)', 'Muito satisfeito(a)'), ('Satisfeito(a)', 'Satisfeito(a)'), ('Indiferente', 'Indiferente'), ('Insatisfeito(a)', 'Insatisfeito(a)'), ('Muito insatisfeito(a)', 'Muito insatisfeito(a)')], max_length=50, null=True, verbose_name='Como você se sente em relação ao seu corpo?'),
        ),
        migrations.CreateModel(
            name='HistoricoCartaoVacinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrado Em')),
                ('prontuario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='saude.Prontuario')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_cadastro_cartao_vacinal', to='comum.Vinculo', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Histórico de Cartão Vacinal',
                'verbose_name_plural': 'Históricos de Cartão Vacinal',
            },
        ),
    ]
