# Generated by Django 3.2.5 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0038_auto_20211215_1218'),
        ('rh', '0031_auto_20220201_1748'),
        ('saude', '0013_auto_20211223_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassaporteVacinalCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', djtools.db.models.CharFieldPlus(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('cadastrado_em', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Cadastrado Em')),
                ('atualizado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Atualizado Em')),
                ('recebeu_alguma_dose', models.BooleanField(null=True, verbose_name='Você já tomou alguma dose de vacina contra a COVID?')),
                ('data_primeira_dose', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data da 1ª Dose')),
                ('data_segunda_dose', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data da 2ª Dose')),
                ('data_terceira_dose', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data da Dose de Reforço')),
                ('esquema_completo', models.BooleanField(default=False, verbose_name='Esquema vacinal completo')),
                ('possui_atestado_medico', models.BooleanField(blank=True, null=True, verbose_name='Você possui atestado/laudo médico ou técnico indicando contraindicação para tomar a vacina?')),
                ('atestado_medico', djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/saude/prontuario', verbose_name='Atestado/Laudo')),
                ('termo_aceito_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Termo de ciência aceito em')),
                ('situacao_declaracao', djtools.db.models.CharFieldPlus(choices=[('Aguardando validação', 'Aguardando validação'), ('Aguardando autodeclaração', 'Aguardando autodeclaração'), ('Deferida', 'Deferida'), ('Indeferida', 'Indeferida')], default='Aguardando validação', max_length=50, verbose_name='Situação da Autodeclaração')),
                ('situacao_passaporte', djtools.db.models.CharFieldPlus(choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('Pendente', 'Pendente')], default='Inválido', max_length=50, verbose_name='Situação do Passaporte Vacinal')),
                ('avaliada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                ('justificativa_indeferimento', models.TextField(null=True, verbose_name='Justificativa do Indeferimento')),
                ('data_expiracao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Expiração do Passaporte')),
                ('tem_pendencia', models.BooleanField(default=False, verbose_name='Tem pendência')),
                ('tem_cadastro', models.BooleanField(default=False, verbose_name='Tem cadastro no RN+Vacina')),
                ('cartao_vacinal', djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/saude/prontuario', verbose_name='Cartão Vacinal Covid-19')),
                ('cartao_vacinal_cadastrado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cartão vacinal cadastrado em')),
                ('avaliada_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_autodeclaracao_avaliada_por', to='comum.vinculo', verbose_name='Avaliada por')),
                ('uo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_autodeclaracao_covid', to='comum.vinculo', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Passaporte Vacinal da COVID',
                'verbose_name_plural': 'Passaportes Vacinais da COVID',
                'permissions': (('pode_ver_todos_passaportes', 'Pode ver Relatório de Passaporte Vacinal'), ('pode_ver_passaportes_do_campus', 'Pode ver Relatório de Passaporte Vacinal do campus')),
            },
        ),
        migrations.AddField(
            model_name='vacina',
            name='eh_covid',
            field=models.BooleanField(default=False, verbose_name='É de COVID-19?'),
        ),
        migrations.CreateModel(
            name='ResultadoTesteCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', djtools.db.models.FileFieldPlus(max_length=255, upload_to='upload/saude/prontuario', verbose_name='Resultado do Teste COVID')),
                ('realizado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Realizado em')),
                ('cadastrado_em', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Cadastrado Em')),
                ('situacao', djtools.db.models.CharFieldPlus(choices=[('Aguardando validação', 'Aguardando validação'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido')], default='Aguardando validação', max_length=50, verbose_name='Situação')),
                ('justificativa_indeferimento', models.TextField(null=True, verbose_name='Justificativa do Indeferimento')),
                ('avaliado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliado Em')),
                ('avaliado_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultadotestecovid_avaliado_por', to='comum.vinculo', verbose_name='Avaliado por')),
                ('passaporte', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='saude.passaportevacinalcovid', verbose_name='Passaporte Vacinal')),
            ],
            options={
                'verbose_name': 'Resultado de Teste COVID',
                'verbose_name_plural': 'Resultados de Teste COVID',
            },
        ),
        migrations.CreateModel(
            name='HistoricoValidacaoPassaporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliado_em', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Avaliado Em')),
                ('situacao_declaracao', djtools.db.models.CharFieldPlus(choices=[('Aguardando validação', 'Aguardando validação'), ('Aguardando autodeclaração', 'Aguardando autodeclaração'), ('Deferida', 'Deferida'), ('Indeferida', 'Indeferida')], default='Aguardando validação', max_length=50, verbose_name='Situação da Autodeclaração')),
                ('situacao_passaporte', djtools.db.models.CharFieldPlus(choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('Pendente', 'Pendente')], default='Inválido', max_length=50, verbose_name='Situação do Passaporte Vacinal')),
                ('justificativa_indeferimento', models.TextField(null=True, verbose_name='Justificativa do Indeferimento')),
                ('possui_atestado_medico', models.BooleanField(blank=True, null=True, verbose_name='Você possui atestado/laudo médico ou técnico indicando contraindicação para tomar a vacina?')),
                ('termo_aceito_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Termo de ciência aceito em')),
                ('avaliado_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_validacao_avaliado_por', to='comum.vinculo', verbose_name='Avaliado por')),
                ('passaporte', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='saude.passaportevacinalcovid', verbose_name='Passaporte Vacinal')),
            ],
            options={
                'verbose_name': 'Histórico de Validação do Passaporte Vacinal da COVID',
                'verbose_name_plural': 'Históricos de Validação dos Passaportes Vacinais da COVID',
            },
        ),
    ]
