# Generated by Django 3.2.5 on 2022-03-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0014_auto_20220302_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passaportevacinalcovid',
            options={'permissions': (('pode_ver_todos_passaportes', 'Pode ver Relatório de Passaporte Vacinal'), ('pode_ver_passaportes_do_campus', 'Pode ver Relatório de Passaporte Vacinal do campus'), ('pode_ver_passaportes_dos_prestadores_do_campus', 'Pode ver Relatório de Passaporte Vacinal dos Prestadores de Serviço do campus'), ('pode_ver_passaportes_dos_alunos_do_curso', 'Pode ver Relatório de Passaporte Vacinal dos Alunos do campus')), 'verbose_name': 'Passaporte Vacinal da COVID', 'verbose_name_plural': 'Passaportes Vacinais da COVID'},
        ),
    ]
