# Generated by Django 3.2.5 on 2022-03-29 09:25

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0034_alter_campoexcecaows_options'),
        ('comum', '0038_auto_20211215_1218'),
        ('saude', '0016_monitoramentocovid_notificacaocovid_sintoma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passaportevacinalcovid',
            options={'permissions': (('pode_ver_todos_passaportes', 'Pode ver Relatório de Passaporte Vacinal'), ('pode_ver_passaportes_do_campus', 'Pode ver Relatório de Passaporte Vacinal do campus'), ('pode_ver_passaportes_dos_prestadores_do_campus', 'Pode ver Relatório de Passaporte Vacinal dos Prestadores de Serviço do campus'), ('pode_ver_passaportes_dos_alunos_do_curso', 'Pode ver Relatório de Passaporte Vacinal dos Alunos do campus'), ('pode_verificar_passaportes', 'Pode verificar situação do passaporte vacinal')), 'verbose_name': 'Passaporte Vacinal da COVID', 'verbose_name_plural': 'Passaportes Vacinais da COVID'},
        ),
        migrations.CreateModel(
            name='ValidadorIntercampi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('campi', djtools.db.models.ManyToManyFieldPlus(to='rh.UnidadeOrganizacional', verbose_name='Campi')),
                ('vinculo', djtools.db.models.OneToOneFieldPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_validacao_intercampi', to='comum.vinculo', verbose_name='Validador')),
            ],
            options={
                'verbose_name': 'Validador Intercampi de Passaportes Vacinais',
                'verbose_name_plural': 'Validadores Intercampi de Passaportes Vacinais',
            },
        ),
    ]
