# Generated by Django 3.2.5 on 2022-04-27 15:37

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0017_auto_20220329_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometria',
            name='pc_biciptal',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Em mm', max_digits=12, null=True, verbose_name='Dobra Cutânea Bicipital'),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pc_subescapular',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Em mm', max_digits=12, null=True, verbose_name='Dobra Cutânea Subescapular'),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pc_suprailiaca',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Em mm', max_digits=12, null=True, verbose_name='Dobra Cutânea Suprailíaca'),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pc_triciptal',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, help_text='Em mm', max_digits=12, null=True, verbose_name='Dobra Cutânea Tricipital'),
        ),
    ]
