# Generated by Django 3.2.5 on 2022-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0019_auto_20220608_0955'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='anexopsicologia',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='atividadegrupo',
            name='responsaveis',
        ),
        migrations.RemoveField(
            model_name='bloqueioatendimentosaude',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='bloqueioatendimentosaude',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='documentoprontuario',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='horarioatendimento',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='horarioatendimento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='atendido_por',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='registroadministrativo',
            name='profissional',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
