# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('estagios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='PraticaProfissional',
            name='empresa',
            field=djtools.db.models.ForeignKeyPlus(help_text='Para adicionar um concedente de estágio pessoa jurídica acesse: <strong>Administração -> Cadastros -> Pessoas Júridicas</strong>. Se for pessoa física, acesse: <strong>Administração -> Cadastros -> Pessoas Externas</strong>.', on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', verbose_name='Concedente'),
        ),
        migrations.AlterField(
            model_name='PraticaProfissional',
            name='representante_concedente',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Só preencher esse campo, se for utilizar a funcionalidade de Documento Eletrônico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagio_representante_concedente', to='rh.pessoafisica', verbose_name='Representante da Concedente'),
        ),
        migrations.AlterField(
            model_name='PraticaProfissional',
            name='supervisor',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Só preencher esse campo, se for utilizar a funcionalidade de Documento Eletrônico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagio_supervisor', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='PraticaProfissional',
            name='testemunha1',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Só preencher esse campo, se for utilizar a funcionalidade de Documento Eletrônico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagio_testemunha1', to='rh.pessoafisica', verbose_name='Testemunha 1'),
        ),
        migrations.AlterField(
            model_name='PraticaProfissional',
            name='testemunha2',
            field=djtools.db.models.ForeignKeyPlus(blank=True, help_text='Só preencher esse campo, se for utilizar a funcionalidade de Documento Eletrônico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagio_testemunha2', to='rh.pessoafisica', verbose_name='Testemunha 2'),
        ),
    ]
