# -*- coding: utf-8 -*

from django.urls import path

from estagios import views

urlpatterns = [
    path('pratica_profissional/<int:pk>/', views.pratica_profissional),
    path('atividade_profissional_efetiva/<int:pk>/', views.atividade_profissional_efetiva),
    path('cancelar_encerramento_estagio/<int:pk>/', views.cancelar_encerramento_estagio),
    path('solicitar_cancelar_encerramento_estagio/<int:pk>/', views.solicitar_cancelar_encerramento_estagio),
    path('solicitar_cancelar_encerramento_aprendizagem/<int:pk>/', views.solicitar_cancelar_encerramento_aprendizagem),
    path('solicitar_cancelar_encerramento_atividade_profissional_efetiva/<int:pk>/', views.solicitar_cancelar_encerramento_atividade_profissional_efetiva),
    path('indeferir_cancelar_encerramento_estagio/<int:pk>/', views.indeferir_cancelar_encerramento_estagio),
    path('aprendizagem/<int:pk>/', views.aprendizagem),
    path('oferta_pratica_profissional/<int:pk>/', views.oferta_pratica_profissional),
    path('ofertas_pratica_profissional/', views.ofertas_pratica_profissional),
    path('encerrar_pratica_profissional/<int:pk>/', views.encerrar_pratica_profissional),
    path('encerrar_estagio_abandono_matricula_irregular/<int:pk>/', views.encerrar_estagio_abandono_matricula_irregular),
    path('encerrar_aprendizagem/<int:pk>/', views.encerrar_aprendizagem),
    path('encerrar_aprendizagem_abandono_matricula_irregular/<int:pk>/', views.encerrar_aprendizagem_abandono_matricula_irregular),
    path('encerrar_atividade_profissional_efetiva/<int:pk>/', views.encerrar_atividade_profissional_efetiva),
    path('cadastrar_cancelamento_atividade_profissional_efetiva/<int:pk>/', views.cadastrar_cancelamento_atividade_profissional_efetiva),
    path('avaliar_pratica_profissional_supervisor/', views.avaliar_pratica_profissional_supervisor),
    path('avaliar_aprendizagem_monitor/', views.avaliar_aprendizagem_monitor),
    path('cadastrar_visitapraticaprofissional/<int:pk>/', views.cadastrar_visitapraticaprofissional),
    path('cadastrar_visitapraticaprofissional/<int:pk>/<int:visita_pk>/', views.cadastrar_visitapraticaprofissional),
    path('cadastrar_visita_aprendizagem/<int:pk>/', views.cadastrar_visita_aprendizagem),
    path('cadastrar_visita_aprendizagem/<int:pk>/<int:visita_pk>/', views.cadastrar_visita_aprendizagem),
    path('visualizar_dados_visita/<int:pk>/', views.visualizar_dados_visita),
    path('visualizar_dados_visita_aprendizagem/<int:pk>/', views.visualizar_dados_visita_aprendizagem),
    path('visualizar_relatorio_aprendizagem/<int:pk>/', views.visualizar_relatorio_aprendizagem),
    path('adicionar_estagio_aditivo_contratual/<int:pk>/', views.adicionar_estagio_aditivo_contratual),
    path('adicionar_estagio_aditivo_contratual/<int:pk>/<int:aditivo_pk>/', views.adicionar_estagio_aditivo_contratual),
    path('adicionar_aditivo_contratual_aprendizagem/<int:pk>/', views.adicionar_aditivo_contratual_aprendizagem),
    path('adicionar_aditivo_contratual_aprendizagem/<int:pk>/<int:aditivo_pk>/', views.adicionar_aditivo_contratual_aprendizagem),
    path('submeter_relatorio_semestral/<int:pk>/', views.submeter_relatorio_semestral),
    path('submeter_relatorio_semestral/<int:pk>/<int:relatorio_pk>/', views.submeter_relatorio_semestral),
    path('submeter_relatorio_modulo_aprendizagem/<int:pk>/', views.submeter_relatorio_modulo_aprendizagem),
    path('submeter_relatorio_modulo_aprendizagem/<int:pk>/<int:modulo_pk>/', views.submeter_relatorio_modulo_aprendizagem),
    path('submeter_relatorio_atividade_profissional_efetiva/<int:pk>/', views.submeter_relatorio_atividade_profissional_efetiva),
    path('submeter_relatorio_monitor/<int:pk>/', views.submeter_relatorio_monitor),
    path('submeter_relatorio_monitor/<int:pk>/<int:modulo_pk>/', views.submeter_relatorio_monitor),
    path('avaliar_relatorio_semestral/<int:pk>/', views.avaliar_relatorio_semestral),
    path('registrar_avaliacao_supervisor_pratica_profissional/<int:pk>/', views.registrar_avaliacao_supervisor_pratica_profissional),
    path('registrar_avaliacao_supervisor_pratica_profissional/<int:pk>/<int:relatorio_pk>/', views.registrar_avaliacao_supervisor_pratica_profissional),
    path('agendar_orientacao_estagio/<int:pk>/', views.agendar_orientacao_estagio),
    path('agendar_orientacao_estagio/<int:pk>/<int:orientacao_pk>/', views.agendar_orientacao_estagio),
    path('agendar_orientacao_aprendizagem/<int:pk>/', views.agendar_orientacao_aprendizagem),
    path('agendar_orientacao_aprendizagem/<int:pk>/<int:orientacao_pk>/', views.agendar_orientacao_aprendizagem),
    path('agendar_orientacao_atividade_profissional_efetiva/<int:pk>/', views.agendar_orientacao_atividade_profissional_efetiva),
    path('agendar_orientacao_atividade_profissional_efetiva/<int:pk>/<int:orientacao_pk>/', views.agendar_orientacao_atividade_profissional_efetiva),
    path('enviar_notificacoes_atividade_profissional_efetiva/<int:pk>/', views.enviar_notificacoes_atividade_profissional_efetiva),
    path('justificar_visita_estagio/<int:pk>/', views.justificar_visita_estagio),
    path('ver_justificativa_visita_estagio/<int:pk>/', views.ver_justificativa_visita_estagio),
    path('justificar_visita_aprendizagem/<int:pk>/', views.justificar_visita_aprendizagem),
    path('ver_justificativa_visita_aprendizagem/<int:pk>/', views.ver_justificativa_visita_aprendizagem),
    path('notificar_pendencias_estagio/<int:pk>/', views.notificar_pendencias_estagio),
    path('gerar_relatorio_visita_estagio/<int:pk>/', views.gerar_relatorio_visita_estagio),
    path('gerar_termo_compromisso/<int:pk>/', views.gerar_termo_compromisso),
    path('gerar_termo_compromisso_documentotexto/<int:pk>/', views.gerar_termo_compromisso_documentotexto),
    path('gerar_relatorio_visita_aprendizagem/<int:pk>/', views.gerar_relatorio_visita_aprendizagem),
    path('notificar_pendencias_aprendizagem/<int:pk>/', views.notificar_pendencias_aprendizagem),
]
