# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:57


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acao', models.CharField(max_length=4, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código Completo')),
            ],
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.CreateModel(
            name='AcaoAno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_capital', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Capital')),
                ('valor_custeio', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Custeio')),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Acao', verbose_name='Ação')),
                ('ano_base', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano Base')),
            ],
            options={'verbose_name': 'Ação do Ano', 'verbose_name_plural': 'Ações do Ano'},
        ),
        migrations.CreateModel(
            name='CategoriaEconomicaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Categoria Econômica da Despesa', 'verbose_name_plural': 'Categorias Econômicas da Despesa', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='ClassificacaoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Classificação de Despesa', 'verbose_name_plural': 'Classificações de Despesas'},
        ),
        migrations.CreateModel(
            name='ClassificacaoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Classificação Institucional', 'verbose_name_plural': 'Classificações Institucionais'},
        ),
        migrations.CreateModel(
            name='ElementoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Elemento de Despesa', 'verbose_name_plural': 'Elementos de Despesa', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='EsferaOrcamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Esfera Orçamenária', 'verbose_name_plural': 'Esferas Orçamenárias'},
        ),
        migrations.CreateModel(
            name='EspecificacaoFonteRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Especificação da Fonte de Recurso', 'verbose_name_plural': 'Especificações das Fontes de Recursos', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                (
                    'tipo',
                    models.IntegerField(
                        choices=[
                            [0, 'Bloqueio de Saldo'],
                            [1, 'Crédito Orçamentário'],
                            [2, 'Crédito Orçamentário - Anulação'],
                            [3, 'Crédito Orçamentário - Devolução'],
                            [4, 'Dotação'],
                            [5, 'Dotação - Cancelamento ou Redução'],
                            [6, 'Empenho'],
                            [7, 'Empenho - Anulação'],
                            [8, 'Empenho - Cancelamento'],
                            [9, 'Empenho - Estorno'],
                            [10, 'Empenho - Reforço'],
                            [11, 'Apropriação de Despesas'],
                            [12, 'Apropriação de Despesas - Anulação'],
                            [99, 'Outros'],
                        ],
                        null=True,
                    ),
                ),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.CreateModel(
            name='FonteRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Fonte do recurso')),
                (
                    'especificacao',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EspecificacaoFonteRecurso', verbose_name='Especificação'),
                ),
            ],
            options={'verbose_name': 'Fonte de Recurso', 'verbose_name_plural': 'Fontes de Recursos'},
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='GrupoFonteRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Grupo de Fonte de Recurso', 'verbose_name_plural': 'Grupos de Fontes de Recursos', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='GrupoNaturezaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Grupo de Natureza de Despesa', 'verbose_name_plural': 'Grupos de Naturezas de Despesa', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='IdentificadorResultadoPrimario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Identificador de Resultado Primário', 'verbose_name_plural': 'Identificadores de Resultado Primário', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='IdentificadorUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Identificador de Uso', 'verbose_name_plural': 'Identificadores de Uso', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='InstrumentoLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Instrumento Legal', 'verbose_name_plural': 'Instrumentos Legais'},
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=2, null=True, verbose_name='Sigla')),
            ],
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='LogImportacaoSIAFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[[1, 'Notas de crédito'], [2, 'Notas de dotação'], [3, 'Notas de empenho'], [4, 'Itens de empenho']])),
                ('data_hora', models.DateTimeField()),
                ('nome_arquivo', models.CharField(max_length=50)),
                ('reg_analisados', models.IntegerField()),
                ('nao_importados', models.IntegerField()),
                ('detalhamento', models.TextField(blank=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='ModalidadeAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Modalidade da Aplicação', 'verbose_name_plural': 'Modalidades da Aplicação', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='ModalidadeLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Modalidade de Licitação', 'verbose_name_plural': 'Modalidades de Licitação'},
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('Custeio', 'Custeio'), ('Capital', 'Capital')], max_length=30, null=True, verbose_name='Tipo')),
                (
                    'categoria_economica_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.CategoriaEconomicaDespesa', verbose_name='Categoria Econômica'),
                ),
                (
                    'elemento_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ElementoDespesa', verbose_name='Elemento da Despesa'),
                ),
                (
                    'grupo_natureza_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.GrupoNaturezaDespesa', verbose_name='Grupo Natureza Despesa'),
                ),
                (
                    'modalidade_aplicacao',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ModalidadeAplicacao', verbose_name='Modalidade da Aplicação'),
                ),
            ],
            options={'verbose_name': 'Natureza de Despesa', 'verbose_name_plural': 'Naturezas de Despesas', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='NEItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(verbose_name='Número')),
                ('subitem_original', models.CharField(max_length=2)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Qtd.')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=17)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor unitário')),
                ('data_transacao', models.DateTimeField(verbose_name='Data de Transação')),
            ],
            options={'verbose_name': 'Item da Nota de Empenho', 'verbose_name_plural': 'Itens da Nota de Empenho', 'ordering': ['numero']},
        ),
        migrations.CreateModel(
            name='NEListaItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='Número')),
                ('numero_original', models.CharField(max_length=23, null=True, unique=True, verbose_name='Número Original')),
            ],
            options={'verbose_name': 'Lista de Itens do Empenho', 'verbose_name_plural': 'Listas de Itens dos Empenhos'},
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='Número')),
                ('numero_original', models.CharField(max_length=20, null=True, verbose_name='Número Original')),
                ('datahora_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('tx_cambial', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Taxa Cambial')),
                ('sistema_origem', models.CharField(max_length=10, null=True, verbose_name='Sistema de Origem')),
                ('registro_manual', models.BooleanField(default=False)),
                (
                    'emitente_ci',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='nc_emitente_ci', to='financeiro.ClassificacaoInstitucional', verbose_name='Gestão Emitente'
                    ),
                ),
            ],
            options={'verbose_name': 'Nota de Crédito', 'verbose_name_plural': 'Notas de Crédito'},
        ),
        migrations.CreateModel(
            name='NotaCreditoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_recurso_original', models.CharField(max_length=10)),
                ('subitem', models.CharField(max_length=2, null=True)),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('esfera', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EsferaOrcamentaria')),
                ('evento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Evento')),
                ('fonte_recurso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso')),
                ('natureza_despesa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa')),
                ('nota_credito', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NotaCredito')),
            ],
            options={'verbose_name': 'Item da Nota de Crédito', 'verbose_name_plural': 'Itens da Nota de Crédito'},
        ),
        migrations.CreateModel(
            name='NotaDotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('datahora_emissao', models.DateTimeField()),
                ('datahora_publicacao', models.DateTimeField(null=True)),
                ('num_instrumento_legal', models.CharField(max_length=6, null=True)),
                ('nota_dotacao', models.CharField(max_length=2, null=True)),
                ('observacao', models.TextField()),
                ('tx_cambial', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('detalhamento_modalidade', models.CharField(max_length=1, null=True)),
                ('detalhamento_especie', models.CharField(max_length=1, null=True)),
                (
                    'emitente_ci',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='nd_emitente_ci', to='financeiro.ClassificacaoInstitucional'),
                ),
            ],
            options={'verbose_name': 'Nota de Dotação', 'verbose_name_plural': 'Notas de Dotação'},
        ),
        migrations.CreateModel(
            name='NotaDotacaoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_recurso_original', models.CharField(max_length=10)),
                ('subitem', models.CharField(max_length=2, null=True)),
                ('idoc', models.CharField(max_length=4, null=True)),
                ('resultado', models.CharField(max_length=1, null=True)),
                ('tipo_credito', models.CharField(max_length=1, null=True)),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('esfera', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EsferaOrcamentaria')),
                ('evento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Evento')),
                ('fonte_recurso', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso')),
                ('natureza_despesa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa')),
                ('nota_dotacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NotaDotacao')),
            ],
            options={'verbose_name': 'Item da Nota de Dotação', 'verbose_name_plural': 'Itens da Nota de Dotação'},
        ),
        migrations.CreateModel(
            name='NotaEmpenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='Número')),
                ('data_emissao', djtools.db.models.DateFieldPlus(verbose_name='Data de Emissão')),
                ('codigo_terminal', models.CharField(blank=True, max_length=50, verbose_name='Código do Terminal')),
                ('data_transacao', models.DateTimeField(verbose_name='Data da Transação')),
                ('favorecido_original', models.CharField(blank=True, max_length=14)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('fonte_recurso_original', models.CharField(blank=True, max_length=10, verbose_name='Fonte de recurso original')),
                ('tipo', models.CharField(blank=True, choices=[['', 'Desconhecido'], ['1', 'Ordinário'], ['3', 'Estimativa'], ['5', 'Global']], max_length=1)),
                ('amparo_legal', models.CharField(blank=True, max_length=8)),
                ('inciso', models.CharField(blank=True, max_length=2)),
                ('processo', models.CharField(blank=True, max_length=20)),
                (
                    'origem_material',
                    models.CharField(
                        blank=True, choices=[['', 'Desconhecido'], ['1', 'Nacional'], ['2', 'Estrangeiro adquirido no Brasil'], ['3', 'Importação direta']], max_length=1
                    ),
                ),
                ('referencia_empenho_original', models.CharField(blank=True, max_length=12)),
                ('referencia_dispensa', models.CharField(blank=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('registro_manual', models.BooleanField(default=False)),
            ],
            options={'verbose_name': 'Nota de Empenho', 'verbose_name_plural': 'Notas de Empenho'},
        ),
        migrations.CreateModel(
            name='NotaSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('data_emissao', models.DateTimeField()),
                ('data_valorizacao', models.DateTimeField(null=True)),
                ('datahora_transacao', models.DateTimeField(null=True)),
                ('titulo_credito', models.CharField(max_length=12, null=True)),
                ('data_venc_tit_credito', models.DateTimeField(null=True)),
                ('favorecido_original', models.CharField(blank=True, max_length=14)),
                ('observacao', models.TextField()),
                ('sistema_origem', models.CharField(blank=True, max_length=10, null=True)),
                ('gestao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ClassificacaoInstitucional')),
            ],
            options={'verbose_name': 'Nota de Sistema', 'verbose_name_plural': 'Notas de Sistema'},
        ),
        migrations.CreateModel(
            name='NotaSistemaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_1', models.CharField(max_length=14, null=True)),
                ('inscricao_2', models.CharField(max_length=14, null=True)),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                (
                    'classif_desp_1',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacao_despesa_1', to='financeiro.ClassificacaoDespesa'
                    ),
                ),
                (
                    'classif_desp_2',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacao_despesa_2', to='financeiro.ClassificacaoDespesa'
                    ),
                ),
            ],
            options={'verbose_name': 'Item da Nota de Sistema', 'verbose_name_plural': 'Itens da Nota de Sistema'},
        ),
        migrations.CreateModel(
            name='PlanoInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('objetivo', models.TextField(null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('esfera_orcamentaria', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.EsferaOrcamentaria')),
                (
                    'orgao',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgao', to='financeiro.ClassificacaoInstitucional'),
                ),
            ],
            options={'verbose_name': 'Plano Interno', 'verbose_name_plural': 'Planos Internos'},
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.CreateModel(
            name='ProgramaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=17, unique=True, verbose_name='Código Completo')),
                ('ativo', models.BooleanField(default=True)),
                ('acao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Acao', verbose_name='Ação')),
                ('funcao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Funcao', verbose_name='Função')),
                ('localizacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Localizacao', verbose_name='Localização')),
                ('municipio', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Municipio', verbose_name='Município')),
            ],
            options={'verbose_name': 'Programa de Trabalho', 'verbose_name_plural': 'Programas de Trabalho'},
        ),
        migrations.CreateModel(
            name='ProgramaTrabalhoResumido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('tipo_credito', models.CharField(max_length=1, null=True, verbose_name='Tipo de Crédito')),
                ('ativo', models.BooleanField(default=True)),
                (
                    'classificacao_institucional',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ClassificacaoInstitucional', verbose_name='Classificação Institucional'
                    ),
                ),
                (
                    'programa_trabalho',
                    djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalho', verbose_name='Programa de Trabalho'),
                ),
                (
                    'resultado_primario',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.IdentificadorResultadoPrimario', verbose_name='Resultado Primário'
                    ),
                ),
            ],
            options={'verbose_name': 'Programa de Trabalho Resumido', 'verbose_name_plural': 'Programas de Trabalho Resumido'},
        ),
        migrations.CreateModel(
            name='SubElementoNaturezaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_subelemento', models.CharField(max_length=2, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                (
                    'natureza_despesa',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa', verbose_name='Natureza de Despesa'),
                ),
            ],
            options={'verbose_name': 'Subelemento da Natureza de Despesa', 'verbose_name_plural': 'Subelementos da Natureza de Despesa'},
        ),
        migrations.CreateModel(
            name='Subfuncao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Subfunção', 'verbose_name_plural': 'Subfunções', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('mnemonico', models.CharField(max_length=20, null=True, verbose_name='Mnemônico')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                (
                    'funcao',
                    models.CharField(
                        choices=[['', ''], ['Executora', 'Executora'], ['Credora', 'Credora'], ['Controle', 'Controle']], default='', max_length=15, verbose_name='Função'
                    ),
                ),
                ('ativo', models.BooleanField(default=True)),
                ('municipio', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Municipio')),
                ('setor', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Setor')),
                ('uo', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional')),
            ],
            options={'verbose_name': 'Unidade Gestora', 'verbose_name_plural': 'Unidades Gestoras'},
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AddField(
            model_name='programatrabalho',
            name='subfuncao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Subfuncao', verbose_name='Subfunção'),
        ),
        migrations.AlterUniqueTogether(name='programa', unique_together=set([('codigo', 'nome')])),
        migrations.AddField(
            model_name='planointerno',
            name='programa_trabalho',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalho'),
        ),
        migrations.AddField(
            model_name='planointerno',
            name='unidade_gestora',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.UnidadeGestora'),
        ),
        migrations.AddField(
            model_name='planointerno',
            name='unidade_orcamentaria',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidade_orcamentaria', to='financeiro.ClassificacaoInstitucional'
            ),
        ),
        migrations.AddField(
            model_name='notasistemaitem',
            name='despesa_1',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_1', to='financeiro.SubElementoNaturezaDespesa'),
        ),
        migrations.AddField(
            model_name='notasistemaitem',
            name='despesa_2',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_2', to='financeiro.SubElementoNaturezaDespesa'),
        ),
        migrations.AddField(
            model_name='notasistemaitem', name='evento', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Evento')
        ),
        migrations.AddField(
            model_name='notasistemaitem', name='nota_sistema', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NotaSistema')
        ),
        migrations.AddField(
            model_name='notasistema', name='ug', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.UnidadeGestora')
        ),
        migrations.AddField(
            model_name='notasistema',
            name='vinculo_favorecido',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_favorecido_notasistema', to='comum.Vinculo'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='emitente_ug',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='ug', to='financeiro.UnidadeGestora', verbose_name='UG Emitente'),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='esfera_orcamentaria',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.EsferaOrcamentaria', verbose_name='Esfera orçamentária'
            ),
        ),
        migrations.AddField(model_name='notaempenho', name='evento', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Evento')),
        migrations.AddField(
            model_name='notaempenho',
            name='fonte_recurso',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.FonteRecurso', verbose_name='Fonte de recurso'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='modalidade_licitacao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ModalidadeLicitacao', verbose_name='Modalidade de Licitação'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='natureza_despesa',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.NaturezaDespesa', verbose_name='Natureza de Despesa'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='plano_interno',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanoInterno'),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='ptres',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalhoResumido', verbose_name='PTRES'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='referencia_empenho',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.NotaEmpenho'),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='referencia_ug',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ug_referencia', to='financeiro.UnidadeGestora', verbose_name='UG Referência'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='ug_operador',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='operador_ug', to='financeiro.UnidadeGestora'),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='ugr',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ug_responsavel', to='financeiro.UnidadeGestora', verbose_name='UG Responsável'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='vinculo_favorecido',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_favorecido_notaempenho', to='comum.Vinculo'
            ),
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='vinculo_operador',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_operador_notaempenho', to='comum.Vinculo'),
        ),
        migrations.AddField(
            model_name='notadotacaoitem',
            name='plano_interno',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanoInterno'),
        ),
        migrations.AddField(
            model_name='notadotacaoitem',
            name='ptres',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalhoResumido'),
        ),
        migrations.AddField(
            model_name='notadotacaoitem', name='ugr', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.UnidadeGestora')
        ),
        migrations.AddField(
            model_name='notadotacao',
            name='emitente_ug',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='nd_emitente_ug', to='financeiro.UnidadeGestora'),
        ),
        migrations.AddField(
            model_name='notadotacao',
            name='favorecido_ci',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nd_favorecido_ci', to='financeiro.ClassificacaoInstitucional'
            ),
        ),
        migrations.AddField(
            model_name='notadotacao',
            name='favorecido_ug',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nd_favorecido_ug', to='financeiro.UnidadeGestora'),
        ),
        migrations.AddField(
            model_name='notadotacao',
            name='instrumento_legal',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.InstrumentoLegal'),
        ),
        migrations.AddField(
            model_name='notacreditoitem',
            name='plano_interno',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.PlanoInterno'),
        ),
        migrations.AddField(
            model_name='notacreditoitem',
            name='ptres',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ProgramaTrabalhoResumido'),
        ),
        migrations.AddField(
            model_name='notacreditoitem', name='ugr', field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.UnidadeGestora')
        ),
        migrations.AddField(
            model_name='notacredito',
            name='emitente_ug',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='nc_emitente_ug', to='financeiro.UnidadeGestora', verbose_name='UG Emitente'
            ),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='favorecido_ci',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='nc_favorecido_ci', to='financeiro.ClassificacaoInstitucional', verbose_name='Gestão Favorecida'
            ),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='favorecido_ug',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='nc_favorecido_ug', to='financeiro.UnidadeGestora', verbose_name='UG Favorecida'
            ),
        ),
        migrations.AddField(
            model_name='nelistaitens',
            name='nota_empenho',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.NotaEmpenho'),
        ),
        migrations.AddField(
            model_name='neitem', name='lista_itens', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.NEListaItens')
        ),
        migrations.AddField(
            model_name='neitem',
            name='subitem',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.SubElementoNaturezaDespesa'),
        ),
        migrations.AddField(
            model_name='fonterecurso',
            name='grupo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.GrupoFonteRecurso', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='acaoano',
            name='ptres',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_ano_ptres', to='financeiro.ProgramaTrabalhoResumido', verbose_name='PTRES'
            ),
        ),
        migrations.AddField(model_name='acao', name='programa', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Programa')),
        migrations.AlterUniqueTogether(name='subelementonaturezadespesa', unique_together=set([('codigo_subelemento', 'natureza_despesa')])),
        migrations.AlterUniqueTogether(name='notasistema', unique_together=set([('ug', 'numero')])),
        migrations.AlterUniqueTogether(name='notaempenho', unique_together=set([('emitente_ug', 'numero')])),
        migrations.AlterUniqueTogether(name='notadotacao', unique_together=set([('emitente_ug', 'numero')])),
        migrations.AlterUniqueTogether(name='notacredito', unique_together=set([('emitente_ug', 'numero')])),
        migrations.AlterUniqueTogether(name='neitem', unique_together=set([('lista_itens', 'numero')])),
        migrations.AlterUniqueTogether(
            name='naturezadespesa', unique_together=set([('categoria_economica_despesa', 'grupo_natureza_despesa', 'modalidade_aplicacao', 'elemento_despesa')])
        ),
        migrations.AlterUniqueTogether(name='fonterecurso', unique_together=set([('grupo', 'especificacao')])),
        migrations.AlterUniqueTogether(name='acaoano', unique_together=set([('ano_base', 'acao', 'ptres')])),
        migrations.AlterUniqueTogether(name='acao', unique_together=set([('codigo_acao', 'programa')])),
    ]
