# Generated by Django 2.2.16 on 2021-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculovittaelattes',
            name='ano_fim_exercicio',
            field=models.IntegerField(null=True, verbose_name='Ano de Fim do Exercício na Instituição'),
        ),
        migrations.AddField(
            model_name='curriculovittaelattes',
            name='ano_inicio_exercicio',
            field=models.IntegerField(null=True, verbose_name='Ano de Início do Exercício na Instituição'),
        ),
        migrations.AddField(
            model_name='curriculovittaelattes',
            name='data_fim_exercicio',
            field=models.DateField(null=True, verbose_name='Data de Fim do Exercício na Instituição'),
        ),
        migrations.AddField(
            model_name='curriculovittaelattes',
            name='data_inicio_exercicio',
            field=models.DateField(null=True, verbose_name='Data de Início do Exercício na Instituição'),
        ),
    ]
