# Generated by Django 2.2.16 on 2021-05-18 11:27

from django.db import migrations
from django.core.management import call_command


def atualizar_datas_do_servidor(apps, schema):
    call_command('atualizar_datas_do_servidor')


class Migration(migrations.Migration):

    dependencies = [
        ('cnpq', '0002_auto_20210518_1127'),
    ]

    operations = [migrations.RunPython(atualizar_datas_do_servidor)]
