# Generated by Django 3.2.5 on 2022-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpq', '0004_auto_20210719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculovittaelattes',
            name='data_importacao_grupos_pesquisa',
            field=models.DateTimeField(null=True),
        ),
    ]
