# Generated by Django 3.2.5 on 2022-02-18 17:53

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpq', '0005_curriculovittaelattes_data_importacao_grupos_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculovittaelattes',
            name='data_extracao',
            field=djtools.db.models.DateTimeFieldPlus(auto_now=True, null=True, verbose_name='Data da Última Extração'),
        ),
    ]
