# Generated by Django 3.2.5 on 2022-06-28 08:46

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpq', '0007_remove_curriculovittaelattes_pessoa_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculovittaelattes',
            name='data_extracao',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Última Extração'),
        ),
    ]
