# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comum', '0002_auto_20190814_1443'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(blank=True, choices=[[1, 1], [2, 2]], null=True, verbose_name='Período Letivo')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('envolve_reitoria', models.BooleanField(default=True, verbose_name='Reitoria')),
                ('envolve_campus_ead', models.BooleanField(default=True, verbose_name='Campus EAD')),
                ('envolve_campus_produtivos', models.BooleanField(default=True, verbose_name='Campus com Unidade Produtiva')),
                ('envolve_campus_nao_produtivos', models.BooleanField(default=True, verbose_name='Campus em Unidade Produtiva')),
                ('token', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Token de Acesso')),
            ],
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
            options={'verbose_name': 'Dimensão', 'verbose_name_plural': 'Dimensões', 'ordering': ('eixo', 'ordem')},
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
            options={'verbose_name': 'Eixo', 'verbose_name_plural': 'Eixos', 'ordering': ('ordem',)},
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Denominação do Indicador')),
                ('aspecto', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Critério de Análise')),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('em_uso', models.BooleanField(default=True, verbose_name='Em uso')),
                ('tipo', models.IntegerField(choices=[[0, 'Qualitativo'], [1, 'Quantitativo']], default=0)),
                ('automatico', models.BooleanField(default=False, verbose_name='Autocalculado')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Resposta Obrigatória')),
                ('gestor_responde_como_docente', models.BooleanField(default=False, verbose_name='Gestor responde também como Docente')),
                (
                    'periodo_curso',
                    models.IntegerField(
                        choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8]],
                        default=1,
                        help_text='Período mínimo do estudante no curso',
                        verbose_name='Período Mínimo',
                    ),
                ),
                ('envolve_reitoria', models.BooleanField(default=True, verbose_name='Reitoria')),
                ('envolve_campus_ead', models.BooleanField(default=True, verbose_name='Campus EAD')),
                ('envolve_campus_produtivos', models.BooleanField(default=True, verbose_name='Campus com Unidade Produtiva')),
                ('envolve_campus_nao_produtivos', models.BooleanField(default=True, verbose_name='Campus sem Unidade Produtiva')),
                (
                    'tipo_resposta',
                    models.IntegerField(
                        choices=[
                            [1, 'Texto Curto'],
                            [2, 'Texto Longo'],
                            [3, 'Número Inteiro'],
                            [4, 'Número Decimal'],
                            [8, 'Escala Padrão'],
                            [9, 'Grau de Satisfação'],
                            [5, 'Única Escolha'],
                            [6, 'Múltipla Escolha'],
                            [7, 'Conjunto de Variáveis'],
                        ],
                        verbose_name='Tipo',
                    ),
                ),
                ('valor_minimo', models.IntegerField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.IntegerField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('formula', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Fórmula')),
                ('anos_referencia', models.ManyToManyField(to='comum.Ano', verbose_name='Anos de Referência')),
                ('areas_vinculacao', djtools.db.models.ManyToManyFieldPlus(to='rh.AreaVinculacao', verbose_name='Áreas')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ('macroprocesso__dimensao__eixo__ordem', 'macroprocesso__dimensao__ordem', 'macroprocesso__ordem', 'ordem'),
            },
        ),
        migrations.CreateModel(
            name='Iterador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'objeto',
                    djtools.db.models.CharFieldPlus(
                        choices=[['edu.CursoCampus', 'Curso'], ['edu.Modalidade', 'Modalidade'], ['edu.Professor', 'Professor'], ['edu.Turma', 'Turma']], max_length=255
                    ),
                ),
                ('indicador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Indicador', verbose_name='Indicador')),
            ],
            options={'verbose_name': 'Iterador', 'verbose_name_plural': 'Iteradores', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Macroprocesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('dimensao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Dimensao', verbose_name='Dimensão')),
            ],
            options={'verbose_name': 'Macroprocesso', 'verbose_name_plural': 'Macroprocessos', 'ordering': ('dimensao__eixo', 'dimensao', 'ordem')},
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('indicador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Indicador', verbose_name='Indicador')),
            ],
            options={'verbose_name': 'Opção de Resposta', 'verbose_name_plural': 'Opções de Resposta', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Respondente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Questionário Finalizado')),
                ('avaliacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Avaliacao', verbose_name='Avaliação')),
            ],
            options={'verbose_name': 'Respondente', 'verbose_name_plural': 'Respondentes', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='')),
                ('identificador', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Identificador')),
                ('valor', models.TextField()),
                (
                    'content_type',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type'
                    ),
                ),
                ('indicador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Indicador', verbose_name='Indicador')),
                ('respondente', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Respondente', verbose_name='Respondente')),
            ],
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Resposta', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Segmento Respondente', 'verbose_name_plural': 'Segmentos Respondentes', 'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Avaliação', 'verbose_name_plural': 'Tipos de Avaliação', 'ordering': ('descricao',)},
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Sigla')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
                ('tipo', models.IntegerField(choices=[[3, 'Número Inteiro'], [4, 'Número Decimal']])),
                ('valor_minimo', models.IntegerField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.IntegerField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('indicador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Indicador', verbose_name='Indicador')),
            ],
            options={'verbose_name': 'Variável', 'verbose_name_plural': 'Variáveis', 'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='resposta',
            name='variavel',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Variavel', verbose_name='Variável'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='segmento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='uo',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='respondente',
            name='user',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='iterador',
            name='segmento',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='macroprocesso',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Macroprocesso', verbose_name='Macroprocessos'),
        ),
    ]
