# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('edu', '0001_initial'), ('rh', '0001_initial'), ('avaliacao_integrada', '0001_initial')]

    operations = [
        migrations.AddField(model_name='indicador', name='modalidades', field=djtools.db.models.ManyToManyFieldPlus(to='edu.Modalidade', verbose_name='Modalidades')),
        migrations.AddField(
            model_name='indicador', name='segmentos', field=djtools.db.models.ManyToManyFieldPlus(to='avaliacao_integrada.Segmento', verbose_name='Segmentos Respondentes')
        ),
        migrations.AddField(
            model_name='indicador', name='subsidio_para', field=djtools.db.models.ManyToManyFieldPlus(to='avaliacao_integrada.TipoAvaliacao', verbose_name='Subsídio p/ Avaliações')
        ),
        migrations.AddField(model_name='indicador', name='uos', field=djtools.db.models.ManyToManyFieldPlus(to='rh.UnidadeOrganizacional', verbose_name='Campi')),
        migrations.AddField(
            model_name='dimensao',
            name='eixo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_integrada.Eixo', verbose_name='Eixo'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ano',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano de Referência'),
        ),
        migrations.AddField(
            model_name='avaliacao', name='areas_vinculacao', field=djtools.db.models.ManyToManyFieldPlus(to='rh.AreaVinculacao', verbose_name='Áreas de Vinculação')
        ),
        migrations.AddField(model_name='avaliacao', name='modalidades', field=djtools.db.models.ManyToManyFieldPlus(to='edu.Modalidade', verbose_name='Modalidades')),
        migrations.AddField(
            model_name='avaliacao', name='segmentos', field=djtools.db.models.ManyToManyFieldPlus(to='avaliacao_integrada.Segmento', verbose_name='Segmentos Respondentes')
        ),
        migrations.AddField(model_name='avaliacao', name='tipos', field=models.ManyToManyField(to='avaliacao_integrada.TipoAvaliacao', verbose_name='Tipo')),
        migrations.AddField(model_name='avaliacao', name='uos', field=djtools.db.models.ManyToManyFieldPlus(to='rh.UnidadeOrganizacional', verbose_name='Campi')),
    ]
