# Generated by Django 2.2.7 on 2019-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('avaliacao_integrada', '0002_auto_20190814_1454')]

    operations = [migrations.AddField(model_name='indicador', name='texto_ajuda', field=models.TextField(blank=True, null=True, verbose_name='Texto de Ajuda'))]
