# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('ponto', '__first__'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='ServidorCessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo_exercicio',
                    models.IntegerField(
                        choices=[[1, 'Cessão'], [2, 'Requisição'], [3, 'Exercício Provisório'], [4, 'Cooperação Técnica']], default=1, verbose_name='Tipo de Exercício'
                    ),
                ),
                ('numero_portaria', models.IntegerField(blank=True, null=True, verbose_name='Número da Portaria')),
                (
                    'ressarcimento_mensal',
                    models.BooleanField(
                        choices=[[True, 'Sim'], [False, 'Não']],
                        default=False,
                        help_text='Ressarcimento mensal da remuneração do servidor por parte do órgão cessionário',
                        verbose_name='Com Ressarcimento',
                    ),
                ),
                (
                    'data_limite_retorno',
                    models.DateField(
                        blank=True, help_text='Data na qual o servidor deverá retornar (deixe em branco para retorno indeterminado)', null=True, verbose_name='Data Limite'
                    ),
                ),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_prazo', models.IntegerField(choices=[[1, 'No prazo'], [2, 'Esgotando'], [3, 'Esgotado']], default=1, verbose_name='Situação do Prazo')),
                ('status_processo', models.IntegerField(choices=[[1, 'Ativo'], [2, 'Finalizado']], default=1, verbose_name='Situação do Processo')),
                (
                    'instituicao_destino',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Instituicao', verbose_name='Instituição/Órgão Destino'
                    ),
                ),
                ('servidor_cedido', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor Cedido')),
                (
                    'tipo_afastamento',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        help_text='Ponto SUAP: Tipo de Afastamento a partir do qual será criado um Afastamento a cada Frequência enviada.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ponto.TipoAfastamento',
                        verbose_name='Tipo de Afastamento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercício Externo',
                'verbose_name_plural': 'Exercícios Externos',
                'ordering': ('data_limite_retorno',),
                'permissions': (('pode_adicionar_frequencia', 'Pode Adicionar Frequência'),),
            },
        ),
        migrations.CreateModel(
            name='ServidorCessaoFrequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', djtools.db.models.DateFieldPlus(verbose_name='Data Inicial')),
                ('data_final', djtools.db.models.DateFieldPlus(verbose_name='Data Final')),
                ('arquivo', models.FileField(upload_to='')),
                ('data_envio', djtools.db.models.DateFieldPlus(editable=False, verbose_name='Data do Envio')),
                ('afastamento', djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto.Afastamento')),
                ('enviado_por', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servidor_cessao', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='acompanhamentofuncional.ServidorCessao')),
            ],
            options={'verbose_name': 'Frequência de Exercício Externo', 'verbose_name_plural': 'Frequências de Exercícios Externos', 'ordering': ('-data_inicial',)},
        ),
        migrations.AlterUniqueTogether(name='servidorcessao', unique_together=set([('numero_portaria',)])),
    ]
