# Generated by Django 2.2.16 on 2020-09-23 18:20

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_auto_20200516_0227'),
        ('acompanhamentofuncional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtoConfiguracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ato', djtools.db.models.PositiveIntegerFieldPlus(choices=[[1, 'Admissão de pessoal'], [2, 'Concessão de aposentadoria'], [3, 'Concessão de pensão civil']], verbose_name='Tipo de ato')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('prazo_envio', djtools.db.models.PositiveIntegerFieldPlus(default=60, verbose_name='Prazo de envio ao E-Pessoal (em dias)')),
            ],
            options={
                'verbose_name': 'Configuração de Tipo de Ato de Admissão/Concessão',
                'verbose_name_plural': 'Configurações de Tipos de Atos de Admissão/Concessão',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', djtools.db.models.PositiveIntegerFieldPlus(choices=[[1, 'Admissão de pessoal'], [2, 'Concessão de aposentadoria'], [3, 'Concessão de pensão civil']], verbose_name='Tipo de ato')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da ocorrência do ato')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data da publicação do ato')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data da emissão do ato')),
                ('numero', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Número do ato')),
                ('numero_doc_eletronico', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Número do documento eletrônico')),
                ('prazo_envio', djtools.db.models.PositiveIntegerFieldPlus(verbose_name='Prazo de envio ao E-Pessoal (em dias)')),
                ('data_limite_envio', models.DateField(editable=False, null=True, verbose_name='Data limite de envio do ato')),
                ('situacao_envio', djtools.db.models.PositiveIntegerFieldPlus(choices=[[1, 'Pendente'], [2, 'Enviado'], [3, 'Cancelado']], verbose_name='Situação de envio')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de envio do ato')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do cancelamento')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Ato de Admissão/Concessão',
                'verbose_name_plural': 'Atos de Admissão/Concessão',
                'ordering': ('servidor__nome',),
            },
        ),
    ]
