# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 12:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('ponto', '0002_auto_20190927_1851')]

    operations = [
        migrations.AlterField(
            model_name='recessoopcaoescolhida',
            name='recesso_opcao',
            field=djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ponto.RecessoOpcao', verbose_name='Opção de Compensação'),
        )
    ]
