# Generated by Django 2.2.10 on 2020-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ponto', '0003_auto_20191018_1224')]

    operations = [
        migrations.AlterField(
            model_name='abonochefia',
            name='acao_abono',
            field=models.PositiveIntegerField(
                choices=[
                    [1, 'Abonado com compensação de horário'],
                    [2, 'Abonado sem compensação de horário'],
                    [9, 'Trabalho Remoto'],
                    [0, 'Não abonado'],
                    [7, 'Tempo de trabalho excedente para compensação de carga-horária (até o limite de 10h de trabalho por dia)'],
                    [4, 'Hora extra justificada (até o limite de 10h de trabalho por dia)'],
                    [3, 'Hora extra não justificada'],
                    [6, 'Trabalho no fim de semana autorizado para compensação de carga horária'],
                    [8, 'Trabalho no fim de semana autorizado como hora extra'],
                    [5, 'Trabalho no fim de semana não justificado/autorizado'],
                ],
                default=0,
                verbose_name='Ação chefia imediata',
            ),
        )
    ]
