# Generated by Django 2.2.10 on 2020-04-13 15:24

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('ponto', '0004_auto_20200325_1614')]

    operations = [
        migrations.AlterField(model_name='observacao', name='data', field=models.DateField(db_index=True, verbose_name='Data da Frequência')),
        migrations.AlterField(model_name='observacao', name='data_cadastro', field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
        migrations.AlterField(model_name='observacao', name='descricao', field=models.TextField(verbose_name='Observação')),
        migrations.AlterField(
            model_name='observacao',
            name='vinculo',
            field=djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo'),
        ),
    ]
