# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_auto_20200413_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='ativo',
            field=models.BooleanField(default=None, help_text='Caso seja desconhecido, a máquina ainda não foi aceita pelo administrador do SUAP.', null=True, verbose_name='Ativa'),
        ),
    ]
