# Generated by Django 3.2.5 on 2022-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0007_auto_20220204_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
    ]
