# Generated by Django 3.2.5 on 2022-05-25 15:19

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0040_auto_20220510_1439'),
        ('ponto', '0009_documentoanexo_vinculo'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='documentoanexo',
            name='pessoa',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoanexo',
            name='vinculo',
            field=djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo'),
        ),
        migrations.AlterField(
            model_name='documentoanexo',
            name='pessoa',
            field=djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoa', null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
