# Generated by Django 2.2.7 on 2019-11-13 16:44

import calculos_pagamentos.models.calculos
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('calculos_pagamentos', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='nivelvencimentotaeporclasseepadrao',
            name='nivel',
            field=djtools.db.models.ForeignKeyPlus(
                limit_choices_to={'categoria': 'tecnico_administrativo'},
                on_delete=django.db.models.deletion.CASCADE,
                to='calculos_pagamentos.NivelVencimento',
                verbose_name='Nível de Vencimento de TAE',
            ),
        ),
        migrations.AlterField(
            model_name='periodocalculoprogressao',
            name='titulacao_nova',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.all_titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_nova4periodocalculoprogressao',
                to='rh.Titulacao',
                verbose_name='Titulação Nova',
            ),
        ),
        migrations.AlterField(
            model_name='periodocalculoprogressao',
            name='titulacao_passada',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.all_titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_passada4periodocalculoprogressao',
                to='rh.Titulacao',
                verbose_name='Titulação Anterior',
            ),
        ),
        migrations.AlterField(
            model_name='periodomudancaregime',
            name='titulacao_nova',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.all_titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_nova4calculos_pagamentos_periodomudancaregime',
                to='rh.Titulacao',
                verbose_name='Titulação',
            ),
        ),
        migrations.AlterField(
            model_name='periodorsc',
            name='titulacao_nova',
            field=djtools.db.models.ForeignKeyPlus(
                limit_choices_to=calculos_pagamentos.models.calculos.rsc_choices,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_nova4calculos_pagamentos_periodorsc',
                to='rh.Titulacao',
                verbose_name='Titulação Nova',
            ),
        ),
        migrations.AlterField(
            model_name='periodorsc',
            name='titulacao_passada',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_passada4calculos_pagamentos_periodorsc',
                to='rh.Titulacao',
                verbose_name='Titulação Anterior',
            ),
        ),
        migrations.AlterField(
            model_name='periodort',
            name='titulacao_nova',
            field=djtools.db.models.ForeignKeyPlus(
                limit_choices_to=calculos_pagamentos.models.calculos.titulacoes_choices,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_nova4calculos_pagamentos_periodort',
                to='rh.Titulacao',
                verbose_name='Titulação Nova',
            ),
        ),
        migrations.AlterField(
            model_name='periodort',
            name='titulacao_passada',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao_passada4calculos_pagamentos_periodort',
                to='rh.Titulacao',
                verbose_name='Titulação Anterior',
            ),
        ),
        migrations.AlterField(
            model_name='periodoterminocontrato',
            name='titulacao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                limit_choices_to=calculos_pagamentos.models.calculos.all_titulacoes_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='titulacao4periodocalculoterminocontrato',
                to='rh.Titulacao',
                verbose_name='Titulação',
            ),
        ),
        migrations.AlterField(
            model_name='valorretribuicaotitulacao',
            name='nivel',
            field=djtools.db.models.ForeignKeyPlus(
                limit_choices_to={'categoria': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to='calculos_pagamentos.NivelVencimento', verbose_name='Nível de Vencimento'
            ),
        ),
        migrations.AlterField(
            model_name='valorretribuicaotitulacao',
            name='titulacoes',
            field=models.ManyToManyField(
                limit_choices_to=models.Q(models.Q(('codigo__gte', '23'), ('codigo__lte', '27')), models.Q(('codigo__gte', '48'), ('codigo__lte', '50')), _connector='OR'),
                related_name='titulacao4valorretribuicaotitulacao',
                to='rh.Titulacao',
                verbose_name='Titulações',
            ),
        ),
    ]
