# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 16:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('calculos_pagamentos', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='MotivoSubstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Motivo do Afastamento', 'verbose_name_plural': 'Motivos do Afastamento'},
        ),
        migrations.AlterField(
            model_name='calculosubstituicao',
            name='motivo_substituicao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='calculos_pagamentos.MotivoSubstituicao', verbose_name='Motivo do Afastamento'),
        ),
    ]
