# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('calculos_pagamentos', '0002_auto_20191112_1645')]

    operations = [
        migrations.AlterField(
            model_name='historicopagamento',
            name='situacao',
            field=models.PositiveIntegerField(
                choices=[[1, 'Não processado'], [2, 'Gerado'], [3, 'Aceito'], [4, 'Rejeitado'], [5, 'Lançado Manualmente'], [6, 'Aceito Parcialmente'], [7, 'Excluído']],
                verbose_name='Situação',
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='situacao',
            field=models.PositiveIntegerField(
                choices=[[1, 'Não processado'], [2, 'Gerado'], [3, 'Aceito'], [4, 'Rejeitado'], [5, 'Lançado Manualmente'], [6, 'Aceito Parcialmente'], [7, 'Excluído']],
                verbose_name='Situação',
            ),
        ),
    ]
