# Generated by Django 2.2.7 on 2019-11-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('calculos_pagamentos', '0003_auto_20191120_1308'), ('calculos_pagamentos', '0003_auto_20191118_1656')]

    operations = []
