# Generated by Django 3.2.5 on 2022-07-31 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0045_merge_0044_contatoemergencia_0044_merge_20220705_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0040_merge_20220722_1505'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=255, verbose_name='Nº da Inscrição')),
                ('cpf', models.CharField(max_length=250, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=255, null=True, verbose_name='Telefone')),
                ('campus_polo', djtools.db.models.CharFieldPlus(default='', max_length=255, verbose_name='Campus/Polo')),
                ('curso_campus', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.cursocampus', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Candidatos',
                'verbose_name_plural': 'Candidato',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMigracaoVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('is_sisu', models.BooleanField(default=False, verbose_name='SISU?')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Migração de Vaga',
                'verbose_name_plural': 'Configurações de Migração de Vagas',
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('sisu', models.BooleanField(default=False, verbose_name='Sisu?')),
                ('qtd_vagas', models.IntegerField(verbose_name='Quantidade de Vagas')),
                ('qtd_inscricoes', models.IntegerField(verbose_name='Quantidade de Inscrições')),
                ('qtd_inscricoes_confirmadas', models.IntegerField(verbose_name='Quantidade de Inscrições Confirmadas')),
                ('detalhamento_por_campus', models.TextField(verbose_name='Detalhamento por Campus')),
                ('remanescentes', models.BooleanField(default=False, verbose_name='Vagas Remanescentes?')),
                ('matricula_no_polo', models.BooleanField(default=False, verbose_name='Matrícula no Polo?')),
                ('matricula_online', models.BooleanField(default=False, verbose_name='Matrícula Online')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.ano', verbose_name='Ano')),
                ('configuracao_migracao_vagas', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.configuracaomigracaovaga', verbose_name='Configuração de Migração de Vagas')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'permissions': (('pode_ausentar_candidatos', 'Pode Ausentar Candidatos'), ('pode_liberar_periodos', 'Pode Liberar Periodos'), ('pode_matricular_proitec', 'Pode Matricular Alunos Proitec')),
            },
        ),
        migrations.CreateModel(
            name='EditalAdesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ano_edital', models.PositiveIntegerField(help_text='Ano do Edital', null=True, verbose_name='Ano do Edital')),
                ('numero_edital', models.PositiveIntegerField(help_text='Numeração do Edital', null=True, verbose_name='Número do Edital')),
                ('data_inicio_adesao', djtools.db.models.DateTimeFieldPlus(verbose_name='Data de início da adesão')),
                ('data_limite_adesao', djtools.db.models.DateTimeFieldPlus(help_text='Data limite para adesão ao edital pelos campi', verbose_name='Data limite para adesão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='edital_adesao_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital de Adesão',
                'verbose_name_plural': 'Editais de Adesão',
            },
        ),
        migrations.CreateModel(
            name='EditalAdesaoCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero_edital', models.PositiveIntegerField(help_text='Numeração do Edital do campus', null=True, verbose_name='Número do Edital')),
                ('ano_edital', models.PositiveIntegerField(help_text='Ano do Edital do campus', null=True, verbose_name='Ano do Edital')),
                ('data_inicio_inscricoes', djtools.db.models.DateTimeFieldPlus(verbose_name='Data da inscrição')),
                ('data_encerramento_inscricoes', djtools.db.models.DateTimeFieldPlus(help_text='Data limite para encerramento das inscrições', verbose_name='Data de encerramento')),
                ('idade_minima', models.BooleanField(default=False)),
                ('data_aplicacao_prova', djtools.db.models.DateTimeFieldPlus(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='edital_adesao_campus_campus', to='rh.unidadeorganizacional')),
                ('edital_regulador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.editaladesao')),
                ('responsavel', djtools.db.models.ForeignKeyPlus(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='edital_adesao_campus_responsavel_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital de Adesão Campus',
                'verbose_name_plural': 'Editais de Adesão Campus',
                'permissions': (('pode_ver_todos_editais', 'Pode ver todos os editais de adesão'), ('pode_ver_edital_campus', 'pode ver edital os editais de adesão do campus')),
                'unique_together': {('edital_regulador', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='EditalPeriodoLiberacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de início das matrículas')),
                ('data_fim_matricula', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de fim das matrículas')),
                ('data_limite_avaliacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data limite para avaliação')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.edital')),
                ('uo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional')),
                ('usuario', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Liberação Matrícula',
                'verbose_name_plural': 'Períodos de Liberação Matrícula',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('edital', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.edital', verbose_name='Edital')),
                ('forma_ingresso', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.formaingresso', verbose_name='Forma de Igresso')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='OfertaVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, null=True, verbose_name='Quantidade')),
                ('lista', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.lista')),
            ],
            options={
                'verbose_name': 'Oferta de Vaga',
                'verbose_name_plural': 'Ofertas de Vagas',
                'ordering': ('oferta_vaga_curso__curso_campus', 'lista__descricao'),
            },
        ),
        migrations.CreateModel(
            name='RotuloLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Rótulo de Lista',
                'verbose_name_plural': 'Rótulos de Lista',
            },
        ),
        migrations.CreateModel(
            name='TipoEditalAdesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo do Edital de Adesão',
                'verbose_name_plural': 'Tipos de Edital de Adesão',
            },
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('url_editais', djtools.db.models.CharFieldPlus(help_text='Endereço do webservice para listagem de editais.Ex: http://ingresso.ifrn.edu.br/ws/editais/', max_length=255, verbose_name='Url Editais')),
                ('url_edital', djtools.db.models.CharFieldPlus(help_text='Endereço do webservice para importação de edital. Ex: http://ingresso.ifrn.edu.br/ws/edital/%s/', max_length=255, verbose_name='Url Edital')),
                ('url_candidato', djtools.db.models.CharFieldPlus(help_text='Endereço do webservice para importação de candidato. Ex: http://ingresso.ifrn.edu.br/ws/candidato/%s/', max_length=255, verbose_name='Url Candidato')),
                ('url_caracterizacoes', djtools.db.models.CharFieldPlus(help_text='Endereço do webservice para importação de todas as caracterizações socio-econômicas dos candidatos. Ex: http://ingresso.ifrn.edu.br/ws/caracterizacoes/%s/', max_length=255, null=True, verbose_name='Url Caracterizações')),
                ('token', djtools.db.models.CharFieldPlus(blank=True, help_text='Token passado no cabeçalho da requisição (Authorization: XXXXX)', max_length=255, null=True, verbose_name='Token de Autorização')),
                ('is_zipped', models.BooleanField(default=False, verbose_name='É compactado')),
            ],
            options={
                'verbose_name': 'Web Service',
                'verbose_name_plural': 'Web Services',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_vaga', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.ofertavaga')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='PrecedenciaMigracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precedencia', models.IntegerField(verbose_name='Precedência')),
                ('configuracao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.configuracaomigracaovaga', verbose_name='Configuração')),
                ('destino', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='precedenciamigracao_set2', to='processo_seletivo.rotulolista', verbose_name='Lista de Destino')),
                ('origem', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.rotulolista', verbose_name='Lista de Origem')),
            ],
            options={
                'verbose_name': 'Precedência',
                'verbose_name_plural': 'Precedências',
            },
        ),
        migrations.CreateModel(
            name='OfertaVagaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_inscritos', models.IntegerField(default=0, verbose_name='Quantidade de Inscritos')),
                ('campus_polo', djtools.db.models.CharFieldPlus(default='', max_length=255, verbose_name='Campus/Polo')),
                ('curso_campus', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.cursocampus')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.edital')),
                ('linha_pesquisa', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.linhapesquisa')),
                ('turno', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Oferta de Vaga em Curso',
                'verbose_name_plural': 'Ofertas de Vagas em Curso',
                'ordering': ('curso_campus',),
            },
        ),
        migrations.AddField(
            model_name='ofertavaga',
            name='oferta_vaga_curso',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.ofertavagacurso'),
        ),
        migrations.CreateModel(
            name='InscricaoFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[['ALUNO', 'Aluno'], ['SERVIDOR', 'Servidor']], max_length=50, verbose_name='Vínculo')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('telefones', models.CharField(max_length=255)),
                ('banco', models.CharField(max_length=50, null=True)),
                ('numero_agencia', models.CharField(max_length=50, null=True, verbose_name='Número da Agência')),
                ('tipo_conta', models.CharField(choices=[['CORRENTE', 'Conta Corrente'], ['POUPANCA', 'Conta Poupança']], max_length=50, null=True, verbose_name='Tipo da Conta')),
                ('numero_conta', models.CharField(max_length=50, null=True, verbose_name='Número da Conta')),
                ('operacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operação')),
                ('pis_pasep', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS/PASEP')),
                ('outros_processos', models.IntegerField(default=0, help_text='Ex.: 0', verbose_name='Já Participou de outros processos? Quantos?')),
                ('aceito_termos', models.BooleanField(default=False, help_text='Declaro junto à Comissão do Concurso Público o meu interesse em trabalhar como fiscal, bem como a veracidade dos dados acima.', verbose_name='Termo de Compromisso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.editaladesaocampus')),
                ('pessoa_fisica', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_seletivo_inscricaofiscal_set', to='rh.pessoafisica', verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Inscrição para Fiscal',
                'verbose_name_plural': 'Inscrições para Fiscal',
            },
        ),
        migrations.CreateModel(
            name='EditalPeriodoLiberacaoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de início das matrículas')),
                ('data_fim_matricula', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data de fim das matrículas')),
                ('data_limite_avaliacao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data limite para avaliação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('periodo_liberacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.editalperiodoliberacao')),
                ('usuario', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Liberação de Matrícula',
                'verbose_name_plural': 'Histórico de Liberações de Matrícula',
            },
        ),
        migrations.AddField(
            model_name='editaladesao',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.tipoeditaladesao'),
        ),
        migrations.AddField(
            model_name='edital',
            name='webservice',
            field=djtools.db.models.ForeignKeyPlus(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.webservice', verbose_name='WebService'),
        ),
        migrations.CreateModel(
            name='CriacaoVagaRemanescente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now=True, verbose_name='Data')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('oferta_vaga', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.ofertavaga', verbose_name='Oferta de Vaga')),
                ('responsavel', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Criação de Vaga Remanescente',
                'verbose_name_plural': 'Criações de Vaga Remanescente',
            },
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_1',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='processo_seletivo.rotulolista', verbose_name='Prioridade 1'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_10',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='processo_seletivo.rotulolista', verbose_name='Prioridade 10'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_11',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p11', to='processo_seletivo.rotulolista', verbose_name='Prioridade 11'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_12',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p12', to='processo_seletivo.rotulolista', verbose_name='Prioridade 12'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_13',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p13', to='processo_seletivo.rotulolista', verbose_name='Prioridade 13'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_14',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p14', to='processo_seletivo.rotulolista', verbose_name='Prioridade 14'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_15',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p15', to='processo_seletivo.rotulolista', verbose_name='Prioridade 15'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_2',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='processo_seletivo.rotulolista', verbose_name='Prioridade 2'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_3',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='processo_seletivo.rotulolista', verbose_name='Prioridade 3'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_4',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='processo_seletivo.rotulolista', verbose_name='Prioridade 4'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_5',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='processo_seletivo.rotulolista', verbose_name='Prioridade 5'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_6',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='processo_seletivo.rotulolista', verbose_name='Prioridade 6'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_7',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='processo_seletivo.rotulolista', verbose_name='Prioridade 7'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_8',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='processo_seletivo.rotulolista', verbose_name='Prioridade 8'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='lista_9',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='processo_seletivo.rotulolista', verbose_name='Prioridade 9'),
        ),
        migrations.AddField(
            model_name='configuracaomigracaovaga',
            name='listas',
            field=djtools.db.models.ManyToManyFieldPlus(to='processo_seletivo.RotuloLista', verbose_name='Listas'),
        ),
        migrations.CreateModel(
            name='CandidatoVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.IntegerField(verbose_name='Classificação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('situacao', djtools.db.models.CharFieldPlus(choices=[['1', 'Matriculado'], ['2', 'Ausente'], ['3', 'Inapto'], ['4', 'Já Matriculado'], ['5', 'Matrícula Cancelada'], ['6', 'Evadido'], ['7', 'Já Convocado'], ['8', 'Transferido']], max_length=255, null=True, verbose_name='Situação')),
                ('convocacao', models.IntegerField(null=True, verbose_name='Chamada da Convocação')),
                ('candidato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.candidato', verbose_name='Candidato')),
                ('migracao', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migracao_set', to='processo_seletivo.ofertavaga', verbose_name='Migração')),
                ('oferta_vaga', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.ofertavaga', verbose_name='Oferta de Vaga')),
                ('vaga', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Vaga Concorrida',
                'verbose_name_plural': 'Vaga Concorrida',
                'ordering': ('classificacao',),
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='edital',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.edital', verbose_name='Edital'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='turno',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.turno', verbose_name='Turno'),
        ),
        migrations.AlterUniqueTogether(
            name='editaladesao',
            unique_together={('nome', 'numero_edital', 'ano_edital')},
        ),
    ]
