# Generated by Django 3.2.5 on 2023-03-24 12:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0049_auto_20230324_1239'),
        ('processo_seletivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='InscricaoFiscal',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='processo_seletivo_inscricaofiscal_set', to='rh.pessoafisica', verbose_name='Fiscal'),
        ),
    ]
