# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:02


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djtools.db.models
import djtools.storages
import gerenciador_projetos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='HistoricoEvolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                (
                    'anexo',
                    djtools.db.models.PrivateFileField(
                        blank=True,
                        help_text='O formato do arquivo deve ser ".pdf", ".jpeg", ".jpg" ou ".png"',
                        null=True,
                        storage=djtools.storages.get_private_storage(),
                        upload_to=gerenciador_projetos.models.anexos_da_tarefa_path,
                        verbose_name='Anexo',
                    ),
                ),
                ('data_conclusao', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('mensagem_automatica', models.BooleanField(default=False, verbose_name='Mensagem Automática?')),
                (
                    'historicoevolucao_pai',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_historicoevolucao_pai_set',
                        to='gerenciador_projetos.HistoricoEvolucao',
                        verbose_name='Histórico de Evolução Pai',
                    ),
                ),
                (
                    'registrado_por',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_historico_evolucao_registrado_por_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Registrado Por',
                    ),
                ),
            ],
            options={'verbose_name': 'Histórico de Evolução', 'verbose_name_plural': 'Histórico de Evolução', 'ordering': ['tarefa', 'data_hora']},
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(help_text='Informe um nome para a lista', max_length=255, verbose_name='Nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                (
                    'criada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_projeto_criada_por_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Criada Por',
                    ),
                ),
            ],
            options={'verbose_name': 'Lista', 'verbose_name_plural': 'Listas', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='ListaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(verbose_name='Posição')),
                ('lista', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Lista', verbose_name='Lista')),
            ],
            options={'verbose_name': 'Lista de Tarefas Por Projeto', 'verbose_name_plural': 'Listas de Tarefas Por Projeto', 'ordering': ['lista', 'posicao']},
        ),
        migrations.CreateModel(
            name='ListaTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(verbose_name='Posição')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_hora_saida', models.DateTimeField(help_text='Informa a data/hora que a tarefa foi removida desta lista.', null=True, verbose_name='Data/Hora Saída')),
                ('lista', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Lista', verbose_name='Lista')),
                (
                    'registrado_por',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_lista_tarefa_registrado_por_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Registrado Por',
                    ),
                ),
            ],
            options={'verbose_name': 'Lista de Tarefas', 'verbose_name_plural': 'Listas de Tarefas', 'ordering': ['lista', 'posicao']},
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                (
                    'visibilidade',
                    djtools.db.models.CharFieldPlus(
                        choices=[['VisibilidadeProjeto', 'VisibilidadeProjeto'], ['Privado', 'Privado'], ['Público', 'Público']],
                        default='Privado',
                        max_length=255,
                        verbose_name='Visibilidade',
                    ),
                ),
                (
                    'situacao',
                    models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em Andamento'), (3, 'Concluído'), (4, 'Suspenso'), (5, 'Cancelado')], default=1, verbose_name='Situação'),
                ),
                ('data_conclusao_estimada', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data Estimada de Conclusão')),
                ('data_conclusao', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('areas', djtools.db.models.ManyToManyFieldPlus(to='comum.AreaAtuacao', verbose_name='Áreas de Atuação')),
                (
                    'criado_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_projeto_criado_por_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Criado Por',
                    ),
                ),
                (
                    'gerente',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='gerenciador_projeto_gerente_set', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'
                    ),
                ),
                (
                    'interessados',
                    models.ManyToManyField(
                        help_text='Interessados são usuários que possuem acesso de leitura a todas as informações do projeto.',
                        related_name='gerenciador_projeto_interessados_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Interessados',
                    ),
                ),
                (
                    'membros',
                    models.ManyToManyField(
                        help_text='Membros são usuários que podem contribuir com o projeto no desenvolvimento de suas tarefas.',
                        related_name='gerenciador_projeto_membros_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Membros',
                    ),
                ),
                (
                    'projeto_pai',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Projeto', verbose_name='Projeto Pai'
                    ),
                ),
                (
                    'uo',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='gerenciador_projeto_campus', to='rh.UnidadeOrganizacional', verbose_name='Campus'
                    ),
                ),
            ],
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos', 'ordering': ['titulo']},
        ),
        migrations.CreateModel(
            name='RecorrenciaTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo_recorrencia',
                    models.IntegerField(choices=[(1, 'Diariamente'), (2, 'Semanalmente'), (3, 'Mensalmente'), (4, 'Anualmente')], verbose_name='Tipo de Recorrência'),
                ),
                (
                    'dia_da_semana',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')],
                        null=True,
                        verbose_name='Dia da Semana',
                    ),
                ),
                ('dia_do_mes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia do Mês')),
                (
                    'mes_do_ano',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, 'Janeiro'),
                            (2, 'Fevereiro'),
                            (3, 'Março'),
                            (4, 'Abril'),
                            (5, 'Maio'),
                            (6, 'Junho'),
                            (7, 'Julho'),
                            (8, 'Agosto'),
                            (9, 'Setembro'),
                            (10, 'Outubro'),
                            (11, 'Novembro'),
                            (12, 'Dezembro'),
                        ],
                        null=True,
                        verbose_name='Mês do Ano',
                    ),
                ),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data Final')),
            ],
            options={'verbose_name': 'Recorrência da Tarefa', 'verbose_name_plural': 'Recorrências da Tarefa', 'ordering': ['tarefa', 'tipo_recorrencia']},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(help_text='Informe um nome para tag', max_length=255, verbose_name='Nome')),
                (
                    'cor',
                    djtools.db.models.CharFieldPlus(
                        choices=[
                            ('error', 'Vermelho'),
                            ('info', 'Azul'),
                            ('success', 'Verde'),
                            ('warning', 'Amarelo'),
                            ('extra', 'Laranja'),
                            ('extra2', 'Roxo'),
                            ('extra3', 'Azul Escuro'),
                            ('extra4', 'Verde Oceano'),
                            ('extra5', 'Verde Claro'),
                        ],
                        default='info',
                        help_text='Informe uma cor para tag',
                        max_length=255,
                        verbose_name='Cor',
                    ),
                ),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Projeto', verbose_name='Projeto')),
            ],
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                (
                    'prioridade',
                    djtools.db.models.CharFieldPlus(
                        choices=[['PrioridadeTarefa', 'PrioridadeTarefa'], ['Alta', 'Alta'], ['Média', 'Média'], ['Baixa', 'Baixa']],
                        default='Média',
                        max_length=10,
                        verbose_name='Prioridade',
                    ),
                ),
                ('aberto_em', models.DateTimeField(auto_now_add=True, verbose_name='Aberto Em')),
                ('data_inicio', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao_estimada', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data Estimada de Conclusão')),
                ('data_conclusao', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Conclusão')),
                (
                    'atribuido_para',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_tarefa_atribuido_para_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Atribuído para',
                    ),
                ),
                (
                    'atribuido_por',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_tarefa_atribuido_por_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Atrabuído por',
                    ),
                ),
                ('criado_por', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    'lista',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_projetos.Lista', verbose_name='Lista'),
                ),
                (
                    'observadores',
                    models.ManyToManyField(
                        help_text='Vincule a esta tarefa usuários que podem ter interesse em acompanhar o andamento da mesma.',
                        related_name='gerenciador_tarefa_observadores_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Observadores',
                    ),
                ),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Projeto', verbose_name='Projeto')),
                (
                    'tags',
                    djtools.db.models.ManyToManyFieldPlus(
                        blank=True,
                        help_text='Vincule tags nesta tarefa para facilitar a identificação da mesma.',
                        related_name='gerenciador_projetos_tags_set',
                        to='gerenciador_projetos.Tag',
                        verbose_name='Tags',
                    ),
                ),
                (
                    'tarefa_pai',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gerenciador_tarefa_pai_set',
                        to='gerenciador_projetos.Tarefa',
                        verbose_name='Tarefa Pai',
                    ),
                ),
            ],
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas', 'ordering': ['data_inicio', 'data_conclusao']},
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Nome')),
            ],
            options={'verbose_name': 'Tipo de Atividade', 'verbose_name_plural': 'Tipos de Atividade', 'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo_atividade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.TipoAtividade', verbose_name='Tipo de Atividade'),
        ),
        migrations.AddField(
            model_name='recorrenciatarefa',
            name='tarefa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Tarefa', verbose_name='Tarefa'),
        ),
        migrations.AddField(
            model_name='listatarefa',
            name='tarefa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Tarefa', verbose_name='Tarefa'),
        ),
        migrations.AddField(
            model_name='listaprojeto',
            name='projeto',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='historicoevolucao',
            name='tarefa',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.Tarefa', verbose_name='Tarefa'),
        ),
    ]
