# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-15 15:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):
    dependencies = [('gerenciador_projetos', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(name='tarefa', options={'ordering': ['data_inicio', 'data_conclusao', 'pk'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'}),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo_atividade',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_projetos.TipoAtividade', verbose_name='Tipo de Atividade'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=djtools.db.models.CharFieldPlus(
                choices=[
                    ('#f1c40f', 'Amarelo'),
                    ('#3498db', 'Azul'),
                    ('#e67e22', 'Laranja'),
                    ('#8e44ad', 'Roxo'),
                    ('#2ecc71', 'Verde'),
                    ('#e74c3c', 'Vermelho'),
                    ('nenhum', 'Nenhum'),
                ],
                default='info',
                help_text='Informe uma cor para tag',
                max_length=255,
                verbose_name='Cor',
            ),
        ),
    ]
