# Generated by Django 2.2.7 on 2020-01-27 09:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('gerenciador_projetos', '0002_auto_20191015_1506')]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='visibilidade',
            field=djtools.db.models.CharFieldPlus(choices=[('Privado', 'Privado'), ('Público', 'Público')], default='Privado', max_length=255, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='atribuido_por',
            field=djtools.db.models.ForeignKeyPlus(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gerenciador_tarefa_atribuido_por_set',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Atribuído por',
            ),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=djtools.db.models.CharFieldPlus(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=10, verbose_name='Prioridade'),
        ),
    ]
