# Generated by Django 3.2.5 on 2021-09-03 16:12

from django.conf import settings
from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciador_projetos', '0003_auto_20200127_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='atribuido_a',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='gerenciador_tarefa_atribuido_a_set', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
    ]
