# Generated by Django 3.2.5 on 2021-09-03 16:15

from django.db import migrations


def atribuir_tarefas(apps, schema):
    Tarefa = apps.get_model('gerenciador_projetos', 'tarefa')
    for tarefa in Tarefa.objects.filter(atribuido_para__isnull=False):
        tarefa.atribuido_a.add(tarefa.atribuido_para)


def desatribuir_tarefas(apps, schema):
    Tarefa = apps.get_model('gerenciador_projetos', 'tarefa')
    for tarefa in Tarefa.objects.filter(atribuido_a__isnull=False):
        tarefa.atribuido_a.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_projetos', '0004_auto_20210903_1612'),
    ]

    operations = [
        migrations.RunPython(atribuir_tarefas, desatribuir_tarefas)
    ]
