# Generated by Django 3.2.5 on 2021-09-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_projetos', '0005_auto_20210903_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='atribuido_para',
        ),
    ]
