# Generated by Django 3.2.5 on 2022-01-18 12:35

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_projetos', '0006_remove_tarefa_atribuido_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoevolucao',
            name='data_conclusao',
            field=djtools.db.models.DateFieldPlus(blank=True, help_text='Ao concluir esta tarefa, todas as suas subtarefas também serão concluídas', null=True, verbose_name='Data de Conclusão'),
        ),
    ]
