# Generated by Django 3.2.5 on 2022-03-14 15:11

from django.db import migrations

import tqdm


def popular_gerentes(apps, schema_editor):
    Projeto = apps.get_model('gerenciador_projetos', 'projeto')

    for projeto in tqdm.tqdm(Projeto.objects.all()):
        projeto.gerentes.add(projeto.gerente)


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_projetos', '0008_projeto_gerentes'),
    ]

    operations = [migrations.RunPython(popular_gerentes)]
