# Generated by Django 2.2.16 on 2021-02-22 10:25

from django.db import migrations
import tqdm


def atualizar_dados(apps, schema_editor):
    Edital = apps.get_model('eleicao.Edital')

    for edital in tqdm.tqdm(Edital.objects.all()):
        for servidor in edital.coordenadores.all():
            edital.vinculos_coordenadores.add(servidor.vinculo_set.first())


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_edital_vinculos_coordenadores'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados),
    ]
