# Generated by Django 2.2.16 on 2021-02-22 10:52

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0005_remove_edital_coordenadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='vinculos_coordenadores',
            field=djtools.db.models.ManyToManyFieldPlus(related_name='vinculos_coordenadores_editais', to='comum.Vinculo', verbose_name='Coordenador(es)'),
        ),
    ]
