# Generated by Django 3.2.5 on 2021-11-18 10:30

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0006_auto_20210222_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='data_campanha_inicio',
            field=djtools.db.models.DateTimeFieldPlus(help_text='Período em que os candidatos são tornados públicos na tela inicial.', verbose_name='Início da Campanha'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='caracteres_campanha',
            field=models.PositiveIntegerField(default=2000, verbose_name='Número de Caracteres para a Campanha'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='caracteres_recurso',
            field=models.PositiveIntegerField(default=2000, verbose_name='Número de Caracteres para Recurso'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='resultado_global',
            field=models.BooleanField(default=False, help_text='O resultado dessa eleição será exibido de forma global entre os campi selecionados, ou seja, sem separar os votos por campus', verbose_name='Resultado Global'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='votacao_global',
            field=models.BooleanField(default=False, help_text='Não marcando esta opçãp, um eleitor de um campus somente poderá votar em candidatos do seu próprio campus', verbose_name='Votação Global'),
        ),
    ]
