# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:13


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('rh', '0001_initial'), ('processo_eletronico', '0001_initial'), ('protocolo', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255)),
                ('diretorio', djtools.db.models.CharFieldPlus(max_length=255, unique=True)),
                ('nota_pretendida', djtools.db.models.DecimalFieldPlus(decimal_places=2, default=0, max_digits=12, null=True)),
                ('qtd_itens', models.IntegerField(null=True)),
                ('data_referencia', models.DateField(null=True, verbose_name='Data de Referência')),
                ('tamanho', models.BigIntegerField()),
                ('descricao', models.TextField(blank=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='ArquivosExigidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255)),
                ('diretorio', djtools.db.models.CharFieldPlus(max_length=255, unique=True)),
                ('tamanho', models.BigIntegerField()),
                (
                    'tipo',
                    models.IntegerField(choices=[[1, 'Título de mestrado / especialização / graduação'], [2, 'Início de exercício na carreira'], [3, 'Concessão da última RT']]),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.IntegerField(
                        choices=[[0, 'Em Avaliação'], [1, 'Deferida'], [2, 'Indeferida'], [3, 'Interrompida'], [4, 'Desistência']], verbose_name='Situação da Avaliação'
                    ),
                ),
                ('motivo_indeferimento', models.CharField(max_length=2000, verbose_name='Motivo do Indeferimento')),
                (
                    'tipo_desistencia',
                    models.IntegerField(
                        blank=True, choices=[[1, 'Relacionado ao Processo em Análise'], [2, 'De Ordem Pessoal'], [3, 'De Ordem Profissional'], [4, 'Outros']], null=True
                    ),
                ),
                ('motivo_desistencia', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Motivo da Desistência')),
                ('data_finalizacao', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data da Finalização da Avaliação')),
                ('avaliacao_paga', models.BooleanField(default=False)),
                ('data_pagamento', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data do Pagamento')),
                (
                    'tipo_avaliador',
                    djtools.db.models.CharFieldPlus(choices=[['avaliador_interno', 'Avaliador Interno'], ['avaliador_externo', 'Avaliador Externo']], max_length=255, null=True),
                ),
                (
                    'avaliador',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_avaliador_rsc', to='rh.Avaliador', verbose_name='Avaliador'
                    ),
                ),
            ],
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.CreateModel(
            name='AvaliacaoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de Referência Validada')),
                ('qtd_itens_validado', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Itens Validados')),
                ('justificativa', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Justificativa da Avaliação')),
                ('arquivo', djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.Arquivo', verbose_name='Arquivo')),
                ('avaliacao', djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.Avaliacao', verbose_name='Avaliação')),
            ],
            options={'verbose_name': 'Avaliação do Item', 'verbose_name_plural': 'Avaliações dos Itens'},
        ),
        migrations.CreateModel(
            name='CategoriaMemorialDescritivo',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nome', djtools.db.models.CharFieldPlus(max_length=255))],
            options={'verbose_name': 'Categoria Memorial descritivo', 'verbose_name_plural': 'Categorias Memoriais Descritivos', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.TextField()),
                ('status', models.IntegerField(choices=[[0, 'Ativo'], [1, 'Inativo']])),
                ('fator', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('teto', models.IntegerField(verbose_name='Valor máximo de itens do criterio')),
                ('categoria_memorial_descritivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rsc.CategoriaMemorialDescritivo')),
            ],
            options={'verbose_name': 'Critério', 'verbose_name_plural': 'Critérios'},
        ),
        migrations.CreateModel(
            name='Diretriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255)),
                ('descricao', models.TextField()),
                ('peso', models.IntegerField(verbose_name='Valor do peso')),
                ('teto', models.IntegerField(help_text='Valor máximo de itens da diretriz ', verbose_name='Teto')),
            ],
            options={'verbose_name': 'Diretriz', 'verbose_name_plural': 'Diretrizes', 'ordering': ('pk',)},
        ),
        migrations.CreateModel(
            name='ParametroPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_por_avaliacao', models.FloatField(verbose_name='Valor por Avaliação')),
                ('hora_por_avaliacao', models.IntegerField(verbose_name='Hora por Avaliação')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={'verbose_name': 'Parâmetro para Pagamento', 'verbose_name_plural': 'Parâmetros para Pagamentos'},
        ),
        migrations.CreateModel(
            name='ProcessoAvaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('data_convite', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data do Convite')),
                ('data_aceite', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data do Aceite')),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            [0, 'Em espera'],
                            [1, 'Aguardando aceite'],
                            [2, 'Aguardando avaliação'],
                            [3, 'Avaliação finalizada'],
                            [4, 'Excedeu tempo de aceite'],
                            [5, 'Excedeu tempo de avaliação'],
                            [6, 'Rejeitado pelo avaliador'],
                        ],
                        verbose_name='Situação do Avaliador no Processo',
                    ),
                ),
                (
                    'tipo_avaliador',
                    djtools.db.models.CharFieldPlus(choices=[['avaliador_interno', 'Avaliador Interno'], ['avaliador_externo', 'Avaliador Externo']], max_length=255),
                ),
                (
                    'tipo_recusa',
                    models.IntegerField(
                        blank=True, choices=[[1, 'Relacionado ao Processo em Análise'], [2, 'De Ordem Pessoal'], [3, 'De Ordem Profissional'], [4, 'Outros']], null=True
                    ),
                ),
                ('motivo_recusa', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Motivo da Recusa')),
                (
                    'avaliador',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_avaliador_rsc', to='rh.Avaliador', verbose_name='Avaliador'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Avaliador do Processo',
                'verbose_name_plural': 'Avaliadores do Processo',
                'permissions': (('pode_avaliar_processorsc', 'Pode avaliar ProcessoRSC'), ('pode_atualizar_dados_cadastrais', 'Pode atualizar dados cadastrais')),
            },
        ),
        migrations.CreateModel(
            name='ProcessoRSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número do Processo')),
                ('pontuacao_validada_com_corte', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pontuação Validada')),
                (
                    'pontuacao_validada_sem_corte',
                    djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pontuação Validada Sem Corte'),
                ),
                ('pontuacao_pretendida', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pontuação Requerida')),
                ('pontuacao_pretendida_rsc1', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pontuacao_pretendida_rsc2', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pontuacao_pretendida_rsc3', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            [0, 'Deferido'],
                            [1, 'Indeferido'],
                            [2, 'Aguardando validação CPPD'],
                            [3, 'Aguardando envio para CPPD'],
                            [4, 'Aguardando avaliadores'],
                            [5, 'Aguardando ajustes do usuário'],
                            [6, 'Rejeitado'],
                            [7, 'Aguardando nova validação'],
                            [8, 'Aguardando aceite dos avaliadores'],
                            [9, 'Em avaliação'],
                            [10, 'Ciente do resultado'],
                            [11, 'Aguardando ciência'],
                            [12, 'Analisado'],
                        ],
                        verbose_name='Situação do Processo',
                    ),
                ),
                ('tipo_processo', models.IntegerField(choices=[[0, 'Tipo de Processo Aposentado'], [1, 'Tipo de Processo Geral']], default=1, verbose_name='Tipo de processo')),
                ('introducao_relatorio_descritivo', models.TextField(blank=True)),
                ('conclusao_relatorio_descritivo', models.TextField(blank=True)),
                ('itinerario_formacao', models.TextField(blank=True)),
                ('atuacao_docente', models.TextField(blank=True)),
                ('producao_cademica', models.TextField(blank=True)),
                ('prestacao_servicos', models.TextField(blank=True)),
                ('atividade_adm', models.TextField(blank=True)),
                ('titulos_homenagens', models.TextField(blank=True)),
                ('data_concessao_ultima_rt', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Concessão')),
                ('data_exercio_carreira', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Exercício na Carreira')),
                ('data_conclusao_titulacao_rsc_pretendido', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Conclusão da Titulação para RSC Pretendido')),
                (
                    'concorda_deferimento',
                    models.IntegerField(
                        blank=True,
                        choices=[[1, 'Concorda com o resultado da avaliação(deferimento/indeferimento)'], [2, 'Discorda do resultado da avaliação(deferimento/indeferimento)']],
                        null=True,
                        verbose_name='Concorda com o deferimento',
                    ),
                ),
                (
                    'concorda_data_retroatividade',
                    models.IntegerField(
                        blank=True,
                        choices=[[1, 'Concorda com a data de retroatividade concedida'], [2, 'Discorda da data de retroatividade concedida']],
                        null=True,
                        verbose_name='Concorda com a data de retroatividade',
                    ),
                ),
                ('data_ciencia', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data da Ciência')),
                ('data_finalizacao_processo', djtools.db.models.DateTimeFieldPlus(blank=True, default=None, null=True, verbose_name='Data de Finalização do Processo')),
                ('assinatura_requerimento', models.TextField(blank=True, default='', null=True, verbose_name='Assinatura do Requerimento')),
                (
                    'processo_eletronico',
                    djtools.db.models.ForeignKeyPlus(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo_eletronico.Processo'),
                ),
                ('protocolo', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.Processo')),
                ('servidor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
            ],
            options={
                'verbose_name': 'Processo de RSC',
                'verbose_name_plural': 'Processos de RSC',
                'permissions': (('pode_validar_processorsc', 'Pode validar ProcessoRSC'), ('pode_ver_relatorio_rsc', 'Pode ver relatório RSC')),
            },
        ),
        migrations.CreateModel(
            name='TipoRsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255)),
                ('categoria', djtools.db.models.CharFieldPlus(max_length=255)),
            ],
            options={'verbose_name': 'Tipo de Rsc', 'verbose_name_plural': 'Tipos de Rsc', 'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=255, unique=True)),
                ('sigla', djtools.db.models.CharFieldPlus(max_length=50)),
            ],
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.CreateModel(
            name='ValidacaoCPPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao_titulacao_rsc_pretendido_validada', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Conclusão Validada')),
                ('data_exercio_carreira_validada', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Exercício na Carreira Validada')),
                ('data_concessao_ultima_rt_validada', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Concessão Validada')),
                ('acao', models.IntegerField(choices=[[0, 'Aceitar'], [1, 'Devolver'], [2, 'Rejeitar']])),
                ('motivo_rejeicao', models.CharField(max_length=2000, verbose_name='Motivo da rejeição')),
                ('data', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('ajustado', models.BooleanField(default=False)),
                ('processo', djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.ProcessoRSC', verbose_name='ProcessoRSC')),
                ('validador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
            ],
            options={'verbose_name': 'Validação CPPD', 'verbose_name_plural': 'Validações CPPD'},
        ),
        migrations.AlterUniqueTogether(name='tiporsc', unique_together=set([('nome', 'categoria')])),
        migrations.AddField(
            model_name='processorsc',
            name='tipo_rsc',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rsc.TipoRsc', verbose_name='RSC Pretendido'),
        ),
        migrations.AddField(
            model_name='processoavaliador',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.ProcessoRSC', verbose_name='ProcessoRSC'),
        ),
        migrations.AddField(
            model_name='processoavaliador',
            name='responsavel_cadastro',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='diretriz', name='tipo_rsc', field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.TipoRsc')
        ),
        migrations.AddField(model_name='criterio', name='diretriz', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rsc.Diretriz')),
        migrations.AddField(
            model_name='criterio',
            name='unidade',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rsc.Unidade', verbose_name='Unidade do critério'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.ProcessoRSC', verbose_name='ProcessoRSC'),
        ),
        migrations.AddField(
            model_name='arquivosexigidos',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.ProcessoRSC', verbose_name='processo associado ao arquivo'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='criterio',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.Criterio', verbose_name='critério associado ao arquivo'
            ),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsc.ProcessoRSC', verbose_name='processo associado ao arquivo'),
        ),
        migrations.AlterUniqueTogether(name='diretriz', unique_together=set([('tipo_rsc', 'nome')])),
    ]
