# Generated by Django 2.2.7 on 2019-12-05 19:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0006_auto_20191128_1142'), ('pesquisa', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='impedir_coordenador_com_pendencia',
            field=models.BooleanField(
                default=False,
                help_text='Marque esta opção para impedir que coordenadores de projetos com conclusão em atraso submetam projetos para este edital.',
                verbose_name='Impedir Submissão de Coordenador com Pendência',
            ),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_aluno',
            field=ckeditor.fields.RichTextField(
                blank=True, help_text='Informe o termo de compromisso do aluno participante do projeto.', null=True, verbose_name='Termo de Compromisso do Aluno'
            ),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_servidor',
            field=ckeditor.fields.RichTextField(
                blank=True, help_text='Informe o termo de compromisso do servidor participante do projeto.', null=True, verbose_name='Termo de Compromisso do Servidor'
            ),
        ),
        migrations.AddField(model_name='participacao', name='termo_aceito_em', field=djtools.db.models.DateTimeFieldPlus(null=True)),
        migrations.AddField(
            model_name='projetocancelado',
            name='arquivo_comprovacao',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/projeto/comprovacao_cancelamento/', verbose_name='Comprovação'),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=2000, verbose_name='Descrição da Alteração')),
                ('cadastrada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrado em')),
                ('atendida', models.NullBooleanField(verbose_name='Atendida')),
                ('avaliada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                ('justificativa', djtools.db.models.CharFieldPlus(blank=True, max_length=1000, null=True, verbose_name='Justificativa')),
                (
                    'avaliada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pesquisa_avaliacao_alteracaoequipe',
                        to='comum.Vinculo',
                        verbose_name='Avaliada por',
                    ),
                ),
                (
                    'cadastrada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pesquisa_cadastro_alteracaoequipe',
                        to='comum.Vinculo',
                        verbose_name='Cadastrado por',
                    ),
                ),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.Projeto')),
            ],
            options={'verbose_name': 'Solicitação de Alteração da Equipe', 'verbose_name_plural': 'Solicitações de Alteração da Equipe'},
        ),
        migrations.CreateModel(
            name='RegistroFrequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=2000, verbose_name='Descrição da Alteração')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('cadastrada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrado em')),
                ('atendida', models.NullBooleanField(verbose_name='Atendida')),
                ('validada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                (
                    'cadastrada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pesquisa_cadastro_registrofrequencia',
                        to='comum.Vinculo',
                        verbose_name='Cadastrado por',
                    ),
                ),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.Projeto')),
                (
                    'validada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pesquisa_avaliacao_registrofrequencia',
                        to='comum.Vinculo',
                        verbose_name='Avaliada por',
                    ),
                ),
            ],
            options={'verbose_name': 'Registro de Frequência/Atividade do Projeto', 'verbose_name_plural': 'Registros de Frequência/Atividade do Projeto'},
        ),
    ]
