# Generated by Django 2.2.10 on 2020-03-11 09:22

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('pesquisa', '0002_auto_20191205_1929')]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='biografia_autor_organizador',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=660, null=True, verbose_name='Biografia do Autor/Organizador'),
        ),
        migrations.AddField(
            model_name='obra',
            name='foto_autor_organizador',
            field=models.ImageField(null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Foto do Autor/Organizador'),
        ),
        migrations.AddField(
            model_name='obra', name='sinopse_quarta_capa', field=djtools.db.models.CharFieldPlus(blank=True, max_length=1050, null=True, verbose_name='Sinopse para Quarta Capa')
        ),
    ]
