# Generated by Django 2.2.10 on 2020-03-20 15:02

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('comum', '0008_auto_20200205_1500'), ('pesquisa', '0003_auto_20200311_0922')]

    operations = [
        migrations.CreateModel(
            name='FinalidadeServicoLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Tipo de Finalidade do Serviço', 'verbose_name_plural': 'Tipos de Finalidade do Serviço'},
        ),
        migrations.CreateModel(
            name='MaterialConsumoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Material de Consumo de Pesquisa', 'verbose_name_plural': 'Materiais de Consumo de Pesquisa'},
        ),
        migrations.CreateModel(
            name='ServicoLaboratorioPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000, verbose_name='Descrição')),
                ('materiais_utilizados', models.CharField(max_length=5000, null=True, verbose_name='Materiais Utilizados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={'verbose_name': 'Serviço do Laboratório de Pesquisa', 'verbose_name_plural': 'Serviços do Laboratório de Pesquisa'},
        ),
        migrations.AddField(model_name='equipamentolaboratoriopesquisa', name='nome', field=djtools.db.models.CharFieldPlus(max_length=200, null=True, verbose_name='Nome')),
        migrations.AddField(
            model_name='equipamentolaboratoriopesquisa',
            name='situacao',
            field=djtools.db.models.CharFieldPlus(
                choices=[('Operacional', 'Operacional'), ('Não-Operacional', 'Não-Operacional'), ('Manutenção', 'Manutenção'), ('Desenvolvimento', 'Desenvolvimento')],
                default='Operacional',
                max_length=150,
                verbose_name='Situação',
            ),
        ),
        migrations.CreateModel(
            name='SolicitacaoServicoLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data')),
                ('hora_inicio', djtools.db.models.TimeFieldPlus(verbose_name='Hora de Início')),
                ('hora_termino', djtools.db.models.TimeFieldPlus(verbose_name='Hora de Término')),
                (
                    'descricao',
                    models.CharField(
                        help_text='Informe aqui as características e quantidades das amostras, materiais que serão entregues ao laboratório, etc.',
                        max_length=5000,
                        verbose_name='Descrição do Serviço',
                    ),
                ),
                (
                    'situacao',
                    djtools.db.models.CharFieldPlus(
                        choices=[('Em Espera', 'Em Espera'), ('Deferida', 'Deferida'), ('Indeferida', 'Indeferida'), ('Atendida', 'Atendida')],
                        default='Em Espera',
                        max_length=100,
                        verbose_name='Situação',
                    ),
                ),
                (
                    'arquivo',
                    models.FileField(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/laboratorios/comprovantes/', verbose_name='Documentos Comprobatórios'),
                ),
                ('parecer', djtools.db.models.CharFieldPlus(max_length=5000, null=True, verbose_name='Retorno do Laboratório')),
                ('cadastrada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Cadastrada em')),
                ('avaliada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliada em')),
                ('concluida_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Concluída em')),
                (
                    'cadastrada_por',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='solicitante_servico_laboratorio',
                        to='comum.Vinculo',
                        verbose_name='Cadastrada por',
                    ),
                ),
                (
                    'finalidade',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.FinalidadeServicoLaboratorio', verbose_name='Finalidade do Serviço'),
                ),
                ('laboratorio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.LaboratorioPesquisa', verbose_name='Laboratório')),
                ('servico', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.ServicoLaboratorioPesquisa', verbose_name='Serviço')),
            ],
            options={'verbose_name': 'Solicitação de Serviço no Laboratório', 'verbose_name_plural': 'Solicitações de Serviço no Laboratório'},
        ),
        migrations.AddField(
            model_name='servicolaboratoriopesquisa',
            name='equipamentos',
            field=djtools.db.models.ManyToManyFieldPlus(to='pesquisa.EquipamentoLaboratorioPesquisa', verbose_name='Equipamentos Utilizados'),
        ),
        migrations.AddField(
            model_name='servicolaboratoriopesquisa',
            name='laboratorio',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.LaboratorioPesquisa', verbose_name='Laboratório'),
        ),
        migrations.CreateModel(
            name='MaterialLaboratorioPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Quantidade em Estoque')),
                ('valor_unitario', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('imagem', models.ImageField(null=True, upload_to='upload/pesquisa/fotos/')),
                ('laboratorio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.LaboratorioPesquisa', verbose_name='Laboratório')),
                ('material', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.MaterialConsumoPesquisa', verbose_name='Material')),
            ],
            options={'verbose_name': 'Material do Laboratório de Pesquisa', 'verbose_name_plural': 'Materiais do Laboratório de Pesquisa'},
        ),
    ]
