# Generated by Django 2.2.16 on 2020-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0004_auto_20200320_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofrequencia',
            name='carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária'),
        ),
    ]
