# Generated by Django 2.2.16 on 2021-02-08 16:24

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0011_merge_20201221_1533'),
        ('pesquisa', '0005_registrofrequencia_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaexternaobra',
            name='validado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Validado em'),
        ),
        migrations.AddField(
            model_name='pessoaexternaobra',
            name='validado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_validador_pessoaexterna', to='comum.Vinculo', verbose_name='Avaliada por'),
        ),
    ]
