# Generated by Django 2.2.16 on 2021-03-01 17:09

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0006_auto_20210208_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalarquivo',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/edital/'),
        ),
        migrations.AlterField(
            model_name='editalsubmissaoobra',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(upload_to='private-media/pesquisa/editalsubmissaoobra/', verbose_name='Arquivo do Edital'),
        ),
        migrations.AlterField(
            model_name='editalsubmissaoobra',
            name='manual',
            field=djtools.db.models.FileFieldPlus(upload_to='private-media/pesquisa/editalsubmissaoobra/', verbose_name='Manual do Autor'),
        ),
        migrations.AlterField(
            model_name='editalsubmissaoobra',
            name='questionario_parecerista',
            field=djtools.db.models.FileFieldPlus(null=True, upload_to='private-media/pesquisa/editalsubmissaoobra/', verbose_name='Ficha de Avaliação para Parecerista'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(help_text='O arquivo com a obra deve estar em formato Word. Outros formatos não serão aceitos. O arquivo Word poderá ser enviado de forma compactada (ZIP ou RAR).', upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Obra Completa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_capa',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Diagramação da Capa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_capa_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Diagramação da Capa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_miolo',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Diagramação do Miolo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_miolo_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Diagramação do Miolo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_versao_final',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Versão Final da Diagramação'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_obra_revisada',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Obra Revisada'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='contrato_cessao_direitos',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Contrato de Cessão e Transferência de Direitos Patrimoniais de Autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ficha_catalografica',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Ficha Catalográfica'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ficha_catalografica_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Ficha Catalográfica (Impresso)'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_concluida',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Obra Concluída'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_corrigida',
            field=djtools.db.models.FileFieldPlus(blank=True, help_text='O arquivo com a obra deve estar em formato Word. Outros formatos não serão aceitos. O arquivo Word poderá ser enviado de forma compactada (ZIP ou RAR).', null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Obra Corrigida'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_sem_identificacao_autor',
            field=djtools.db.models.FileFieldPlus(help_text='O arquivo não deve ter nenhum dado que identifique a autoria e/ou organização da obra. O arquivo com a obra deve estar em formato Word. Outros formatos não serão aceitos. O arquivo Word poderá ser enviado de forma compactada (ZIP ou RAR).', upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Obra Sem Identificação'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='revisada_pelo_autor',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Obra Revisada pelo Autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_autorizacao_publicacao',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termos de Autorização de Publicação'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_autorizacao_uso_imagem',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termo de Autorização para uso de Imagem e Fotografia'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_cessao_direitos_autorais',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termo de cessão de Direitos Autorais'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_compromisso_autor_editora',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termo de Compromisso do Autor com a Editora'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_nome_menor',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termo de Autorização para uso de Nome de Menor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='termo_uso_imagem',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Termos de Uso de Imagem, Voz e Texto'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='versao_final_revisao',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Versão Final da Revisão'),
        ),
        migrations.AlterField(
            model_name='parecerobra',
            name='arquivo_parecer_area',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='', verbose_name='Parecer'),
        ),
        migrations.AlterField(
            model_name='projetocancelado',
            name='arquivo_comprovacao',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/projeto/comprovacao_cancelamento/', verbose_name='Comprovação'),
        ),
        migrations.AlterField(
            model_name='registroexecucaoetapa',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/atividades/comprovantes/'),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/registrogasto/comprovantes/'),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='cotacao_precos',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/registrogasto/comprovantes/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservicolaboratorio',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='upload/pesquisa/laboratorios/comprovantes/', verbose_name='Documentos Comprobatórios'),
        ),
    ]
