# Generated by Django 2.2.16 on 2021-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0007_auto_20210301_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='imprimir_certificado',
            field=models.BooleanField(default=True, help_text='Marque este campo se quiser permitir que os membros do projeto possam emitir o certificado de participação, na aba "Equipe", quando o projeto estiver concluído.', verbose_name='Permitir Impressão do Certificado de Participação'),
        ),
    ]
