# Generated by Django 2.2.16 on 2021-03-10 10:48

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0009_auto_20210309_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoprojeto',
            name='imagem',
            field=djtools.db.models.ImageFieldPlus(upload_to='upload/pesquisa/fotos/'),
        ),
        migrations.AlterField(
            model_name='materiallaboratoriopesquisa',
            name='imagem',
            field=djtools.db.models.ImageFieldPlus(null=True, upload_to='upload/pesquisa/fotos/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='foto_autor_organizador',
            field=djtools.db.models.ImageFieldPlus(null=True, upload_to='private-media/pesquisa/arquivos_obra/', verbose_name='Foto do Autor/Organizador'),
        ),
    ]
