# Generated by Django 2.2.16 on 2021-04-28 15:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_servidorreativacaotemporaria'),
        ('comum', '0018_auto_20210401_1853'),
        ('pesquisa', '0011_auto_20210420_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='permite_colaborador_externo',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso seja permitida a inclusão de colaborador externo nas equipes dos projetos', verbose_name='Permite Colaborador Externo'),
        ),
        migrations.AddField(
            model_name='edital',
            name='termo_compromisso_colaborador_externo',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Informe o termo de compromisso do colaborador externo participante do projeto.', null=True, verbose_name='Termo de Compromisso do Colaborador Externo'),
        ),
        migrations.AlterField(
            model_name='editalanexo',
            name='tipo_membro',
            field=models.CharField(blank=True, choices=[('1', 'Docente'), ('5', 'Técnico Administrativo'), ('2', 'Aluno'), ('3', 'Coordenador Docente'), ('4', 'Coordenador Técnico Administrativo'), ('6', 'Colaborador Externo')], max_length=1, null=True, verbose_name='Tipo de Membro'),
        ),
        migrations.AlterField(
            model_name='historicoequipe',
            name='tipo_de_evento',
            field=models.PositiveIntegerField(blank=True, choices=[(11, 'Saiu da coordenação do projeto'), (12, 'Tornou-se coordenador do projeto'), (1, 'Assumiu a coordenação do projeto'), (2, 'Aluno inserido'), (3, 'Servidor inserido'), (13, 'Colaborador Externo inserido'), (4, 'Participante ativado'), (5, 'Participante inativado'), (6, 'Participante excluído'), (7, 'Bolsa concedida durante a distribuição de bolsas'), (8, 'Bolsas não concedida durante a distribuição de bolsas'), (9, 'Aluno alterado'), (10, 'Servidor alterado'), (14, 'Colaborador Externo alterado')]),
        ),
        migrations.CreateModel(
            name='ColaboradorExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('lattes', models.URLField(blank=True, null=True)),
                ('documentacao', djtools.db.models.PrivateFileField(blank=True, help_text='Caso necessário, anexe os documentos comprobatórios.', null=True, storage=djtools.storages.get_private_storage(), upload_to='pesquisa/colaborador_externo', verbose_name='Documentação')),
                ('instituicao_origem', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_instituicao_colaboradorexterno', to='rh.Instituicao', verbose_name='Instituição')),
                ('prestador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_colaborador_externo', to='comum.PrestadorServico')),
                ('titulacao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_colaboradorexterno_instituicao', to='rh.Titulacao', verbose_name='Titulação')),
            ],
            options={
                'verbose_name': 'Colaborador Externo',
                'verbose_name_plural': 'Colaboradores Externos',
                'ordering': ['nome'],
            },
        ),
    ]
