# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0012_auto_20210428_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='autorizado',
            field=models.BooleanField(default=True, null=True, verbose_name='Edital autorizado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='anuencia',
            field=models.BooleanField(null=True, verbose_name='Chefia de Acordo'),
        ),
        migrations.AlterField(
            model_name='registrofrequencia',
            name='atendida',
            field=models.BooleanField(null=True, verbose_name='Atendida'),
        ),
        migrations.AlterField(
            model_name='solicitacaoalteracaoequipe',
            name='atendida',
            field=models.BooleanField(null=True, verbose_name='Atendida'),
        ),
    ]
