# Generated by Django 3.2.5 on 2021-08-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0013_auto_20210719_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoprojeto',
            options={'ordering': ['id']},
        ),
    ]
