# Generated by Django 3.2.5 on 2021-11-22 12:03

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0014_alter_fotoprojeto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaPosGraduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', djtools.db.models.CharFieldPlus(max_length=1000, verbose_name='Nome do Programa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Programa de Pós-Graduação',
                'verbose_name_plural': 'Programas de Pós-Graduação',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='parceria_externa',
            field=djtools.db.models.CharFieldPlus(max_length=1000, null=True, verbose_name='Programa/Instituição de Parceria Externa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ppg',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='pesquisa.programaposgraduacao', verbose_name='Programa de Pós-Graduação Vinculado'),
        ),
    ]
