# Generated by Django 3.2.5 on 2021-12-10 15:24

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0033_groupdetail_app_manager'),
        ('pesquisa', '0015_auto_20211122_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliadorindicado',
            name='aceito_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Aceito em'),
        ),
        migrations.AddField(
            model_name='avaliadorindicado',
            name='prazo_para_aceite',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prazo para Aceite'),
        ),
        migrations.AddField(
            model_name='avaliadorindicado',
            name='prazo_para_avaliacao',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prazo para Avaliação'),
        ),
        migrations.AddField(
            model_name='avaliadorindicado',
            name='rejeitado_automaticamente',
            field=models.BooleanField(default=False, verbose_name='Rejeitado Automaticamente'),
        ),
        migrations.AddField(
            model_name='edital',
            name='exige_comissao',
            field=models.BooleanField(default=True, help_text='Marque esta opção para que apenas membros da comissão de avaliação do edital possam ser indicados como avaliadores dos projetos. Caso contrário, qualquer usuário registrado como avaliador e que tenha a titulação exigida pelo edital poderá ser indicado.', verbose_name='Exigir Comissão de Avaliação'),
        ),
        migrations.AddField(
            model_name='edital',
            name='prazo_aceite_indicacao',
            field=models.IntegerField(blank=True, help_text='Informe o prazo máximo, em dias, para que um avaliador indicado registre que aceita a indicação. Se não há prazo máximo, deixe este campo em branco.', null=True, verbose_name='Prazo para Aceite da Indicação (em dias)'),
        ),
        migrations.AddField(
            model_name='edital',
            name='prazo_avaliacao',
            field=models.IntegerField(blank=True, help_text='Informe o prazo máximo, em dias, após o registro de aceite, para que o avaliador faça a avaliação do projeto. Se não há prazo máximo, deixe este campo em branco.', null=True, verbose_name='Prazo para Avaliar Projeto (em dias)'),
        ),
        migrations.AddField(
            model_name='edital',
            name='tipo_monitoramento',
            field=models.CharField(choices=[('Atividades', 'Atividades'), ('Relatórios', 'Relatórios')], default='Atividades', help_text='Por atividades exige a validação de atividades e gastos para conclusão do projeto. Por relatórios exige o cadastro de pelo menos um relatório parcial e um final no projeto.', max_length=15, verbose_name='Tipo de Monitoramento dos Projetos'),
        ),
        migrations.CreateModel(
            name='RelatorioProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', djtools.db.models.CharFieldPlus(choices=[('Parcial', 'Parcial'), ('Final', 'Final')], max_length=10, verbose_name='Tipo do Relatório')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=1000, verbose_name='Descrição')),
                ('obs', models.TextField(blank=True, help_text='Informação adicional que você julgar relevante.', null=True, verbose_name='Observação')),
                ('cadastrado_em', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Cadastrado em')),
                ('avaliado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Avaliado em')),
                ('aprovado', models.BooleanField(default=False)),
                ('arquivo', djtools.db.models.FileFieldPlus(max_length=255, upload_to='upload/pesquisa/relatorios/')),
                ('justificativa_reprovacao', models.CharField(blank=True, help_text='Informação adicional que você julgar relevante no que diz respeito à reprovação do relatório.', max_length=5000, null=True, verbose_name='Justificativa da Reprovação do Relatório')),
                ('avaliado_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_avaliador_relatorio', to='comum.vinculo')),
                ('projeto', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.projeto')),
            ],
            options={
                'verbose_name': 'Relatório do Projeto',
                'verbose_name_plural': 'Relatórios do Projeto',
                'ordering': ['-cadastrado_em'],
            },
        ),
    ]
