# Generated by Django 3.2.5 on 2021-12-23 15:07

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0016_auto_20211210_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_capa',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/capa', verbose_name='Diagramação da Capa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_capa_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/capa_impresso', verbose_name='Diagramação da Capa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_miolo',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/miolo', verbose_name='Diagramação do Miolo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_miolo_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/miolo_impresso', verbose_name='Diagramação do Miolo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_diagramacao_versao_final',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/diagramacao_final', verbose_name='Versão Final da Diagramação'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='arquivo_obra_revisada',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/arquivo_revisada', verbose_name='Obra Revisada'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ficha_catalografica_impresso',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/ficha_impresso', verbose_name='Ficha Catalográfica (Impresso)'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_concluida',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/concluida', verbose_name='Obra Concluída'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='revisada_pelo_autor',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/revisada_autor', verbose_name='Obra Revisada pelo Autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='versao_final_revisao',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/final', verbose_name='Versão Final da Revisão'),
        ),
        migrations.AlterField(
            model_name='parecerobra',
            name='arquivo_parecer_area',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/parecer', verbose_name='Parecer'),
        ),
    ]
