# Generated by Django 3.2.5 on 2021-12-23 15:31

import os
import shutil
import tqdm
from django.db import migrations
from django.conf import settings


def atualizar(qs, field_str, path):
    marcar_para_deletar = []
    folder = os.path.join(settings.MEDIA_ROOT, path)
    os.makedirs(folder, exist_ok=True)
    for obj in tqdm.tqdm(qs):
        field = getattr(obj, field_str)
        file_name = field.name
        file_name = file_name and file_name.startswith('./') and file_name[2:] or file_name
        if file_name:
            original = os.path.join(settings.MEDIA_ROOT, file_name)
            marcar_para_deletar.append(original)
            target = os.path.join(folder, file_name)
            setattr(obj, field_str, os.path.join(path, file_name))
            obj.save()
            if not settings.DEBUG:
                shutil.copyfile(original, target)
    if not settings.DEBUG:
        for arquivo in marcar_para_deletar:
            os.remove(arquivo)
    with open(os.path.join(settings.MEDIA_ROOT, 'arquivos_excluidos.txt'), 'a') as f:
        for arquivo in marcar_para_deletar:
            f.write(arquivo + '\n')
    return marcar_para_deletar


def atualizar_dados(apps, schema):

    Obra = apps.get_model('pesquisa.obra')
    ParecerObra = apps.get_model('pesquisa.parecerobra')

    print('\natualizando Obra.arquivo_diagramacao_capa\n')
    atualizar(Obra.objects.all(), 'arquivo_diagramacao_capa', 'pesquisa/obra/capa')

    print('\natualizando Obra.arquivo_diagramacao_capa_impresso\n')
    atualizar(Obra.objects.all(), 'arquivo_diagramacao_capa_impresso', 'pesquisa/obra/capa_impresso')

    print('\natualizando Obra.arquivo_diagramacao_miolo\n')
    atualizar(Obra.objects.all(), 'arquivo_diagramacao_miolo', 'pesquisa/obra/miolo')

    print('\natualizando Obra.arquivo_diagramacao_miolo_impresso\n')
    atualizar(Obra.objects.all(), 'arquivo_diagramacao_miolo_impresso', 'pesquisa/obra/miolo_impresso')

    print('\natualizando Obra.arquivo_diagramacao_versao_final\n')
    atualizar(Obra.objects.all(), 'arquivo_diagramacao_versao_final', 'pesquisa/obra/diagramacao_final')

    print('\natualizando Obra.arquivo_obra_revisada\n')
    atualizar(Obra.objects.all(), 'arquivo_obra_revisada', 'pesquisa/obra/arquivo_revisada')

    print('\natualizando Obra.ficha_catalografica_impresso\n')
    atualizar(Obra.objects.all(), 'ficha_catalografica_impresso', 'pesquisa/obra/ficha_impresso')

    print('\natualizando Obra.obra_concluida\n')
    atualizar(Obra.objects.all(), 'obra_concluida', 'pesquisa/obra/concluida')

    print('\natualizando Obra.revisada_pelo_autor\n')
    atualizar(Obra.objects.all(), 'revisada_pelo_autor', 'pesquisa/obra/revisada_autor')

    print('\natualizando Obra.versao_final_revisao\n')
    atualizar(Obra.objects.all(), 'versao_final_revisao', 'pesquisa/obra/final')

    print('\natualizando ParecerObra\n')
    atualizar(ParecerObra.objects.all(), 'arquivo_parecer_area', 'pesquisa/obra/parecer')


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0017_auto_20211223_1507'),
    ]

    operations = [
        migrations.RunPython(atualizar_dados)
    ]
