# Generated by Django 3.2.5 on 2022-01-07 09:43

from decimal import Decimal
from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0018_auto_20211223_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='peso_avaliacao_grupo_pesquisa',
            field=models.PositiveIntegerField(default=0, help_text='Informe o peso em percentual que será usado na Avaliação do Grupo de Pesquisa do projeto. A nota de avaliação será a soma das pontuações dos currículos dos servidores que fazem parte do grupo de pesquisa.', null=True, verbose_name='Peso da Avaliação do Grupo de Pesquisa (%)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pontuacao_grupo_pesquisa',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True, verbose_name='Pontuação do Grupo de Pesquisa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pontuacao_grupo_pesquisa_normalizado',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True, verbose_name='Pontuação do Grupo de Pesquisa normalizado'),
        ),
    ]
