# Generated by Django 3.2.5 on 2022-03-30 11:30

from django.db import migrations, models
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0019_auto_20220107_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='arquivo_diagramacao_versao_final_ebook',
            field=djtools.db.models.FileFieldPlus(blank=True, max_length=255, null=True, upload_to='pesquisa/obra/diagramacao_final', verbose_name='Versão Final(E-book)'),
        ),
        migrations.AddField(
            model_name='obra',
            name='justificativa_cancelamento',
            field=models.TextField(null=True, verbose_name='Justificativa do Cancelamento'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obs_sobre_diagramacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Autor/Organizador sobre a Diagramação'),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefone',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
