# Generated by Django 3.2.5 on 2022-07-14 09:25

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_auto_20220610_0752'),
        ('pesquisa', '0020_auto_20220330_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_avaliador', to='rh.pessoafisica', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='avaliadorexterno',
            name='pessoa_fisica',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_avaliador_externo', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='avaliadorindicado',
            name='pessoa_fisica',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_avaliador_indicado', to='rh.pessoafisica', verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='submetido_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_submeteu_obra', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='parecerobra',
            name='parecer_realizado_por',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_parecer_obra', to='rh.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='pessoa',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_participacao', to='rh.pessoafisica', verbose_name='Participante'),
        ),
    ]
