# Generated by Django 3.2.5 on 2022-07-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0021_auto_20220714_0925'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='avaliadorexterno',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='avaliadorindicado',
            name='pessoa_fisica',
        ),
        migrations.RemoveField(
            model_name='comissaoeditalpesquisa',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='editalarquivo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='aceita_editora_realizada_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='autenticidade_verificada_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='cancelada_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='diagramacao_realizada_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='julgamento_conselho_realizado_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='revisao_realizada_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='submetido_por',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='termos_assinados_realizado_por',
        ),
        migrations.RemoveField(
            model_name='parecerobra',
            name='parecer_realizado_por',
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='autor_pre_avaliacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='projetoanexo',
            name='membro_equipe',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetoanexo',
            options={'ordering': ['vinculo_membro_equipe__pessoa__nome']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )

    ]
