# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# mysql -u bn_moodle --host=localhost bitnami_moodle < /home/backup/dump-moodleava-202402240940.sql
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MYSQL_TCP_PORT=3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - './backup:/home/backup:z'
    ports:
      - '3307:3306'
  moodle:
    image: docker.io/bitnami/moodle:4.1
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=True
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - './plugins/moodle__local_suap:/home'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
