# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443'), ('rh', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, verbose_name='Identificação')),
                ('ativa', models.BooleanField(default=True)),
                ('disponivel', models.BooleanField(default=True, editable=False, verbose_name='Disponível')),
                ('pessoas', models.ManyToManyField(blank=True, to='rh.Pessoa', verbose_name='Pessoas Permitidas')),
                ('sala', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'ordering': ['sala__predio__uo', 'sala__nome', 'identificacao'],
                'permissions': (('poder_ver_todas', 'Pode ver todas as chaves'), ('poder_ver_do_campus', 'Pode ver as chaves do campus')),
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(verbose_name='Data do Empréstimo')),
                ('observacao_emprestimo', models.TextField(blank=True, null=True, verbose_name='Observação Empréstimo')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução')),
                ('observacao_devolucao', models.TextField(blank=True, null=True, verbose_name='Observação Devolução')),
                ('chave', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='chaves.Chave')),
                (
                    'operador_devolucao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chaves_movimentadas_devolucao_como_operador_set',
                        to='rh.Pessoa',
                        verbose_name='Operador Devolução',
                    ),
                ),
                (
                    'operador_emprestimo',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chaves_movimentadas_emprestimo_como_operador_set',
                        to='rh.Pessoa',
                        verbose_name='Operador Empréstimo',
                    ),
                ),
                (
                    'pessoa_devolucao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chaves_movimentadas_devolucao_set',
                        to='rh.Pessoa',
                        verbose_name='Pessoa Devolução',
                    ),
                ),
                (
                    'pessoa_emprestimo',
                    djtools.db.models.ForeignKeyPlus(
                        on_delete=django.db.models.deletion.CASCADE, related_name='chaves_movimentadas_emprestimo_set', to='rh.Pessoa', verbose_name='Pessoa Empréstimo'
                    ),
                ),
            ],
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterUniqueTogether(name='movimentacao', unique_together=set([('chave', 'data_emprestimo'), ('chave', 'data_devolucao')])),
    ]
