from django.urls import path

from eventos import views

urlpatterns = [
    path('calendario_eventos/', views.calendario_eventos),
    path('inscricao_publica/', views.inscricao_publica),
    path('inscricao_publica/<int:evento_id>/', views.inscricao_publica),
    path('evento/<int:evento_id>/', views.evento),
    path('deferir/<int:evento_id>/', views.deferir),
    path('indeferir/<int:evento_id>/', views.indeferir),
    path('cancelar_avaliacao/<int:evento_id>/', views.cancelar_avaliacao),
    path('cancelar/<int:evento_id>/', views.cancelar),
    path('desfazer_cancelamento/<int:evento_id>/', views.desfazer_cancelamento),
    path('desfazer_finalizacao/<int:evento_id>/', views.desfazer_finalizacao),
    path('ativar/<int:evento_id>/', views.ativar_evento),
    path('importar_participantes_evento/<int:evento_id>/<int:tipo_id>/', views.importar_participantes_evento),
    path('exportar_participantes_evento/<int:evento_id>/<int:tipo_id>/', views.exportar_participantes_evento),
    path('desativar/<int:evento_id>/', views.desativar_evento),
    path('submeter/<int:evento_id>/', views.submeter),
    path('devolver/<int:evento_id>/', views.devolver),
    path('finalizar/<int:evento_id>/', views.finalizar),
    path('relatorio/', views.relatorio),
    path('enviar_certificados/<int:evento_id>/<int:tipo_participante_id>/<str:pks>/', views.enviar_certificados),
    path('confirmar_presenca/<int:evento_id>/<int:tipo_participante_id>/<str:pks>/', views.confirmar_presenca),
    path('confirmar_inscricao/<int:evento_id>/<int:tipo_participante_id>/<str:pks>/', views.confirmar_inscricao),
    path('baixar_certificado/', views.baixar_certificado),
    path('baixar_certificado/<int:evento_id>/', views.baixar_certificado),
    path('baixar_certificado/<int:evento_id>/<int:atividade_id>/', views.baixar_certificado),
    path('adicionar_participante/<int:evento_id>/<int:tipo_id>/', views.adicionar_participante),
    path('informar_participantes/<int:pk>/<int:atividade_id>/', views.informar_participantes),
    path('lista_participantes/<int:pk>/<int:atividade_id>/', views.lista_participantes),
    path('lista_participantes_pdf/<int:pk>/<int:atividade_id>/', views.lista_participantes_pdf),
    path('editar_participante/<int:participante_id>/', views.editar_participante),
    path('informar_atividades/<int:participante_id>/', views.informar_atividades),
    path('adicionar_anexo_evento/<int:evento_id>/', views.adicionar_anexo_evento),
    path('adicionar_foto_evento/<int:evento_id>/', views.adicionar_foto_evento),
    path('enviar_link_registro_presenca/<int:evento_id>/<int:tipo_participante_id>/<str:pks>/', views.enviar_link_registro_presenca),
    path('confirmar_presenca_por_link/<int:evento_id>/<int:participante_id>/', views.confirmar_presenca_por_link),
    path('importar_lista_presenca/<int:evento_id>/<int:tipo_id>/', views.importar_lista_presenca),
    path('enviar_mensagem/<int:pk>/', views.enviar_mensagem),
]
