# Generated by Django 3.2.5 on 2021-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'permissions': (('pode_exibir_indicadores', 'Pode exibir indicadores'),), 'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='periodoreferencia',
            options={'permissions': (('pode_editar_meu_periodo_referencia', 'Pode editar meu período de referência'), ('pode_editar_periodo_referencia_global', 'Pode editar período de referência global')), 'verbose_name': 'Período de Referência', 'verbose_name_plural': 'Períodos de Referências'},
        ),
        migrations.AlterModelOptions(
            name='variavel',
            options={'permissions': (('pode_exibir_variaveis', 'Pode exibir variáveis'), ('pode_detalhar_variavel', 'Pode detalhar variável'), ('pode_comparar_variavel', 'Pode comparar variável')), 'verbose_name': 'Variável', 'verbose_name_plural': 'Variáveis'},
        ),
    ]
