# Generated by Django 2.2.10 on 2020-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('compras', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='processocompra',
            options={
                'permissions': (('pode_gerenciar_processocompra', 'Pode gerenciar processos de compra'),),
                'verbose_name': 'Processo de Compra',
                'verbose_name_plural': 'Processos de Compra',
            },
        ),
        migrations.AlterField(model_name='processocompra', name='data_fim', field=models.DateTimeField(verbose_name='Data de Fim')),
        migrations.AlterField(model_name='processocompra', name='data_inicio', field=models.DateTimeField(verbose_name='Data de Início')),
        migrations.AlterField(model_name='processocompra', name='observacao', field=models.TextField(blank=True, verbose_name='Observação')),
    ]
