# Generated by Django 2.2.16 on 2021-04-22 16:06

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_auto_20210126_1840'),
        ('compras', '0003_calendario_evento_tipoevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', djtools.db.models.CharFieldPlus(choices=[('alert', 'Amarelo'), ('info', 'Azul'), ('extra', 'Laranja'), ('extra2', 'Roxo'), ('success', 'Verde'), ('error', 'Vermelho'), ('nenhum', 'Nenhum')], help_text='Informe uma cor para a fase', max_length=255, verbose_name='Cor')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=1000, verbose_name='Descrição')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Data de Fim')),
                ('fase_inicial', models.BooleanField(default=False, verbose_name='É uma fase inicial?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fase do Processo',
                'verbose_name_plural': 'Fases do Processo',
            },
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=1000, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('componentes', djtools.db.models.ManyToManyFieldPlus(to='rh.Servidor', verbose_name='Servidores Relacionados')),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=1000, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nucleo_responsavel', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='compras.Nucleo', verbose_name='Núcleo Responsável')),
                ('tipo_calendario', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='compras.Calendario', verbose_name='Tipo do Calendário')),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processo',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoParticipacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitada_em', djtools.db.models.DateTimeFieldPlus(verbose_name='Solicitada Em')),
                ('campus_solicitante', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus Solicitante')),
                ('fase', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='compras.Fase', verbose_name='Fase')),
                ('solicitada_por', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Solicitada Por')),
            ],
            options={
                'verbose_name': 'Solicitação de Participação',
                'verbose_name_plural': 'Solicitações de Participação',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', djtools.db.models.CharFieldPlus(choices=[('Aberto', 'Aberto'), ('Suspenso', 'Suspenso'), ('Concluído', 'Concluído')], max_length=30, verbose_name='Situação')),
                ('tipo_processo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='compras.TipoProcesso', verbose_name='Tipo do Processo')),
            ],
            options={
                'verbose_name': 'Processo de Compra e Contratação',
                'verbose_name_plural': 'Processos de Compra e Contratação',
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='compras.Processo', verbose_name='Processo'),
        ),
    ]
