# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [('edu', '0002_auto_20190814_1454'), ('rh', '0001_initial'), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='AtividadeEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                (
                    'subgrupo',
                    models.IntegerField(
                        choices=[
                            (1, 'Aulas'),
                            (2, 'Atividade de Preparação, Manutenção e Apoio ao Ensino'),
                            (3, 'Programas ou Projetos de Ensino'),
                            (4, 'Atendimento, Acompanhamento, Avaliação e Orientação de Alunos'),
                            (5, 'Reuniões Pedagógicas, de Grupo e Afins'),
                        ],
                        verbose_name='Subgrupo',
                    ),
                ),
            ],
            options={'verbose_name': 'Atividade de Ensino', 'verbose_name_plural': 'Atividades de Ensino'},
        ),
        migrations.CreateModel(
            name='AtividadeExtensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Atividade de Extensão', 'verbose_name_plural': 'Atividades de Extensão'},
        ),
        migrations.CreateModel(
            name='AtividadeGestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Atividade de Gestão', 'verbose_name_plural': 'Atividades de Gestão'},
        ),
        migrations.CreateModel(
            name='AtividadePesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Atividade de Pesquisa e Inovação', 'verbose_name_plural': 'Atividades de Pesquisa e Inovação'},
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djtools.db.models.DateTimeFieldPlus(verbose_name='Data')),
                ('obs', models.TextField(verbose_name='Observação')),
            ],
            options={'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.CreateModel(
            name='PlanoIndividualTrabalhoV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.IntegerField(choices=settings.PERIODO_LETIVO_CHOICES, verbose_name='Período Letivo')),
                ('ch_preparacao_manutencao_ensino', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('obs_preparacao_manutencao_ensino', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_preparacao_manutencao_ensino', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_apoio_ensino', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_apoio_ensino', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_apoio_ensino', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_apoio_ensino', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_programas_projetos_ensino', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('obs_programas_projetos_ensino', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_programas_projetos_ensino', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_orientacao_alunos', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_orientacao_alunos', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_orientacao_alunos', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_orientacao_alunos', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_reunioes', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_reunioes', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_reunioes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_reunioes', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_pesquisa', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_pesquisa', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_pesquisa', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_pesquisa', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_extensao', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_extensao', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_extensao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_extensao', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('ch_gestao', models.PositiveIntegerField(default=0, verbose_name='Carga-Horária')),
                ('outras_atividades_gestao', models.TextField(blank=True, null=True, verbose_name='Outras Atividades')),
                ('obs_gestao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_gestao', djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo')),
                ('data_envio', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data do Envio do Plano')),
                ('aprovado', models.NullBooleanField(verbose_name='Plano Aprovado')),
                ('data_aprovacao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Aprovação do Plano')),
                ('relatorio_entregue', models.NullBooleanField(verbose_name='Relatório Entregue')),
                ('relatorio_aprovado', models.NullBooleanField(verbose_name='Relatório Aprovado')),
                ('data_aprovacao_relatorio', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Aprovação do Relatório')),
                ('publicado', models.NullBooleanField(verbose_name='Publicado')),
                ('data_publicacao', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data da Publicação')),
                ('ano_letivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano', verbose_name='Ano Letivo')),
                ('atividades_apoio_ensino', djtools.db.models.ManyToManyFieldPlus(related_name='a1', to='pit_rit_v2.AtividadeEnsino', verbose_name='Atividades')),
                ('atividades_extensao', djtools.db.models.ManyToManyFieldPlus(to='pit_rit_v2.AtividadeExtensao', verbose_name='Atividades')),
                ('atividades_gestao', djtools.db.models.ManyToManyFieldPlus(to='pit_rit_v2.AtividadeGestao', verbose_name='Atividades')),
                ('atividades_orientacao_alunos', djtools.db.models.ManyToManyFieldPlus(related_name='a2', to='pit_rit_v2.AtividadeEnsino', verbose_name='Atividades')),
                ('atividades_pesquisa', djtools.db.models.ManyToManyFieldPlus(to='pit_rit_v2.AtividadePesquisa', verbose_name='Atividades')),
                ('atividades_reunioes', djtools.db.models.ManyToManyFieldPlus(related_name='a3', to='pit_rit_v2.AtividadeEnsino', verbose_name='Atividades')),
                ('avaliador', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Avaliador')),
                ('professor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Professor', verbose_name='Professor')),
                (
                    'responsavel_publicacao',
                    djtools.db.models.ForeignKeyPlus(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responsavel_publiacao_set',
                        to='rh.Servidor',
                        verbose_name='Responsável pela Publicação',
                    ),
                ),
            ],
            options={'verbose_name': 'Plano Individual de Trabalho', 'verbose_name_plural': 'Planos Individuais de Trabalho'},
        ),
        migrations.AddField(
            model_name='parecer',
            name='pit',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, to='pit_rit_v2.PlanoIndividualTrabalhoV2', verbose_name='Plano Individual de Trabalho'
            ),
        ),
    ]
