# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 17:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0002_auto_20190902_1545'), ('pit_rit_v2', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='planoindividualtrabalhov2',
            name='avaliador_relatorio',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliador_relatorio_set', to='rh.Servidor', verbose_name='Avaliador do Relatório'
            ),
        ),
        migrations.AddField(
            model_name='planoindividualtrabalhov2', name='data_envio_relatorio', field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data do Envio do Relatório')
        ),
        migrations.AlterField(
            model_name='planoindividualtrabalhov2',
            name='avaliador',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Avaliador do Plano'),
        ),
        migrations.AddField(
            model_name='parecer',
            name='tipo',
            field=djtools.db.models.CharFieldPlus(choices=[['PIT', 'PIT'], ['RIT', 'RIT']], max_length=255, null=True, verbose_name='Tipo', default='PIT'),
        ),
    ]
