# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 17:35
from __future__ import unicode_literals

from django.db import migrations


def update_avaliador(apps, schema_editor):
    PlanoIndividualTrabalhoV2 = apps.get_model('pit_rit_v2', 'PlanoIndividualTrabalhoV2')
    for plano in PlanoIndividualTrabalhoV2.objects.all():
        if plano.avaliador and plano.relatorio_entregue:
            plano.avaliador_relatorio = plano.avaliador
            plano.save()


def reverse_update_avaliador(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('pit_rit_v2', '0002_auto_20191016_1734')]

    operations = [migrations.RunPython(update_avaliador, reverse_update_avaliador)]
