# Generated by Django 2.2.10 on 2020-04-15 07:59

from django.db import migrations


def update_data_envio(apps, schema_editor):
    PlanoIndividualTrabalhoV2 = apps.get_model('pit_rit_v2', 'PlanoIndividualTrabalhoV2')
    for rit in PlanoIndividualTrabalhoV2.objects.filter(data_envio_relatorio__isnull=True, relatorio_entregue=True):
        rit.data_envio_relatorio = rit.data_aprovacao or rit.data_aprovacao_relatorio
        rit.save()


def reverse_update_data_envio(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('pit_rit_v2', '0003_auto_20191016_1735')]

    operations = [migrations.RunPython(update_data_envio, reverse_update_data_envio)]
