# Generated by Django 2.2.10 on 2020-04-23 18:07

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('rh', '0010_auto_20200421_1719'), ('pit_rit_v2', '0004_auto_20200415_0759')]

    operations = [
        migrations.AlterModelOptions(name='parecer', options={'ordering': ('-data',), 'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'}),
        migrations.RemoveField(model_name='planoindividualtrabalhov2', name='relatorio_entregue'),
        migrations.AddField(
            model_name='parecer',
            name='servidor',
            field=djtools.db.models.ForeignKeyPlus(
                help_text='Servidor que emitiu o parecer', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Servidor'
            ),
        ),
        migrations.AddField(
            model_name='planoindividualtrabalhov2',
            name='arquivo_aulas',
            field=djtools.db.models.FileFieldPlus(blank=True, null=True, upload_to='pit_rit_v2', verbose_name='Arquivo'),
        ),
        migrations.AddField(model_name='planoindividualtrabalhov2', name='obs_aulas', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_apoio_ensino', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_extensao', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_gestao', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_orientacao_alunos', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_pesquisa', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_preparacao_manutencao_ensino', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_programas_projetos_ensino', field=models.TextField(null=True, verbose_name='Observações')),
        migrations.AlterField(model_name='planoindividualtrabalhov2', name='obs_reunioes', field=models.TextField(null=True, verbose_name='Observações')),
    ]
