# Generated by Django 2.2.10 on 2020-04-27 15:31

from django.db import migrations


def update_data_envio(apps, schema_editor):
    PlanoIndividualTrabalhoV2 = apps.get_model('pit_rit_v2', 'PlanoIndividualTrabalhoV2')
    qs = PlanoIndividualTrabalhoV2.objects.filter(data_envio_relatorio__isnull=False, avaliador_relatorio__isnull=True, relatorio_aprovado__isnull=True)
    for q in qs:
        q.data_envio_relatorio = None
        q.save()


def reverse_update_data_envio(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('pit_rit_v2', '0005_auto_20200423_1807')]

    operations = [migrations.RunPython(update_data_envio, reverse_update_data_envio)]
