# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit_rit_v2', '0006_auto_20200427_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoindividualtrabalhov2',
            name='aprovado',
            field=models.BooleanField(null=True, verbose_name='Plano Aprovado'),
        ),
        migrations.AlterField(
            model_name='planoindividualtrabalhov2',
            name='publicado',
            field=models.BooleanField(null=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='planoindividualtrabalhov2',
            name='relatorio_aprovado',
            field=models.BooleanField(null=True, verbose_name='Relatório Aprovado'),
        ),
    ]
