# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('edu', '0002_auto_20190814_1454'), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'avaliacao_carga_horaria',
                    djtools.db.models.CharFieldPlus(
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        verbose_name='Avaliação da Carga Horária',
                    ),
                ),
                (
                    'avaliacao_sequencia_didatica',
                    djtools.db.models.CharFieldPlus(
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        verbose_name='Avaliação da Sequência Didática',
                    ),
                ),
                (
                    'avaliacao_ementa_disciplina',
                    djtools.db.models.CharFieldPlus(
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        verbose_name='Avaliação da Ementa da Disciplina',
                    ),
                ),
                ('avaliacao_carga_horaria_justificativa', models.TextField(blank=True, null=True)),
                ('avaliacao_sequencia_didatica_justificativa', models.TextField(blank=True, null=True)),
                ('avaliacao_ementa_disciplina_justificativa', models.TextField(blank=True, null=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='AvaliacaoProcessualCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'avaliacao_regime_credito',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                    ),
                ),
                ('identificacao_5_bolsa_trabalho', models.BooleanField(default=False, help_text='Utiliza bolsa trabalho', verbose_name='Bolsa trabalho')),
                ('identificacao_5_alimentacao', models.BooleanField(default=False, help_text='Utiliza bolsa alimentação', verbose_name='Alimentação')),
                ('identificacao_5_transporte', models.BooleanField(default=False, help_text='Utiliza bolsa transporte', verbose_name='Transporte')),
                (
                    'identificacao_5_outroi',
                    models.BooleanField(default=False, help_text='Utiliza aluma bolsa sem ser de trabalho, alimentação e transporte.', verbose_name='Outro'),
                ),
                ('identificacao_5_outroii', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Outro')),
                ('identificacao_7_bolsa_de_IC_ifrn', models.BooleanField(default=False, verbose_name='Bolsa de iniciação científica do IFRN')),
                ('identificacao_7_bolsa_de_IC_externa', models.BooleanField(default=False, verbose_name='Bolsa de iniciação científica externa')),
                ('identificacao_7_bolsa_de_extensao_ifrn', models.BooleanField(default=False, verbose_name='Bolsa de extensão do IFRN')),
                ('identificacao_7_bolsa_de_extensao_externa', models.BooleanField(default=False, verbose_name='Bolsa de extensão externa')),
                ('identificacao_7_pibid', models.BooleanField(default=False, verbose_name='PIBID')),
                ('identificacao_7_pibic', models.BooleanField(default=False, verbose_name='PIBIC')),
                ('identificacao_7_pibit', models.BooleanField(default=False, verbose_name='PIBIT')),
                (
                    'identificacao_8',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[
                            ['Sim, trabalho em empresa pública', 'Sim, trabalho em empresa pública'],
                            ['Sim, trabalho em empresa privada', 'Sim, trabalho em empresa privada'],
                            ['Sim, trabalho como autônomo', 'Sim, trabalho como autônomo'],
                            ['Sim, faço estágio em empresa pública', 'Sim, faço estágio em empresa pública'],
                            ['Sim, faço estágio em empresa privada', 'Sim, faço estágio em empresa privada'],
                            ['Não', 'Não'],
                        ],
                        max_length=255,
                        null=True,
                        verbose_name='Trabalha ou faz estágio?',
                    ),
                ),
                (
                    'identificacao_9',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Sim', 'Sim'], ['Não', 'Não'], ['Não estou trabalhando/estagiando', 'Não estou trabalhando/estagiando']],
                        max_length=255,
                        null=True,
                        verbose_name='O Trabalho/Estágio foi conseguido por intermédio do curso?',
                    ),
                ),
                ('parte_2_I_4', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Organização do curso em Regime de Crédito')),
                ('parte_2_I_5', models.TextField(blank=True, null=True, verbose_name='Sugestões')),
                (
                    'parte_2_II_a_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Infraestrutura das salas de aulas',
                    ),
                ),
                (
                    'parte_2_II_a_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Qualidade dos equipamentos nos laboratórios',
                    ),
                ),
                (
                    'parte_2_II_a_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Quantidade de alunos por aula laboratório',
                    ),
                ),
                (
                    'parte_2_II_a_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Qualidade dos equipamentos nas sala de aula',
                    ),
                ),
                (
                    'parte_2_II_a_5',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Material didático',
                    ),
                ),
                (
                    'parte_2_II_a_6',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Qualidade dos livros da biblioteca',
                    ),
                ),
                (
                    'parte_2_II_a_7',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Funcionamento da biblioteca',
                    ),
                ),
                (
                    'parte_2_II_a_8',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Acessibilidade à salas de aula, laboratórios e demais espaços',
                    ),
                ),
                (
                    'parte_2_II_b_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='aulas expositivas',
                    ),
                ),
                (
                    'parte_2_II_b_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='seminários e oficinas',
                    ),
                ),
                (
                    'parte_2_II_b_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='eventos científico-artístico-culturais',
                    ),
                ),
                (
                    'parte_2_II_b_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='aulas de campo',
                    ),
                ),
                (
                    'parte_2_II_b_5',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='aulas práticas em laboratórios',
                    ),
                ),
                (
                    'parte_2_II_b_6',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='aulas de recuperação e centros de aprendizagens',
                    ),
                ),
                (
                    'parte_2_II_b_7',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='desenvolvimento do projeto integrador',
                    ),
                ),
                (
                    'parte_2_II_b_8i',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='outros',
                    ),
                ),
                ('parte_2_II_b_8ii', models.TextField(blank=True, null=True, verbose_name='outros')),
                (
                    'parte_2_II_c_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='a sua participação em projetos de pesquisa',
                    ),
                ),
                (
                    'parte_2_II_c_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='a sua participação em projetos de extensão',
                    ),
                ),
                (
                    'parte_2_II_c_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='o desenvolvimento de projetos de pesquisas na formação dos estudantes durante o curso',
                    ),
                ),
                (
                    'parte_2_II_c_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='o desenvolvimento de projetos de extensão na formação dos estudantes durante o curso',
                    ),
                ),
                (
                    'parte_2_II_c_5',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='qualidade dos projetos de pesquisas desenvolvidos durante o curso',
                    ),
                ),
                (
                    'parte_2_II_c_6',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='qualidade dos projetos de extensão desenvolvidos durante o curso',
                    ),
                ),
                (
                    'parte_2_II_d_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Orientações recebidas para a realização da prática profissional',
                    ),
                ),
                (
                    'parte_2_II_d_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Orientações recebidas para a elaboração de TCC',
                    ),
                ),
                (
                    'parte_2_II_d_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Organização interna para o desenvolvimento da prática profissional',
                    ),
                ),
                (
                    'parte_2_II_d_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Qualidade do acompanhamento da prática profissional',
                    ),
                ),
                (
                    'parte_2_II_e_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Acompanhamento pedagógico',
                    ),
                ),
                (
                    'parte_2_II_e_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Organização e funcionamento do trabalho coletivo entre os educadores',
                    ),
                ),
                (
                    'parte_2_II_e_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Atendimento na Diretoria Acadêmica',
                    ),
                ),
                ('parte_2_II_e_4', models.TextField(blank=True, null=True, verbose_name='Sugestões')),
                (
                    'parte_2_II_f_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Acompanhamento pedagógico',
                    ),
                ),
                (
                    'parte_2_II_f_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Estrutura do curso',
                    ),
                ),
                (
                    'parte_2_II_f_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Procedimentos metodológicos utilizados',
                    ),
                ),
                (
                    'parte_2_II_f_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Práticas de avaliação da aprendizagem',
                    ),
                ),
                (
                    'parte_2_II_f_5',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Articulação entre teoria e prática',
                    ),
                ),
                (
                    'parte_2_II_f_6',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Indissociabilidade entre ensino, pesquisa e extensão',
                    ),
                ),
                (
                    'parte_2_II_f_7',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Práticas interdisciplinares',
                    ),
                ),
                ('parte_2_II_f_8', models.TextField(blank=True, null=True, verbose_name='Sugestões')),
                (
                    'parte_2_II_g_1',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Participação, envolvimento/motivação nas atividades do curso',
                    ),
                ),
                (
                    'parte_2_II_g_2',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Desempenho nas disciplinas',
                    ),
                ),
                (
                    'parte_2_II_g_3',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Identidade com o curso',
                    ),
                ),
                (
                    'parte_2_II_g_4',
                    djtools.db.models.CharFieldPlus(
                        blank=True,
                        choices=[['Ótimo', 'Ótimo'], ['Bom', 'Bom'], ['Regular', 'Regular'], ['Insuficiente', 'Insuficiente'], ['Desconheço', 'Desconheço']],
                        max_length=255,
                        null=True,
                        verbose_name='Responsabilidade com as atividades estudantis',
                    ),
                ),
                (
                    'parte_2_II_h_1',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Participação em projetos de pesquisa e/ou extensão'
                    ),
                ),
                (
                    'parte_2_II_h_2',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Acompanhamento pedagógico'),
                ),
                (
                    'parte_2_II_h_3',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Programas de Assistência Estudantil'
                    ),
                ),
                (
                    'parte_2_II_h_4',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Condições de infraestrutura do curso'
                    ),
                ),
                (
                    'parte_2_II_h_5',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Articulação teoria-prática'),
                ),
                (
                    'parte_2_II_h_6',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Acompanhamento do estágio'),
                ),
                (
                    'parte_2_II_h_7i',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Outros (descrever)'),
                ),
                ('parte_2_II_h_7ii', models.TextField(blank=True, null=True)),
                (
                    'parte_2_II_i_1',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Metodologia de ensino adotada'
                    ),
                ),
                (
                    'parte_2_II_i_2',
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)],
                        null=True,
                        verbose_name='Dificuldade de conciliar o trabalho com o estudo',
                    ),
                ),
                (
                    'parte_2_II_i_3',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Dificuldade de aprendizagem'
                    ),
                ),
                (
                    'parte_2_II_i_4',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Nível de complexidade dos conteúdos'
                    ),
                ),
                (
                    'parte_2_II_i_5',
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)],
                        null=True,
                        verbose_name='Critérios e instrumentos de avaliação utilizados',
                    ),
                ),
                (
                    'parte_2_II_i_6',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Estrutura curricular do curso'
                    ),
                ),
                (
                    'parte_2_II_i_7',
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)],
                        null=True,
                        verbose_name='Infraestrutura e recursos materiais do curso/instituição',
                    ),
                ),
                (
                    'parte_2_II_i_8i',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True, verbose_name='Outro (descrever)'),
                ),
                ('parte_2_II_i_8ii', models.TextField(blank=True, null=True)),
                (
                    'parte_2_II_j_1',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Metodologia de ensino adotada '
                    ),
                ),
                (
                    'parte_2_II_j_2',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Dificuldade de conciliar o trabalho com o estudo'
                    ),
                ),
                (
                    'parte_2_II_j_3',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Mudança de cidade'),
                ),
                (
                    'parte_2_II_j_4',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Dificuldade de aprendizagem'
                    ),
                ),
                ('parte_2_II_j_5', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Reprovação')),
                (
                    'parte_2_II_j_6',
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Dificuldades com transporte'
                    ),
                ),
                (
                    'parte_2_II_j_7i',
                    models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name='Outro (descrever)'),
                ),
                ('parte_2_II_j_7ii', models.TextField(blank=True, null=True)),
                ('parte_2_observacoes_sugestoes', models.TextField(blank=True, null=True, verbose_name='Sugestões de melhorias')),
                ('aluno', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='ItemQuestionarioMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Disciplina')),
                ('nucleo', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Núcleo')),
                (
                    'periodo',
                    djtools.db.models.CharFieldPlus(
                        help_text='Caso a discplina seja ofertada em mais de um período, informe os períodos separados por ";"', max_length=255, verbose_name='Período'
                    ),
                ),
                (
                    'aulas_por_semana',
                    djtools.db.models.CharFieldPlus(
                        help_text='Caso tenha informado mais de um período no campo anterior, separa a quantidade de aulas por semana com ";" ',
                        max_length=255,
                        verbose_name='Aulas por semana',
                    ),
                ),
            ],
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.CreateModel(
            name='PeriodoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('ano', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Ano')),
            ],
            options={'verbose_name': 'Período de Resposta', 'verbose_name_plural': 'Períodos de Resposta'},
        ),
        migrations.CreateModel(
            name='QuestionarioMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('periodo', models.IntegerField(help_text='Período a partir do qual os alunos deverão realizar a avaliação. Ex: 3', verbose_name='Período')),
                ('cursos', djtools.db.models.ManyToManyFieldPlus(to='edu.CursoCampus', verbose_name='Curso')),
            ],
            options={'verbose_name': 'Questionário de Matriz', 'verbose_name_plural': 'Questionários de Matrizes'},
        ),
        migrations.AddField(
            model_name='itemquestionariomatriz',
            name='questionario_matriz',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pedagogia.QuestionarioMatriz', verbose_name='Questionário da Matriz'),
        ),
        migrations.AddField(
            model_name='avaliacaoprocessualcurso',
            name='questionario_matriz',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pedagogia.QuestionarioMatriz', verbose_name='Questionário da Matriz'),
        ),
        migrations.AddField(
            model_name='avaliacaodisciplina',
            name='avaliacao_processual_curso',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, to='pedagogia.AvaliacaoProcessualCurso', verbose_name='Avaliação Processual do Curso'
            ),
        ),
        migrations.AddField(
            model_name='avaliacaodisciplina',
            name='item_questionario_matriz',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='pedagogia.ItemQuestionarioMatriz', verbose_name='Disciplina'),
        ),
    ]
