# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


import contratos.models
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('numero', djtools.db.models.CharFieldPlus(help_text='No formato: 99999/9999', max_length=255, verbose_name='Número')),
                ('valor', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('data_inicio', djtools.db.models.DateFieldPlus(blank=True, db_column='data_inicio', null=True, verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, db_column='data_fim', null=True, verbose_name='Data de Vencimento')),
                ('de_prazo', models.BooleanField(default=False, verbose_name='Aditivo de Prazo')),
                ('de_valor', models.BooleanField(default=False, verbose_name='Aditivo de Valor')),
                ('de_fiscal', models.BooleanField(default=False, verbose_name='Aditivo de Fiscal')),
                ('de_outro', models.BooleanField(default=False, verbose_name='Outros')),
                ('especificacao', models.TextField(blank=True, null=True, verbose_name='Especificação')),
                (
                    'tipo_termo_aditivo',
                    djtools.db.models.CharFieldPlus(
                        blank=True, choices=[['MAJ', 'Majoração'], ['SUP', 'Supressão']], max_length=5, null=True, verbose_name='Tipo de Termo de Aditivo'
                    ),
                ),
                ('numero_parcelas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('numero_processo', djtools.db.models.CharFieldPlus(blank=True, max_length=20, null=True, verbose_name='Número Processo')),
                (
                    'numero_empenho',
                    djtools.db.models.CharFieldPlus(
                        blank=True, help_text='Números de Empenhos separados por vírgula', max_length=255, null=True, verbose_name='Números de Empenhos'
                    ),
                ),
            ],
            options={'verbose_name': 'Termos Aditivos'},
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(help_text='Breve descrição sobre o conteúdo do anexo', max_length=255, verbose_name='Descrição')),
                ('data', models.DateTimeField(null=True)),
            ],
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.CreateModel(
            name='Apostilamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacao', models.TextField(blank=True, null=True, verbose_name='Especificação')),
                ('numero', djtools.db.models.CharFieldPlus(help_text='No formato: 99999/9999', max_length=255, verbose_name='Número')),
                ('valor', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('data_inicio', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', djtools.db.models.DateFieldPlus(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('arquivo', models.FileField(upload_to=contratos.models.anexo_apostilamento_path)),
                ('numero_processo', djtools.db.models.CharFieldPlus(blank=True, max_length=20, null=True, verbose_name='Número Processo')),
                (
                    'numero_empenho',
                    djtools.db.models.CharFieldPlus(
                        blank=True, help_text='Números de Empenhos separados por vírgula', max_length=255, null=True, verbose_name='Números de Empenhos'
                    ),
                ),
            ],
            options={'verbose_name': 'Apostilamento', 'verbose_name_plural': 'Apostilamentos'},
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', djtools.db.models.CharFieldPlus(help_text='No formato: 99999/9999', max_length=255, verbose_name='Número')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Valor do Contrato')),
                ('valor_executado', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Executado')),
                ('valor_total', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total')),
                ('valor_previsto_parcela', djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio', djtools.db.models.DateFieldPlus(db_column='data_inicio', verbose_name='Data de Início')),
                (
                    'data_fim',
                    models.DateField(
                        blank=True,
                        db_column='data_fim',
                        help_text='Caso você não informe uma Data de Término, o Contrato vai ser considerado como Indeterminado',
                        null=True,
                        verbose_name='Data de Término',
                    ),
                ),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento do Contrato')),
                ('objeto', models.TextField(max_length=500, verbose_name='Objeto de Contrato')),
                ('continuado', models.BooleanField(default=False, verbose_name='É Continuado?')),
                ('qtd_parcelas', models.SmallIntegerField(db_column='qtd_parcelas', default=1, verbose_name='Quantidade de Parcelas')),
                ('pregao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pregão')),
                ('estimativa_licitacao', models.DateField(blank=True, null=True, verbose_name='Estimativa para início dos procedimentos para nova Licitação')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído?')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado?')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo de Cancelamento')),
                ('dh_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Cancelamento')),
                ('numero_processo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Processo')),
                (
                    'numero_empenho',
                    models.CharField(blank=True, help_text='Números de Empenhos separados por vírgula', max_length=100, null=True, verbose_name='Números de Empenhos'),
                ),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'permissions': (
                    ('pode_visualizar_contrato', 'Pode visualizar contrato'),
                    ('pode_submeter_arquivo', 'Pode submeter arquivo'),
                    ('pode_visualizar_arquivo', 'Pode visualizar aquivo'),
                    ('pode_efetuar_medicao', 'Pode efetuar medição'),
                    ('pode_gerar_cronograma', 'Pode gerar cronograma'),
                    ('pode_visualizar_cronograma', 'Pode visualizar cronograma'),
                    ('pode_adicionar_publicacao', 'Pode adicionar publicação'),
                    ('pode_excluir_publicacao', 'Pode excluir publicação'),
                    ('pode_submeter_publicacao', 'Pode submeter publicação'),
                    ('pode_adicionar_anexo', 'Pode adicionar anexo'),
                    ('pode_visualizar_anexo', 'Pode visualizar anexo'),
                    ('pode_visualizar_publicacao', 'Pode visualizar publicação'),
                    ('pode_adicionar_fiscal', 'Pode adicionar fiscal'),
                    ('pode_excluir_fiscal', 'Pode exlcuir fiscal'),
                    ('pode_aditivar_contrato', 'Pode aditivar contrato'),
                    ('pode_cancelar_contrato', 'Pode cancelar contrato'),
                    ('pode_submeter_medicao', 'Pode submeter medição'),
                ),
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Número do Cronograma')),
                ('nl', djtools.db.models.CharFieldPlus(help_text='Nota de Lançamento', max_length=25, null=True, verbose_name='NL')),
                ('rc', djtools.db.models.CharFieldPlus(help_text='Registro de Contrato', max_length=25, null=True, verbose_name='RC')),
            ],
            options={'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portaria', djtools.db.models.CharFieldPlus(max_length=20, verbose_name='Portaria')),
                (
                    'data_nomeacao',
                    djtools.db.models.DateFieldPlus(
                        blank=True, help_text='Data em que o servidor foi nomeado fiscal do contrato (consultar portaria)', null=True, verbose_name='Data da Nomeação'
                    ),
                ),
                (
                    'data_vigencia',
                    djtools.db.models.DateFieldPlus(
                        blank=True, help_text='Data limite prevista para atuação como fiscal do contrato (consultar portaria)', null=True, verbose_name='Data da Vigência'
                    ),
                ),
                ('data_exclusao', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data da Exclusão')),
                ('inativo', models.BooleanField(default=False, verbose_name='Inativo?')),
            ],
            options={'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo',
                    djtools.db.models.CharFieldPlus(
                        choices=[['SEGURO', 'Seguro Garantia'], ['FIANCA', 'Fiança'], ['CAUCAO', 'Caução']], max_length=20, verbose_name='Tipo de Garantia'
                    ),
                ),
                ('vigencia', djtools.db.models.DateFieldPlus(verbose_name='Data de Vigência')),
                ('pa_siafi', djtools.db.models.CharFieldPlus(help_text='Lançamento patrimonial (PA) SIAFI', max_length=255, verbose_name='PA do SIAFI')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('consulta_susep', models.FileField(help_text='Susep, anexos, etc', null=True, upload_to=contratos.models.consulta_susep_path, verbose_name='Anexo')),
            ],
            options={'verbose_name': 'Garantias'},
        ),
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', djtools.db.models.DateFieldPlus(verbose_name='Data de Nascimento')),
                ('categoria', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Categoria')),
                ('funcao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Função')),
                ('escolaridade', djtools.db.models.CharFieldPlus(max_length=100, verbose_name='Escolaridade')),
                ('jornada_trabalho', djtools.db.models.CharFieldPlus(max_length=40, verbose_name='Jornada de Trabalho')),
                ('salario_bruto', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Salário Bruto')),
                ('custo_mensal', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, verbose_name='Custo Mensal')),
                ('desligamento', djtools.db.models.DateFieldPlus(null=True, verbose_name='Data de Desligamento')),
            ],
            options={'verbose_name': 'Mãos-de-Obra'},
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_medicao', models.DateField()),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('valor_executado', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ocorrencia', models.TextField(max_length=500, verbose_name='Ocorrência')),
                ('providencia', models.TextField(max_length=500, null=True, verbose_name='Providência Adotada')),
                ('numero_processo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número Processo')),
                ('arquivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
                ('fiscal', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Fiscal')),
            ],
            options={'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.CreateModel(
            name='MedicaoEletrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'mes_referencia',
                    djtools.db.models.PositiveIntegerFieldPlus(
                        choices=[
                            [1, 'Janeiro'],
                            [2, 'Fevereiro'],
                            [3, 'Março'],
                            [4, 'Abril'],
                            [5, 'Maio'],
                            [6, 'Junho'],
                            [7, 'Julho'],
                            [8, 'Agosto'],
                            [9, 'Setembro'],
                            [10, 'Outubro'],
                            [11, 'Novembro'],
                            [12, 'Dezembro'],
                        ],
                        verbose_name='Mês de Referência',
                    ),
                ),
                ('ano_referencia', djtools.db.models.PositiveIntegerFieldPlus(verbose_name='Ano de Referência')),
                ('consumo_ponta', djtools.db.models.DecimalFieldPlus(decimal_places=0, max_digits=12, null=True, verbose_name='Consumo Ponta(kWh)')),
                ('consumo_fora_ponta', djtools.db.models.DecimalFieldPlus(decimal_places=0, max_digits=12, null=True, verbose_name='Consumo Fora de Ponta(kWh)')),
                ('medicao', djtools.db.models.OneToOneFieldPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Medicao')),
            ],
            options={'verbose_name': 'Medição Elétrica', 'verbose_name_plural': 'Medições Elétricas'},
        ),
        migrations.CreateModel(
            name='MotivoConclusaoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Motivo de Conclusão de Contrato', 'verbose_name_plural': 'Motivos de Conclusão de Contratos'},
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(max_length=1024, verbose_name='Descrição')),
                ('prazo_resolucao', models.DateField(null=True, verbose_name='Prazo para Resolução')),
                ('situacao', models.CharField(blank=True, choices=[['PEN', 'Pendente'], ['RES', 'Resolvida']], max_length=3, null=True, verbose_name='Situação')),
                ('anexo_resposta', models.FileField(null=True, upload_to=contratos.models.anexo_resposta_ocorrencia_path)),
                ('notificacao_enviada', models.BooleanField(default=False, verbose_name='Notificação Enviada?')),
                ('arquivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
                ('contrato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
                ('fiscal', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Fiscal')),
            ],
            options={'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista_inicio', models.DateField(verbose_name='Data Prevista Início')),
                ('data_prevista_fim', models.DateField(verbose_name='Data Prevista Conclusão')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sem_medicao', models.NullBooleanField(verbose_name='Parcela Sem Medição')),
                ('cronograma', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_set', to='contratos.Cronograma')),
            ],
            options={'verbose_name': 'Parcela de Contrato', 'verbose_name_plural': 'Parcelas de Contrato'},
        ),
        migrations.CreateModel(
            name='PublicacaoAditivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', djtools.db.models.CharFieldPlus(max_length=50, verbose_name='Número')),
                ('data', djtools.db.models.DateFieldPlus(verbose_name='Data da Publicação')),
                ('descricao', djtools.db.models.CharFieldPlus(help_text='Breve descrição sobre o conteúdo da publicação', max_length=255, verbose_name='Descrição')),
                ('aditivo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_set', to='contratos.Aditivo')),
                ('arquivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
            ],
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.CreateModel(
            name='PublicacaoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Número')),
                ('data', models.DateField()),
                ('descricao', djtools.db.models.CharFieldPlus(help_text='Breve descrição sobre o conteúdo da publicação', max_length=255, verbose_name='Descrição')),
                ('arquivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
                (
                    'contrato',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_set', to='contratos.Contrato', verbose_name='Contrato'),
                ),
            ],
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.CreateModel(
            name='SubtipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Subtipo de Contrato', 'verbose_name_plural': 'Subtipos de Contratos'},
        ),
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Anexo', 'verbose_name_plural': 'Tipos de Anexos'},
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=30, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Contrato', 'verbose_name_plural': 'Tipos de Contratos'},
        ),
        migrations.CreateModel(
            name='TipoFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('pode_gerenciar_todas_medicoes_contrato', models.BooleanField(default=False, verbose_name='Físcal pode gerênciar medições de outros fiscais?')),
            ],
            options={'verbose_name': 'Tipo de Fiscal', 'verbose_name_plural': 'Tipos de Fiscais'},
        ),
        migrations.CreateModel(
            name='TipoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Licitação', 'verbose_name_plural': 'Tipos de Licitação'},
        ),
        migrations.CreateModel(
            name='TipoPublicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
            ],
            options={'verbose_name': 'Tipo de Publicação', 'verbose_name_plural': 'Tipos de Publicações'},
        ),
        migrations.AddField(
            model_name='subtipocontrato',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoContrato', verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='publicacaocontrato',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoPublicacao', verbose_name='Tipo de Publicação'),
        ),
        migrations.AddField(
            model_name='publicacaoaditivo', name='tipo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoPublicacao')
        ),
        migrations.AddField(
            model_name='medicao',
            name='parcela',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_set', to='contratos.Parcela'),
        ),
    ]
