# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comum', '0002_auto_20190814_1443'),
        ('rh', '0001_initial'),
        ('contratos', '0001_initial'),
        ('protocolo', '0001_initial'),
        ('almoxarifado', '0002_auto_20190814_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicao_processo_set', to='protocolo.Processo', verbose_name='Processo'
            ),
        ),
        migrations.AddField(
            model_name='maodeobra',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='maodeobra_set', to='contratos.Contrato'),
        ),
        migrations.AddField(
            model_name='maodeobra',
            name='prestador_servico',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.PROTECT, related_name='prestadorservico_set', to='comum.PrestadorServico'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='garantias_set', to='contratos.Contrato'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(db_column='campus_id', on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campi'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='fiscais_set', to='contratos.Contrato'),
        ),
        migrations.AddField(model_name='fiscal', name='servidor', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
        migrations.AddField(
            model_name='fiscal',
            name='termo_aditivo',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.Aditivo'),
        ),
        migrations.AddField(model_name='fiscal', name='tipo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoFiscal')),
        migrations.AddField(model_name='cronograma', name='contrato', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
        migrations.AddField(model_name='contrato', name='arquivo', field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
        migrations.AddField(
            model_name='contrato',
            name='campi',
            field=models.ManyToManyField(db_column='campus_id', related_name='contrato_uo_set', to='rh.UnidadeOrganizacional', verbose_name='Campi'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratada',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaJuridica', verbose_name='Contratada'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empenho',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_empenho_set', to='almoxarifado.Empenho', verbose_name='Empenho'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_conclusao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.MotivoConclusaoContrato', verbose_name='Motivo de Conclusão'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_processo_set', to='protocolo.Processo', verbose_name='Processo'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='subtipo',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.SubtipoContrato', verbose_name='SubTipo de Contrato'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='contratos_set', to='contratos.TipoContrato', verbose_name='Tipo de Contrato'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_licitacao',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_set', to='contratos.TipoLicitacao', verbose_name='Tipo de Licitação'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_cancelamento',
            field=djtools.db.models.ForeignKeyPlus(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usuario_cancelamento',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário Cancelamento',
            ),
        ),
        migrations.AddField(
            model_name='apostilamento',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='apostilamentos_set', to='contratos.Contrato'),
        ),
        migrations.AddField(model_name='anexocontrato', name='arquivo', field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
        migrations.AddField(
            model_name='anexocontrato',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_set', to='contratos.Contrato'),
        ),
        migrations.AddField(model_name='anexocontrato', name='tipo', field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoAnexo')),
        migrations.AddField(model_name='aditivo', name='arquivo', field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.Arquivo')),
        migrations.AddField(
            model_name='aditivo',
            name='contrato',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos_set', to='contratos.Contrato'),
        ),
        migrations.AddField(
            model_name='aditivo',
            name='empenho',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditivo_empenho_set', to='almoxarifado.Empenho', verbose_name='Empenho'
            ),
        ),
        migrations.AddField(
            model_name='aditivo',
            name='processo',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditivo_processo_set', to='protocolo.Processo', verbose_name='Processo'
            ),
        ),
        migrations.AlterUniqueTogether(name='aditivo', unique_together=set([('contrato', 'ordem')])),
    ]
