# Generated by Django 2.2.7 on 2019-12-03 15:32

from django.db import migrations
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [('contratos', '0002_auto_20190814_1454')]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arquivo_contrato',
            field=djtools.db.models.PrivateFileField(
                help_text='O formato do arquivo deve ser ".pdf"',
                max_length=500,
                null=True,
                storage=djtools.storages.get_private_storage(),
                upload_to='contratos/arquivos/',
                verbose_name='Arquivo do Contrato',
            ),
        )
    ]
