# Generated by Django 2.2.7 on 2019-12-03 17:21
from django.conf import settings
from django.db import migrations


def get_path(apps, contrato):
    import os

    BASE_MEDIA = settings.BASE_DIR + '/deploy/media/'
    FS_ROOT_PATH = BASE_MEDIA + 'upload/'
    extensao = os.path.splitext(contrato.arquivo.nome)[1]
    return os.path.join(FS_ROOT_PATH, 'contratos/contrato/{:d}/{:d}{}'.format(contrato.id, contrato.id, extensao))


def popular_arquivo_contrato(apps, schema_editor):
    import shutil
    import os
    from django.core.files import File

    Contrato = apps.get_model('contratos', 'contrato')
    if not os.path.exists(Contrato.arquivo_contrato.field.storage.path("contratos/arquivos/")):
        os.makedirs(Contrato.arquivo_contrato.field.storage.path("contratos/arquivos/"))

    for contrato in Contrato.objects.filter(arquivo__isnull=False):
        if os.path.exists(get_path(apps, contrato)):
            shutil.copyfile(get_path(apps, contrato), Contrato.arquivo_contrato.field.storage.path(f"contratos/arquivos/{contrato.pk}.pdf"))
            with open(Contrato.arquivo_contrato.field.storage.path(f"contratos/arquivos/{contrato.pk}.pdf"), 'rb') as f:
                file = File(f, name=f'{contrato.pk}.pdf')
                contrato.arquivo_contrato = file
                contrato.save()


def despopular_arquivo_contrato(apps, schema_editor):
    Contrato = apps.get_model('contratos', 'contrato')

    for contrato in Contrato.objects.filter(arquivo_contrato__isnull=False):
        contrato.arquivo_contrato = None
        contrato.save()


class Migration(migrations.Migration):

    dependencies = [('contratos', '0003_contrato_arquivo_contrato')]

    operations = [migrations.RunPython(popular_arquivo_contrato, despopular_arquivo_contrato)]
