# Generated by Django 2.2.7 on 2020-01-21 08:59

from django.db import migrations


def despopular_pessoa_contratada(apps, schema_editor):
    Contrato = apps.get_model('contratos', 'contrato')
    for contrato in Contrato.objects.all():
        contrato.pessoa_contratada = None
        contrato.save()


def popular_pessoa_contratada(apps, schema_editor):
    Contrato = apps.get_model('contratos', 'contrato')
    for contrato in Contrato.objects.all():
        contrato.pessoa_contratada = contrato.contratada
        contrato.save()


class Migration(migrations.Migration):
    dependencies = [('contratos', '0005_contrato_pessoa_contratada')]

    operations = [migrations.RunPython(popular_pessoa_contratada, despopular_pessoa_contratada)]
