# Generated by Django 2.2.7 on 2020-01-21 15:29

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('contratos', '0006_auto_20200121_0859')]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contratada',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.PessoaJuridica', verbose_name='Contratada'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pessoa_contratada',
            field=djtools.db.models.ForeignKeyPlus(
                on_delete=django.db.models.deletion.CASCADE, related_name='pessoacontratada_set', to='rh.Pessoa', verbose_name='Pessoa Contratada'
            ),
        ),
    ]
