# Generated by Django 2.2.10 on 2020-03-31 10:05

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [('contratos', '0007_auto_20200121_1529')]

    operations = [
        migrations.AlterModelOptions(name='aditivo', options={'verbose_name': 'Termo Aditivo', 'verbose_name_plural': 'Termos Aditivos'}),
        migrations.AlterModelOptions(name='maodeobra', options={'verbose_name': 'Mão-de-Obra', 'verbose_name_plural': 'Mãos-de-Obra'}),
        migrations.CreateModel(
            name='AnexoMaoDeObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('arquivo', djtools.db.models.FileFieldPlus(upload_to='contratos/maodeobra/', verbose_name='Arquivo')),
                ('data', models.DateTimeField(auto_now=True)),
                ('maodeobra', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_set', to='contratos.MaoDeObra')),
            ],
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
    ]
