# Generated by Django 2.2.16 on 2020-11-23 18:47

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('documento_eletronico', '0009_auto_20200428_1554'),
        ('contratos', '0008_auto_20200331_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='despacho_documentotexto',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.PROTECT, to='documento_eletronico.DocumentoTexto', verbose_name='Despacho - Documento Eletrônico'),
        ),
    ]
