# Generated by Django 2.2.16 on 2020-12-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documento_eletronico', '0009_auto_20200428_1554'),
        ('contratos', '0009_medicao_despacho_documentotexto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTextoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inclusao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('data_hora_remocao', djtools.db.models.DateTimeFieldPlus(blank=True, editable=False, null=True, verbose_name='Data de Remoção')),
                ('contrato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='documentotexto_contrato_set', to='contratos.Contrato')),
                ('documento', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='documento_eletronico.DocumentoTexto', verbose_name='Documento')),
                ('usuario_inclusao', djtools.db.models.CurrentUserField(blank=True, default=djtools.middleware.threadlocals.get_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_documentotextocontrato_documentos_processos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Inclusão')),
                ('usuario_remocao', djtools.db.models.ForeignKeyPlus(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_documentotextocontrato_documentos_processos_alterados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Remoção')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
