# Generated by Django 2.2.16 on 2021-01-19 10:54

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_documentotextocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='maodeobra',
            name='numero_cct',
            field=djtools.db.models.CharFieldPlus(blank=True, max_length=50, verbose_name='Número da CCT'),
        ),
    ]
