# Generated by Django 2.2.16 on 2021-01-22 16:04

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_maodeobra_numero_cct'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arrecadacao_receita',
            field=models.BooleanField(default=False, help_text='Caso esta opção seja marcada, será possível registrar Valores de Concessão para o contrato', verbose_name='Possui arrecadação de receita?'),
        ),
        migrations.CreateModel(
            name='ArrecadacaoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12)),
                ('data', djtools.db.models.DateFieldPlus(db_column='data_inicio', verbose_name='Data da Concessão')),
                ('contrato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacaoreceita_set', to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Arrecadação de Receita',
                'verbose_name_plural': 'Arrecadação das Receitas',
            },
        ),
    ]
