# Generated by Django 2.2.16 on 2021-03-01 17:09

import contratos.models
from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_auto_20210122_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostilamento',
            name='arquivo',
            field=djtools.db.models.FileFieldPlus(upload_to=contratos.models.anexo_apostilamento_path),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='consulta_susep',
            field=djtools.db.models.FileFieldPlus(help_text='Susep, anexos, etc', null=True, upload_to=contratos.models.consulta_susep_path, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='anexo_resposta',
            field=djtools.db.models.FileFieldPlus(null=True, upload_to=contratos.models.anexo_resposta_ocorrencia_path),
        ),
    ]
