# Generated by Django 2.2.16 on 2021-03-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('documento_eletronico', '0010_auto_20210301_1709'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0013_auto_20210301_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoComprobatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Comprobatório para Medição',
                'verbose_name_plural': 'Tipos de Documentos Comprobatórios para Medição',
            },
        ),
        migrations.AddField(
            model_name='medicao',
            name='termo_definitivo_documentotexto',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_termo_definitivo_set', to='documento_eletronico.DocumentoTexto', verbose_name='Termo de Recebimento Definitivo - Documento Eletrônico'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='despacho_documentotexto',
            field=djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_despacho_set', to='documento_eletronico.DocumentoTexto', verbose_name='Despacho - Documento Eletrônico'),
        ),
        migrations.CreateModel(
            name='MedicaoTipoDocumentoComprobatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('recebido_gerente', models.CharField(blank=True, choices=[('Recebido', 'Recebido'), ('Pendente', 'Pendente')], max_length=8, null=True, verbose_name='Recebimento')),
                ('parecer_gerente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição da Pendência')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data_Avaliaca')),
                ('avaliador_gerente', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('medicao', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Medicao')),
                ('tipo_documento_comprobatorio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.TipoDocumentoComprobatorio')),
            ],
            options={
                'verbose_name': 'Documento Comprobatório da Medição',
                'verbose_name_plural': 'Documentos Comprobatórios da Medicao',
            },
        ),
        migrations.CreateModel(
            name='ContratoTipoDocumentoComprobatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
                ('tipo_documento_comprobatorio', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.PROTECT, to='contratos.TipoDocumentoComprobatorio')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Comprobatório do Contrato',
                'verbose_name_plural': 'Tipos de Documentos Comprobatórios do Contrato',
            },
        ),
    ]
