# Generated by Django 2.2.16 on 2021-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20210308_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaotipodocumentocomprobatorio',
            options={'verbose_name': 'Documento Comprobatório da Medição', 'verbose_name_plural': 'Documentos Comprobatórios da Medição'},
        ),
        migrations.AlterField(
            model_name='medicaotipodocumentocomprobatorio',
            name='data_avaliacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação'),
        ),
    ]
