# Generated by Django 2.2.16 on 2021-04-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_auto_20210323_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscal',
            options={'ordering': ('inativo',), 'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
    ]
