# Generated by Django 2.2.16 on 2021-04-20 21:03

from django.db import migrations
import djtools.db.models
import tqdm

add_field_confirmacao_fiscal = migrations.AddField(
    model_name='medicaotipodocumentocomprobatorio',
    name='confirmacao_fiscal',
    field=djtools.db.models.PositiveIntegerFieldPlus(blank=True,
                                                     choices=[[1, 'Sim'], [2, 'Não se aplica']],
                                                     null=True, verbose_name='Incluído no Processo:'),)


def popular_field_confirmacao_fiscal(apps, schema_editor):
    MedicaoTipoDocumentoComprobatorio = apps.get_model('contratos', 'medicaotipodocumentocomprobatorio')

    for documento_medicao in tqdm.tqdm(MedicaoTipoDocumentoComprobatorio.objects.all()):
        if documento_medicao.confirmado:
            documento_medicao.confirmacao_fiscal = 1
        else:
            documento_medicao.confirmacao_fiscal = 2

        documento_medicao.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0017_auto_20210409_1340'),
    ]

    operations = [add_field_confirmacao_fiscal, migrations.RunPython(popular_field_confirmacao_fiscal)]
