# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_medicaotipodocumentocomprobatorio_confirmacao_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='sem_medicao',
            field=models.BooleanField(null=True, verbose_name='Parcela Sem Medição'),
        ),
    ]
