# Generated by Django 3.2.5 on 2021-11-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_alter_parcela_sem_medicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofiscal',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Fiscal', 'verbose_name_plural': 'Tipos de Fiscais'},
        ),
    ]
