# Generated by Django 3.2.5 on 2022-04-26 15:29

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0034_alter_campoexcecaows_options'),
        ('contratos', '0020_alter_tipofiscal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexocontrato',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='maodeobra',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus'),
        ),
    ]
