# Generated by Django 3.2.5 on 2022-04-28 10:16

import contratos.models
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0039_remove_preferencia_contraste'),
        ('contratos', '0021_auto_20220426_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', djtools.db.models.CharFieldPlus(choices=[['Advertência', 'Advertência'], ['Multa', 'Multa'], ['Suspensão', 'Suspensão']], max_length=20, verbose_name='Tipo')),
                ('arquivo', djtools.db.models.FileFieldPlus(upload_to=contratos.models.penalidade_path, verbose_name='Arquivo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('atualizado_por', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atualizado_por_vinculo', to='comum.vinculo', verbose_name='Atualizado Por')),
                ('contrato', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, related_name='penalidades_set', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Penalidades',
                'ordering': ('-atualizado_em',),
            },
        ),
    ]
