# Generated by Django 3.2.5 on 2022-05-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_auto_20220427_1918'),
        ('contratos', '0022_penalidade'),
    ]

    operations = [
    ]
