# Generated by Django 3.2.5 on 2022-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_merge_0022_auto_20220427_1918_0022_penalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofiscal',
            name='eh_gestor_contrato',
            field=models.BooleanField(default=False, help_text='Um Fiscal Gestor do Contrato poderá gerar o Termo de Recebimento Definitivo.', verbose_name='É gestor do contrato?'),
        ),
    ]
