# Generated by Django 3.2.5 on 2022-05-25 13:39

from django.db import migrations
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0036_auto_20220405_2129'),
        ('contratos', '0024_tipofiscal_eh_gestor_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='campus',
        ),
        migrations.AddField(
            model_name='medicao',
            name='campus',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.unidadeorganizacional', verbose_name='Campus'),
        ),
    ]
