# Generated by Django 3.2.5 on 2022-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_auto_20220525_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
    ]
