# Generated by Django 3.2.5 on 2024-03-05 20:46

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0059_auto_20230427_1602'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('url', models.TextField(verbose_name='URL com Erro')),
                ('url_sentry', models.TextField(blank=True, null=True, verbose_name='URL do Sentry')),
                ('sentry_issue_id', djtools.db.models.CharFieldPlus(blank=True, max_length=255, null=True, verbose_name='Id da Issue do Sentry')),
                ('gitlab_issue_url', models.TextField(blank=True, null=True, verbose_name='URL do Gitlab')),
                ('view', djtools.db.models.CharFieldPlus(max_length=255, verbose_name='View')),
                ('maquina', models.TextField(blank=True, verbose_name='Máquina')),
                ('situacao', models.IntegerField(choices=[[1, 'Reportado'], [2, 'Em análise'], [7, 'Em correção'], [3, 'Resolvido'], [4, 'Aguardando feedback'], [5, 'Cancelado'], [6, 'Reaberto'], [8, 'Unificado']], default=1, verbose_name='Situação')),
                ('data_criacao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_alteracao', djtools.db.models.DateTimeFieldPlus(auto_now=True, verbose_name='Data da Última Alteração')),
                ('qtd_vinculos_afetados', models.IntegerField(default=1, verbose_name='Quantidade de Usuários Afetados')),
                ('titulo_atualizacao', djtools.db.models.CharFieldPlus(max_length=255, null=True, verbose_name='Título')),
                ('tipo_atualizacao', djtools.db.models.CharFieldPlus(choices=[('Bug', 'Bug'), ('Funcionalidade', 'Funcionalidade'), ('Manutenção', 'Manutenção')], default='Bug', max_length=255, null=True, verbose_name='Tipo')),
                ('ip_address', models.TextField(blank=True, verbose_name='Endereço IP')),
                ('agent', models.TextField(blank=True, verbose_name='Navegador')),
                ('atendente_atual', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendentes_erros', to='comum.vinculo', verbose_name='Atendente Atual')),
                ('atualizacao', djtools.db.models.OneToOneFieldPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.atualizacao', verbose_name='Atualização')),
                ('grupos_atualizacao', djtools.db.models.ManyToManyFieldPlus(to='auth.Group', verbose_name='Grupos Envolvidos')),
                ('informante', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informantes_erros', to='comum.vinculo', verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Erro',
                'verbose_name_plural': 'Erros',
            },
        ),
        migrations.CreateModel(
            name='HistoricoComentarioErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Tipo')),
                ('automatico', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', djtools.db.models.CharFieldPlus(choices=[('comentario', 'Comentário'), ('nota_interna', 'Nota Interna')], default='comentario', max_length=255)),
                ('data_alteracao', djtools.db.models.DateTimeFieldPlus(auto_now_add=True)),
                ('visibilidade', djtools.db.models.CharFieldPlus(choices=[('interessados', 'Interessados e Atendentes'), ('atendentes', 'Atendentes')], default='interessados', max_length=255)),
                ('erro', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='erros.erro')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo', verbose_name='Atendente')),
            ],
            options={
                'ordering': ('-data_alteracao',),
            },
        ),
        migrations.CreateModel(
            name='AnexoErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', djtools.db.models.CharFieldPlus(help_text='Informe uma descrição resumida sobre o arquivo anexado', max_length=80, verbose_name='Descrição')),
                ('arquivo', djtools.db.models.FileFieldPlus(max_length=255, upload_to='erros/anexos/')),
                ('ativo', models.BooleanField(default=True)),
                ('anexado_em', djtools.db.models.DateTimeFieldPlus(auto_now_add=True, verbose_name='Anexado em')),
                ('anexado_por', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo', verbose_name='Anexado por')),
                ('erro', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='erros.erro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteressadoErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', djtools.db.models.CharFieldPlus(blank=True, default='', max_length=255, verbose_name='Tema ao ser vinculado ao erro')),
                ('ativo', models.BooleanField(default=True)),
                ('erro', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='erros.erro')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo', verbose_name='Interessado')),
            ],
            options={
                'unique_together': {('vinculo', 'erro')},
            },
        ),
        migrations.CreateModel(
            name='AtendenteErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('erro', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='erros.erro')),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.vinculo', verbose_name='Interessado')),
            ],
            options={
                'unique_together': {('vinculo', 'erro')},
            },
        ),
    ]
