# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.middleware.threadlocals
import djtools.thumbs
import djtools.storages
import djtools.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('rh', '0001_initial'), ('comum', '0002_auto_20190814_1443')]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255, verbose_name='Objetivo')),
                ('cracha', models.CharField(blank=True, max_length=5, null=True, verbose_name='Crachá')),
                ('data_hora_entrada', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data Hora de Entrada')),
                ('data_hora_saida', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data Hora de Saída')),
                ('chave_wifi', models.CharField(max_length=255, null=True, verbose_name='Chave wi-fi')),
                ('data_geracao_chave_wifi', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data Geração da Chave wi-fi')),
                ('quantidade_dias_chave_wifi', djtools.db.models.PositiveIntegerFieldPlus(default=1, verbose_name='Quantidade de dias da Chave wi-fi')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistemaPortaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cracha_obrigatorio', models.BooleanField(default=False, verbose_name='O uso do crachá é obrigatório?')),
                ('habilitar_camera', models.BooleanField(default=True, verbose_name='Habilitar uso da câmera?')),
                ('habilitar_geracao_chave_wifi', models.BooleanField(default=True, verbose_name='Habilitar a geração de chave WI-FI?')),
                ('url_ruckus', models.URLField(blank=True, verbose_name='URL de integração com o Ruckus')),
                ('limite_compartilhamento_chave', models.IntegerField(default=1, verbose_name='Limite de compartilhamento da chave do WI-FI')),
                ('campus', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Campus')),
            ],
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.CreateModel(
            name='SolicitacaoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_entrada', djtools.db.models.TimeFieldPlus(verbose_name='Hora da Entrada')),
                ('hora_saida', djtools.db.models.TimeFieldPlus(verbose_name='Hora da Saída')),
                ('atividade', models.CharField(max_length=255, verbose_name='Atividade a ser realizada')),
                ('deferida', models.NullBooleanField()),
                ('cancelada', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('sala', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Sala', verbose_name='Sala')),
                ('solicitantes', models.ManyToManyField(to='comum.Vinculo', verbose_name='Solicitantes')),
                (
                    'usuario_cadastro',
                    djtools.db.models.CurrentUserField(
                        blank=True,
                        default=djtools.middleware.threadlocals.get_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário de Cadastro',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Solicitação de Entrada',
                'verbose_name_plural': 'Solicitações de Entrada',
                'permissions': (('pode_avaliar_solicitacoes_entrada', 'Pode avaliar Solicitações de Entrada'),),
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('sexo', models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('data_cadastro', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data do Cadastro')),
                ('data_ultima_alteracao', djtools.db.models.DateTimeFieldPlus(blank=True, null=True, verbose_name='Data da Última Alteração')),
                ('foto', djtools.thumbs.ImageWithThumbsField(blank=True, null=True, storage=djtools.storages.get_overwrite_storage(), upload_to='portaria_visitante_externo')),
                (
                    'user_cadastro',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_cadastro',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário do Cadastro',
                    ),
                ),
                (
                    'user_ultima_alteracao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_ultima_alteracao',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário da Última Alteração',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='AcessoExterno',
            fields=[
                (
                    'acesso_ptr',
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portaria.Acesso'),
                ),
                ('pessoa_externa', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='portaria.Visitante', verbose_name='Pessoa Externa')),
            ],
            options={'verbose_name': 'Acesso Externo', 'verbose_name_plural': 'Acessos Externo'},
            bases=('portaria.acesso',),
        ),
        migrations.CreateModel(
            name='AcessoInterno',
            fields=[
                (
                    'acesso_ptr',
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portaria.Acesso'),
                ),
                ('vinculo', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='comum.Vinculo', verbose_name='Vínculo')),
            ],
            options={'verbose_name': 'Acesso Interno', 'verbose_name_plural': 'Acessos Internos'},
            bases=('portaria.acesso',),
        ),
        migrations.AddField(
            model_name='acesso',
            name='local_acesso',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.UnidadeOrganizacional', verbose_name='Local de Acesso'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='user_entrada',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_entrada', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Registro de Entrada'
            ),
        ),
        migrations.AddField(
            model_name='acesso',
            name='user_geracao_chave_wifi',
            field=djtools.db.models.ForeignKeyPlus(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_geracao_chave_wifi',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário Geração da Chave wi-fi',
            ),
        ),
        migrations.AddField(
            model_name='acesso',
            name='user_saida',
            field=djtools.db.models.ForeignKeyPlus(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_saida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Registro de Saída'
            ),
        ),
    ]
