# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 15:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('portaria', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='configuracaosistemaportaria', name='url_ruckus'),
        migrations.AddField(
            model_name='configuracaosistemaportaria',
            name='url_wifi',
            field=models.URLField(
                blank=True,
                help_text='Caso esse campo permaneça vazio será utilizado a configuração padrão de integração wifi',
                verbose_name='URL de integração com o Sistema de Wifi',
            ),
        ),
    ]
