# Generated by Django 3.2.5 on 2021-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20190902_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoentrada',
            name='deferida',
            field=models.BooleanField(null=True),
        ),
    ]
