# Generated by Django 3.2.5 on 2022-06-27 14:39

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_alter_solicitacaoentrada_deferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistemaportaria',
            name='senha',
            field=djtools.db.models.CharFieldPlus(max_length=10, null=True, verbose_name='Senha do WI-FI'),
        ),
    ]
