# Generated by Django 3.2.5 on 2022-07-13 11:53

from django.db import migrations
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_configuracaosistemaportaria_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistemaportaria',
            options={'verbose_name': 'Configuração de Portaria', 'verbose_name_plural': 'Configurações de Portaria'},
        ),
        migrations.AlterField(
            model_name='configuracaosistemaportaria',
            name='senha',
            field=djtools.db.models.CharFieldPlus(max_length=30, null=True, verbose_name='Senha do WI-FI'),
        ),
    ]
