# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 15:05


from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('processo_eletronico', '0001_initial'), ('rh', '0001_initial'), ('protocolo', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCriterioNota',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nota', models.FloatField(default=-1))],
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.CreateModel(
            name='AvaliacaoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Descrição do Modelo')),
                (
                    'funcao_gratificada',
                    models.BooleanField(default=False, help_text='Não se aplica ao estágio probatório', verbose_name='Modelo para Servidores com Função Gratificada'),
                ),
            ],
            options={'verbose_name': 'Modelo/Ficha de Avaliação', 'verbose_name_plural': 'Modelos/Fichas de Avaliação'},
        ),
        migrations.CreateModel(
            name='AvaliacaoModeloCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_questao', models.TextField(unique=True, verbose_name='Descrição do Critério/Questão')),
                ('nota_minima', models.PositiveIntegerField(default=0, help_text='Nota mínima que pode ser dada ao critério/questão', null=True, verbose_name='Nota Mínima')),
                ('nota_maxima', models.PositiveIntegerField(default=10, help_text='Nota máxima que pode ser dada ao critério/questão', null=True, verbose_name='Nota Máxima')),
                ('passo_nota', models.FloatField(default=1.0, help_text='Passo da nota', null=True, verbose_name='Intervalo entre Notas')),
            ],
            options={'verbose_name': 'Critério de Avaliação', 'verbose_name_plural': 'Critérios de Avaliação', 'ordering': ('descricao_questao',)},
        ),
        migrations.CreateModel(
            name='ProcessoProgressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_contagem_progressao', models.DateField(help_text='Início do período da contagem da progressão.', verbose_name='Data Início da Contagem')),
                (
                    'data_fim_contagem_progressao',
                    models.DateField(
                        help_text='Final do período da contagem da progressão. Essa data será igual a Data início da contagem + meses de interstício + afastamentos no período da contagem (se for o caso).',
                        verbose_name='Data Final da Contagem',
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[[0, 'A iniciar'], [1, 'Em trâmite'], [2, 'Finalizado']],
                        default=0,
                        help_text='Indica a situação atual do processo de progressão.',
                        verbose_name='Status do Processo',
                    ),
                ),
                ('tipo', models.IntegerField(choices=[[1, 'Progressão Funcional por Mérito'], [2, 'Estágio Probatório']], default=1, verbose_name='Tipo do Processo')),
                ('media_processo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Média do Processo')),
                ('avaliado', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor', verbose_name='Avaliado')),
                (
                    'padrao_anterior',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrao_anterior', to='rh.PadraoVencimento', verbose_name='Padrão de Vencimento Atual'
                    ),
                ),
                (
                    'padrao_novo',
                    djtools.db.models.ForeignKeyPlus(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrao_novo', to='rh.PadraoVencimento', verbose_name='Padrão de Vencimento Novo'
                    ),
                ),
                (
                    'processo_eletronico',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo_eletronico.Processo', verbose_name='Processo Eletrônico'
                    ),
                ),
                (
                    'protocolo',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolo.Processo', verbose_name='Protocolo'),
                ),
            ],
            options={
                'verbose_name': 'Processo de Progressão/Estágio Probatório',
                'verbose_name_plural': 'Processos de Progressão/Estágio Probatório',
                'ordering': ('-data_inicio_contagem_progressao',),
                'permissions': (
                    ('pode_ver_todos_os_processos', 'Pode visualizar todos os processos'),
                    ('pode_ver_apenas_processos_do_seu_campus', 'Pode visualizar apenas os processos do seu campus'),
                ),
            },
        ),
        migrations.CreateModel(
            name='ProcessoProgressaoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avaliador', models.IntegerField(choices=[[0, 'Chefe Imediato'], [1, 'Membro da Equipe'], [2, 'Auto-Avaliação']])),
                ('status_avaliacao', models.IntegerField(choices=[[0, 'Pendente'], [1, 'Avaliada']], default=0, verbose_name='Situação do Período')),
                ('data_avaliacao', models.DateField(null=True, verbose_name='Data da Avaliação')),
                ('total_pontos', models.FloatField(default=0.0)),
                ('comentario_avaliador', models.TextField(blank=True)),
                ('comentario_avaliado', models.TextField(blank=True)),
                ('comentario_rh', models.TextField(blank=True)),
                ('hash_string', models.TextField(blank=True, verbose_name='String formadora do Hash')),
                ('hash_valor', djtools.db.models.CharFieldPlus(blank=True, max_length=255, verbose_name='Hash')),
                ('assinatura_avaliador', models.TextField(blank=True, default='', null=True, verbose_name='Assinatura do Avaliador')),
                ('data_assinatura_avaliador', models.DateField(default=None, null=True, verbose_name='Data de Assinatura do Avaliador')),
                ('assinatura_avaliado', models.TextField(blank=True, default='', null=True, verbose_name='Assinatura do Avaliado')),
                ('data_assinatura_avaliado', models.DateField(default=None, null=True, verbose_name='Data de Assinatura do Avaliador')),
                ('assinatura_chefe_imediato', models.TextField(blank=True, default='', null=True, verbose_name='Assinatura do Chefe Imediato')),
                ('data_assinatura_chefe_imediato', models.DateField(default=None, null=True, verbose_name='Data de Assinatura do Chefe Imediato')),
                ('numero_liberacoes', models.IntegerField(default=0, editable=False)),
                ('avaliador', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Servidor')),
                (
                    'chefe_imediato_assinante',
                    djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefe_imediato_assinante', to='rh.Servidor'),
                ),
            ],
            options={'verbose_name': 'Ficha de Avaliação', 'verbose_name_plural': 'Fichas de Avaliações', 'ordering': ('-status_avaliacao', 'avaliador__nome')},
        ),
        migrations.CreateModel(
            name='ProcessoProgressaoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', djtools.db.models.DateFieldPlus(verbose_name='Data Inicial')),
                ('data_fim', djtools.db.models.DateFieldPlus(verbose_name='Data Final')),
                ('media_periodo', djtools.db.models.DecimalFieldPlus(decimal_places=2, default=0, max_digits=12)),
                (
                    'avaliacao_modelo',
                    djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='progressoes.AvaliacaoModelo', verbose_name='Modelo de Avaliação'),
                ),
                (
                    'processo_progressao',
                    djtools.db.models.ForeignKeyPlus(
                        blank=True, on_delete=django.db.models.deletion.CASCADE, to='progressoes.ProcessoProgressao', verbose_name='Processo de Progressão'
                    ),
                ),
                ('setor', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='rh.Setor')),
            ],
            options={'verbose_name': 'Período Avaliado', 'verbose_name_plural': 'Períodos Avaliados', 'ordering': ('data_inicio',)},
        ),
        migrations.AddField(
            model_name='processoprogressaoavaliacao',
            name='periodo',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='progressoes.ProcessoProgressaoPeriodo'),
        ),
        migrations.AddField(
            model_name='avaliacaomodelo', name='itens_avaliados', field=models.ManyToManyField(to='progressoes.AvaliacaoModeloCriterio', verbose_name='Critérios Avaliados')
        ),
        migrations.AddField(
            model_name='avaliacaocriterionota',
            name='avaliacao',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='progressoes.ProcessoProgressaoAvaliacao'),
        ),
        migrations.AddField(
            model_name='avaliacaocriterionota',
            name='criterio_avaliado',
            field=djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='progressoes.AvaliacaoModeloCriterio'),
        ),
    ]
