# Generated by Django 2.2.10 on 2021-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaomodelo',
            name='tipo',
            field=models.IntegerField(choices=[[1, 'Progressão Funcional por Mérito'], [2, 'Estágio Probatório']], default=1, verbose_name='Tipo do Processo'),
        ),
    ]
