# Generated by Django 2.2.10 on 2020-09-24 08:24

from django.db import migrations
from django.core.management import call_command


def atualizar_data_documentacao(apps, schema):
    call_command('atualizar_data_documentacao')


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioemergencial', '0002_auto_20200924_0820'),
    ]

    operations = [
        migrations.RunPython(atualizar_data_documentacao)
    ]
