# Generated by Django 2.2.16 on 2020-11-10 09:47

from django.db import migrations
import django.db.models.deletion
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0009_auto_20201023_1542'),
        ('auxilioemergencial', '0004_auto_20200924_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='arquivo_prestacao_contas',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Prestação de Contas'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_contas_cadastrada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas cadastrada em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_contas_cadastrada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacaocontas_por', to='comum.Vinculo', verbose_name='Prestação de Contas cadastrada por'),
        ),
    ]
