# Generated by Django 2.2.16 on 2020-11-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioemergencial', '0005_auto_20201110_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricaodispositivo',
            options={'permissions': (('pode_adicionar_prestacao_contas', 'Pode Adicionar Prestação de Contas'),), 'verbose_name': 'Inscrição de Auxílio para Aquisição de Dispositivo Eletrônico', 'verbose_name_plural': 'Inscrições de Auxílio para Aquisição de Dispositivo Eletrônico'},
        ),
    ]
