# Generated by Django 2.2.16 on 2021-02-05 15:47

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0037_auto_20210203_1103'),
        ('comum', '0011_merge_20201221_1533'),
        ('auxilioemergencial', '0006_auto_20201110_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoAlunoConectado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('ultima_atualizacao', models.DateTimeField(null=True, verbose_name='Última Atualização')),
                ('casa_possui_servico_internet', djtools.db.models.CharFieldPlus(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não, compartilho a do(a) vizinho(a)', 'Não, compartilho a do(a) vizinho(a)')], max_length=100, verbose_name='Na casa que você mora possui algum serviço de internet wifi?')),
                ('foi_contemplado_servico_internet', models.BooleanField(default=False, verbose_name='Você foi contemplado(a) com o auxílio emergencial para contratação de serviço de internet?')),
                ('localidade_possui_cobertura', models.BooleanField(default=False, verbose_name='A localidade que você mora é coberta pelas operadoras Claro ou Oi?')),
                ('justificativa_solicitacao', djtools.db.models.CharFieldPlus(max_length=5000, verbose_name='Justificativa para Solicitação')),
                ('situacao', djtools.db.models.CharFieldPlus(choices=[('Concluída', 'Concluída'), ('Pendente de assinatura do responsável', 'Pendente de assinatura do responsável')], default='Pendente de assinatura do responsável', max_length=100, verbose_name='Situação')),
                ('assinado_pelo_responsavel', models.BooleanField(default=False, verbose_name='Assinado pelo Responsável')),
                ('assinado_pelo_responsavel_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Assinado pelo Responsável em')),
                ('parecer', djtools.db.models.CharFieldPlus(choices=[('Sem parecer', 'Sem parecer'), ('Deferido', 'Deferido'), ('Deferido, mas sem recurso disponível para atendimento no momento', 'Deferido, mas sem recurso disponível para atendimento no momento'), ('Pendente de documentação complementar', 'Pendente de documentação complementar'), ('Indeferido', 'Indeferido')], default='Sem parecer', max_length=100, verbose_name='Parecer')),
                ('data_parecer', models.DateTimeField(null=True, verbose_name='Data do Parecer')),
                ('documentacao_pendente', djtools.db.models.CharFieldPlus(max_length=2000, null=True, verbose_name='Indique qual documentação esse estudante deve anexar')),
                ('data_limite_envio_documentacao', djtools.db.models.DateFieldPlus(null=True, verbose_name='Indique a data limite para que o estudante anexe essa documentação')),
                ('valor_concedido', djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=6, null=True, verbose_name='Valor Concedido')),
                ('termo_compromisso_assinado', models.BooleanField(default=False, verbose_name='Termo de Compromisso Assinado')),
                ('termo_compromisso_assinado_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Termo de Compromisso Assinado em')),
                ('fim_auxilio', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Fim do Auxílio')),
                ('documentacao_atualizada_em', djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Documentação Atualizada em')),
                ('aluno', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='edu.Aluno', verbose_name='Aluno')),
                ('autor_parecer', djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor_parecer_alunoconectado', to='comum.Vinculo', verbose_name='Autor do Parecer')),
                ('edital', djtools.db.models.ForeignKeyPlus(on_delete=django.db.models.deletion.CASCADE, to='auxilioemergencial.Edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Inscrição de Auxílio para o Projeto Alunos Conectados',
                'verbose_name_plural': 'Inscrições de Auxílio para o Projeto Alunos Conectados',
            },
        ),
    ]
