# Generated by Django 2.2.16 on 2021-05-14 18:49

from django.db import migrations, models
import django.db.models.deletion
import djtools.db.models
import djtools.storages


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0018_auto_20210401_1853'),
        ('auxilioemergencial', '0007_inscricaoalunoconectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoaluno',
            name='integrante_familiar',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auxilioemergencial.IntegranteFamiliar', verbose_name='Integrante Familiar'),
        ),
        migrations.AddField(
            model_name='documentoaluno',
            name='tipo',
            field=djtools.db.models.CharFieldPlus(choices=[('Comprovante de Renda', 'Comprovante de Renda'), ('Comprovante de Residência', 'Comprovante de Residência'), ('Documentação Complementar', 'Documentação Complementar'), ('Parecer emitido pelo NAPNE e/ou ETEP', 'Parecer emitido pelo NAPNE e/ou ETEP'), ('Declaração de ausência de renda da família', 'Declaração de ausência de renda da família'), ('Termo de Compromisso', 'Termo de Compromisso')], max_length=50, null=True, verbose_name='Tipo do Documento'),
        ),
        migrations.AddField(
            model_name='edital',
            name='arquivo_instrucoes',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/edital/documentos', verbose_name='Instruções Gerais'),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_divulgacao',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Data de Divulgação do Resultado'),
        ),
        migrations.AddField(
            model_name='edital',
            name='impedir_fic',
            field=models.BooleanField(default=False, verbose_name='Impedir inscrição para alunos de cursos FIC'),
        ),
        migrations.AddField(
            model_name='edital',
            name='impedir_pos_graduacao',
            field=models.BooleanField(default=False, verbose_name='Impedir inscrição para alunos de cursos de pós-graduação'),
        ),
        migrations.AddField(
            model_name='inscricaoaluno',
            name='valor_doacoes',
            field=djtools.db.models.DecimalFieldPlus(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor que a família está recebendo de doações e/ou ajuda de terceiros (R$)'),
        ),
        migrations.AddField(
            model_name='inscricaoalunoconectado',
            name='data_limite_assinatura_termo',
            field=djtools.db.models.DateTimeFieldPlus(default='2020-12-31', verbose_name='Data Limite para Assinar Termo de Compromisso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='arquivo_gru',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Arquivo GRU'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='arquivo_gru_cadastrado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Arquivo GRU cadastrado em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='arquivo_gru_cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivogru_por', to='comum.Vinculo', verbose_name='Arquivo GRU cadastrado por'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='comprovante_gru',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Comprovante GRU'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='comprovante_gru_cadastrado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Comprovante GRU cadastrado em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='comprovante_gru_cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantegru_por', to='comum.Vinculo', verbose_name='Comprovante GRU cadastrado por'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='data_limite_assinatura_termo',
            field=djtools.db.models.DateTimeFieldPlus(default='2020-12-31', verbose_name='Data Limite para Assinar Termo de Compromisso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='data_limite_envio_prestacao_contas',
            field=djtools.db.models.DateFieldPlus(null=True, verbose_name='Indique a data limite para que o estudante anexe essa documentação'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='pendencia_cadastrada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas cadastrada em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='pendencia_cadastrada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_por', to='comum.Vinculo', verbose_name='Pendências cadastrada por'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='pendencia_prestacao_contas',
            field=djtools.db.models.CharFieldPlus(max_length=2000, null=True, verbose_name='Indique qual documentação esse estudante deve anexar'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_concluida_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas concluída em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_concluida_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacao_concluida_por', to='comum.Vinculo', verbose_name='Prestação concluída por'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_contas_atualizada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas atualizada em'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='prestacao_contas_atualizada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacaocontas_atualizada_por', to='comum.Vinculo', verbose_name='Prestação de Contas atualizada por'),
        ),
        migrations.AddField(
            model_name='inscricaodispositivo',
            name='situacao_prestacao_contas',
            field=djtools.db.models.CharFieldPlus(choices=[('Aguardando documentos', 'Aguardando documentos'), ('Pendente de validação', 'Pendente de validação'), ('Concluída', 'Concluída')], default='Não Informado', max_length=255, verbose_name='Situação da Prestação de Contas'),
        ),
        migrations.AddField(
            model_name='inscricaointernet',
            name='data_limite_assinatura_termo',
            field=djtools.db.models.DateTimeFieldPlus(default='2020-12-31', verbose_name='Data Limite para Assinar Termo de Compromisso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='arquivo_gru',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Arquivo GRU'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='arquivo_gru_cadastrado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Arquivo GRU cadastrado em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='arquivo_gru_cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivogru_material_por', to='comum.Vinculo', verbose_name='Arquivo GRU cadastrado por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='arquivo_prestacao_contas',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Prestação de Contas'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='comprovante_gru',
            field=djtools.db.models.PrivateFileField(max_length=255, null=True, storage=djtools.storages.get_private_storage(), upload_to='auxilioemergencial/inscricao/documentos', verbose_name='Comprovante GRU'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='comprovante_gru_cadastrado_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Comprovante GRU cadastrado em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='comprovante_gru_cadastrado_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantegru_material_por', to='comum.Vinculo', verbose_name='Comprovante GRU cadastrado por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='data_limite_assinatura_termo',
            field=djtools.db.models.DateTimeFieldPlus(default='2020-12-31', verbose_name='Data Limite para Assinar Termo de Compromisso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='data_limite_envio_prestacao_contas',
            field=djtools.db.models.DateFieldPlus(null=True, verbose_name='Indique a data limite para que o estudante anexe essa documentação'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='pendencia_cadastrada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas cadastrada em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='pendencia_cadastrada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_material_por', to='comum.Vinculo', verbose_name='Pendências cadastrada por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='pendencia_prestacao_contas',
            field=djtools.db.models.CharFieldPlus(max_length=2000, null=True, verbose_name='Indique qual documentação esse estudante deve anexar'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_concluida_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas concluída em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_concluida_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacaomaterial_concluida_por', to='comum.Vinculo', verbose_name='Prestação concluída por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_contas_atualizada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas atualizada em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_contas_atualizada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacaocontasmaterial_atualizada_por', to='comum.Vinculo', verbose_name='Prestação de Contas atualizada por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_contas_cadastrada_em',
            field=djtools.db.models.DateTimeFieldPlus(null=True, verbose_name='Prestação de contas cadastrada em'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='prestacao_contas_cadastrada_por',
            field=djtools.db.models.ForeignKeyPlus(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacaocontasmaterial_por', to='comum.Vinculo', verbose_name='Prestação de Contas cadastrada por'),
        ),
        migrations.AddField(
            model_name='inscricaomaterialpedagogico',
            name='situacao_prestacao_contas',
            field=djtools.db.models.CharFieldPlus(choices=[('Aguardando documentos', 'Aguardando documentos'), ('Pendente de validação', 'Pendente de validação'), ('Concluída', 'Concluída')], default='Não Informado', max_length=255, verbose_name='Situação da Prestação de Contas'),
        ),
        migrations.AlterField(
            model_name='integrantefamiliar',
            name='remuneracao',
            field=djtools.db.models.DecimalFieldPlus(decimal_places=2, max_digits=12, null=True, verbose_name='6. Renda Bruta* Mensal'),
        ),
    ]
